### ISSUE TITLE
tf.exe fails with invalid uri

### ISSUE THREAD

**Issue by vinaykalasannavar** [Microsoft/azure-pipelines-agent#1358]
## Agent version and platform
Version of your agent? 2.126.0

OS of the machine running the agent?
Windows 7

## VSTS type and version
https://<our-site>.VisualStudio.com

## What's not working?
**vsts-agent-win-x64-2.126.0** doesn't work when installed as a service.. on a Win7 machine for a VSTS environment

The build fails at the step "Get Services":
with the error message:

2018-01-05T12:13:08.5627766Z Invalid URI: The hostname could not be parsed.
2018-01-05T12:13:08.5767766Z ##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://out-site.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.

![image](https://user-images.githubusercontent.com/7059125/34616472-43d98dee-f230-11e7-80d0-ce74cbbd2457.png)

I have tried installing the agent to run as a service both 
via the command line:
- config.cmd --url https://ourtfsurl.visualstudio.com --replace --unattended --auth PAT --token <token> --pool pool --agent agent --runasservice
also tried installing it with a simple config.cmd, 
- and then provide the PAT token, etc... and when asked would you like to run as a service, I said 'y' to install as a service.

The only way it works is I had to run the agent manually using the run.cmd or choose to run the command using auto logon:
![image](https://user-images.githubusercontent.com/7059125/34616890-72728d76-f231-11e7-885c-0720d9fc54a9.png)

I've verified this behaviour by installing the Agent on 3 different Win 7 computers, and it has had the same issue on all three computers - installing it as a service fails.

## Agent and Worker's diag log
(I've put in only the relevant part here):

```
2018-01-05T12:13:08.2347766Z ##[section]Starting: Get Sources
2018-01-05T12:13:08.2377766Z ##[debug]Sync source for endpoint: ENDPOINT_NAME
2018-01-05T12:13:08.2717766Z Prepending Path environment variable with directory containing 'tf.exe'.
2018-01-05T12:13:08.2727766Z ##[debug]Path: 'C:\agent\externals\vstsom;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\Program Files (x86)\Intel\UCRT\;C:\Program Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\HP\HP Performance Advisor;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\WindowsPowerShell\v1.0\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Git\cmd'
2018-01-05T12:13:08.2727766Z Setting environment variable TFVC_BUILDAGENT_POLICYPATH
2018-01-05T12:13:08.2727766Z Querying workspace information.
2018-01-05T12:13:08.2847766Z ##[debug]tf vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt
2018-01-05T12:13:08.5537766Z ##[debug]Invalid URI: The hostname could not be parsed.
2018-01-05T12:13:08.5627766Z Invalid URI: The hostname could not be parsed.
2018-01-05T12:13:08.5767766Z ##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.
2018-01-05T12:13:08.5797766Z ##[debug]Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCCommandManager.<RunPorcelainCommandAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TFCommandManager.<WorkspacesAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider.<GetSourceAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<GetSourceAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-01-05T12:13:08.5807766Z ##[section]Finishing: Get Sources

```

**Comment by TingluoHuang** [comment]
@vinaykalasannavar when you run as service, which account it's running as?
can you check registry for that account?
search `TeamFoundation\Instances` under `HK_Current_User`

**Comment by vinaykalasannavar** [comment]
I've tried the two options:
When installing using 
config.cmd --unattended... 
it's under NT AUTHORITY\NETWORKSERVICE
I've also tried installing it to run under a domain account, by just config.cmd , and doing the interactive installation:
![image](https://user-images.githubusercontent.com/7059125/34619583-83bc92b2-f23a-11e7-9006-a75c5fb320aa.png)
Enter User account to use for the service (press enter for NT AUTHORITY\NETWORK
SERVICE) >

and it still has the same issue.

**Comment by TingluoHuang** [comment]
@vinaykalasannavar have you try config as service with a domain account instead of `network service`?

**Comment by TingluoHuang** [comment]
@vinaykalasannavar also, can you disable sync source, and add a PowerShell task to search you registry, looking for `TeamFoundation` under `HK_Current_User`

**Comment by vinaykalasannavar** [comment]
How do I disable sync source?
What do you intend the powershell task to achieve, after searching for `TeamFoundation `under `HK_Current_User`?

Also, earlier when I said it's running under NETWIRK SERVICE, I say that because the command prompt tells me this:
![image](https://user-images.githubusercontent.com/7059125/34620486-89826e30-f23d-11e7-8d90-a63e6cdf3cfa.png)

I can't physically find a registry entry for the account under which the service runs:
![image](https://user-images.githubusercontent.com/7059125/34620402-42f1bbec-f23d-11e7-868d-5f81e9b9f759.png)
Do you find anything missing, by looking at my registry snapshot?

**Comment by vinaykalasannavar** [comment]
Also, why are you digging into what service it's running under, the error log seems to say:

```
2018-01-05T12:13:08.2847766Z ##[debug]tf vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt
2018-01-05T12:13:08.5537766Z ##[debug]Invalid URI: The hostname could not be parsed.

2018-01-05T12:13:08.5767766Z ##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.
```

**Comment by TingluoHuang** [comment]
set machine level env `agent.source.skip=true` will disable sync source.
check the Uri value of your registry, is that a valid url?

the error `Invalid URI: The hostname could not be parsed` seems like coming from Tf.exe itself, it haven't hit the service yet.

Which means in tf.exe's code there should be a place, we try to do New Uri("invaliduri") which cause the problem.

after check the source code, i found that tf.exe will try read some url from Registry.

**Comment by vinaykalasannavar** [comment]
@TingluoHuang 

I tried `agent.source.skip=true`:
The build skipped the `Get Sources` step
```
2018-01-09T11:29:50.2980876Z ##[section]Starting: Get Sources
2018-01-09T11:29:50.3010879Z Skip sync source for endpoint: My Project
2018-01-09T11:29:50.3010879Z ##[section]Finishing: Get Sources
```
But then the build failed failed at the next step - (`NuGet restore`) saying it couldn't find the required file:

```
2018-01-09T11:29:50.3340912Z ##[debug]tf vc resolvePath "$\My Project\Blah.Api.sln" /loginType:OAuth /login:.,******** /noprompt
2018-01-09T11:29:50.4070985Z ##[error]The system cannot find the file specified
```

I also had reinstalled the agent (because earlier, I had set it to run manually with autologon configured). 
So here's what I did before running the build:
- `config.cmd remove` (since the agent was configured to run with `autologon`),
- and I re-installed the agent to `-runasservice` with a `--unattended` param

The registry has valid values for Uri parameter. I'm looking at registry values at these two places under the `TeamFoundation\Instances`:
![image](https://user-images.githubusercontent.com/7059125/34719872-6894ce4e-f534-11e7-83ab-cf830936070d.png)
and 
![image](https://user-images.githubusercontent.com/7059125/34719877-6c0ae5f4-f534-11e7-92bb-f60b30b5ab07.png)




> haven't hit the service yet

If the service isn't running, the build agent will show as offline doesn't it:
![image](https://user-images.githubusercontent.com/7059125/34719776-f1bb299e-f533-11e7-9a7a-a1a05ebb26d0.png)
Not sure I understand you here, hitting which service?

**Comment by bryanmacfarlane** [comment]
He's saying tf.exe is failing before it makes a network call.  The agent runs get sources which calls tf.exe which looks up the uri.  For some reason, it's failing parsing the uri which means it doesn't call the vsts service.  Perhaps it's failing to read the registry (permissions, etc...), getting null and not handling.

**Comment by bryanmacfarlane** [comment]
Updating title and marking to build since failing in tf.exe get sources.  Another thing to prove the point would be to create a sample git project - it would work.  it's not running as a svc that's failing.

**Comment by moswald** [comment]
This issue hasn't seen activity in about 10 months; I'm going to close it. @vinaykalasannavar, please reopen if you still have issues.
