### ISSUE TITLE
OSX agent running as launch agent goes offline if not interactively logged on (RDP, etc.)

### ISSUE THREAD

**Issue by 199219921992** [Microsoft/azure-pipelines-agent#1459]
@bryanmacfarlane-
I am unsing VSTS agent 2.129.1 on OSX, agent type is launch agent. VSTS agent are going offline when I close RDP connection with MAC machine and it will come online once i do RDP. Agent logs are shown below. I see issue thread talks about same issue. Is there a permanent fix for the issue.

[2018-03-12 09:26:46Z ERR Terminal] WRITE ERROR: 2018-03-12 09:26:46Z: Agent connect error: The HTTP request timed out after 00:01:40.. Retrying until reconnected.
[2018-03-12 09:26:46Z INFO MessageListener] Sleeping for 18.66 seconds before retrying.
[2018-03-12 09:27:04Z INFO MessageListener] No message retrieved from session 'd716a919-c9c4-4708-be94-3113be8e53b0' within last 30 minutes.
[2018-03-12 09:34:38Z WARN VisualStudioServices] GET request to https:///_apis/distributedtask/pools/9/messages?sessionId=d716a919-c9c4-4708-be94-3113be8e53b0&lastMessageId=38 timed out after 100 seconds.
[2018-03-12 09:34:38Z ERR MessageListener] Catch exception during get next message.
[2018-03-12 09:34:38Z ERR MessageListener] System.TimeoutException: The HTTP request timed out after 00:01:40. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.d__17.MoveNext()
--- End of inner exception stack trace ---
at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()\ at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\ --- End of stack trace from previous location where exception was thrown ---\ at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\ at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\ at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()\ --- End of stack trace from previous location where exception was thrown ---\ at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\ at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\ at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__461.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.d__13.MoveNext()
}

**Comment by TingluoHuang** [comment]
@199219921992 running agent interactively requires an interactive session on the machine, you can change the agent to running as service or use `nohup` to launch the agent in RDP session.

**Comment by bryanmacfarlane** [comment]
note that launch agents on run when a user is logged on:
http://www.grivet-tools.com/blog/2014/launchdaemons-vs-launchagents/

**Comment by bryanmacfarlane** [comment]
Also potentially relevant:
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-osx#automatic-log-on-and-lock
