### ISSUE TITLE
Please explain vsts agents log

### ISSUE THREAD

**Issue by melezhik** [Microsoft/azure-pipelines-agent#1913]
Hi! During agent autoupdate I can see this error in agent log ( taken from `_diag/` folder):

```
[2018-10-29 15:53:51Z INFO SelfUpdater] Version '2.141.1' of 'agent' package available in server.
[2018-10-29 15:53:51Z INFO SelfUpdater] Current running agent version is 2.140.2
[2018-10-29 15:53:51Z INFO SelfUpdater] An update is available.
[2018-10-29 15:53:51Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2018-10-29 15:53:51Z INFO Terminal] WRITE LINE: Downloading 2.141.1 agent
[2018-10-29 15:53:51Z INFO HostContext] Well known directory 'Bin': 'C:\agent33\bin'
[2018-10-29 15:53:51Z INFO HostContext] Well known directory 'Root': 'C:\agent33'
[2018-10-29 15:53:51Z INFO HostContext] Well known directory 'Work': 'C:\agent33\_work'
[2018-10-29 15:53:51Z INFO SelfUpdater] Save latest agent into C:\agent33\_work\_update\agent.zip.
[2018-10-29 15:53:52Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2018-10-29 15:53:52Z ERR  Terminal] WRITE ERROR: An error occurred: An error occurred while sending the request.
[2018-10-29 15:53:52Z ERR  AgentProcess] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.<DownloadLatestAgent>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.<SelfUpdate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.<MainAsync>d__1.MoveNext()

```

Could anyone explain what does it mean? ( "The connection with the server was terminated abnormally"), I'd like to address this to our netwrok team, however I'd like to get vsts agent maintainers input first ... Thanks

**Comment by TingluoHuang** [comment]
@melezhik the error from that winhttp exception is:
```
ERROR_WINHTTP_CONNECTION_ERROR

12030

The connection with the server has been reset or terminated, or an incompatible SSL protocol was encountered. For example, WinHTTP version 5.1 does not support SSL2 unless the client specifically enables it.
```
https://docs.microsoft.com/en-us/windows/desktop/winhttp/error-messages

can you hit the agent download url from the machine that having the problem from IE?
https://vstsagentpackage.azureedge.net/agent/2.141.1/vsts-agent-win-x64-2.141.1.zip

make sure you configure the agent to use the same proxy server as your browser.

**Comment by melezhik** [comment]
> can you hit the agent download url from the machine that having the problem from IE?

yes I can


> make sure you configure the agent to use the same proxy server as your browser.

How can I do so? I don't see any proxy settings for my browser ... The thing is, IE get run by my account and I successfully download the mentioned URL. However the agent gets run under `Local system account with "Allow service to interact with desctop checkbox on"`  ...

**Comment by TingluoHuang** [comment]
@melezhik can you try use powershell to run as `local system account` and see whether you can hit that url from powershell?

**Comment by melezhik** [comment]
Running commands under user in windows seems not easy, could you give me a hint how can I do so?

**Comment by TingluoHuang** [comment]
@melezhik which `local system account` you are using? NETWORK SERVICE or LOCAL SYSTEM?

**Comment by TingluoHuang** [comment]
maybe this help?
https://stackoverflow.com/questions/6911310/how-do-i-run-as-network-service

**Comment by melezhik** [comment]
local system account

![https://raw.githubusercontent.com/melezhik/images/master/service.png](https://raw.githubusercontent.com/melezhik/images/master/service.png)

**Comment by melezhik** [comment]
Looks like it gets downloaded through local system account, if my understanding PsExec is correct:

  
```
Start-Process -FilePath cmd.exe -Verb Runas -ArgumentList '/k C:\Users\alex\Downloads\PSTools\PsExec.exe -i -s powershell.exe'



PS C:\WINDOWS\system32> $url = "https://vstsagentpackage.azureedge.net/agent/2.1
41.1/vsts-agent-win-x64-2.141.1.zip"
PS C:\WINDOWS\system32> $output = "C:\temp\vsts-agent-win-x64-2.141.1.zip"
PS C:\WINDOWS\system32> Invoke-WebRequest -Uri $url -OutFile $output
PS C:\WINDOWS\system32>
```

**Comment by TingluoHuang** [comment]
try
```
whoami
$url = "https://vstsagentpackage.azureedge.net/agent/2.141.1/vsts-agent-win-x64-2.141.1.zip"
$output = "C:\temp\vsts-agent-win-x64-2.141.1.zip"
Invoke-WebRequest -Uri $url -OutFile $output -NoProxy
```

**Comment by TingluoHuang** [comment]
if `-noproxy` doesn't existing for your powershell version you can do:
```
 $proxy = new-object System.Net.WebProxy
 Invoke-WebRequest -Proxy $proxy -Uri $url -OutFile $output 
```

**Comment by TingluoHuang** [comment]
Most .net applications like Powershell will follow IE's proxy setting by default. The agent is written in dotnet core, and it will not follow IE proxy setting by default.

**Comment by melezhik** [comment]
? what does it mean for me?

**Comment by TingluoHuang** [comment]
try `[System.Net.WebProxy]::GetDefaultProxy()`

do you have proxy server in your network and everyone requires to use them?

few things we tried:
1. `you` can hit the download url from IE (will use IE proxy setting if there is one)
2. `LocalSystem` can hit the download url from Powershell (will use IE proxy setting if there is one)
3. `Agent` that running as `LocalSystem` can't hit the download url.

the agent will not using proxy server unless you configure it to use. (.proxy file under agent root)
the issue might be a result of proxy problem or some intermittent networks issue.
i am trying to figure out which one it is.

**Comment by melezhik** [comment]
as for the `[System.Net.WebProxy]::GetDefaultProxy()`
```
PS C:\WINDOWS\system32> [System.Net.WebProxy]::GetDefaultProxy()


Address               :
BypassProxyOnLocal    : False
BypassList            : {}
Credentials           :
UseDefaultCredentials : False
BypassArrayList       : {}
```

**Comment by melezhik** [comment]
> do you have proxy server in your network and everyone requires to use them?

I think we have but the proxy is not configurable through IE, I am not even sure that it is configurable on this machine ...

**Comment by TingluoHuang** [comment]
@melezhik ok, thanks for your information.
1. does all your agents have similar configuration? run as `LocalSystem` on your windows machine and on the same network.
2. does all your agents hit the same problem during upgrade?

**Comment by melezhik** [comment]
it is correct

**Comment by TingluoHuang** [comment]
@melezhik you might want to check with your network team see whether they block http request base on `User-Agent`.

try
```
whoami
$url = "https://vstsagentpackage.azureedge.net/agent/2.141.1/vsts-agent-win-x64-2.141.1.zip"
$output = "C:\temp\vsts-agent-win-x64-2.141.1.zip"
Invoke-WebRequest -Uri $url -OutFile $output -UserAgent ""
```

**Comment by melezhik** [comment]
`Invoke-WebRequest -Uri $url -OutFile $output -UserAgent ""` works  too ...

**Comment by TingluoHuang** [comment]
What about `Invoke-WebRequest -Uri $url -OutFile $output -UserAgent "BlockMe"`? :D
make sure you still run it as LocalSystem. :)

**Comment by melezhik** [comment]
not blocked:

```
PS C:\WINDOWS\system32> whoami
nt authority\system
PS C:\WINDOWS\system32> Invoke-WebRequest -Uri $url -OutFile $output -UserAgent "BlockMe"
PS C:\WINDOWS\system32>
```

**Comment by TingluoHuang** [comment]
Can you try capture low level network trace when this problem happen, and see which remote host is terminate the request?
here is what you need to do when you want to repro the problem. :D

1. Stop the service
2. delete bin.2.141.1, delete externals.2.141.1
3. delete bin/externals
4. rename bin.2.140.2 back to bin, rename external.2.140.2 back to externals.
5. Start the service and queue a yaml build to this pool.

**Comment by melezhik** [comment]
Hi! Not sure if I understand points 2,3,4
what is ` bin.2.141.1,` and so on?

**Comment by TingluoHuang** [comment]
sorry, i forgot you haven't successfully upgrade yet. you can just queue a YAML build to your pool, it will try push agent upgrade.

the steps i paste is how to re-run upgrade after a succeed upgrade.

**Comment by melezhik** [comment]
Still not clear. what is `bin.2.141.1` ?

**Comment by TingluoHuang** [comment]
it's the internal detail of how the agent doing self-upgrade.
During upgrade:
1. we download 2.141.1 agent.
2. we rename `bin` ->`bin.2.140.2`, `externals`->`externals.2.140.2`
3. from 2.141.1 agent zip, copy `bin` to `bin.2.141.1`, copy `externals` to `externals.2.141.1`
4. create junction folder `bin` point to `bin.2.141.1` and junction `externals` point to `externals.2.141.1`
