### ISSUE TITLE
Jobs fail to start on Linux agent: "Input/output error"

### ISSUE THREAD

**Issue by sshorkey** [Microsoft/azure-pipelines-agent#2013]
Every attempt to run jobs on a private Linux agent fails; when I attempt to run the job in Pipelines, it stays stuck at "An agent is ready for the job. Connecting..." for a few minutes, then fails with:

"The agent: <agent> lost communication with the server. Verify the machine is running and has a healthy network connection. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610"

When viewing the logs on the agent, this is what shows up:

```
[2018-12-12 21:13:42Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/vmadmin/.credentials_rsaparams
[2018-12-12 21:13:42Z INFO MessageListener] Message '6' received from session '59965243-262d-4d87-a2a4-f5c054e4ac59'.
[2018-12-12 21:13:42Z INFO JobDispatcher] Job request 23 for plan 1fec785d-9d96-4430-b18d-627a59faa1b6 job 011e1ec8-6569-5e69-4f06-baf193d1351e received.
[2018-12-12 21:13:42Z ERR  JobDispatcher] Worker Dispatch failed witn an exception for job request 011e1ec8-6569-5e69-4f06-baf193d1351e.
[2018-12-12 21:13:42Z ERR  JobDispatcher] System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count)
   at System.ConsolePal.Write(SafeFileHandle fd, Byte[] buffer, Int32 offset, Int32 count)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.EnsureDispatchFinished(WorkerDispatcher jobDispatch, Boolean cancelRunningJob)
[2018-12-12 21:13:42Z INFO Terminal] WRITE LINE: 2018-12-12 21:13:42Z: Running job: Job

```
I'm running 2.144.0 of the agent software.

**Comment by TingluoHuang** [comment]
@sshorkey the error indicates agent can't write output to STDOUT/STDERR, how is your agent process got launched? did you close STDOUT/STDERR?
