### ISSUE TITLE
Null Ref exception in ProcessInvoker during cancellation

### ISSUE THREAD

**Issue by TingluoHuang** [Microsoft/azure-pipelines-agent#2042]
##[Error 1]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.WindowsKillProcessTree()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<CancelAndKillProcessTree>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.<>c__DisplayClass26_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by TingluoHuang** [comment]
yes.
