### ISSUE TITLE
Agent connection fail

### ISSUE THREAD

**Issue by hanxinimm** [Microsoft/azure-pipelines-agent#2124]
[2019-02-25 09:15:36Z INFO AgentProcess] Agent is built for Windows - win-x64.
[2019-02-25 09:15:36Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 6.3.9600 .
[2019-02-25 09:15:36Z INFO AgentProcess] Version: 2.131.0
[2019-02-25 09:15:36Z INFO AgentProcess] Commit: 0cf7b2e90c2258027f198114885ce8d9f9f3497e
[2019-02-25 09:15:36Z INFO AgentProcess] Culture: zh-CN
[2019-02-25 09:15:36Z INFO AgentProcess] UI Culture: zh-CN

[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'Agent.Name': 'WIN-AGENT-4'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'Agent.OS': 'Windows_NT'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentMajorVersionNumber' is null.
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentMinorVersionNumber' is null.
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentVersion': '6.3'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentBuildNumber': '9600'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'Agent.OSVersion': '6.3.9600'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'Cmd': 'C:\Windows\system32\cmd.exe'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'InteractiveSession': 'False'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'Agent.Version': '2.136.1'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'Agent.ComputerName': 'WIN-AGENT-4'
[2019-02-25 10:42:57Z INFO HostContext] Well known directory 'Bin': 'C:\vstsagent\bin'
[2019-02-25 10:42:57Z INFO HostContext] Well known directory 'Root': 'C:\vstsagent'
[2019-02-25 10:42:57Z INFO AgentCapabilitiesProvider] Adding 'Agent.HomeDirectory': 'C:\vstsagent'
[2019-02-25 10:42:57Z INFO ConfigurationStore] HasCredentials()
[2019-02-25 10:42:57Z INFO ConfigurationStore] stored True
[2019-02-25 10:42:57Z INFO CredentialManager] GetCredentialProvider
[2019-02-25 10:42:57Z INFO CredentialManager] Creating type OAuth
[2019-02-25 10:42:57Z INFO CredentialManager] Creating credential type: OAuth
[2019-02-25 10:42:57Z INFO HostContext] Well known directory 'Bin': 'C:\vstsagent\bin'
[2019-02-25 10:42:57Z INFO HostContext] Well known directory 'Root': 'C:\vstsagent'
[2019-02-25 10:42:57Z INFO HostContext] Well known config file 'RSACredentials': 'C:\vstsagent\.credentials_rsaparams'
[2019-02-25 10:42:57Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vstsagent\.credentials_rsaparams
[2019-02-25 10:42:58Z INFO Terminal] WRITE LINE: 正在连接到服务器。
[2019-02-25 10:42:58Z INFO MessageListener] Attempt to create session.
[2019-02-25 10:42:58Z INFO MessageListener] Connecting to the Agent Server...
[2019-02-25 10:42:58Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-02-25 10:42:58Z ERR  VisualStudioServices] GET request to https://tfs.cp.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: 发生了安全错误
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
[2019-02-25 10:42:58Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-02-25 10:42:58Z INFO AgentServer] Catch exception during connect. 4 attemp left.
[2019-02-25 10:42:58Z ERR  AgentServer] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: 发生了安全错误
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()

**Comment by TingluoHuang** [comment]
@hanxinimm did you install your TFS server's SSL certificate into the agent machine certificate store.

**Comment by hanxinimm** [comment]
@hanxinimm  yes,i can cnfig it success,but service run is connection fail~
![image](https://user-images.githubusercontent.com/13499426/53381598-39e55600-39ac-11e9-8eee-87bf9b355de5.png)

**Comment by TingluoHuang** [comment]
@hanxinimm you might want to install the certificate into your service account's cert store or mahinc level cert store.
I guess, when you configure, you login the machine as USER_A, but you configure the agent run as service for USER_B and you didn't install the certificate for USER_B.

**Comment by hanxinimm** [comment]
@TingluoHuang  you right,i install the certificate in local machine,it ok~

**Comment by TingluoHuang** [comment]
@hanxinimm cool, glad you unblock, i am going to close this issue, please reopen if you need more help. :D
