### ISSUE TITLE
Integration with Test result log parser causes timeout in on-prem agent

### ISSUE THREAD

**Issue by dmossberg** [microsoft/azure-pipelines-agent#2138]
## Agent Version and Platform
Version of your agent? 
**2.148.0 (x64)**

We noticed in this version, one of the features added is:

- _Integrate Log Parser with master #2066_

OS of the machine running the agent? OSX/Windows/Linux/...
**Windows Server 2016 (Version 1607)**

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
**dev.azure.com**

If dev.azure.com, what is your organization name? 
**https://dev.azure.com/bankinter**

## What's not working?
After a successful release, the **Finalize Job** task takes about 4 minutes, and shows the output below. The releases ends succesfully, but this adds an additional 4 min to finalize: 

```
2019-03-06T15:26:17.1310880Z ##[section]Starting: Finalize Job
2019-03-06T15:28:36.6152178Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-06T15:28:36.6152614Z    --- End of inner exception stack trace ---
2019-03-06T15:28:36.6152735Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-06T15:28:36.6152827Z    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-06T15:28:36.6152937Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-03-06T15:28:36.6153029Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2019-03-06T15:28:36.6153435Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
2019-03-06T15:28:36.6153545Z    at Microsoft.VisualStudio.Services.CustomerIntelligence.WebApi.CustomerIntelligenceHttpClient.PublishEventsAsync(CustomerIntelligenceEvent[] events, Object userState, CancellationToken cancellationToken)
2019-03-06T15:28:36.6153652Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.PopulatePipelineConfig(IAgentLogPluginContext context)
2019-03-06T15:28:36.6153725Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.InitializeAsync(IAgentLogPluginContext context)
2019-03-06T15:28:36.6153817Z TestResultLogParser: Warning: Unable to initialize TestResultLogParser.
2019-03-06T15:30:16.5896286Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-06T15:30:16.5896458Z    --- End of inner exception stack trace ---
2019-03-06T15:30:16.5896528Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-06T15:30:16.5896627Z    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-06T15:30:16.5896711Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-03-06T15:30:16.5896821Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2019-03-06T15:30:16.5897136Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
2019-03-06T15:30:16.5897345Z    at Microsoft.VisualStudio.Services.CustomerIntelligence.WebApi.CustomerIntelligenceHttpClient.PublishEventsAsync(CustomerIntelligenceEvent[] events, Object userState, CancellationToken cancellationToken)
2019-03-06T15:30:16.5897532Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.InitializeAsync(IAgentLogPluginContext context)
2019-03-06T15:30:16.5897672Z    at Agent.Sdk.AgentLogPluginHost.RunAsync(IAgentLogPlugin plugin, CancellationToken token)
2019-03-06T15:30:16.5897965Z TestResultLogParser: Waiting for log plugin to finish, pending process 1329 log lines.
2019-03-06T15:30:16.5898214Z TestResultLogParser: Fail to process output: Fail to initialize: The HTTP request timed out after 00:01:40..
2019-03-06T15:30:16.5911885Z Start cleaning up orphan processes.
2019-03-06T15:30:16.6262381Z ##[section]Finishing: Finalize Job
```

Most likelly, our firewall is not allowing the traffic requiered by the **TestResultLogParser**. Is it possible to disable this feature? What URLs need to be enabled?

**Comment by TingluoHuang** [comment]
@dmossberg set `agent.disablelogplugin=true` on your definition should unblock you. if you have too many definition needs to modified, i can turn it off from server side for your entire account.

**Comment by TingluoHuang** [comment]
@nigurr FYI,

**Comment by dmossberg** [comment]
> @dmossberg set `agent.disablelogplugin=true` on your definition should unblock you. if you have too many definition needs to modified, i can turn it off from server side for your entire account.

Thanks @TingluoHuang, we have quite a few so please go ahead and turn it off for our entire account. 

Thanks, 
Daniel

**Comment by nigurr** [comment]
@dmossberg Currently Service side deployment is still on going. Once it's fully rolled out, this will be disabled automatically.
Because of delay in service deployment, it's getting activated for all builds.

**Comment by TingluoHuang** [comment]
@dmossberg the service side deployment has finished for your account, so the problem should goes away even i didn't do anything for your account, can you confirm whether you still seeing any problem?

**Comment by dmossberg** [comment]
> @dmossberg the service side deployment has finished for your account, so the problem should goes away even i didn't do anything for your account, can you confirm whether you still seeing any problem?

@TingluoHuang we are still seeing the problem unfortunatelly, can you turn it off for our account?

**Comment by nigurr** [comment]
@dmossberg It's already turned off for your account. Can you share your latest build logs where you are facing this issue?

**Comment by nigurr** [comment]
@dmossberg It's turned off for your account

**Comment by dmossberg** [comment]
@nigurr Then "turning off" is not working as expected, we still see this:  

`2019-03-20T17:07:56.8083106Z ##[section]Starting: Finalize Job
2019-03-20T17:07:56.8146325Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-20T17:07:56.8146395Z    --- End of inner exception stack trace ---
2019-03-20T17:07:56.8146428Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-20T17:07:56.8146465Z    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-20T17:07:56.8146556Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-03-20T17:07:56.8146589Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2019-03-20T17:07:56.8147124Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
2019-03-20T17:07:56.8147161Z    at Microsoft.VisualStudio.Services.CustomerIntelligence.WebApi.CustomerIntelligenceHttpClient.PublishEventsAsync(CustomerIntelligenceEvent[] events, Object userState, CancellationToken cancellationToken)
2019-03-20T17:07:56.8147440Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.PopulatePipelineConfig(IAgentLogPluginContext context)
2019-03-20T17:07:56.8147476Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.InitializeAsync(IAgentLogPluginContext context)
2019-03-20T17:07:56.8147561Z TestResultLogParser: Warning: Unable to initialize TestResultLogParser.
2019-03-20T17:07:56.8148023Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-20T17:07:56.8148074Z    --- End of inner exception stack trace ---
2019-03-20T17:07:56.8148107Z    at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-20T17:07:56.8148166Z    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-03-20T17:07:56.8148206Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-03-20T17:07:56.8148243Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2019-03-20T17:07:56.8148301Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
2019-03-20T17:07:56.8148345Z    at Microsoft.VisualStudio.Services.CustomerIntelligence.WebApi.CustomerIntelligenceHttpClient.PublishEventsAsync(CustomerIntelligenceEvent[] events, Object userState, CancellationToken cancellationToken)
2019-03-20T17:07:56.8148404Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.InitializeAsync(IAgentLogPluginContext context)
2019-03-20T17:07:56.8148448Z    at Agent.Sdk.AgentLogPluginHost.RunAsync(IAgentLogPlugin plugin, CancellationToken token)
2019-03-20T17:07:56.8148752Z TestResultLogParser: Fail to process output: Fail to initialize: The HTTP request timed out after 00:01:40..
2019-03-20T17:07:56.8431042Z Start cleaning up orphan processes.
2019-03-20T17:07:56.9090236Z ##[section]Finishing: Finalize Job`

Any suggestions?

**Comment by nigurr** [comment]
@dmossberg I checked the feature flag and it's already turned off.
Do you have any build variable `agent.disablelogplugin` in your pipeline. If so, please remove it

**Comment by dmossberg** [comment]
@nigurr no we don't, we never made any changes awaiting for the feature to get turned off at the account level

**Comment by nigurr** [comment]
@TingluoHuang can you please help on this?

**Comment by pedroneil** [comment]
Hello, why is this closed? Our on Premise Self Hoted Agent Deployments time has increase nearly exponentially.

why should I have to add this variable to the Releases when the release definitions doe not even have a Test phase or when it was not required in 2.147 and I do not like the idea of setting the variable agent.disablelogplugin at subscription level?

There are 10s of Release definitions and the extra time taken for each TaskGroup and Agent Phase results in multiples of 100 seconds longer per release e.g. A release with 3 Stages and 6 phases is taking nearly 30minutes longer since upgrading to 2.148.1

**Comment by nigurr** [comment]
@pedroneil Can you please share your account name?

**Comment by pedroneil** [comment]
@nigurr I am unable to share the account name on this thread.  You would have to provide me with an email address to PM you.

This issue occurs on both Linux and Windows hosted Agents and started occuring after the upgrade to 2.148.1

The release Definitions use Task Groups and have no Tests or Upload Tests. We do use an Upload Test Results Task but not in the Release Definitions to which I am referring.

**Comment by nigurr** [comment]
@pedroneil 
please mail us at devops_tools at microsoft

**Comment by pedroneil** [comment]
I attempted using .com but the email bounced.
Acc is
ReAssure-dev
Visual Studio
.com

I have seen this issue using he upload test results task where the release
upload test results task is powershell and fails as it dies not correctly
use the vsts proxy utility,  the same agent can upset test results for tree
build test results task and hat task is written in node

**Comment by nigurr** [comment]
@pedroneil I have disabled this temporarily for this account.
@dmossberg Can you share your build/release logs with "debug" mode and share to devops_tools at microsoft

**Comment by tinytone** [comment]
The Finalize Job step on all our pipelines is erroring and adding an additional 2 minutes 28 seconds to all our release pipelines.
```
2019-04-01T14:26:11.9731379Z ##[section]Starting: Finalize Job
2019-04-01T14:28:40.1764097Z    at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
2019-04-01T14:28:40.1764183Z    at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
2019-04-01T14:28:40.1764250Z    --- End of inner exception stack trace ---
2019-04-01T14:28:40.1764293Z    at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-04-01T14:28:40.1764338Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-04-01T14:28:40.1764417Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2019-04-01T14:28:40.1764468Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
2019-04-01T14:28:40.1764561Z    at Microsoft.VisualStudio.Services.CustomerIntelligence.WebApi.CustomerIntelligenceHttpClient.PublishEventsAsync(CustomerIntelligenceEvent[] events, Object userState, CancellationToken cancellationToken)
2019-04-01T14:28:40.1764635Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.PopulatePipelineConfig(IAgentLogPluginContext context)
2019-04-01T14:28:40.1764687Z    at Agent.Plugins.Log.TestResultParser.Plugin.TestResultLogPlugin.InitializeAsync(IAgentLogPluginContext context)
2019-04-01T14:28:40.1764728Z TestResultLogParser: Warning: Unable to initialize TestResultLogParser.
...
2019-04-01T14:28:40.1791571Z ##[section]Finishing: Finalize Job
```

Is this an error that is currently being looked into with an expected fix? It's adding hours (cumulatively) to the waiting time for each of our releases throughout our teams and is not ideal

**Comment by tinytone** [comment]
Hi all,
The Finalize Job step has suddenly dropped from 2 minutes 30 to less than 1 second. I'm not sure if a change has gone in... but if one has "Thank you!". This will make a big difference on our side to the release times:

```
2019-04-02T08:48:59.2618629Z ##[section]Starting: Finalize Job
2019-04-02T08:48:59.2657274Z Start cleaning up orphan processes.
2019-04-02T08:48:59.2665279Z ##[section]Finishing: Finalize Job
```

Thank you :)

**Comment by nigurr** [comment]
@tinytone @dmossberg @pedroneil 

I need more info on your usage for better solution and avoiding such breakages

1. Are you using Self hosted Agents?
2. Are they behind any proxy?
3. Are they are having issues with build pipeline/release pipeline?

Please do share this info to help us better

**Comment by pedroneil** [comment]
@nigurr 

1. The agents are self hosted - Linux and Windows
2. They are behind a proxy that requires Domain Account Authentication
3. It is the release pipeline Finalize

The issue does NOT occur on Windows Agents that are installed with a Domain Account so that they can publish test results through the Proxy to Azure DevOps Release Definitions using the
