### ISSUE TITLE
Release Agent lost connection with Azure: https://dev.azure.com

### ISSUE THREAD

**Issue by ComicCameleo** [microsoft/azure-pipelines-agent#2155]
## Having issue with software on Hosted Agent?
no

## Have you tried troubleshooting?
Yes

## Agent Version and Platform
vsts-agent-win-x64-2.144.0
Windows Server 2016 Standard

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
Release agents become not available or not responsible during and before stage runs of Release Pipelines. This causes current stage failure and stops next stages from running. To bring Agent to live after this crash we have to restart it.
This happens regularly with different error messages. Last error: "Unhandled: read ECONNRESET"
Issue happens with Agent Pool of 25 Release Agents. These agents installed on 25 virtual machines in private cloud. Release Agents is running as interactive process: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#account.
We investigated Event logs, Agent logs, performance metrics on VM when Agent became not responsible but did not found the root cause.

## Agent and Worker's Diagnostic Logs
Agent`s logs:
[2019-03-10 21:02:29Z INFO MessageListener] Attempt to create session.
[2019-03-10 21:02:29Z INFO MessageListener] Connecting to the Agent Server...
[2019-03-10 21:02:29Z INFO MessageListener] Session created.
[2019-03-10 21:02:29Z INFO Terminal] WRITE LINE: 2019-03-10 21:02:29Z: Agent reconnected.
[2019-03-10 21:02:29Z INFO Terminal] WRITE LINE: 2019-03-10 21:02:29Z: Listening for Jobs
[2019-03-10 21:02:29Z INFO JobDispatcher] Set agent/worker IPC timeout to 30 seconds.
[2019-03-10 21:22:40Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vsts-agent-win-x64-2.144.0\.credentials_rsaparams
[2019-03-10 21:22:40Z INFO MessageListener] Message '1181' received from session 'e5d2e1f0-a96f-49ab-ab31-4b18eda8c7fe'.
[2019-03-10 21:22:40Z INFO JobDispatcher] Job request 41204 for plan 7c756cd8-f26c-4999-9a75-6d17c495000f job 499666d5-4242-4a21-ac0f-b97471935c0b received.
[2019-03-10 21:22:40Z INFO Terminal] WRITE LINE: 2019-03-10 21:22:40Z: Running job: Agent 11 of 15
[2019-03-10 21:22:40Z INFO JobDispatcher] Start renew job request 41204 for job 499666d5-4242-4a21-ac0f-b97471935c0b.
[2019-03-10 21:22:41Z INFO JobDispatcher] Successfully renew job request 41204, job is valid till 3/10/2019 9:32:41 PM
[2019-03-10 21:22:41Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper] Starting process:
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper]   File name: 'C:\vsts-agent-win-x64-2.144.0\bin\Agent.Worker.exe'
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper]   Arguments: 'spawnclient 2368 2312'
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper]   Working directory: 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'True'
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper]   Lines to send through STDIN: '0'
[2019-03-10 21:22:41Z INFO ProcessInvokerWrapper] Process started with process id 5028, waiting for process exit.
[2019-03-10 21:22:41Z INFO JobDispatcher] Send job request message to worker for job 499666d5-4242-4a21-ac0f-b97471935c0b.
[2019-03-10 21:22:41Z INFO JobNotification] Entering JobStarted Notification
[2019-03-10 21:22:56Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:56Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:56Z INFO ProcessInvokerWrapper] Finished process 5028 with exit code 102, and elapsed time 00:00:15.1041016.
[2019-03-10 21:22:56Z INFO JobDispatcher] Worker finished for job 499666d5-4242-4a21-ac0f-b97471935c0b. Code: 102
[2019-03-10 21:22:56Z INFO JobDispatcher] finish job request for job 499666d5-4242-4a21-ac0f-b97471935c0b with result: Failed
[2019-03-10 21:22:56Z INFO Terminal] WRITE LINE: 2019-03-10 21:22:56Z: Job Agent 11 of 15 completed with result: Failed
[2019-03-10 21:22:56Z INFO JobDispatcher] Stop renew job request for job 499666d5-4242-4a21-ac0f-b97471935c0b.
[2019-03-10 21:22:56Z INFO JobDispatcher] job renew has been canceled, stop renew job request 41204.
[2019-03-10 21:22:56Z INFO JobNotification] Entering JobCompleted Notification
[2019-03-10 21:52:43Z INFO MessageListener] No message retrieved from session 'e5d2e1f0-a96f-49ab-ab31-4b18eda8c7fe' within last 30 minutes.
[2019-03-10 21:57:43Z WARN VisualStudioServices] Authentication failed with status code 401.

Worker's log
[2019-03-10 21:22:43Z INFO ReleaseJobExtension] Parsing all task's condition inputs.
[2019-03-10 21:22:43Z INFO ExpressionManager] Parsing expression: <succeeded()>
[2019-03-10 21:22:43Z INFO ExpressionManager] Parsing expression: <succeededOrFailed()>
[2019-03-10 21:22:43Z INFO ExpressionManager] Parsing expression: <succeededOrFailed()>
[2019-03-10 21:22:43Z INFO ExpressionManager] Parsing expression: <succeededOrFailed()>
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Work': 'C:\vsts-agent-win-x64-2.144.0\_work'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Tasks': 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks'
[2019-03-10 21:22:43Z INFO TaskManager] Loading task definition 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.148.0\task.json'.
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Work': 'C:\vsts-agent-win-x64-2.144.0\_work'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Tasks': 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks'
[2019-03-10 21:22:43Z INFO TaskManager] Loading task definition 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\task.json'.
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Work': 'C:\vsts-agent-win-x64-2.144.0\_work'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Tasks': 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks'
[2019-03-10 21:22:43Z INFO TaskManager] Loading task definition 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.1.5\task.json'.
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Work': 'C:\vsts-agent-win-x64-2.144.0\_work'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Tasks': 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks'
[2019-03-10 21:22:43Z INFO TaskManager] Loading task definition 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.148.7\task.json'.
[2019-03-10 21:22:43Z INFO ReleaseJobExtension] Adding pre-job step from extension.
[2019-03-10 21:22:43Z INFO ReleaseJobExtension] Adding post-job step from extension.
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Diag': 'C:\vsts-agent-win-x64-2.144.0\_diag'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Diag': 'C:\vsts-agent-win-x64-2.144.0\_diag'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Diag': 'C:\vsts-agent-win-x64-2.144.0\_diag'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:43Z INFO HostContext] Well known directory 'Diag': 'C:\vsts-agent-win-x64-2.144.0\_diag'
[2019-03-10 21:22:43Z INFO ReleaseJobExtension] Adding post-job steps from tasks.
[2019-03-10 21:22:43Z INFO JobRunner] Total job steps: 4.
[2019-03-10 21:22:44Z INFO JobRunner] Total accessible running process: 63.
[2019-03-10 21:22:44Z INFO JobRunner] Run all job steps.
[2019-03-10 21:22:44Z INFO StepsRunner] Processing step: DisplayName='Download artifact - EWB.RunUITests_RD - drop', ContinueOnError=False, Enabled=True
[2019-03-10 21:22:44Z INFO ExpressionManager] Evaluating: succeeded()
[2019-03-10 21:22:44Z INFO ExpressionManager] Result: True
[2019-03-10 21:22:44Z INFO StepsRunner] Starting the step.
[2019-03-10 21:22:44Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:44Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:44Z INFO HostContext] Well known directory 'Work': 'C:\vsts-agent-win-x64-2.144.0\_work'
[2019-03-10 21:22:44Z INFO HostContext] Well known directory 'Tasks': 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks'
[2019-03-10 21:22:44Z INFO TaskManager] Loading task definition 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.148.0\task.json'.
[2019-03-10 21:22:44Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IWorkerCommandExtension'
[2019-03-10 21:22:44Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension, Agent.Worker
[2019-03-10 21:22:44Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.ArtifactCommandExtension, Agent.Worker
[2019-03-10 21:22:44Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildCommandExtension, Agent.Worker
[2019-03-10 21:22:44Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.CodeCoverage.CodeCoverageCommandExtension, Agent.Worker
[2019-03-10 21:22:44Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.TestResults.ResultsCommandExtension, Agent.Worker
[2019-03-10 21:22:44Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Telemetry.TelemetryCommandExtension, Agent.Worker
[2019-03-10 21:22:44Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseCommandExtension, Agent.Worker
[2019-03-10 21:22:44Z INFO WorkerCommandManager] Register command extension for area task
[2019-03-10 21:22:44Z INFO WorkerCommandManager] Register command extension for area artifact
[2019-03-10 21:22:44Z INFO WorkerCommandManager] Register command extension for area build
[2019-03-10 21:22:44Z INFO WorkerCommandManager] Register command extension for area codecoverage
[2019-03-10 21:22:44Z INFO WorkerCommandManager] Register command extension for area results
[2019-03-10 21:22:44Z INFO WorkerCommandManager] Register command extension for area telemetry
[2019-03-10 21:22:44Z INFO WorkerCommandManager] Register command extension for area release
[2019-03-10 21:22:44Z INFO NodeHandler] Inspect node_modules folder, make sure vsts-task-lib doesn't overwrite String.startsWith/endsWith.
[2019-03-10 21:22:44Z INFO NodeHandler] This task has already been scanned and corrected, no more operation needed.
[2019-03-10 21:22:44Z INFO NodeHandler] Task.json has node10 handler data: False, use node10 for node tasks: False
[2019-03-10 21:22:44Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:44Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:44Z INFO HostContext] Well known directory 'Externals': 'C:\vsts-agent-win-x64-2.144.0\externals'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Starting process:
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper]   File name: 'C:\vsts-agent-win-x64-2.144.0\externals\node\bin\node.exe'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper]   Arguments: '"C:\vsts-agent-win-x64-2.144.0\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.148.0\main.js"'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper]   Working directory: 'C:\vsts-agent-win-x64-2.144.0\_work\r7\a'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper]   Encoding web name: utf-8 ; code page: '65001'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper]   Lines to send through STDIN: '0'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Process started with process id 4132, waiting for process exit.
[2019-03-10 21:22:45Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'e33796db-1549-4f12-b9d8-626036bad6cf', success rate: 1/1.
[2019-03-10 21:22:45Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2019-03-10 21:22:46Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'e33796db-1549-4f12-b9d8-626036bad6cf', success rate: 1/1.
[2019-03-10 21:22:46Z INFO JobServerQueue] Try to append 1 batches web console lines for record '61d0c62a-5f47-4bb7-a2cf-2ccfa361f7cb', success rate: 1/1.
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] Finished process 4132 with exit code 7, and elapsed time 00:00:04.3013165.
[2019-03-10 21:22:48Z ERR  StepsRunner] Caught exception from step: Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 7 returned from process: file name 'C:\vsts-agent-win-x64-2.144.0\externals\node\bin\node.exe', arguments '"C:\vsts-agent-win-x64-2.144.0\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.148.0\main.js"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, IList`1 contentsToStandardIn, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, IList`1 contentsToStandardIn, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
[2019-03-10 21:22:48Z INFO StepsRunner] Step result: Failed
[2019-03-10 21:22:48Z INFO StepsRunner] Update job result with current step result 'Failed'.
[2019-03-10 21:22:48Z INFO StepsRunner] Current state: job state = 'Failed'
[2019-03-10 21:22:48Z INFO StepsRunner] Processing step: DisplayName='Adding settings to custom.runsettings', ContinueOnError=False, Enabled=True
[2019-03-10 21:22:48Z INFO ExpressionManager] Evaluating: succeededOrFailed()
[2019-03-10 21:22:48Z INFO ExpressionManager] Result: True
[2019-03-10 21:22:48Z INFO StepsRunner] Starting the step.
[2019-03-10 21:22:48Z INFO HostContext] Well known directory 'Bin': 'C:\vsts-agent-win-x64-2.144.0\bin'
[2019-03-10 21:22:48Z INFO HostContext] Well known directory 'Root': 'C:\vsts-agent-win-x64-2.144.0'
[2019-03-10 21:22:48Z INFO HostContext] Well known directory 'Work': 'C:\vsts-agent-win-x64-2.144.0\_work'
[2019-03-10 21:22:48Z INFO HostContext] Well known directory 'Tasks': 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks'
[2019-03-10 21:22:48Z INFO TaskManager] Loading task definition 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\task.json'.
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Generation: '1'
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Generation: '3'
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.14393.0'
[2019-03-10 21:22:48Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] Starting process:
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper]   File name: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper]   Arguments: '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\vsts-agent-win-x64-2.144.0\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\InlinePowershell.ps1'''))"'
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper]   Working directory: 'C:\vsts-agent-win-x64-2.144.0\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7'
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper]   Lines to send through STDIN: '0'
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] Process started with process id 3432, waiting for process exit.
[2019-03-10 21:22:48Z INFO JobServerQueue] Try to append 1 batches web console lines for record '61d0c62a-5f47-4bb7-a2cf-2ccfa361f7cb', success rate: 1/1.
[2019-03-10 21:22:48Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'c6e04d34-3bd5-464a-b476-0eb12ee034fc', success rate: 1/1.
[2019-03-10 21:22:49Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2019-03-10 21:22:50Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'c6e04d34-3bd5-464a-b476-0eb12ee034fc', success rate: 1/1.
[2019-03-10 21:22:51Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:51Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:51Z INFO ProcessInvokerWrapper] Finished process 3432 with exit code 0, and elapsed time 00:00:02.7088855.
[2019-03-10 21:22:51Z INFO StepsRunner] Step result: Failed

**Comment by TingluoHuang** [comment]
```
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Starting process:
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] File name: 'C:\vsts-agent-win-x64-2.144.0\externals\node\bin\node.exe'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Arguments: '"C:\vsts-agent-win-x64-2.144.0_work_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.148.0\main.js"'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Working directory: 'C:\vsts-agent-win-x64-2.144.0_work\r7\a'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Require exit code zero: 'True'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Encoding web name: utf-8 ; code page: '65001'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Force kill process on cancellation: 'False'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Lines to send through STDIN: '0'
[2019-03-10 21:22:44Z INFO ProcessInvokerWrapper] Process started with process id 4132, waiting for process exit.
[2019-03-10 21:22:45Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'e33796db-1549-4f12-b9d8-626036bad6cf', success rate: 1/1.
[2019-03-10 21:22:45Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2019-03-10 21:22:46Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'e33796db-1549-4f12-b9d8-626036bad6cf', success rate: 1/1.
[2019-03-10 21:22:46Z INFO JobServerQueue] Try to append 1 batches web console lines for record '61d0c62a-5f47-4bb7-a2cf-2ccfa361f7cb', success rate: 1/1.
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2019-03-10 21:22:48Z INFO ProcessInvokerWrapper] Finished process 4132 with exit code 7, and elapsed time 00:00:04.3013165.
```
@ComicCameleo looks like the `node.exe` exits with return code 7 which should never happened.
https://github.com/nodejs/node/blob/master/doc/api/process.md#exit-codes

can you try logon the machine run `node.exe` manually see what might happen?

**Comment by Shakevg** [comment]
@TingluoHuang Node.js console is opening when we are running node.exe manually

**Comment by TingluoHuang** [comment]
@Shakevg what's the return code for your manual invocation? do you get consistent repro?

**Comment by ComicCameleo** [comment]
Yes, issue reproducing. @TingluoHuang what do you mean by "return code for your manual invocation"? node.js?

**Comment by Shakevg** [comment]
Problem was related with network adapter issue on virtual machine with Agent.
Microsoft helped to figure out the root cause and we are working on fix.
Issue can be closed.
