### ISSUE TITLE
Getting HTTP Status: ProxyAuthenticationRequired when starting agent.listener

### ISSUE THREAD

**Issue by freebird8x** [Microsoft/azure-pipelines-agent#2171]
When we deployed the azure-pipelines-agent image locally on a Windows PC using Docker CE, the deployment went fine and we were able to connect to the agent pool. However, when deployed the same image to OpenShift, we kept getting this error: 
`POST request to https://<project>.vssps.visualstudio.com/_apis/oauth2/token failed. HTTP Status: ProxyAuthenticationRequired`

Looking into the debug log, the only difference between the two environments is at this REST API call:

**On OpenShift**
`X-TFS-FedAuthRedirect: https://spsprodeus22.vssps.visualstudio.com/_signin?realm=<project>.visualstudio.com&reply_to=https://<project>.visualstudio.com/_apis/connectionData?`**`connectOptions=1&lastChangeId=-1&lastChangeId64=-1`**`&redirect=1&aadinmsa=true&context=<encrypted>`

**Locally via Docker CE**
`X-TFS-FedAuthRedirect: https://spsprodeus22.vssps.visualstudio.com/_signin?realm=<project>.visualstudio.com&reply_to=https://<project>.visualstudio.com/_apis/connectionData?`**`connectOptions=0&lastChangeId=226832426&lastChangeId64=226832426`**`&redirect=1&aadinmsa=true&context=<encrypted>`

And in these API calls, the only differences are at the connectionOptions and lastChangeId parameters. Could these differences cause the failures? What are these parameters for and where do they get the values from?

Proxy seems to be OK since the script was able to download the agent before this error occurred.

Greatly appreciate any help solving this problem.

**Comment by TingluoHuang** [comment]
@freebird8x did you configure the agent to talk through your proxy? and make sure you don't have firewall rules that block the call.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows

**Comment by freebird8x** [comment]
Yup we did. Both the Windows PC and the OpenShift server are on-prem network and were configured with the same proxy settings. In fact, all environment variables, including proxy, are the same for the 2 deployments.

**Comment by TingluoHuang** [comment]
can you share full log for agent inside `OpenShift`?
you can paste here or send me email `tihuang @ microsoft.com`

**Comment by freebird8x** [comment]
definitely
```
Successfully added the agent
[2019-03-15 14:52:04Z INFO ConfigurationManager] Agent server url resolve by server: 'https://<project>.visualstudio.com/'.
[2019-03-15 14:52:04Z INFO ConfigurationStore] Saving OAuth credential @ /ado/agent/.credentials
[2019-03-15 14:52:04Z INFO ConfigurationStore] Credentials Saved.
[2019-03-15 14:52:04Z INFO Terminal] WRITE LINE: Testing agent connection.
[2019-03-15 14:52:04Z INFO ConfigurationStore] HasCredentials()
[2019-03-15 14:52:04Z INFO ConfigurationStore] stored True
[2019-03-15 14:52:04Z INFO CredentialManager] GetCredentialProvider
[2019-03-15 14:52:04Z INFO CredentialManager] Creating type OAuth
[2019-03-15 14:52:04Z INFO CredentialManager] Creating credential type: OAuth
[2019-03-15 14:52:04Z INFO RSAFileKeyManager] Loading RSA key parameters from file /ado/agent/.credentials_rsaparams
[2019-03-15 14:52:04Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2019-03-15 14:52:04Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-03-15 14:52:04Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/<guid>, Basic realm="https://tfsprodscussu5.app.visualstudio.com/", TFS-Federated
X-TFS-ProcessId: <guid>
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: <guid>
X-TFS-Session: <guid>
X-VSS-E2EID: <guid>
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://tfsprodscussu5.app.visualstudio.com/
X-TFS-FedAuthIssuer: https://<project>.visualstudio.com/
X-VSS-AuthorizationEndpoint: https://<project>.vssps.visualstudio.com/
X-VSS-ResourceTenant: <guid>
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://spsprodeus22.vssps.visualstudio.com/_signin?realm=<project>.visualstudio.com&reply_to=https%3A%2F%2F<project>.visualstudio.com%2F_apis%2FconnectionData%3FconnectOptions%3D1%26lastChangeId%3D-1%26lastChangeId64%3D-1&redirect=1&aadinmsa=true&context=<****>#ctx=<****>
X-Content-Type-Options: nosniff
X-MSEdge-Ref: Ref A: 911231DDD3D84D4B8C953B4C38A00D4E Ref B: SN1EDGE1015 Ref C: 2019-03-15T14:52:04Z
Date: Fri, 15 Mar 2019 14:52:03 GMT
[2019-03-15 14:52:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file /ado/agent/.credentials_rsaparams
[2019-03-15 14:52:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file /ado/agent/.credentials_rsaparams
[2019-03-15 14:52:05Z ERR  VisualStudioServices] POST request to https://<project>.vssps.visualstudio.com/_apis/oauth2/token failed. HTTP Status: ProxyAuthenticationRequired
[2019-03-15 14:52:05Z ERR  VisualStudioServices] OAuth issued token provider instance 45176538 failed to retrieve a token.
Reason: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenHttpClient.GetTokenAsync(VssOAuthGrant grant, VssOAuthClientCredential credential, VssOAuthTokenParameters tokenParameters, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
[2019-03-15 14:52:05Z WARN VisualStudioServices] Authentication failed with status code 401.
```

**Comment by TingluoHuang** [comment]
@freebird8x 
when you configure the agent with proxy, did you provide proxy credential to it?

your proxy server requires different proxy credential when the agent making request to `https://<project>.vssps.visualstudio.com/_apis/oauth2/token`

when making request to `https://<project>.visualstudio.com/_apis/connectionData`, your proxy server allow it through.

**Comment by freebird8x** [comment]
The proxy we used don't require credential. I'll check with the proxy group to see if they actually blocks that particular endpoint, but it's weird that both our local PC and the OpenShift servers sit on the corporate network. It's strange that proxy problem only happens on the server and not on local PC (with Docker CE)

**Comment by freebird8x** [comment]
I got feedback from the proxy team and they whitelisted the endpoints to make this work now. I'll close this issue. Thank you for the support.
