### ISSUE TITLE
PipelineArtifactPlugin generates no debug information

### ISSUE THREAD

**Issue by epvanhouten** [microsoft/azure-pipelines-agent#2190]
## Having issue with Tasks?

> Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.

Not logging on Azure-Pipelines-Tasks due to this being implemented in src/Agent.Plugins/PipelineArtifact.

## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
This was encountered while attempting to debug a build issue.

## Agent Version and Platform
Agent Version: 2.149.1

OS of the machine running the agent? All platforms

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com

https://dev.azure.com/beergarden

## Example Log
I would expect additional information to be presented between Starting and Finishing DownloadPipelineArtifact.

```
## Agent and Worker's Diagnostic Logs
##[debug]Evaluating condition for step: 'DownloadPipelineArtifact'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: DownloadPipelineArtifact
==============================================================================
Task         : Download Pipeline Artifact
Description  : Download Pipeline Artifact
Version      : 1.1.0
Author       : Microsoft Corporation
Help         : Download named artifact from a pipeline to a local path.
==============================================================================
Download from the specified build: #1205
Download artifact to: D:\_work\1\a/<artifact name>/
Information, Minimatch patterns: [**]
Information, Start downloading artifact - <artifact name>
Information, Filtered 37 files from the Minimatch filters supplied.
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 12.4 MB (0%).
Information, Downloaded 12.4 MB out of 12.4 MB (100%).
Information, Download completed.
Information, 
Download statistics:
Total Content: 12.4 MB 
Physical Content Downloaded: 4.2 MB
Compression Saved: 8.1 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 171

Downloading artifact finished.
##[section]Finishing: DownloadPipelineArtifact
```

**Comment by TingluoHuang** [comment]
@owenhuynMSFT

**Comment by Thilas** [comment]
Could we expect something about this? I have an issue with some pipeline artifact downloads and I don't have a clue where to begin with without debug information..

**Comment by Creetor** [comment]
Yes, please add additional logging and, if reasonable, documentation.  An unexpected failure should provide more than:

```
2019-09-18T21:19:53.4370047Z ##[debug]Evaluating condition for step: 'Download artifact - vm-image - 3rdPartyDependencies'
2019-09-18T21:19:53.4371118Z ##[debug]Evaluating: succeeded()
2019-09-18T21:19:53.4371419Z ##[debug]Evaluating succeeded:
2019-09-18T21:19:53.4371951Z ##[debug]=> True
2019-09-18T21:19:53.4372509Z ##[debug]Result: True
2019-09-18T21:19:53.4372729Z ##[section]Starting: Download artifact - vm-image - 3rdPartyDependencies
2019-09-18T21:19:53.5379713Z ==============================================================================
2019-09-18T21:19:53.5379850Z Task         : Download Pipeline Artifact
2019-09-18T21:19:53.5379916Z Description  : Download Pipeline Artifact
2019-09-18T21:19:53.5379994Z Version      : 1.1.3
2019-09-18T21:19:53.5380055Z Author       : Microsoft Corporation
2019-09-18T21:19:53.5380141Z Help         : Download named artifact from a pipeline to a local path.
2019-09-18T21:19:53.5380223Z ==============================================================================
2019-09-18T21:19:53.5763527Z ##[error]Value cannot be null.
Parameter name: DownloadPipelineArtifact (61f2a582-95ae-4948-b34d-a1b3c4f6a737/1.1.3)
2019-09-18T21:19:53.5775452Z ##[debug]System.ArgumentNullException: Value cannot be null.
Parameter name: DownloadPipelineArtifact (61f2a582-95ae-4948-b34d-a1b3c4f6a737/1.1.3)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.AgentPluginHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2019-09-18T21:19:53.5776879Z ##[section]Finishing: Download artifact - vm-image - 3rdPartyDependencies
```

**Comment by richardgavel** [comment]
This sort of goes along with debug information, but it would also be nice to add variables that allow us later in the pipeline to determine which build got pulled (i.e PipelineArtifactPlugin.{artifactName}.buildId).

**Comment by Thilas** [comment]
@owenhuynMSFT, @jahsu-MSFT, any news about this? I have a new issue using this task and I still don't know why. It's very frustrating.

When dealing with `AgentPlugin` type of task, I was thinking it could be great to automatically get all its argument values when system.debug is true? I know it would make debugging much easier for sure.

**Comment by stephenmichaelf** [comment]
@fadnavistanmay Could you take a look at this please?
