### ISSUE TITLE
Agents running in azure loses connection intermittently

### ISSUE THREAD

**Issue by hgran** [microsoft/azure-pipelines-agent#2218]
## Have you tried troubleshooting?
Yes

## Agent Version and Platform
Version of your agent? 2.136.1/2.144.1

Windows Server 2016

## Azure DevOps Type and Version
TFS On-premise
Team Foundation Server 2018 Update 3.2 Patch 3

## What's not working?
Since about a month the agents running in Azure will lose connection to server:
The agent: xxx lost communication with the server. Verify the machine is running and has a healthy network connection. 
Either restarting the VM or waiting a couple of hours will fix the problem.

The agents running on-premise keep on working.
Problem usually occurs once or twice per day.

We have a Site-To-Site VPN connection to Azure.
RDP keeps working on the Azure VMs. When connected, there are no problems pinging the TFS app server. It is possible to RDP from Azure VM to TFS App Server. The Azure VMs have no Public IPs.

## Agent and Worker's Diagnostic Logs
Example logs from build server 1
```
[2019-04-16 10:11:59Z WARN VisualStudioServices] Attempt 5 of POST request to https://tfs.company.com/tfs/nameofCollection/908b2f80-8024-4219-a6af-a0ddee100811/_apis/distributedtask/hubs/Build/plans/32d704c6-3dcf-438c-981e-963d29baf744/timelines/32d704c6-3dcf-438c-981e-963d29baf744/records/df143ba0-1c7a-5b21-02e1-d41a394e29c9/feed failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 38.923 seconds.
[2019-04-16 10:12:57Z ERR  VisualStudioServices] Attempt 6 of POST request to https://tfs.company.com/tfs/nameofCollection/908b2f80-8024-4219-a6af-a0ddee100811/_apis/distributedtask/hubs/Build/plans/32d704c6-3dcf-438c-981e-963d29baf744/timelines/32d704c6-3dcf-438c-981e-963d29baf744/records/df143ba0-1c7a-5b21-02e1-d41a394e29c9/feed failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The maximum number of attempts has been reached.
[2019-04-16 10:12:57Z INFO JobServerQueue] Catch exception during append web console line, keep going since the process is best effort.
[2019-04-16 10:12:57Z ERR  JobServerQueue] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ThrottlingReportHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.DistributedTask.WebApi.TaskHttpClientBase.AppendTimelineRecordFeedAsync(Guid scopeIdentifier, String hubName, Guid planId, Guid timelineId, Guid recordId, TimelineRecordFeedLinesWrapper lines, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.ProcessWebConsoleLinesQueueAsync(Boolean runOnce)
```

Example from build server 2:

```
[2019-04-16 09:30:16Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:35:16 AM
[2019-04-16 09:31:16Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:36:16 AM
[2019-04-16 09:31:48Z WARN VisualStudioServices] Authentication failed with status code 401.
Date: Tue, 16 Apr 2019 09:31:47 GMT
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Server: Microsoft-IIS/10.0
WWW-Authenticate: Bearer, Basic realm="https://tfs.company.com/tfs", NTLM
X-TFS-ProcessId: 557c9bd9-dc85-44ce-bcce-5c52989b3308
ActivityId: 0aebe637-94a1-4e20-8030-d26b0ad2fd65
X-TFS-Session: 00231598-37c9-41f1-bdef-1b84755a6e86
X-VSS-E2EID: 370fad1a-9517-49d9-9c7c-c6ef0438e51f
X-FRAME-OPTIONS: SAMEORIGIN
X-TFS-SoapException: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
X-TFS-ServiceError: TF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.
X-Powered-By: ASP.NET
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff

[2019-04-16 09:31:48Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file F:\335-1\.credentials_rsaparams
[2019-04-16 09:32:16Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:37:16 AM
[2019-04-16 09:33:16Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:38:16 AM
[2019-04-16 09:34:17Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:39:16 AM
[2019-04-16 09:35:17Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:40:17 AM
[2019-04-16 09:36:17Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:41:17 AM
[2019-04-16 09:37:17Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:42:17 AM
[2019-04-16 09:38:17Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:43:17 AM
[2019-04-16 09:39:17Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:44:17 AM
[2019-04-16 09:40:17Z INFO JobDispatcher] Successfully renew job request 427552, job is valid till 4/16/2019 9:45:17 AM
[2019-04-16 09:40:40Z INFO ProcessInvokerWrapper] Finished process with exit code 102, and elapsed time 00:16:24.1414611.
[2019-04-16 09:40:40Z INFO JobDispatcher] Worker finished for job df143ba0-1c7a-5b21-02e1-d41a394e29c9. Code: 102
[2019-04-16 09:40:40Z INFO JobDispatcher] finish job request for job df143ba0-1c7a-5b21-02e1-d41a394e29c9 with result: Failed
[2019-04-16 09:40:40Z INFO Terminal] WRITE LINE: 2019-04-16 09:40:40Z: Job Job completed with result: Failed
[2019-04-16 09:40:40Z INFO JobDispatcher] Stop renew job request for job df143ba0-1c7a-5b21-02e1-d41a394e29c9.
[2019-04-16 09:40:40Z INFO JobDispatcher] job renew has been canceled, stop renew job request 427552.
[2019-04-16 09:40:40Z INFO JobNotification] Entering JobCompleted Notification
[2019-04-16 09:52:35Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file F:\335-1\.credentials_rsaparams
[2019-04-16 09:52:35Z INFO MessageListener] Message '77' received from session 'e78c6d4b-6b7e-4a45-9d13-434b0f419527'.
[2019-04-16 09:52:35Z INFO JobDispatcher] Job request 427606 for plan 494098fb-ce5e-4c88-ae31-6b937a211ed3 job df143ba0-1c7a-5b21-02e1-d41a394e29c9 received.
[2019-04-16 09:52:35Z INFO JobDispatcher] Job request df143ba0-1c7a-5b21-02e1-d41a394e29c9 processed succeed.
[2019-04-16 09:52:35Z INFO Terminal] WRITE LINE: 2019-04-16 09:52:35Z: Running job: Job
[2019-04-16 09:52:35Z INFO JobDispatcher] Start renew job request 427606 for job df143ba0-1c7a-5b21-02e1-d41a394e29c9.
[2019-04-16 09:52:35Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 9:57:35 AM
[2019-04-16 09:52:35Z INFO HostContext] Well known directory 'Bin': 'F:\335-1\bin'
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper] Starting process:
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper]   File name: 'F:\335-1\bin\Agent.Worker.exe'
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper]   Arguments: 'spawnclient 1956 3964'
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper]   Working directory: 'F:\335-1\bin'
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'True'
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper]   Lines to send through STDIN: '0'
[2019-04-16 09:52:35Z INFO ProcessInvokerWrapper] Process started with process id 17072, waiting for process exit.
[2019-04-16 09:52:35Z INFO JobDispatcher] Send job request message to worker for job df143ba0-1c7a-5b21-02e1-d41a394e29c9.
[2019-04-16 09:52:35Z INFO JobNotification] Entering JobStarted Notification
[2019-04-16 09:53:35Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 9:58:35 AM
[2019-04-16 09:54:35Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 9:59:35 AM
[2019-04-16 09:55:35Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:00:35 AM
[2019-04-16 09:56:35Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:01:35 AM
[2019-04-16 09:57:35Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:02:35 AM
[2019-04-16 09:58:35Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:03:35 AM
[2019-04-16 09:59:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:04:35 AM
[2019-04-16 10:00:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:05:36 AM
[2019-04-16 10:01:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:06:36 AM
[2019-04-16 10:02:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:07:36 AM
[2019-04-16 10:03:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:08:36 AM
[2019-04-16 10:04:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:09:36 AM
[2019-04-16 10:05:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:10:36 AM
[2019-04-16 10:06:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:11:36 AM
[2019-04-16 10:07:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:12:36 AM
[2019-04-16 10:08:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:13:36 AM
[2019-04-16 10:09:36Z INFO JobDispatcher] Successfully renew job request 427606, job is valid till 4/16/2019 10:14:36 AM
[2019-04-16 10:09:36Z WARN VisualStudioServices] Attempt 1 of GET request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/messages?sessionId=e78c6d4b-6b7e-4a45-9d13-434b0f419527&lastMessageId=77 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 10.991 seconds.
[2019-04-16 10:10:55Z WARN VisualStudioServices] Attempt 1 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 11.035 seconds.
[2019-04-16 10:11:26Z WARN VisualStudioServices] Attempt 2 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 12.589 seconds.
[2019-04-16 10:11:57Z WARN VisualStudioServices] Attempt 3 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 16.692 seconds.
[2019-04-16 10:12:33Z WARN VisualStudioServices] Attempt 4 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 27.835 seconds.
[2019-04-16 10:13:20Z WARN VisualStudioServices] Attempt 5 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 47.107 seconds.
[2019-04-16 10:14:26Z ERR  VisualStudioServices] Attempt 6 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The maximum number of attempts has been reached.
[2019-04-16 10:14:26Z ERR  JobDispatcher] Catch exception during renew agent jobrequest 427606.
[2019-04-16 10:14:26Z ERR  JobDispatcher] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.<RenewJobRequestAsync>d__15.MoveNext()
[2019-04-16 10:14:26Z INFO JobDispatcher] Retrying lock renewal for jobrequest 427606. Job is still locked for: 9.8398479 seconds.
[2019-04-16 10:14:55Z WARN VisualStudioServices] Attempt 1 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 11.19 seconds.
[2019-04-16 10:15:26Z WARN VisualStudioServices] Attempt 2 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 13.429 seconds.
[2019-04-16 10:15:58Z WARN VisualStudioServices] Attempt 3 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 17.84 seconds.
[2019-04-16 10:16:35Z WARN VisualStudioServices] Attempt 4 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 25.9 seconds.
[2019-04-16 10:17:20Z WARN VisualStudioServices] Attempt 5 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 44.007 seconds.
[2019-04-16 10:18:23Z ERR  VisualStudioServices] Attempt 6 of PATCH request to https://tfs.company.com/tfs/_apis/distributedtask/pools/22/jobrequests/427606?lockToken=00000000-0000-0000-0000-000000000000 failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The maximum number of attempts has been reached.
[2019-04-16 10:18:23Z ERR  JobDispatcher] Catch exception during renew agent jobrequest 427606.
[2019-04-16 10:18:23Z ERR  JobDispatcher] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown --
```

**Comment by TingluoHuang** [comment]
@hgran seems like a network problem to me since the error agent get is `WinHttp Error: ERROR_WINHTTP_TIMEOUT`, that means the agent can't reach your TFS server. Since the problem is intermittent, you might need to have some powershell script that continue monitor the network by hint your TFS http endpoint in a loop.

**Comment by hgran** [comment]
I have created a powershell script that does a GET  to the TFS rest API every ten seconds and have it running on the build servers. Had another incident yesterday but the logs from my script were unfortunately missing relevant information, but it never had any issues connecting to TFS while the build agent did. 

As soon as I have better logs I'll update here.

**Comment by lshilei** [comment]
We are facing the similar issue for the Agent Version 2.149.2. The agent is unstable during checking out the Files.

Window Version: Windows Server 2008 R2 SP1 

We have Teamcity installed on the same machine and checking out the same TFS repository as the Agent, But Teamcity would able to get all the files all the time.

The always failing file size is about 41.3 MB

The target log is
[2019-04-15 14:20:14Z INFO JobServerQueue] Try to append 1 batches web console lines for record '771d55ec-34a7-5ddd-398e-3e8e57b4f3f0', success rate: 1/1.
[2019-04-15 14:20:34Z WARN VisualStudioServices] Attempt 1 of POST request to https://dev.azure.com/oscia/06276ebb-bd80-4d36-873a-09859e8d3d6a/_apis/distributedtask/hubs/Build/plans/369affba-a96a-4f6a-9c1c-239a7eeea628/timelines/369affba-a96a-4f6a-9c1c-239a7eeea628/records/275f1d19-1bd8-5591-b06b-07d489ea915a/feed failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 10.946 seconds.
[2019-04-15 14:21:03Z WARN VisualStudioServices] Attempt 2 of POST request to https://dev.azure.com/oscia/06276ebb-bd80-4d36-873a-09859e8d3d6a/_apis/distributedtask/hubs/Build/plans/369affba-a96a-4f6a-9c1c-239a7eeea628/timelines/369affba-a96a-4f6a-9c1c-239a7eeea628/records/275f1d19-1bd8-5591-b06b-07d489ea915a/feed failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 12.832 seconds.
[2019-04-15 14:21:58Z WARN VisualStudioServices] Attempt 3 of POST request to https://dev.azure.com/oscia/06276ebb-bd80-4d36-873a-09859e8d3d6a/_apis/distributedtask/hubs/Build/plans/369affba-a96a-4f6a-9c1c-239a7eeea628/timelines/369affba-a96a-4f6a-9c1c-239a7eeea628/records/275f1d19-1bd8-5591-b06b-07d489ea915a/feed failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The operation will be retried in 16.748 seconds.
[2019-04-15 14:22:57Z ERR  VisualStudioServices] Attempt 4 of POST request to https://dev.azure.com/oscia/06276ebb-bd80-4d36-873a-09859e8d3d6a/_apis/distributedtask/hubs/Build/plans/369affba-a96a-4f6a-9c1c-239a7eeea628/timelines/369affba-a96a-4f6a-9c1c-239a7eeea628/records/275f1d19-1bd8-5591-b06b-07d489ea915a/feed failed (WinHttp Error: ERROR_WINHTTP_TIMEOUT). The maximum number of attempts has been reached.
[2019-04-15 14:22:57Z INFO JobServerQueue] Catch exception during append web console line, keep going since the process is best effort.
[2019-04-15 14:22:57Z ERR  JobServerQueue] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ThrottlingReportHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.DistributedTask.WebApi.TaskHttpClientBase.AppendTimelineRecordFeedAsync(Guid scopeIdentifier, String hubName, Guid planId, Guid timelineId, Guid recordId, TimelineRecordFeedLinesWrapper lines, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.ProcessWebConsoleLinesQueueAsync(Boolean runOnce)

**Comment by hgran** [comment]
The problem no longer occurs. May have been issues with the connection site-to-site VPN to Azure as suggested by @TingluoHuang 
Closing.
