### ISSUE TITLE
Insufficient documentation for Linux

### ISSUE THREAD

**Issue by djsowa** [microsoft/azure-pipelines-agent#2285]
I'm having issues with agents 2.150.0 running on Centos 7.

Agent is installed successfully, but it fail when trying to update itself.
It will be best if You can provide some guidance about permissions for directories and users running agent as a service ?

I'm using this script to provision agents on VM.

```
readonly VSTSHOMEPATH=/opt/vstsagent
readonly USERNAME=vstsbuildagent
readonly CACHEPATH=/var/cache/$USERNAME

# just in case
umask 007
echo "Creating a user"
sudo useradd -r -s /sbin/nologin -d $CACHEPATH $USERNAME
sudo mkdir $CACHEPATH
sudo chgrp $USERNAME $CACHEPATH
sudo chown $USERNAME $CACHEPATH
sudo chmod 0770 $CACHEPATH
sudo mkdir $VSTSHOMEPATH
sudo curl -fkSL -o $VSTSHOMEPATH/vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.150.0/vsts-agent-rhel.6-x64-2.150.0.tar.gz

if ! echo "b01b2c24e1fedfc853b1f6acbd1d096bb4f4f426345b99ebca0eeac2178d0190 $VSTSHOMEPATH/vstsagent.tar.gz" | sudo sha256sum -c; then
  echo "Invalid vstsagent checksum"
  exit 1
fi


echo "Downloading ICU for Dotnet Core" 
#https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

sudo curl -fkSL -o $CACHEPATH/icu4c-57_1-RHEL6-x64.tgz http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz

if ! echo "c847c539fde47648c7005730186745b15950a40cde4446c8901f00657a43b9be $CACHEPATH/icu4c-57_1-RHEL6-x64.tgz" | sudo sha256sum -c; then
  echo "Invalid ICU checksum"
  exit 1
fi

echo "Installing ICU for Dotnet Core"
sudo tar -zxvf $CACHEPATH/icu4c-57_1-RHEL6-x64.tgz -C /
sudo rm -f $CACHEPATH/icu4c-57_1-RHEL6-x64.tgz


#Unpack and cleanup
sudo tar -zxvf $VSTSHOMEPATH/vstsagent.tar.gz -C $VSTSHOMEPATH
sudo rm -f $VSTSHOMEPATH/vstsagent.tar.gz

echo "Changing a group"
sudo chgrp -R $USERNAME $VSTSHOMEPATH

echo "Sticky bit and file permissions"
sudo chmod 1770 $VSTSHOMEPATH
sudo find $VSTSHOMEPATH -executable -type f -exec chmod 770 {} \;
sudo find $VSTSHOMEPATH -type f \( -iname \*.dll -o -iname \*.so \) -exec chmod 770 {} \;

echo "Installing VSTS agent dependencies."
sudo $VSTSHOMEPATH/bin/installdependencies.sh

sudo systemctl set-environment LD_LIBRARY_PATH=/usr/local/lib
sudo sh -c 'cd $0;./svc.sh install $1' $VSTSHOMEPATH $USERNAME
sudo sh -c 'cd $0;./svc.sh start' $VSTSHOMEPATH

```

Update logs:

```
[2019-06-04 12:25:21Z INFO ProcessInvokerWrapper] Finished process 116282 with exit code 0, and elapsed time 00:00:02.6524663.
[2019-06-04 12:25:21Z INFO SelfUpdater] Finished getting latest agent package at: /opt/vstsagent/_work/_update.
[2019-06-04 12:25:21Z INFO HostContext] Well known directory 'Bin': '/opt/vstsagent/bin'
[2019-06-04 12:25:21Z INFO HostContext] Well known directory 'Root': '/opt/vstsagent'
[2019-06-04 12:25:21Z INFO SelfUpdater] Copy /opt/vstsagent/_work/_update/bin to /opt/vstsagent/bin.2.150.3.
[2019-06-04 12:25:21Z INFO HostContext] Well known directory 'Bin': '/opt/vstsagent/bin'
[2019-06-04 12:25:21Z INFO HostContext] Well known directory 'Root': '/opt/vstsagent'
[2019-06-04 12:25:21Z INFO SelfUpdater] Copy /opt/vstsagent/_work/_update/externals to /opt/vstsagent/externals.2.150.3.
[2019-06-04 12:25:21Z INFO SelfUpdater] Copy any remaining .sh/.cmd files into agent root.
[2019-06-04 12:25:21Z INFO HostContext] Well known directory 'Bin': '/opt/vstsagent/bin'
[2019-06-04 12:25:21Z INFO HostContext] Well known directory 'Root': '/opt/vstsagent'
[2019-06-04 12:25:21Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2019-06-04 12:25:21Z ERR  Terminal] WRITE ERROR: An error occurred: Access to the path is denied.
[2019-06-04 12:25:21Z ERR  AgentProcess] System.UnauthorizedAccessException: Access to the path is denied. ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by TingluoHuang** [comment]
@djsowa it failing when it trying to overwrite the `config.sh`/`run.sh` under agent root directory, does your agent service account has permission to those file?

**Comment by djsowa** [comment]
It should. Service is running as vstsbuildagent user.
Here is output from ls -lais for root agent directory:

```
total 88
  206229  0 drwxrwx--T.  8           1001 vstsbuildagent   285 06-04 10:02 .
33679648  0 drwxr-xr-x.  7 root           root              75 06-04 09:09 ..
  142225  4 -rw-r-----.  1 vstsbuildagent vstsbuildagent   173 06-04 08:55 .agent
50352317 20 drwxr-xr-x. 22           1001 vstsbuildagent 16384 06-04 08:55 bin
36811800 20 drwxr-xr-x. 22 vstsbuildagent vstsbuildagent 16384 06-04 10:02 bin.2.150.3
  263014  4 -rwxrwx---.  1           1001 vstsbuildagent  2940 06-04 12:25 config.sh
  142224  4 -rw-r-----.  1 vstsbuildagent vstsbuildagent   268 06-04 08:54 .credentials
  142223  4 -rw-------.  1 vstsbuildagent vstsbuildagent  1667 06-04 08:54 .credentials_rsaparams
33657681  4 drwxr-x---.  2 vstsbuildagent vstsbuildagent  4096 06-04 12:25 _diag
  142220  4 -rw-r-----.  1 vstsbuildagent vstsbuildagent    48 06-04 08:54 .env
  262652  4 -rwxrwx---.  1           1001 vstsbuildagent   707 04-10 01:58 env.sh
16819698  0 drwxr-xr-x.  6           1001 vstsbuildagent    63 04-10 02:00 externals
 2440545  0 drwxr-xr-x.  6 vstsbuildagent vstsbuildagent    63 06-04 10:02 externals.2.150.3
  142221  4 -rw-r-----.  1 vstsbuildagent vstsbuildagent    30 06-04 08:54 .path
  262651  4 -rwxrwx---.  1           1001 vstsbuildagent  1660 04-10 01:58 run.sh
  142219  4 -rwxr-xr-x.  1 vstsbuildagent vstsbuildagent   510 06-04 08:55 runsvc.sh
  142229  4 -rw-r-----.  1 vstsbuildagent vstsbuildagent    45 06-04 08:55 .service
  142226  4 -rwxr-xr-x.  1 vstsbuildagent vstsbuildagent  4017 06-04 08:55 svc.sh
33655051  0 drwxr-xr-x.  3 vstsbuildagent vstsbuildagent    21 06-04 12:25 _work

```

**Comment by TingluoHuang** [comment]
@djsowa what about your agent home path? the folder contains the agent, does the service account has permission to that folder?

**Comment by djsowa** [comment]
@TingluoHuang It seems to be fine too.
`ls -lais /var/cache/vstsbuildagent`

```
total 0
50351618 0 drwxrwx---. 8 vstsbuildagent vstsbuildagent 91 06-25 16:02 .
16808129 0 drwxr-xr-x. 7 root           root           81 06-25 12:29 ..
 2356062 0 drwx------. 4 vstsbuildagent vstsbuildagent 29 06-25 16:02 .cache
 2356066 0 drwx------. 5 vstsbuildagent vstsbuildagent 41 06-25 23:00 .local
50339128 0 drwxr-----. 3 vstsbuildagent vstsbuildagent 19 06-25 12:30 .pki
51108592 0 drwxr-xr-x. 2 vstsbuildagent vstsbuildagent  6 06-25 16:07 .ssh
 2356384 0 drwxr-xr-x. 2 vstsbuildagent vstsbuildagent 58 06-25 13:58 .terraform.d
37142967 0 drwxr-xr-x. 3 vstsbuildagent vstsbuildagent 17 06-25 16:02 .yarn

```

**Comment by jtpetty** [comment]
@djsowa - are you still seeing this issue?

Looking at the directory listing, it seems that there are several files owned by user '1001' and not vstsbuildagent.

The bin directory is the first one that jumps out to me that is an issue since that is what is in the log most recently and it is not group writable.
```
50352317 20 drwxr-xr-x. 22           1001 vstsbuildagent 16384 06-04 08:55 bin
```

Can you chown those files that are owned by 1001 to be owned by vstsbuildagent and see if that fixes your issue?

**Comment by jtpetty** [comment]
@djsowa - did you have any success with that fixing your issue?

**Comment by djsowa** [comment]
@jtpetty  Thanks for checking my problem.
I try to check permissions for 'bin' directory and will get back with feedback.

**Comment by djsowa** [comment]
It was indeed issue with bin and externals directory owner. Was changed to root. After update to vsts user all works fine. Thanks for help !
