### ISSUE TITLE
Not able to run configuration of vsts-agent-linux-x64-2.144.2.tar.gz in ubuntu 16.04

### ISSUE THREAD

**Issue by polamarasetti** [microsoft/azure-pipelines-agent#2325]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...

OS of the machine running the agent? OSX/Windows/Linux/...

## What's not working?
Configuration is failing with SSL error.

## Agent and Worker's Diagnostic Logs
[2019-06-26 19:13:35Z ERR  VisualStudioServices] GET request to https://xx.yy.zz.com/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Problem with the SSL CA cert (path? access rights?)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2019-06-26 19:13:35Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-06-26 19:13:35Z INFO LocationServer] Catch exception during connect. 4 attempt left.
[2019-06-26 19:13:35Z ERR  LocationServer] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Problem with the SSL CA cert (path? access rights?)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)

**Comment by juliobbv** [comment]
Hi @polamarasetti,

Is the agent trying to connect to a TFS server that uses a self-signed certificate? Try following these instructions: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/certificate

**Comment by jtpetty** [comment]
Closing due to no response.

**Comment by 4F2E4A2E** [comment]
Experiencing the same behavior on rhel6 with curl 7.67, no matter what I do.
openssh, curl and dotnet-console tests to the very same host can be stablished are nonimal

buut with the agent it's not working at all
![image](https://user-images.githubusercontent.com/64590/87253597-c8ad2280-c47c-11ea-86a5-0bd70cb580c0.png)
![image](https://user-images.githubusercontent.com/64590/87253612-ed08ff00-c47c-11ea-80d9-9c2c0f6a0652.png)
![image](https://user-images.githubusercontent.com/64590/87253667-48d38800-c47d-11ea-91ee-d9c2c5035ef6.png)
