### ISSUE TITLE
Getting the System.IO.IOException: Input/output error after some times of Agent starts

### ISSUE THREAD

**Issue by Sukumarnayak** [microsoft/azure-pipelines-agent#2378]
Running the Azure Agent RHEL6 version 2.155.1
 https://vstsagentpackage.azureedge.net/agent/2.155.1/vsts-agent-rhel.6-x64-2.155.1.tar.gz

Running the agent service in Interactive Mode. The agent service runs fine, but after sometimes the jobs fails and gives the below error.
[2019-08-08 10:24:11Z ERR  JobDispatcher] Worker Dispatch failed witn an exception for job request 0dbeb697-20ba-5521-a7b2-c923cc00a23c.
[2019-08-08 10:24:11Z ERR  JobDispatcher] System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count)
   at System.ConsolePal.Write(SafeFileHandle fd, Byte[] buffer, Int32 offset, Int32 count)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.EnsureDispatchFinished(WorkerDispatcher jobDispatch, Boolean cancelRunningJob)

Getting the below error in Azure Devops side when build starts
![image](https://user-images.githubusercontent.com/42177131/62704630-73b19280-ba09-11e9-99d6-948878c448a3.png)

**Comment by juliobbv** [comment]
This is a shot in the dark, but could it be that you're running out of disk space? Run `df` and look for partitions that are close to/at their capacity.

**Comment by Sukumarnayak** [comment]
There is no out of disk space in the machine where the Agent is running. As i mentioned the agent was running as Interactive mode in background mode like **./run.sh &**
I have just started the Agent as a run as service and i do not see the issue is coming.

**Comment by jtpetty** [comment]
@Sukumarnayak - Are you still experiencing this issue?

**Comment by jd-mtb** [comment]
I am getting the same error with the rhel6 agent running "as a service" (but non-native, basically running ./run.sh &) using 2.170.1 so far. Support / help would be great.

**Comment by anatolybolshakov** [comment]
@Sukumarnayak is this issue still actual for you? 
@jd-mtb could you please share logs also?

**Comment by jd-mtb** [comment]
@anatolybolshakov Thanks for reminding me on this issue and while the issue persists how I mention it I was actually using it incorrectly and others might be as well. **_I discovered the issue is that I was supposed to be using the includes runsvc.sh script instead._** If you just use run.sh it doesn't start the node server in a way that keeps it open for a long time. I was tipped off by a comment somewhere in one of the included microsoft files.

**Comment by anatolybolshakov** [comment]
@jd-mtb ok thanks! Yes, you can use this to run agent as systemd (here are some [steps](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#run-as-a-systemd-service) describing it)

**Comment by jd-mtb** [comment]
@anatolybolshakov on rhel6 the service install command just tells you it isn't supported or something like that. I forget exactly, but point is it doesn't work. https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

That said, we did get it working, our init file looks like this... disclaimer: I'm new to rhel6 init files, inherited most of this as is, provide it as is, and there's no guarantee of form or function:
```
#!/bin/bash
#
# chkconfig: 35 90 12
# description: VSTS-Agent
#

# Get function from functions library
. /etc/init.d/functions

# Start the service VSTS
start() {
        echo -n "Starting VSTS-Agent service: "
        runuser -l wasadmin bash -c 'export LD_LIBRARY_PATH=/usr/local/lib && /opt/vsts-agent/runsvc.sh --startuptype service &'
        ### Create the lock file ###
        touch /var/lock/subsys/vsts
        success $"VSTS-Agent service startup"
        echo
}

# Restart the service VSTS-Agent
stop() {
        echo -n "Stopping VSTS-Agent service: "
        killproc Agent.Listener
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/vsts
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        echo "This isn't a native SysV sevice, and has no status"
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0

```

**Comment by anatolybolshakov** [comment]
I double-checked the logs of original issue - it seems that error happened during console output ([line](https://github.com/microsoft/azure-pipelines-agent/blob/bf4659b1cc686869234e2f9f3ce9d0b279132e48/src/Agent.Listener/JobDispatcher.cs#L407)), which has been removed in latest versions of agent - so I assume this one is not actual for last agent version.
Let me leave this open to investigate issue with running on rhel.

**Comment by vrealizebuildtools** [comment]
getting same error. Extract from diag log:


[2021-03-18 13:00:13Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/github/vbt-actions-runner/.credentials_rsaparams
[2021-03-18 13:00:14Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2021-03-18 13:07:04Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/github/vbt-actions-runner/.credentials_rsaparams
[2021-03-18 13:07:04Z INFO MessageListener] Message '8' received from session 'a69f4ee5-b97a-479c-9ed2-aca50c20b5d9'.
[2021-03-18 13:07:04Z INFO JobDispatcher] Job request 7 for plan 3715c64e-dd2b-4267-9243-c37569e2cdf4 job fc0a80d9-498d-5bd0-554f-fcf801ec0127 received.
[2021-03-18 13:07:04Z INFO JobDispatcher] Pull OrchestrationId 3715c64e-dd2b-4267-9243-c37569e2cdf4.upload-artifact.__default from JWT claims
[2021-03-18 13:07:04Z ERR  JobDispatcher] Worker Dispatch failed with an exception for job request 5ceb2da2-285c-5143-78bc-b37abc043dd3.
[2021-03-18 13:07:04Z ERR  JobDispatcher] System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count, Boolean mayChangeCursorPosition)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GitHub.Runner.Common.Terminal.WriteLine(String line, Nullable`1 colorCode)
   at GitHub.Runner.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, String orchestrationId, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at GitHub.Runner.Listener.JobDispatcher.EnsureDispatchFinished(WorkerDispatcher jobDispatch, Boolean cancelRunningJob)
[2021-03-18 13:07:04Z INFO Terminal] WRITE LINE: 2021-03-18 13:07:04Z: Running job: Upload artifact
[2021-03-18 13:10:47Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/github/vbt-actions-runner/.credentials_rsaparams
[2021-03-18 13:10:47Z INFO MessageListener] Message '9' received from session 'a69f4ee5-b97a-479c-9ed2-aca50c20b5d9'.
[2021-03-18 13:10:47Z INFO JobDispatcher] Job cancellation request fc0a80d9-498d-5bd0-554f-fcf801ec0127 received, cancellation timeout 5 minutes.
[2021-03-18 13:17:34Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/github/vbt-actions-runner/.credentials_rsaparams
[2021-03-18 13:17:34Z INFO MessageListener] Message '10' received from session 'a69f4ee5-b97a-479c-9ed2-aca50c20b5d9'.
[2021-03-18 13:17:34Z INFO JobDispatcher] Job request 9 for plan dcbb2225-3421-4e22-8ba9-128db968c388 job fc0a80d9-498d-5bd0-554f-fcf801ec0127 received.
[2021-03-18 13:17:34Z INFO JobDispatcher] Pull OrchestrationId dcbb2225-3421-4e22-8ba9-128db968c388.upload-artifact.__default from JWT claims
[2021-03-18 13:17:34Z ERR  JobDispatcher] Worker Dispatch failed with an exception for job request fc0a80d9-498d-5bd0-554f-fcf801ec0127.
[2021-03-18 13:17:34Z ERR  JobDispatcher] System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count, Boolean mayChangeCursorPosition)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GitHub.Runner.Common.Terminal.WriteLine(String line, Nullable`1 colorCode)
   at GitHub.Runner.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, String orchestrationId, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at GitHub.Runner.Listener.JobDispatcher.EnsureDispatchFinished(WorkerDispatcher jobDispatch, Boolean cancelRunningJob)
[2021-03-18 13:17:34Z INFO Terminal] WRITE LINE: 2021-03-18 13:17:34Z: Running job: Upload artifact
[2021-03-18 13:46:37Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/github/vbt-actions-runner/.credentials_rsaparams
[2021-03-18 13:46:37Z INFO MessageListener] Message '11' received from session 'a69f4ee5-b97a-479c-9ed2-aca50c20b5d9'.
[2021-03-18 13:46:37Z INFO JobDispatcher] Job request 10 for plan 61e4708d-baf5-4de9-aa4a-e2f83769d322 job fc0a80d9-498d-5bd0-554f-fcf801ec0127 received.
[2021-03-18 13:46:37Z INFO JobDispatcher] Pull OrchestrationId 61e4708d-baf5-4de9-aa4a-e2f83769d322.upload-artifact.__default from JWT claims
[2021-03-18 13:46:37Z ERR  JobDispatcher] Worker Dispatch failed with an exception for job request fc0a80d9-498d-5bd0-554f-fcf801ec0127.
[2021-03-18 13:46:37Z ERR  JobDispatcher] System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count, Boolean mayChangeCursorPosition)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GitHub.Runner.Common.Terminal.WriteLine(String line, Nullable`1 colorCode)
   at GitHub.Runner.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, String orchestrationId, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at GitHub.Runner.Listener.JobDispatcher.EnsureDispatchFinished(WorkerDispatcher jobDispatch, Boolean cancelRunningJob)
[2021-03-18 13:46:37Z INFO Terminal] WRITE LINE: 2021-03-18 13:46:37Z: Running job: Upload artifact

**Comment by anatolybolshakov** [comment]
@jd-mtb looks like it should work as expected on RHEL too.
Just as conclusion - please make sure that all required [dependencies ](https://github.com/dotnet/core/blob/main/Documentation/build-and-install-rhel6-prerequisites.md#required-packages)are installed on RHEL 6. Running of 'svc.sh' script is the preferred way to run agent as a service (here are some more info about [steps](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#run-as-a-systemd-service)). Please also not that you would need specific agent package for RHEL 6 - you can find it on agent release [pages](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.189.0).
