### ISSUE TITLE
Intermittent PowerShell Task Error

### ISSUE THREAD

**Issue by JDCain** [microsoft/azure-pipelines-agent#2379]
## Agent Version and Platform

Windows: 10.0.17134
Agent: 2.122.1

## Azure DevOps Type and Version
on-premises: 15.117.27414.0 (TFS2017.3.1 I think)

## What's not working?
Experiencing intermittent issues where powershell tasks will report the error listed below. Seems to come from [this](https://github.com/microsoft/azure-pipelines-agent/blob/b88ea4735e48cb04c78a6236f84763e9ca174514/src/Agent.Worker/Handlers/PowerShellExeHandler.cs#L90) line in the source code but I am not sure why,

>2019-08-08T05:00:29.0126463Z ==============================================================================
2019-08-08T05:00:29.0126463Z Task         : PowerShell
2019-08-08T05:00:29.0126463Z Description  : Run a PowerShell script
2019-08-08T05:00:29.0126463Z Version      : 1.2.3
2019-08-08T05:00:29.0126463Z Author       : Microsoft Corporation
2019-08-08T05:00:29.0126463Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2019-08-08T05:00:29.0126463Z ==============================================================================
2019-08-08T05:00:29.0126463Z ##[command]. 'C:\Agents\Console\_work\_temp\7dc8ac70-0692-4a34-9bce-994d52e8fca3.ps1' 
2019-08-08T05:00:29.7636376Z ##[error]Write-Verbose : The term 'Write-Verbose' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:70
\+ ... .Security.Cryptography.ProtectedData] } catch { Write-Verbose 'Adding ...
\+                                                     ~~~~~~~~~~~~~
\+ CategoryInfo          : ObjectNotFound: (Write-Verbose:String) [], CommandNotFoundException
\+ FullyQualifiedErrorId : CommandNotFoundException
Unable to find type [System.Security.Cryptography.ProtectedData].
At line:1 char:304
\+ ... ::UTF8.GetString([System.Security.Cryptography.ProtectedData]::Unprot ...
\+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\+ CategoryInfo          : InvalidOperation: (System.Security...y.ProtectedData:TypeName) [], RuntimeException
\+ FullyQualifiedErrorId : TypeNotFound
Test-Path : The term 'Test-Path' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:831
\+ ... graphy.DataProtectionScope]::CurrentUser))) ; if (!(Test-Path -Litera ...
\+                                                         ~~~~~~~~~
\+ CategoryInfo          : ObjectNotFound: (Test-Path:String) [], CommandNotFoundException
\ + FullyQualifiedErrorId : CommandNotFoundException
 2019-08-08T05:00:29.7937509Z ##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream. 

## Agent and Worker's Diagnostic Logs
>{
      "inputs": {
        "scriptType": "inlineScript",
        "scriptName": "",
        "arguments": "",
        "inlineScript": "Import-Module PowerShellGet -Force -ErrorAction SilentlyContinue;\nsave-script -Name \"Run-Tests\" -AllowPrerelease -Repository Proget -Path .\\ -v",
        "workingFolder": "",
        "failOnStandardError": "true"
      },
      "instanceId": "5fe8b47b-d823-44fb-93bf-f3690f7c8bec",
      "displayName": "Download Run-Tests.ps1",
      "enabled": true,
      "condition": null,
      "continueOnError": false,
      "alwaysRun": false,
      "timeoutInMinutes": 0,
      "refName": null,
      "id": "e213ff0f-5d5c-4791-802d-52ea3e7be1f1",
      "name": "PowerShell",
      "version": "1.2.3"
    },

>[2019-08-08 05:00:29Z INFO ProcessInvoker] Starting process:
[2019-08-08 05:00:29Z INFO ProcessInvoker]   File name: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[2019-08-08 05:00:29Z INFO ProcessInvoker]   Arguments: '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "try { $null = [System.Security.Cryptography.ProtectedData] } catch { Write-Verbose 'Adding assemly: System.Security' ; Add-Type -AssemblyName 'System.Security' ; $null = [System.Security.Cryptography.ProtectedData] ; $Error.Clear() } ; Invoke-Expression -Command ([System.Text.Encoding]::UTF8.GetString([System.Security.Cryptography.ProtectedData]::Unprotect([System.Convert]::FromBase64String('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAZOXn0JgL3kC/6q1me8nF9wAAAAACAAAAAAADZgAAwAAAABAAAADemdb24tVemV43uPkkFtN5AAAAAASAAACgAAAAEAAAALESMAreFohhTsUzXoRtWyZQAAAAGO6Ra8Hn08yTQpxK8YRebcoSDY/Br00tvzLGqG03sUwRIlEfY+mN6a38l0luoI855iyMuBsdDTi/oh3omXpCsqw5EhJsvztmfrQ14LAxtvUUAAAA4C6O9xvyHi8l8CBpfIhEcFWdlF4='), [System.Convert]::FromBase64String('t1c3bDWK+05k0Mt7Vvnt/A=='), [System.Security.Cryptography.DataProtectionScope]::CurrentUser))) ; if (!(Test-Path -LiteralPath variable:\LastExitCode)) { Write-Verbose 'Last exit code is not set.' } else { Write-Verbose ('$LastExitCode: {0}' -f $LastExitCode) ; exit $LastExitCode }"'
[2019-08-08 05:00:29Z INFO ProcessInvoker]   Working directory: 'C:\Agents\Console\_work\r67\a'
[2019-08-08 05:00:29Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2019-08-08 05:00:29Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2019-08-08 05:00:29Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2019-08-08 05:00:29Z INFO ProcessInvoker] Process started with process id 5208, waiting for process exit.
[2019-08-08 05:00:29Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2019-08-08 05:00:29Z INFO ProcessInvoker] Finished process with exit code 1, and elapsed time 00:00:00.7480626.
[2019-08-08 05:00:29Z ERR  StepsRunner] Caught exception from step: System.Exception: Process completed with exit code 1 and had 1 error(s) written to the error stream.
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShellExeHandler.<RunAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
[2019-08-08 05:00:29Z INFO StepsRunner] Step result: Failed
[2019-08-08 05:00:29Z INFO StepsRunner] Update job result with current step result 'Failed'.
[2019-08-08 05:00:29Z INFO StepsRunner] Current state: job state = 'Failed'`

**Comment by juliobbv** [comment]
@JDCain, It looks like there might be some determinism issue where some essential PowerShell modules are sometimes not correctly defined, causing the task to fail.

What happens if you print out the contents of `$Env:PSModulePath` at the very first line in the powershell task? The issue might actually be thrown from the 'wrapper' script so by that moment it might be too late, but I'd be curious with what's going on.

**Comment by JDCain** [comment]
@juliobbv I do think is happening in that wrapper. The log output from TFS shows an exception which seems to match up with the code the agent attempts to run from it's log. See bold below.

This issue only happens when the agent is run as a different user then the one logged on to the console. Reverting the change corrects the issue, however I am being asked to try and find a fix as there are security reasons for the change. I was wondering if perhaps the console agent does not support being run as a different user then the one logged into the console. I've never had this issue with the service agent when it runs as a separate user on a machine. 

> -Command "try { $null = [System **.Security.Cryptography.ProtectedData] } catch { Write-Verbose 'Adding** assemly: System.Security' ; Add-Type -AssemblyName 'System.Security' ; $null = [System.Security.Cryptography.ProtectedData] ; $Error.Clear() } ; Invoke-Expression -Command ([System.Text.Encoding]::UTF8.GetString([System.Security.Cryptography.ProtectedData]::Unprotect([System.Convert]::FromBase64String('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAZOXn0JgL3kC/6q1me8nF9wAAAAACAAAAAAADZgAAwAAAABAAAADemdb24tVemV43uPkkFtN5AAAAAASAAACgAAAAEAAAALESMAreFohhTsUzXoRtWyZQAAAAGO6Ra8Hn08yTQpxK8YRebcoSDY/Br00tvzLGqG03sUwRIlEfY+mN6a38l0luoI855iyMuBsdDTi/oh3omXpCsqw5EhJsvztmfrQ14LAxtvUUAAAA4C6O9xvyHi8l8CBpfIhEcFWdlF4='), [System.Convert]::FromBase64String('t1c3bDWK+05k0Mt7Vvnt/A=='), [System.Security.Cryptography.DataProtectionScope]::CurrentUser))) ; if (!(Test-Path -LiteralPath variable:\LastExitCode)) { Write-Verbose 'Last exit code is not set.' } else { Write-Verbose ('$LastExitCode: {0}' -f $LastExitCode) ; exit $LastExitCode }"'

>##[error]Write-Verbose : The term 'Write-Verbose' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
At line:1 char:70+ ... **.Security.Cryptography.ProtectedData] } catch { Write-Verbose 'Adding** ...

**Comment by juliobbv** [comment]
Interesting observation! It looks like some of the core assemblies are not defined, so commands like `Write-Verbose`, and `Test-Path` can't even run.

I looked up ["The term 'Write-Verbose"](https://www.google.com/search?q=%22The+term+%27Write-Verbose%27%22) on Google, and there's only one result, suggesting that the PowerShell environment may not be set up correctly. @JDCain, you said that the agent runs into this problem intermittently, and only when the agent is run as a different user, right? Is that user 'special' in any way? (e.g. more restricted permissions, different environment variables set)

@ericsciple, have you seen anything like this before?

**Comment by JDCain** [comment]
@juliobbv I've begun to think this issue is only indirectly related to running as the other user. I did see the error still occasionally after switching it back to the original setup, but never before.
 - After originally changing the user some tasks could no longer run as admin, so -scope currentuser was added to the commands.
- a default profile redirect to a UNC path exists for ad profiles documents folder, so documents\WindowsPowerShell is shared between different machines.
 - multiple agents are using this account to run sometimes runs at the same time.

I **_think_** multiple installs of the same modules happening at the same time being written to the UNC path along with issues reading the modules from the UNC path at the start of a powershell.exe instance were causing the issues. 

To test this I removed the powershellget module install commands from the TFS tasks and made sure they were already setup for allusers on the machine. I did not see any errors last night.

**Comment by juliobbv** [comment]
@JDCain I see. Did you get any more errors during the past few days? I'm curious about the UNC path redirect -- what was the path it was redirecting to? I was wondering because I find that behavior from PowerShell surprising (that said, I'm not a Powershell expert).

We usually discourage installing multiple agents in the same machine specifically to avoid these "shared folder" scenarios that sometimes may pop up inadvertently and cause race conditions.

If you don't mind: what were the the TFS tasks that you modified to stop installing the modules? I'm wondering if there's anything we can do defensively from our side to avoid multiple agents from stomping each other at installing modules.

**Comment by JDCain** [comment]
@juliobbv The GPO for folder redirection takes the users documents folder and places it on a network share. So c:\users\samaccountname\Documents\WindowsPowerShell becomes \\networkserver\profiles\sameaccountname\documents\WindowsPowerShell

I was using the inline script function of the generic PoweSshell task to run the following commands:

```
Install-PackageProvider NuGet -Force -Scope CurrentUser
Install-Module -Name PowerShellGet -Force -Scope CurrentUser
if (-not (Get-PSRepository).name -icontains "Proget"){
Register-PSRepository -Name "ProGet" -SourceLocation "http://nugetfeed/" -InstallationPolicy Trusted -ScriptSourceLocation "http://nugetfeed";
}
```

Originally those commands were run without '-Scope CurrentUser' since the agent was running as admin. After the executing user was changed I had to add the scope. 

It seems that when one machine was writing / deleting items in the now shared WindowsPowerShell/modules folder and another attempted to start PowerShell, loading modules caused some kind of error. I was able to examine the times on a couple to see them running at the exact same time.

For now I've just made sure each server already has the modules  installed as admin and commented out the items. However I prefer to have the setup always take place in the run to make sure things are setup.  I've contacted our support to see about disabling the folder redirection on the account we use to run the agents.
