### ISSUE TITLE
All agents suddenly go offline， reconnect timeout

### ISSUE THREAD

**Issue by bj-yinyan** [microsoft/azure-pipelines-agent#2416]
##  Agent Version and Platform
vsts-agent-win7-x64-2.122.2
OS：win7

## Azure DevOps Type and Version
TFS2018 DevOps Server

## What's not working?
all agents go offline suddenly at 2019/8/29, But Accessing TFS successfully through browser on Proxy. Attempt to create a new agent at original agent machine, stay at “testing agent connection”, then timeout.
*******************Start: This is console output*****************
>> 连接:

输入 服务器 URL > http://xxx.xxx.xxx.xxx:8080/tfs
输入 身份验证类型 (对于 Integrated 按 Enter) > negotiate
输入 用户名 > administrator
输入 密码 > **********
正在连接到服务器...

>> 注册代理:

输入 代理池 (对于 default 按 Enter) > windows-build-agent04
输入 代理名称 (对于 WIN-JIRA 按 Enter) > agent01
正在扫描工具功能。
正在连接到服务器。
已成功添加代理
正在测试代理连接。
The HTTP request timed out after 00:01:40.
*******************End: This is console output*****************

## Have you tried troubleshooting?
Try to reboot TFS service, but no effect.
Try to add negotiate for windows authentication mode, but no effect.
Try to close the firewall, but no effect.
Confirm that the password of the account is correct.

 Any similar problems and what solutions do you have?

## Agent and Worker's Diagnostic Logs
[2019-09-02 07:52:51Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-09-02 07:52:51Z WARN VisualStudioServices] Authentication failed with status code 401.
Date: Mon, 02 Sep 2019 07:50:51 GMT
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Server: Microsoft-IIS/10.0
WWW-Authenticate: Bearer, Basic realm="http://xxx.xxx.xxx.xxx:8080/tfs", Negotiate, NTLM
X-TFS-ProcessId: 80f5db63-53ee-47a5-8e2c-db4902f3997d
ActivityId: 03a36378-eb99-4316-a503-51e3953f1669
X-TFS-Session: 2bd158d1-79a5-41aa-a0b2-9b18687545ec
X-VSS-E2EID: d2bd9a01-6fa3-441c-9f01-6d1bf617b8f2
X-FRAME-OPTIONS: SAMEORIGIN
X-TFS-SoapException: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22zh%22%3ETF400813%3A%20%E8%B5%84%E6%BA%90%E4%B8%8D%E5%8F%AF%E7%94%A8%E4%BA%8E%E5%8C%BF%E5%90%8D%E8%AE%BF%E9%97%AE%E3%80%82%E9%9C%80%E8%A6%81%E8%BF%9B%E8%A1%8C%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BA%AB%E4%BB%BD%E9%AA%8C%E8%AF%81%E3%80%82%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
X-TFS-ServiceError: TF400813%3A%20%E8%B5%84%E6%BA%90%E4%B8%8D%E5%8F%AF%E7%94%A8%E4%BA%8E%E5%8C%BF%E5%90%8D%E8%AE%BF%E9%97%AE%E3%80%82%E9%9C%80%E8%A6%81%E8%BF%9B%E8%A1%8C%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%BA%AB%E4%BB%BD%E9%AA%8C%E8%AF%81%E3%80%82
X-Powered-By: ASP.NET
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff

[2019-09-02 07:52:51Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file E:\Agents\BuildAgent3\.credentials_rsaparams
[2019-09-02 07:54:31Z WARN VisualStudioServices] GET request to http://xxx.xxx.xxx.xxx:8080/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 100 seconds.
[2019-09-02 07:54:31Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-09-02 07:54:31Z ERR  MessageListener] Catch exception during create session.
[2019-09-02 07:54:31Z ERR  MessageListener] System.TimeoutException: The HTTP request timed out after 00:01:40. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenHttpClient.<GetTokenAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.<OnGetTokenAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenOperation.<GetTokenAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.<GetTokenAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__11.MoveNext()
[2019-09-02 07:54:31Z INFO MessageListener] Retriable exception: The HTTP request timed out after 00:01:40.
[2019-09-02 07:54:31Z ERR  Terminal] WRITE ERROR: 2019-09-02 07:54:31Z: 代理连接错误: The HTTP request timed out after 00:01:40.。 每隔 30 秒重试，直到重新连接为止。

**Comment by cawoodm** [comment]
Bump

**Comment by jtpetty** [comment]
@bj-yinyan , @cawoodm  - Are you still experiencing this issue?

**Comment by jtpetty** [comment]
closing due to inactivity.

It is possible that this issue is solved by:
https://developercommunity.visualstudio.com/solutions/802663/view.html
Use "https://[servername]/[organizationname]"
