### ISSUE TITLE
VS30063: You are not authorized to access http://{servername}:8080.

### ISSUE THREAD

**Issue by coreyperkins** [microsoft/azure-pipelines-agent#2486]
Connecting to server ...
VS30063: You are not authorized to access http://tfs2013.united-systems.local:8080.
Failed to connect.  Try again or ctrl-c to quit

I have tried everything I've found online including:

1) Assigning my user as admin on the tfs build agent
2) Going through and assigning myself to all collection service accounts, etc. Not sure where else to turn, but I need help. Please ask any questions necessary. Thanks!

`[2019-10-07 21:57:24Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2019-10-07 21:57:24Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 6.3.9600 .
[2019-10-07 21:57:24Z INFO AgentProcess] Version: 2.122.2
[2019-10-07 21:57:24Z INFO AgentProcess] Commit: d6dfa262c95d60addb71822e84bfa78e2e601e5e
[2019-10-07 21:57:24Z INFO AgentProcess] Culture: en-US
[2019-10-07 21:57:24Z INFO AgentProcess] UI Culture: en-US
[2019-10-07 21:57:24Z INFO HostContext] Well known directory 'Bin': 'C:\vstsagent\A8\bin'
[2019-10-07 21:57:24Z INFO HostContext] Well known directory 'Root': 'C:\vstsagent\A8'
[2019-10-07 21:57:24Z INFO AgentProcess] Validating directory permissions for: 'C:\vstsagent\A8'
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Generation: '1'
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Generation: '3'
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.0.10105.0'
[2019-10-07 21:57:24Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'CDF'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'v2.0.50727'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'v3.0'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'v3.5'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'v4'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'v4.0'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Version': '2.0.50727.4927'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Install': '1'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Found version: 2.0.50727
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version': '3.0.30729.4926'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Install': '1'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.0'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Found version: 3.0
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Version': '3.5.30729.4926'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Install': '1'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.5'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Found version: 3.5
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'Client'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  'Full'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.7.03062'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '461814'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Type is System.Int32
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.7.03062'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '461814'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Type is System.Int32
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Found 5 versions:
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  2.0.50727
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  3.0
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  3.5
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  4.6.2
[2019-10-07 21:57:24Z INFO NetFrameworkUtil]  4.6.2
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2019-10-07 21:57:24Z INFO CommandLineParser] Parse
[2019-10-07 21:57:24Z INFO CommandLineParser] Parsing 17 args
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: False
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding Command: configure
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: deploymentgroup
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: agent
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding flag: deploymentgroup
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding option 'agent': 'TFS2013001'
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: runasservice
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: work
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding flag: runasservice
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding option 'work': '_work'
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: url
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding option 'url': 'http://tfs2013.united-systems.local:8080/tfs/'
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: collectionname
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding option 'collectionname': 'WebSites'
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: projectname
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding option 'projectname': 'Web Portal'
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: deploymentgroupname
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding option 'deploymentgroupname': 'Web Portal G5 Test Deployment Group'
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] arg: auth
[2019-10-07 21:57:24Z INFO CommandLineParser] parsing argument
[2019-10-07 21:57:24Z INFO CommandLineParser] HasArgs: True
[2019-10-07 21:57:24Z INFO CommandLineParser] Adding option 'auth': 'Negotiate'
[2019-10-07 21:57:24Z INFO AgentProcess] Arguments parsed
[2019-10-07 21:57:24Z INFO VstsAgentWebProxy] No proxy setting found.
[2019-10-07 21:57:24Z INFO Agent] ExecuteCommand
[2019-10-07 21:57:24Z INFO ConfigurationStore] currentAssemblyLocation: C:\vstsagent\A8\bin\Agent.Listener.dll
[2019-10-07 21:57:24Z INFO HostContext] Well known directory 'Bin': 'C:\vstsagent\A8\bin'
[2019-10-07 21:57:24Z INFO ConfigurationStore] binPath: C:\vstsagent\A8\bin
[2019-10-07 21:57:24Z INFO HostContext] Well known directory 'Bin': 'C:\vstsagent\A8\bin'
[2019-10-07 21:57:24Z INFO HostContext] Well known directory 'Root': 'C:\vstsagent\A8'
[2019-10-07 21:57:24Z INFO ConfigurationStore] RootFolder: C:\vstsagent\A8
[2019-10-07 21:57:24Z INFO ConfigurationStore] ConfigFilePath: C:\vstsagent\A8\.agent
[2019-10-07 21:57:24Z INFO ConfigurationStore] CredFilePath: C:\vstsagent\A8\.credentials
[2019-10-07 21:57:24Z INFO ConfigurationStore] ServiceConfigFilePath: C:\vstsagent\A8\.service
[2019-10-07 21:57:24Z INFO ConfigurationStore] AutoLogonSettingsFilePath: C:\vstsagent\A8\.autologon
[2019-10-07 21:57:24Z INFO CommandSettings] Flag 'help': 'False'
[2019-10-07 21:57:24Z INFO CommandSettings] Flag 'version': 'False'
[2019-10-07 21:57:24Z INFO CommandSettings] Flag 'commit': 'False'
[2019-10-07 21:57:24Z INFO CommandSettings] Command 'configure': 'True'
[2019-10-07 21:57:24Z INFO ConfigurationManager] ConfigureAsync
[2019-10-07 21:57:24Z INFO ConfigurationStore] IsConfigured()
[2019-10-07 21:57:24Z INFO ConfigurationStore] IsConfigured: False
[2019-10-07 21:57:24Z INFO ConfigurationManager] Is configured: False
[2019-10-07 21:57:24Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.6'
[2019-10-07 21:57:24Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2019-10-07 21:57:24Z INFO CommandSettings] Flag 'deploymentgroup': 'True'
[2019-10-07 21:57:24Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2019-10-07 21:57:24Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2019-10-07 21:57:24Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2019-10-07 21:57:24Z INFO Terminal] WRITE LINE: 
[2019-10-07 21:57:24Z INFO Terminal] WRITE LINE: >> Connect:
[2019-10-07 21:57:24Z INFO Terminal] WRITE LINE: 
[2019-10-07 21:57:24Z INFO CommandSettings] Arg 'url': 'http://tfs2013.united-systems.local:8080/tfs/'
[2019-10-07 21:57:24Z INFO CommandSettings] Remove url from Arg dictionary.
[2019-10-07 21:57:24Z INFO DeploymentGroupAgentConfigProvider] url - http://tfs2013.united-systems.local:8080/tfs/
[2019-10-07 21:57:24Z INFO DeploymentGroupAgentConfigProvider] Provided url is for onprem tfs, need collection name
[2019-10-07 21:57:24Z INFO CommandSettings] Arg 'collectionname': 'WebSites'
[2019-10-07 21:57:24Z INFO CommandSettings] Remove collectionname from Arg dictionary.
[2019-10-07 21:57:24Z INFO ConfigurationManager] GetCredentialProvider
[2019-10-07 21:57:24Z INFO CommandSettings] Arg 'auth': 'Negotiate'
[2019-10-07 21:57:24Z INFO CommandSettings] Remove auth from Arg dictionary.
[2019-10-07 21:57:24Z INFO ConfigurationManager] Creating credential for auth: Negotiate
[2019-10-07 21:57:24Z INFO CredentialManager] GetCredentialProvider
[2019-10-07 21:57:24Z INFO CredentialManager] Creating type Negotiate
[2019-10-07 21:57:24Z INFO CredentialManager] Creating credential type: Negotiate
[2019-10-07 21:57:24Z INFO PersonalAccessToken] EnsureCredential
[2019-10-07 21:57:24Z INFO CommandSettings] Arg 'username': ''
[2019-10-07 21:57:24Z INFO CommandSettings] Flag 'unattended': 'False'
[2019-10-07 21:57:24Z INFO PromptManager] ReadValue
[2019-10-07 21:57:24Z INFO Terminal] WRITE: Enter user name > 
[2019-10-07 21:57:24Z INFO Terminal] READ LINE
[2019-10-07 21:57:27Z INFO Terminal] Read value: 'coreyp'
[2019-10-07 21:57:27Z INFO CommandSettings] Arg 'password': ''
[2019-10-07 21:57:27Z INFO CommandSettings] Flag 'unattended': 'False'
[2019-10-07 21:57:27Z INFO PromptManager] ReadValue
[2019-10-07 21:57:27Z INFO Terminal] WRITE: Enter password > 
[2019-10-07 21:57:27Z INFO Terminal] READ SECRET
[2019-10-07 21:57:32Z INFO Terminal] Read value: '********'
[2019-10-07 21:57:32Z INFO NegotiateCredential] GetVssCredentials
[2019-10-07 21:57:32Z INFO NegotiateCredential] User name retrieved.
[2019-10-07 21:57:32Z INFO NegotiateCredential] Password retrieved.
[2019-10-07 21:57:32Z INFO NegotiateCredential] URL retrieved: http://tfs2013.united-systems.local:8080/tfs/
[2019-10-07 21:57:32Z INFO ConfigurationManager] cred retrieved
[2019-10-07 21:57:32Z INFO Terminal] WRITE LINE: Connecting to server ...
[2019-10-07 21:57:32Z INFO DeploymentGroupAgentConfigProvider] Test connection with deployment group
[2019-10-07 21:57:32Z INFO DeploymentGroupAgentConfigProvider] Tfs Collection level url to connect - http://tfs2013.united-systems.local:8080/tfs//WebSites
[2019-10-07 21:57:32Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-10-07 21:57:32Z WARN VisualStudioServices] Authentication failed with status code 401.
Date: Mon, 07 Oct 2019 21:57:31 GMT
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Server: Microsoft-IIS/8.5
WWW-Authenticate: Bearer, Basic realm="http://tfs2013.united-systems.local:8080/tfs", Negotiate, NTLM
X-TFS-ProcessId: 8bb4b7f2-1f5c-46fe-a975-14fd79ca14ef
ActivityId: 5fed5111-3642-436b-bfaa-cc98fca9eed1
X-TFS-Session: 74534abf-9fb4-4a40-b442-f5be9024118a
X-VSS-E2EID: 11a8632f-39b9-4aa5-bf71-061cdd2a1e5c
X-FRAME-OPTIONS: SAMEORIGIN
X-TFS-SoapException: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
X-TFS-ServiceError: TF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.
X-Powered-By: ASP.NET
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff

[2019-10-07 21:57:32Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: private
Date: Mon, 07 Oct 2019 21:57:32 GMT
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Server: Microsoft-IIS/8.5
WWW-Authenticate: Bearer, Basic realm="http://tfs2013.united-systems.local:8080/tfs", Negotiate, NTLM
X-TFS-ProcessId: 8bb4b7f2-1f5c-46fe-a975-14fd79ca14ef
ActivityId: 5fed5113-3642-436b-bfaa-cc98fca9eed1
X-TFS-Session: 74534abf-9fb4-4a40-b442-f5be9024118a
X-VSS-E2EID: 11a8632f-39b9-4aa5-bf71-061cdd2a1e5c
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff

[2019-10-07 21:57:32Z WARN VisualStudioServices] Windows issued token provider instance 4032828 requires an interactive prompt which is not allowed by the current settings
[2019-10-07 21:57:32Z ERR  VisualStudioServices] GET request to http://tfs2013.united-systems.local:8080/tfs//WebSites/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 is not authorized. Details: VS30063: You are not authorized to access http://tfs2013.united-systems.local:8080.
[2019-10-07 21:57:32Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-10-07 21:57:32Z INFO CommandSettings] Flag 'unattended': 'False'
[2019-10-07 21:57:32Z ERR  Terminal] WRITE ERROR (exception):
[2019-10-07 21:57:32Z ERR  Terminal] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://tfs2013.united-systems.local:8080.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.DeploymentGroupServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider.<TestConnectionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__6.MoveNext()
[2019-10-07 21:57:32Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2019-10-07 21:57:32Z INFO CommandSettings] Arg 'url': ''
[2019-10-07 21:57:32Z INFO CommandSettings] Flag 'unattended': 'False'
[2019-10-07 21:57:32Z INFO PromptManager] ReadValue
[2019-10-07 21:57:32Z INFO Terminal] WRITE: Enter server URL > 
[2019-10-07 21:57:32Z INFO Terminal] READ LINE
`

**Comment by cawoodm** [comment]
Bump

**Comment by StingyJack** [comment]
It's probably nothing you are doing, VS has been suffering this error since 2017's release. 

I have found it's generally a transient or at least correctable condition. Usually I have to close all VS instances, then open a command prompt to one of the workspaces I have mapped for that server and run `tf vc status`

I used to have this happen a lot with a TFS2015.4 server, and my teammates have it periodically with azure DevOps. The only common parts I can ID are VS 2017 or later and TFVC workspaces.

If you run a Google search against the developer community site (don't bother with that sites built in search, it's awful) and use the criteria "TF30063" (the error code this used to be) there are a bunch of other ways I've found to address this. (No joke, I've opened more than a dozen reports of this over there with different originating conditions.)

**Comment by cawoodm** [comment]
We've certainly seen issue when an agent is not updating or fails during update - running the update manually from the agent pools section of devops can help. Otherwise it's manually reinstall the agent.

**Comment by jtpetty** [comment]
Is this the same as #2704 ?

https://developercommunity.visualstudio.com/solutions/802663/view.html
Use "https://[servername]/[organizationname]"

**Comment by StingyJack** [comment]
@jtpetty - how are we supposed to know if they are the same? This TF30063 (why rename it?) error pops up all the time and has since VS 2017 was released. I fairly sure its due to adding all the git ~advertising~ support.

Why did you suggest an azure devops url when OP clearly has an on premises server? Reopen and review this, if you need more examples I've pointed  out where to find them above.
