### ISSUE TITLE
Can't download two Github artifacts in the same release pipeline

### ISSUE THREAD

**Issue by joelshea** [microsoft/azure-pipelines-agent#2494]
## Agent Version and Platform
Version of your agent? 2.158.0

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/vimla

## What's not working?
I have a release pipeline (setup with the classic UI) that includes one pipeline artifact (which is not used, only for triggering the builds) and two GitHub artifacts.  The issue is that the second Github artifact always fails to download.  It doesn't matter what repo it is.  I've changed the order, I've changed the repos, always the same result. Only thing I will note is that they are both always private (connected using the GitHub Azure Pipelines app).  Every time, I get the same error message and stacktrace (first couple lines added for context):

```
2019-10-09T15:37:32.7804647Z Downloaded linked artifact devops
2019-10-09T15:37:32.7806488Z Starting artifacts download...
2019-10-09T15:37:33.0596835Z ##[error]Downloading artifacts failed: System.InvalidOperationException: NotFound
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.GitHubHttpClient.GetUserRepo(String accessToken, String repositoryName)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.GitHubArtifact.GetArtifactDetails(IExecutionContext context, AgentArtifactDefinition agentArtifactDefinition)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass46_0.<ConvertToArtifactDefinition>b__1()
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.Execute(Action action)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.ConvertToArtifactDefinition(AgentArtifactDefinition agentArtifactDefinition, IExecutionContext executionContext, IArtifactExtension extension)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.DownloadArtifacts(IExecutionContext executionContext, IList`1 agentArtifactDefinitions, String artifactsWorkingFolder)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.DownloadArtifactsAndCommitsAsync(IExecutionContext executionContext, Object data)
2019-10-09T15:37:33.0653937Z ##[error]NotFound
```

I _think_ that what is happening is that the same token is being used by the task for both calls but GitHub invalidates it after the first one is successful, maybe?  Either way, it's a real bummer.  Am I missing something obvious or is this truly an issue?

**Comment by Prachiti9** [comment]
@joelshea Can you please share your Azure pipeline url?

**Comment by Prachiti9** [comment]
Just noticed this is old post. Would be good to know if this is still an issue for you.

**Comment by joelshea** [comment]
Honestly, I'm not sure if this is still an issue.  We have mostly migrated to multi-stage YAML builds at this point (and this was for the old Classic view Release builds).

**Comment by sergerad** [comment]
Just experienced this bug today
