### ISSUE TITLE
Object reference not set to an instance of an object when registering on Ubuntu

### ISSUE THREAD

**Issue by pf1gura** [microsoft/azure-pipelines-agent#2513]
## Agent Version and Platform
Version of your agent? 2.158.0

OS of the machine running the agent? Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com/pf1gura

## What's not working?
When registering agent on new box, it fails on `config.sh` with below error.
Also, wen I run `installdependencies.sh`, the script deleted `curl` from the system.
```
[2019-10-15 20:00:02Z ERR  Agent] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.CalendarData.NormalizeDatePattern(String input)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarId calendarId)
   at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
   at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.DateTimeFormat.TryFormat(DateTime dateTime, Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider, TimeSpan offset)       at System.DateTimeFormat.TryFormat(DateTime dateTime, Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.DateTime.TryFormat(Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.VisualStudio.Services.Agent.Util.StringUtil.Format(CultureInfo culture, String format, Object[] args)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
```

The overall install script from Azure DevOps finishes with below messages.
```
Successfully replaced the agent
Testing agent connection.
Error reported in diagnostic logs. Please examine the log for more details.
    - /home/pf1gura/azagent/_diag/Agent_20191015-195939-utc.log
Object reference not set to an instance of an object.
sudo: ./svc.sh: command not found
sudo: ./svc.sh: command not found
```

## Agent and Worker's Diagnostic Logs
[Agent_20191015-195939-utc.txt](https://github.com/microsoft/azure-pipelines-agent/files/3731274/Agent_20191015-195939-utc.txt)

**Comment by sidleegit** [comment]
Getting the exact same error as of right now.
Installed the agent two days ago, went just fine, and now getting the same error.

Running Ubuntu 18.04.3 LTS in Azure.

@pf1gura Did you ever end up figuring out what was the issue ?

**Comment by pf1gura** [comment]
@sidleegit not really. This is a small project, so I am doing manual deployments for now. It would be nice to have this looked into.

**Comment by sidleegit** [comment]
@pf1gura, figured out the issue later in the day yesterday. Turns out it was a locale issue in the server... can’t pinpoint where or why it happened though, but it happened.

Here’s the command I used to fix it: `sudo sed -i "s/C.UTF-8/en_US.utf8/" /etc/default/locale `

Been setting up those exact same servers for more than a year now with no issue. It started happening the first time yesterday when I added extra repositories to get PHP7.3 and the latest Apache version. Will have to do some extra digging to figure out why, but worst case scenario, doing the above command makes everything work properly.

**Comment by pf1gura** [comment]
It worked for me. Thank you very much @sidleegit

**Comment by trevonmckay** [comment]
I'm having the same issue but the suggestion from @sidleegit is not working for me

![image](https://user-images.githubusercontent.com/18320804/73936237-5d00d100-48b0-11ea-901e-16d7549e5251.png)

**Comment by sidleegit** [comment]
@trevonmckay , have you restarted your server after applying the fix I gave ? I noticed last time I used it that without a restart, the ADO pipeline provisioning would still fail, but would immediately work after a quick reboot.

**Comment by trevonmckay** [comment]
@sidleegit yes restarting did solve it. Thanks!
