### ISSUE TITLE
config.sh does not ask for nor respect http_proxy

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-agent#2555]
The latest `config.sh` is unable to connect to devops - it is neither asking for a proxy nor is it respecting the `$http_proxy` environment setting.

## Agent Version and Platform
Latest

OS of the machine running the agent? CentOS

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/buhlergroup

## What's not working?
Following the installation instructions from the "New Agent" button in DevOps -> Agent Pools leads to an agent which cannot complete - it just hangs for several minutes then says:
> Error reported in diagnostic logs. Please examine the log for more details.
>    - /prg/_diag/Agent_20191030-143534-utc.log

## Agent and Worker's Diagnostic Logs
The log reveals an HTTP connect issue:
```
[2019-10-30 14:36:32Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-10-30 14:38:13Z WARN VisualStudioServices] GET request to https://buhlergroup.visualstudio.com/%1B/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 100 seconds.
[2019-10-30 14:38:13Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-10-30 14:38:13Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-10-30 14:39:53Z WARN VisualStudioServices] GET request to https://buhlergroup.visualstudio.com/%1B/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 100 seconds.
[2019-10-30 14:39:53Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-10-30 14:39:53Z INFO LocationServer] Catch exception during connect. 4 attempt left.
[2019-10-30 14:39:53Z ERR  LocationServer] System.TimeoutException: The HTTP request timed out after 00:01:40. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](Htt
```

**Comment by RufusJWB** [comment]
This is not working. I have configured `http_proxy` and `https_proxy` but only after using the `--proxyurl` switch the proxy is being picked up correctly.
