### ISSUE TITLE
Update Flaky

### ISSUE THREAD

**Issue by cawoodm** [microsoft/azure-pipelines-agent#2567]
The update process is causing agents to fail very often. We suspect the problem is with older Windows 2012 Servers and the "junction" functionality.

As can be seen here - the agent just hangs after deleting the junction:

![image](https://user-images.githubusercontent.com/498834/68049197-912d8a00-fce2-11e9-9b3e-f5474e3a4bc9.png)

# Log Extract at 20:05
```
[01.11.2019 19:50:02,35] --------whoami-------- 
foo\bar
[01.11.2019 19:50:02,44] --------whoami-------- 
[01.11.2019 19:50:02,44] Waiting for Agent.Listener.exe (8124) to complete 
Agent.Listener.exe            8124 Services                   0         32 K
[01.11.2019 19:50:02,75] Process 8124 still running, check again after 1 second. 
[01.11.2019 19:50:04,21] Process 8124 finished running 
[01.11.2019 19:50:04,21] Sleep 1 more second to make sure process exited 
[01.11.2019 19:50:05,04] Re-organize folders 
[01.11.2019 19:50:05,45] Delete existing junction bin folder 
```

There seem to be no other relevant logs.

Workaround - rename the newly created `./bin.2.159.2` folder to `bin`.

**Comment by jtpetty** [comment]
@cawoodm - Could you tell me what the externals link is pointing to? Looking at the screen shot I suspect it is still pointing to externals.2.158.0.

Looking at the update script, the next command that would have been executed is:

`dir "%rootfolder%" /AL 2>&1 | findstr "externals" >> "%logfile%" 2>&1`

It is possible that something is causing either the dir command to hang.

Can you verify that you have virus scanning disabled for the agent directory?

**Comment by cawoodm** [comment]
Yes, it was pointing at the old 2.158.0 version. We do indeed have Sophos and no easy possibility to turn it off. I cannot fathom why dir should hang either...

**Comment by jtpetty** [comment]
Can you add an exclusion in Sophos for the agent directory?

**Comment by cawoodm** [comment]
Unfortunately not easy to achieve. And even if we did - the agent is now updated after some wrangling so we could not reproduce the issue. As I say... flaky.

**Comment by cawoodm** [comment]
We're again having agents dropping out - this time at a partner location with no common infrastructure or anti-virus software.

## Self-Update-Log:
```
[Thu 11/07/2019  7:31:24.13] --------whoami-------- 
nt authority\system
[Thu 11/07/2019  7:31:24.16] --------whoami-------- 
[Thu 11/07/2019  7:31:24.16] Waiting for Agent.Listener.exe (160) to complete 
Agent.Listener.exe             160 Services                   0     60,156 K
[Thu 11/07/2019  7:31:24.31] Process 160 still running, check again after 1 second. 
[Thu 11/07/2019  7:31:25.44] Process 160 finished running 
[Thu 11/07/2019  7:31:25.44] Sleep 1 more second to make sure process exited
```

The updater/agent hangs around here:
```
echo [%date% %time%] Sleep 1 more second to make sure process exited >> "%logfile%" 2>&1
ping -n 2 127.0.0.1 >nul 
echo [%date% %time%] Re-organize folders >> "%logfile%" 2>&1
```

Im Agent-Log steht folgendes:
```
[2019-11-07 06:31:24Z INFO SelfUpdater] Update script start running
[2019-11-07 06:31:24Z INFO Terminal] WRITE LINE: Agent will exit shortly for update, should back online within 10 seconds.
[2019-11-07 06:31:24Z INFO Agent] Auto update task finished at backend, an agent update is ready to apply exit the current agent instance.
[2019-11-07 06:31:24Z INFO Agent] Stop message queue looping.
[2019-11-07 06:31:24Z WARN VisualStudioServices] GET request to https://buhlergroup.visualstudio.com/_apis/distributedtask/pools/41/messages?sessionId=7f780b2d-5cc4-4a8b-9cf5-*****&lastMessageId=41 has been cancelled.
[2019-11-07 06:31:24Z INFO MessageListener] Get next message has been cancelled.
[2019-11-07 06:31:24Z INFO Agent] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
[2019-11-07 06:31:24Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.

```
One theory: we run the agent with NSSM and NSSM's job is to restart the service if it stops. However we have seen successful updates on 1 of 4 servers with "exactly" the same setup.

**Comment by cawoodm** [comment]
We're also seeing the agent on Linux (CentOS) having issues updating. Is there any way to check which version is installed and/or run an update from the command prompt?

**Comment by cawoodm** [comment]
Also, it's weird that we can't run the agent as root. This means we cannot say, deploy a systemd service since we can't stop/start it.

**Comment by cawoodm** [comment]
We are seeing tasks queued and agents half-updated again on Windows servers. We run the agent as a windows service with NSSM. Could it be that the update script is unable to properly start and stop the service? In our `.service` file is the correct name of the windows service which can indeed be started and stopped with normal commands (net or powershell).

**Comment by jtpetty** [comment]
@cawoodm - Your theory about NSSM makes sense. It could be that when the update script takes down the service to perform the update, NSSM restarts it before the update script finishes and that is where problems happen.

@vtbassmatt - Does this make sense? I think we have talked previously about this issue. Does it align with what you have seen?

@cawoodm - Regarding your question about updating from the command line, you can do that manually by downloading the latest agent binaries from GitHub (https://github.com/microsoft/azure-pipelines-agent/releases)

**Comment by vtbassmatt** [comment]
@jtpetty interesting. Windows service management is definitely not a strong suit of mine, but this seems plausible.

**Comment by cawoodm** [comment]
So we've seen the agent hang again today on update (Windows and Linux), apparently trying to update to `1.163.0`. We are not using the auto-restart feature of NSSM so I can't see how NSSM could be causing the problem.

It looks as though the agent stopped itself but never regained consciousness.

Again the "solution" was to fix the junction (symlinks) which pointed to e.g. `bin.2.160.1` and make them point at the correct version e.g. `bin.2.163.1`.

## .\_diag\SelfUpdate-20191219-080823.log (entire log)
```
[19.12.2019  9:08:23.92] --------whoami-------- 
mydomain\u*****
[19.12.2019  9:08:24.03] --------whoami-------- 
[19.12.2019  9:08:24.03] Waiting for Agent.Listener.exe (4704) to complete 
Agent.Listener.exe            4704 Services                   0     67'044 K
[19.12.2019  9:08:24.50] Process 4704 still running, check again after 1 second. 
[19.12.2019  9:08:25.85] Process 4704 finished running 
[19.12.2019  9:08:25.85] Sleep 1 more second to make sure process exited 
```

## .\_diag\Agent_20191214-132604-utc.log (tail of log)
```
[2019-12-19 08:06:52Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file D:\azure\azagent\build\.credentials_rsaparams
[2019-12-19 08:06:52Z INFO MessageListener] Message '325' received from session '********-a938-4307-974e-c171e9d6f144'.
[2019-12-19 08:06:52Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2019-12-19 08:06:52Z INFO SelfUpdater] Version '2.163.1' of 'agent' package available in server.
[2019-12-19 08:06:52Z INFO SelfUpdater] Current running agent version is 2.160.1
[2019-12-19 08:06:52Z INFO SelfUpdater] An update is available.
[2019-12-19 08:06:52Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2019-12-19 08:06:52Z INFO Terminal] WRITE LINE: Downloading 2.163.1 agent
[2019-12-19 08:06:52Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:06:52Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:06:52Z INFO HostContext] Well known directory 'Work': 'D:\azure\azagent\build\_work'
[2019-12-19 08:07:02Z INFO SelfUpdater] Attempt 1: save latest agent into D:\azure\azagent\build\_work\_update\agent1.zip.
[2019-12-19 08:07:02Z INFO SelfUpdater] Download agent: begin download
[2019-12-19 08:07:17Z INFO SelfUpdater] Download agent: finished download
[2019-12-19 08:08:03Z INFO SelfUpdater] Finished getting latest agent package at: D:\azure\azagent\build\_work\_update.
[2019-12-19 08:08:03Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:03Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:03Z INFO SelfUpdater] Copy D:\azure\azagent\build\_work\_update\bin to D:\azure\azagent\build\bin.2.163.1.
[2019-12-19 08:08:03Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:03Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:03Z INFO SelfUpdater] Copy D:\azure\azagent\build\_work\_update\externals to D:\azure\azagent\build\externals.2.163.1.
[2019-12-19 08:08:12Z INFO SelfUpdater] Copy any remaining .sh/.cmd files into agent root.
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO SelfUpdater] Download latest agent and unzip into agent root.
[2019-12-19 08:08:12Z INFO Terminal] WRITE LINE: Waiting for current job finish running.
[2019-12-19 08:08:12Z INFO JobDispatcher] Waiting WorkerDispather for job ecce315e-dd11-5410-94b8-fc794d4b3401 run to finish.
[2019-12-19 08:08:12Z INFO JobDispatcher] Job request ecce315e-dd11-5410-94b8-fc794d4b3401 processed succeed.
[2019-12-19 08:08:12Z INFO SelfUpdater] All running jobs have exited.
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:12Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:12Z INFO SelfUpdater] Delete agent bin folder's backup at D:\azure\azagent\build\bin.2.160.0.
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:15Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:15Z INFO SelfUpdater] Delete agent externals folder's backup at D:\azure\azagent\build\externals.2.160.0.
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO SelfUpdater] Delete old version agent backup.
[2019-12-19 08:08:23Z INFO Terminal] WRITE LINE: Generate and execute update script.
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Diag': 'D:\azure\azagent\build\_diag'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Bin': 'D:\azure\azagent\build\bin'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Root': 'D:\azure\azagent\build'
[2019-12-19 08:08:23Z INFO HostContext] Well known directory 'Work': 'D:\azure\azagent\build\_work'
[2019-12-19 08:08:23Z INFO SelfUpdater] Generate update script into: D:\azure\azagent\build\_work\_update.cmd
[2019-12-19 08:08:23Z INFO SelfUpdater] Which: 'cmd.exe'
[2019-12-19 08:08:23Z INFO SelfUpdater] Location: 'C:\windows\system32\cmd.exe'
[2019-12-19 08:08:23Z INFO SelfUpdater] Update script start running
[2019-12-19 08:08:23Z INFO Terminal] WRITE LINE: Agent will exit shortly for update, should back online within 10 seconds.
[2019-12-19 08:08:23Z INFO Agent] Auto update task finished at backend, an agent update is ready to apply exit the current agent instance.
[2019-12-19 08:08:23Z INFO Agent] Stop message queue looping.
[2019-12-19 08:08:23Z WARN VisualStudioServices] GET request to https://mygroup.visualstudio.com/_apis/distributedtask/pools/41/messages?sessionId=********-a938-4307-974e-c171e9d6f144&lastMessageId=325 has been cancelled.
[2019-12-19 08:08:23Z INFO MessageListener] Get next message has been cancelled.
[2019-12-19 08:08:23Z INFO Agent] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
[2019-12-19 08:08:23Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
```

**Comment by cawoodm** [comment]
Our Linux systemd config:
```
[Unit]
Description=Azure Build Agent
After=network.target remote-fs.target nss-lookup.target

[Service]
WorkingDirectory=/prg/azure/build/
ExecStart=/prg/azure/build/run.sh
User=myserviceuser
SyslogIdentifier=azurebuild
# Don't restart agent because this breaks the update process
#Restart=on-failure
#RestartSec=10
StandardOutput=syslog
StandardError=syslog
Type=simple

[Install]
WantedBy=multi-user.target
```

**Comment by damccorm** [comment]
@cawoodm sorry this has slipped through the cracks a little bit - are you still experiencing the issue?

**Comment by cawoodm** [comment]
This issue seems to be resolved - We haven't had an agent fail in weeks now.

**Comment by cawoodm** [comment]
No, we're failing again.

**Comment by cawoodm** [comment]
## Check the Service
```
[me@myserver ~]$ journalctl -u  azurebuild.service
-- No entries --
[me@myserver ~]$ systemctl status azurebuild.service
● azurebuild.service - Azure Build Agent
   Loaded: loaded (/etc/systemd/system/azurebuild.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-05-15 20:37:41 CEST; 2 days ago
  Process: 1310 ExecStart=/prg/azure/build/run.sh (code=exited, status=2)
 Main PID: 1310 (code=exited, status=2)

May 13 13:22:46 myserver azurebuild[1310]: 2020-05-13 11:22:46Z: Running job: Deploy on all DEV Servers ecom_app03_dev
May 13 13:22:50 myserver powershell[1377]: (6.2.3:1:80) [Perftrack_ConsoleStartupStart:PowershellConsoleStartup.WinStart.Informational] PowerShell console is starting up
May 13 13:22:50 myserver powershell[1377]: (6.2.3:8:80) [NamedPipeIPC_ServerListenerStarted:NamedPipe.Open.Informational] Windows PowerShell has started an IPC listening thread on process: 137...pDomain: None.
May 13 13:22:50 myserver powershell[1377]: (6.2.3:1:80) [Perftrack_ConsoleStartupStop:PowershellConsoleStartup.WinStop.Informational] PowerShell console is ready for user input
May 13 13:23:10 myserver azurebuild[1310]: 2020-05-13 11:23:10Z: Job Deploy on all DEV Servers ecom_app03_dev completed with result: Canceled
May 15 20:30:51 myserver azurebuild[1310]: 2020-05-15 18:30:51Z: Agent connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.
May 15 20:37:41 myserver azurebuild[1310]: An error occurred: A task was canceled.
May 15 20:37:41 myserver systemd[1]: azurebuild.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 15 20:37:41 myserver systemd[1]: Unit azurebuild.service entered failed state.
May 15 20:37:41 myserver systemd[1]: azurebuild.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

## Restart Service
```
[me@myserver ~]$ systemctl stop azurebuild.service
[me@myserver ~]$ ps -ax | grep azure
 90325 pts/0    S+     0:00 grep --color=auto azure
[me@myserver ~]$ systemctl start azurebuild.service
[me@myserver ~]$ systemctl status azurebuild.service
● azurebuild.service - Azure Build Agent
   Loaded: loaded (/etc/systemd/system/azurebuild.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-05-18 15:12:51 CEST; 2s ago
 Main PID: 90337 (run.sh)
    Tasks: 13
   Memory: 42.9M
   CGroup: /system.slice/azurebuild.service
           ├─90337 /bin/bash /prg/azure/build/run.sh
           └─90343 /prg/azure/build/bin/Agent.Listener run

May 18 15:12:51 myserver systemd[1]: Started Azure Build Agent.
May 18 15:12:52 myserver azurebuild[90337]: Scanning for tool capabilities.
May 18 15:12:52 myserver azurebuild[90337]: Connecting to the server.
May 18 15:12:53 myserver azurebuild[90337]: 2020-05-18 13:12:53Z: Listening for Jobs
```

**Comment by cawoodm** [comment]
## Systemd Config:
```
[Unit]
Description=Azure Build Agent
After=network.target remote-fs.target nss-lookup.target

[Service]
WorkingDirectory=/prg/azure/build/
ExecStart=/prg/azure/build/run.sh
User=myserviceuser
# Can't be run as root
#User=root
SyslogIdentifier=azurebuild
# Don't restart agent because this breaks the update process
#Restart=on-failure
#RestartSec=10
StandardOutput=syslog
StandardError=syslog
Type=simple

[Install]
WantedBy=multi-user.target
```

**Comment by cawoodm** [comment]
@damccorm I've posted some more details from our linux agent which was down.

**Comment by cawoodm** [comment]
Windows update failed today again. Had to delete the JUNCTIONS and re-create them. It just hangs on:

```
Downloading 2.169.1 agent
Waiting for current job finish running.
Generate and execute update script.
Agent will exit shortly for update, should back online within 10 seconds.
```
