### ISSUE TITLE
Slow DownloadPipelineArtifact with many logged exceptions

### ISSUE THREAD

**Issue by Tragetaschen** [microsoft/azure-pipelines-agent#2570]
## Agent Version and Platform
2.159.2 / Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com
target-sg.visualstudio.com

## What's not working?
I have migrated from build artifacts to pipeline artifacts. For publishing, I'm already seeing great time saves due to the deduplication. However, downloading the pipeline artifact—especially the large ones—results in many logged exceptions. I have one artifacts with two files and a total size of about 550 MiB. This takes more than 10 minutes (15, 20) to download while with the 100Mbit/s connection I have, it should/could be done in less than a minute. I'm downloading the artifacts into a new folder, so a full download is necessary. Downloading succeeds eventually.

All download tasks typically start with a couple of these:
```
2019-11-04T10:02:25.2914315Z No LastRequestResponse on exception HttpRequestException: An error occurred while sending the request. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
2019-11-04T10:02:25.2914459Z    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
2019-11-04T10:02:25.2914497Z    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
2019-11-04T10:02:25.2914715Z    --- End of inner exception stack trace ---
2019-11-04T10:02:25.2914759Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-11-04T10:02:25.2914796Z    at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
2019-11-04T10:02:25.2914837Z    at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass56_0.<<GetRedirectResponseAsync>b__0>d.MoveNext()
2019-11-04T10:02:25.2915035Z --- End of stack trace from previous location where exception was thrown ---
2019-11-04T10:02:25.2915077Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
```

The larger ones later switch to these logged exceptions
```
2019-11-04T10:06:00.0351867Z Task was requested to be canceled. System.Threading.Tasks.TaskCanceledException: A task was canceled.
2019-11-04T10:06:00.0352031Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-11-04T10:06:00.0352241Z    at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
2019-11-04T10:06:00.0352422Z    at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass56_0.<<GetRedirectResponseAsync>b__0>d.MoveNext()
2019-11-04T10:06:00.0353408Z --- End of stack trace from previous location where exception was thrown ---
2019-11-04T10:06:00.0353594Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
```

**Comment by johnterickson** [comment]
@jahsu-MSFT

**Comment by jahsu-MSFT** [comment]
Looking into it

**Comment by Tragetaschen** [comment]
Looks like it's not tied to the task. I just tried downloading one of the two artifacts manually in the browser with a size of 170 MiB. It started at 2 MiB/s (instead of 10 MiB/s that would be my available bandwidth) and at around 150 MiB it pretty much stalled for way more than minute before continuing it to the end.
I had time to start capturing a GIF and and all (yes, GIF, not static image :)
![slow-artifact-download](https://user-images.githubusercontent.com/1947968/68964436-aeca1b80-07d9-11ea-9cb5-893b59e42a48.gif)

**Comment by jahsu-MSFT** [comment]
@Tragetaschen  Are you downloading it using the download pipeline artifact task or using the rest api endpoint from browser?

**Comment by Tragetaschen** [comment]
Both.
During build, I'm using the task, but the above is captured from Edge.

**Comment by Tragetaschen** [comment]
I have monitored my router's bandwidth usage reporting during both the upload and download pipeline artifact tasks.

The upload task is an absolute pleasure to watch. It's fully saturating my available upstream bandwidth.

The download task starts slowish and then a moves to a pattern where every sixty seconds, there's a bit of upload and then 45 seconds of stalling:

I've stiched together a couple of screen shots from the router's graphs when the pattern started:
![image](https://user-images.githubusercontent.com/1947968/68967015-98bf5980-07df-11ea-9caa-ab1031846f06.png)
The marked pattern repeats about every 60 seconds and I'm 17 minutes in to the download task

**Comment by Tragetaschen** [comment]
Are there any updates?
Every Download Pipeline Artifacts task is still struggling. In my most recent build, uploading 530 MiB (two files) took 2.5 minutes while downloading that same artifact afterwards took 20 minutes

**Comment by jahsu-MSFT** [comment]
Adding @fadnavistanmay who will be working on Pipeline Artifacts related features/improvements.

**Comment by 4F2E4A2E** [comment]
I am experiencing the same error all over different agent version:
` at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)`

Pls anyone, what the is this? Can you provide some `dotnet new console` example code to reproduce this in a manner which brings us closer to a solution?

curl: works
csharp-example-code: works
libcurl: works
openssh: works
ssl connections in any way: works
dotnet dependencies and tools: works
azure agent for linux: does not work at all

Experiencing the same behavior on rhel6 with curl 7.67, no matter what I do.
openssh, curl and dotnet-console tests to the very same host can be established are nominal

buut with the agent it's not working at all
![image](https://user-images.githubusercontent.com/64590/87253597-c8ad2280-c47c-11ea-86a5-0bd70cb580c0.png)
![image](https://user-images.githubusercontent.com/64590/87253612-ed08ff00-c47c-11ea-80d9-9c2c0f6a0652.png)
![image](https://user-images.githubusercontent.com/64590/87253667-48d38800-c47d-11ea-91ee-d9c2c5035ef6.png)

**Comment by jahsu-MSFT** [comment]
@fadnavistanmay

**Comment by 4F2E4A2E** [comment]
Compiling the latest curl, installing it, and replacing the curl symbolic link in the RHEL6 did solve the problem. 
The issue can be closed.

**Comment by anatolybolshakov** [comment]
@4F2E4A2E @Tragetaschen do you still see this issue?

**Comment by Tragetaschen** [comment]
I don’t have access to the pipeline anymore

**Comment by anatolybolshakov** [comment]
@Tragetaschen ok thanks!
@4F2E4A2E do you still face with this issue?

**Comment by 4F2E4A2E** [comment]
> Compiling the latest curl, installing it, and replacing the curl symbolic link in the RHEL6 did solve the `ThrowIfCURLEError` problem.

As stated, the problem is solved. Thank you.

**Comment by anatolybolshakov** [comment]
Ok thanks! 
@Tragetaschen let us investigate if there's any possible bottleneck which could lead to this slow down.
