### ISSUE TITLE
A session for this agent already exists.

### ISSUE THREAD

**Issue by rychuhardy** [microsoft/azure-pipelines-agent#2588]
## Agent Version and Platform
Version: 2.160.0
Commit: 075cdc67f485e241a308e534c38d7caa2bc355e5

OS of the machine running the agent? 
Linux
Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/rsikora

## What's not working?
The agent successfully connects to DevOps and runs a build, but then after some time or after VM is restarted (static IP on the VM) the agent loses connection:
![obraz](https://user-images.githubusercontent.com/11320146/68598921-f5e5a300-049f-11ea-9723-906b4587d16f.png)
Trying to restart svc.sh causes the following exception:
```
Nov 11 15:20:57 build-agent-1 runsvc.sh[36752]: Connecting to the server.
Nov 11 15:21:00 build-agent-1 runsvc.sh[36752]: Error reported in diagnostic logs. Please examine the log for more details.
Nov 11 15:21:00 build-agent-1 runsvc.sh[36752]:     - /home/emt_admin/myagent/_diag/Agent_20191111-152056-utc.log
Nov 11 15:21:00 build-agent-1 runsvc.sh[36752]: A session for this agent already exists.
Nov 11 15:21:00 build-agent-1 runsvc.sh[36752]: An error occurred: Object reference not set to an instance of an object.
Nov 11 15:21:00 build-agent-1 runsvc.sh[36752]: Agent listener exited with error code 2
Nov 11 15:21:00 build-agent-1 runsvc.sh[36752]: Agent listener exit with retryable error, re-launch agent in 5 seconds.
```

## Agent and Worker's Diagnostic Logs
```
[2019-11-11 15:16:10Z INFO Terminal] WRITE LINE: Connecting to the server.
[2019-11-11 15:16:10Z INFO MessageListener] Attempt to create session.
[2019-11-11 15:16:10Z INFO MessageListener] Connecting to the Agent Server...
[2019-11-11 15:16:10Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2019-11-11 15:16:10Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-11-11 15:16:10Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-11-11 15:16:11Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2019-11-11 15:16:11Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-11-11 15:16:11Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-11-11 15:16:12Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2019-11-11 15:16:12Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2019-11-11 15:16:12Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2019-11-11 15:16:13Z INFO MessageListener] VssConnection created
[2019-11-11 15:16:13Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/9d3d2e3a-d5b6-48ec-95db-da6b462775cd, Basic realm="http
s://tfsprodweu5.visualstudio.com/", TFS-Federated
X-TFS-ProcessId: 3394e371-315d-42c3-b429-6a42c4448dac
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: df16edbf-a4a7-425d-be13-de76b778f3da
X-TFS-Session: 928ca1ce-7f82-42fb-863b-956b6475d62e
X-VSS-E2EID: faf30b46-28c8-4598-9b37-9eaf17f4f1e8
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://tfsprodweu5.visualstudio.com/
X-TFS-FedAuthIssuer: https://dev.azure.com/rsikora/
X-VSS-AuthorizationEndpoint: https://vssps.dev.azure.com/rsikora/
X-VSS-ResourceTenant: 9d3d2e3a-d5b6-48ec-95db-da6b462775cd
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://spsprodweu4.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2Frsikora%2F_apis%2Fdistributedtask%2Fpools%2F10%2Fsessions&redirect=1&hid=52bb600e-27c7-4148-9c90-989130ac8006&context=****
Request-Context: appId=cid-v1:1d01aa00-5a22-493d-8bc0-acd0af8f839d
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-MSEdge-Ref: Ref A: B3118CE127AF4E228F398AC044F1B5C3 Ref B: LON21EDGE1407 Ref C: 2019-11-11T15:16:13Z
Date: Mon, 11 Nov 2019 15:16:12 GMT

[2019-11-11 15:16:13Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/emt_admin/myagent/.credentials_rsaparams
[2019-11-11 15:16:13Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/emt_admin/myagent/.credentials_rsaparams
[2019-11-11 15:16:13Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2019-11-11 15:16:13Z INFO MessageListener] Session created.
[2019-11-11 15:16:13Z ERR  Terminal] WRITE ERROR: An error occurred: Object reference not set to an instance of an object.
[2019-11-11 15:16:13Z ERR  AgentProcess] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.CalendarData.NormalizeDatePattern(String input)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarId calendarId)
   at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
   at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.DateTimeFormat.TryFormat(DateTime dateTime, Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider, TimeSpan offset)
   at System.DateTimeFormat.TryFormat(DateTime dateTime, Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.DateTime.TryFormat(Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.VisualStudio.Services.Agent.Util.StringUtil.Format(CultureInfo culture, String format, Object[] args)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)

```

**Comment by rychuhardy** [comment]
The problem is related to the bug described here https://github.com/dotnet/corefx/issues/37630 and solution with setting locale worked for me

**Comment by jtpetty** [comment]
@rychuhardy - since you were able to work around this issue and since it is a bug in dotnet and not with the agent, and we are actively working to migrate the agent to dotnet 3.1 which has the bug fixed, I am going to close this particular issue.
