### ISSUE TITLE
Devops Agent fails to start on k8s cluster

### ISSUE THREAD

**Issue by jchauncey** [microsoft/azure-pipelines-agent#2632]
## Agent Version and Platform
2.160.1

OS of the machine running the agent? OSX/Windows/Linux/...
Linux

## Azure DevOps Type and Version
dev.azure.com 

If dev.azure.com, what is your organization name? 
https://dev.azure.com/AzureContainerUpstream

## What's not working?
I am trying to run the agent as a pod on a kubernetes cluster. Ive used [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#environment-variables) doc as a template to get me started. The container works fine locally and attaches to my agent pool. But when starting it on the k8s cluster I get the following:

```
1. Determining matching Azure Pipelines agent...
2. Downloading and installing Azure Pipelines agent...
3. Configuring Azure Pipelines agent...
AZP_URL:https://dev.azure.com/AzureContainerUpstream
2.160.1
4. Running Azure Pipelines agent...
Starting Agent listener interactively
Started listener process
Started running service
Error reported in diagnostic logs. Please examine the log for more details.
    - /azp/agent/_diag/Agent_20191126-181247-utc.log
An error occurred: Not configured
Agent listener exited with error code 2
Agent listener exit with retryable error, re-launch agent in 5 seconds.
```

That log file shows the following:

```
[2019-11-26 18:21:00Z INFO AgentProcess] Agent built on Linux (X64) - linux-x64.
[2019-11-26 18:21:00Z INFO AgentProcess] Agent built for Linux (X64).
[2019-11-26 18:21:00Z INFO AgentProcess] Running on Linux (X64).
[2019-11-26 18:21:00Z INFO AgentProcess] RuntimeInformation: Linux 4.15.0-1060-azure #65-Ubuntu SMP Wed Sep 18 08:55:51 UTC 2019.
[2019-11-26 18:21:00Z INFO AgentProcess] Version: 2.160.1
[2019-11-26 18:21:00Z INFO AgentProcess] Commit: 8c04bd1029f0b89ede934e870f0eac413da3156c
[2019-11-26 18:21:00Z INFO AgentProcess] Culture: 
[2019-11-26 18:21:00Z INFO AgentProcess] UI Culture: 
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO AgentProcess] Validating directory permissions for: '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO CommandLineParser] Parse
[2019-11-26 18:21:00Z INFO CommandLineParser] Parsing 1 args
[2019-11-26 18:21:00Z INFO CommandLineParser] parsing argument
[2019-11-26 18:21:00Z INFO CommandLineParser] HasArgs: False
[2019-11-26 18:21:00Z INFO CommandLineParser] Adding Command: run
[2019-11-26 18:21:00Z INFO AgentProcess] Arguments parsed
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known config file 'Proxy': '/azp/agent/.proxy'
[2019-11-26 18:21:00Z INFO VstsAgentWebProxy] No proxy setting found.
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known config file 'Certificates': '/azp/agent/.certificates'
[2019-11-26 18:21:00Z INFO AgentCertificateManager] No certificate setting found.
[2019-11-26 18:21:00Z INFO Agent] ExecuteCommand
[2019-11-26 18:21:00Z INFO ConfigurationStore] currentAssemblyLocation: /azp/agent/bin/Agent.Listener.dll
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO ConfigurationStore] binPath: /azp/agent/bin
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO ConfigurationStore] RootFolder: /azp/agent
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known config file 'Agent': '/azp/agent/.agent'
[2019-11-26 18:21:00Z INFO ConfigurationStore] ConfigFilePath: /azp/agent/.agent
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known config file 'Credentials': '/azp/agent/.credentials'
[2019-11-26 18:21:00Z INFO ConfigurationStore] CredFilePath: /azp/agent/.credentials
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known config file 'Service': '/azp/agent/.service'
[2019-11-26 18:21:00Z INFO ConfigurationStore] ServiceConfigFilePath: /azp/agent/.service
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known config file 'Autologon': '/azp/agent/.autologon'
[2019-11-26 18:21:00Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /azp/agent/.autologon
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Bin': '/azp/agent/bin'
[2019-11-26 18:21:00Z INFO HostContext] Well known directory 'Root': '/azp/agent'
[2019-11-26 18:21:00Z INFO HostContext] Well known config file 'Options': '/azp/agent/.options'
[2019-11-26 18:21:00Z INFO ConfigurationStore] RuntimeOptionsFilePath: /azp/agent/.options
[2019-11-26 18:21:00Z INFO CommandSettings] Flag 'help': 'False'
[2019-11-26 18:21:00Z INFO CommandSettings] Flag 'version': 'False'
[2019-11-26 18:21:00Z INFO CommandSettings] Flag 'commit': 'False'
[2019-11-26 18:21:00Z INFO CommandSettings] Command 'configure': 'False'
[2019-11-26 18:21:00Z INFO CommandSettings] Command 'remove': 'False'
[2019-11-26 18:21:00Z INFO CommandSettings] Command 'warmup': 'False'
[2019-11-26 18:21:00Z INFO ConfigurationManager] LoadSettings
[2019-11-26 18:21:00Z INFO ConfigurationStore] IsConfigured()
[2019-11-26 18:21:00Z INFO ConfigurationStore] IsConfigured: False
[2019-11-26 18:21:00Z INFO ConfigurationManager] Is configured: False
[2019-11-26 18:21:00Z ERR  Terminal] WRITE ERROR: An error occurred: Not configured
[2019-11-26 18:21:00Z ERR  AgentProcess] System.InvalidOperationException: Not configured
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.LoadSettings()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by jtpetty** [comment]
@jchauncey - the issue is that the agent is not configured. On the node in the k8s cluster, do you see a .agent file in the root of the agent install directory? This file (along with .credentials and .credentials_rsaparams) are what tells the agent it has been configured.

**Comment by jchauncey** [comment]
Ok so I dont have a .agent file/dir in the install directory. According to the logs it looks like everything is fine. And this works correctly if I just start the container using a straight `docker run`. Is there some place beside that log file I posted above that can tell me what is happening during configuration?

**Comment by jtpetty** [comment]
Do you have write permission to the install directory for the agent when it starts up in the k8s node? Is it possible that the config step is silently bombing out that it can't write the .agent file?

**Comment by jchauncey** [comment]
Ok so I got it working but I changed a few different things so I'm not entirely sure what fixed it. I think it had something to do with the `--version` flag.

**Comment by kalebasiyakup** [comment]
how did you solve this problem? I'm getting the same error.
