### ISSUE TITLE
Same container definition is created twice and both are then started, thus conflict

### ISSUE THREAD

**Issue by zielyn** [microsoft/azure-pipelines-agent#2674]
#Agent Version and Platform
2.162.0
Code of yml:

```
variables:
  saPassword: 'P@ssw0rd'

resources:    
  containers: 
  - container: sqlserver_dev
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    env: 
      SA_PASSWORD: '$(saPassword)'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
    ports:
      - 1433:1433
    options: --user 0:0
      
jobs:
- job: Container_Test
  displayName: Test Container Issue

  pool:
    vmImage: 'ubuntu-16.04'

  services:
    sqlserver: sqlserver_dev

  steps:
  - checkout: none
  - pwsh: |
      docker ps -a
```
Troubleshooting: 
changed pool to ubuntu-18.04
changed docker image to mcr.microsoft.com/mssql/server:2017-latest
Removed option

"Initialize containers" log
```
##[debug]Evaluating condition for step: 'Initialize containers'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Initialize containers
##[command]/usr/bin/docker version --format '{{.Server.APIVersion}}'
'1.40'
Docker daemon API version: '1.40'
##[command]/usr/bin/docker version --format '{{.Client.APIVersion}}'
'1.40'
Docker client API version: '1.40'
##[debug]Delete stale containers from previous jobs
##[command]/usr/bin/docker ps --all --quiet --no-trunc --filter "label=726480"
##[debug]Delete stale container networks from previous jobs
##[command]/usr/bin/docker network prune --force --filter "label=726480"
##[command]/usr/bin/docker pull mcr.microsoft.com/mssql/server:2019-latest
2019-latest: Pulling from mssql/server
59ab41dd721a: Pulling fs layer
57da90bec92c: Pulling fs layer
06fe57530625: Pulling fs layer
5a6315cba1ff: Pulling fs layer
739f58768b3f: Pulling fs layer
b77fc38faae9: Pulling fs layer
11ca25075c70: Pulling fs layer
c957a137b2c5: Pulling fs layer
4794f7ad490c: Pulling fs layer
739f58768b3f: Waiting
b77fc38faae9: Waiting
11ca25075c70: Waiting
c957a137b2c5: Waiting
4794f7ad490c: Waiting
5a6315cba1ff: Waiting
57da90bec92c: Verifying Checksum
57da90bec92c: Download complete
06fe57530625: Verifying Checksum
06fe57530625: Download complete
5a6315cba1ff: Verifying Checksum
5a6315cba1ff: Download complete
739f58768b3f: Verifying Checksum
739f58768b3f: Download complete
b77fc38faae9: Download complete
59ab41dd721a: Verifying Checksum
59ab41dd721a: Download complete
11ca25075c70: Verifying Checksum
11ca25075c70: Download complete
4794f7ad490c: Verifying Checksum
4794f7ad490c: Download complete
59ab41dd721a: Pull complete
57da90bec92c: Pull complete
c957a137b2c5: Verifying Checksum
c957a137b2c5: Download complete
06fe57530625: Pull complete
5a6315cba1ff: Pull complete
739f58768b3f: Pull complete
b77fc38faae9: Pull complete
11ca25075c70: Pull complete
c957a137b2c5: Pull complete
4794f7ad490c: Pull complete
Digest: sha256:0753f9e9c614c469e1e6b98ea60b21e20abd249323c9f6a9eab476c87a8cf826
Status: Downloaded newer image for mcr.microsoft.com/mssql/server:2019-latest
mcr.microsoft.com/mssql/server:2019-latest
##[command]/usr/bin/docker pull mcr.microsoft.com/mssql/server:2019-latest
2019-latest: Pulling from mssql/server
Digest: sha256:0753f9e9c614c469e1e6b98ea60b21e20abd249323c9f6a9eab476c87a8cf826
Status: Image is up to date for mcr.microsoft.com/mssql/server:2019-latest
mcr.microsoft.com/mssql/server:2019-latest
##[command]/usr/bin/docker info -f "{{range .Plugins.Network}}{{println .}}{{end}}"
bridge
host
ipvlan
macvlan
null
overlay
##[command]/usr/bin/docker network create --label 726480 vsts_network_a2618a90ab7845979f9004ac9d509db8
7cbf016075bca81cfeb68a101a34d3e496106bee8a03b2ba2efe9744de64aaa0
##[debug]Default Working Directory /__w/1/s
##[debug]Working Directory /__w/1
##[debug]Mount Working Directory /home/vsts/work/1
##[command]/usr/bin/docker inspect --format="{{index .Config.Labels \"com.azure.dev.pipelines.agent.handler.node.path\"}}" mcr.microsoft.com/mssql/server:2019-latest
##[command]/usr/bin/docker create --name sqlserver_dev_mcrmicrosoftcommssqlserver2019latest_66fe51 --label 726480 --network vsts_network_a2618a90ab7845979f9004ac9d509db8 -p 1433:1433 --user 0:0 -e "SA_PASSWORD=P@ssw0rd" -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Developer" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/agents/2.162.0/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" mcr.microsoft.com/mssql/server:2019-latest "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff
##[command]/usr/bin/docker start c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff
c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff
##[command]/usr/bin/docker ps --all --filter id=c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff Up Less than a second
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff sh -c "command -v bash"
/bin/bash
##[command]whoami 
vsts
##[command]id -u vsts
1001
Try create an user with UID '1001' inside the container.
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff useradd -m -u 1001 vsts_azpcontainer
Grant user 'vsts_azpcontainer' SUDO privilege and allow it run any command without authentication.
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff groupadd azure_pipelines_sudo
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff usermod -a -G azure_pipelines_sudo vsts_azpcontainer
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff su -c "echo '%azure_pipelines_sudo ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers"
Allow user 'vsts_azpcontainer' run any docker command without SUDO.
##[command]stat -c %g /var/run/docker.sock
117
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff bash -c "cat /etc/group"
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff groupadd -g 117 azure_pipelines_docker
##[command]/usr/bin/docker exec  c3c59698249b1760bc82d358ca1f79070064b7afb5077e0fe07dbc66b8193aff usermod -a -G azure_pipelines_docker vsts_azpcontainer
##[debug]Default Working Directory /__w/1/s
##[debug]Working Directory /__w/1
##[debug]Mount Working Directory /home/vsts/work/1
##[command]/usr/bin/docker create --name sqlserver_dev_mcrmicrosoftcommssqlserver2019latest_0cd024 --label 726480 --network vsts_network_a2618a90ab7845979f9004ac9d509db8 --network-alias sqlserver -p 1433:1433 --user 0:0 -e "SA_PASSWORD=P@ssw0rd" -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Developer" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/agents/2.162.0/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" mcr.microsoft.com/mssql/server:2019-latest
9d77d8ba62821cc4c80e9f955f33fd4a25fc40015cad81ce8644bc50cfc41220
##[command]/usr/bin/docker start 9d77d8ba62821cc4c80e9f955f33fd4a25fc40015cad81ce8644bc50cfc41220
Error response from daemon: driver failed programming external connectivity on endpoint sqlserver_dev_mcrmicrosoftcommssqlserver2019latest_0cd024 (3be75e6d2f8024b84a21d7d4e8282010d310ce28c0b08d953033aca22f7650a7): Bind for 0.0.0.0:1433 failed: port is already allocated
Error: failed to start containers: 9d77d8ba62821cc4c80e9f955f33fd4a25fc40015cad81ce8644bc50cfc41220
##[error]Docker start fail with exit code 1
##[debug]System.InvalidOperationException: Docker start fail with exit code 1
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.StartContainerAsync(IExecutionContext executionContext, ContainerInfo container)
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Finishing: Initialize containers
```

**Comment by zielyn** [comment]
Seems this has been fixed in Agent version '2.163.1'
