### ISSUE TITLE
Build Agent fails after server reboot

### ISSUE THREAD

**Issue by dcparsons** [microsoft/azure-pipelines-agent#2789]
## Agent Version and Platform
Version of your agent? 2.153.1

OS of the machine running the agent? Windows Server 2012

## Azure DevOps Type and Version
Azure DevOps On-Prem | Dev17.M153.3

## What's not working?
I am configuring on-prem build agents using the following command:

`.\config.cmd --sslcacert ca-cert-bundle.pem --sslclientcert client-cert.pem --sslclientcertkey client-cert-key.pem --sslclientcertarchive devops-cert.pfx --sslclientcertpassword "password"`

I configure the build agents as follows:

- Server Url: URL
- Authentication: PAT
- Token: [token]
- Pool: Default
- Run As a Service: Y
- Service Account: [domain service account]
- Service Account Password: [password]

The setup completes correctly and the agent is registered with Azure DevOps. These agents worked as expected up until the Build Server was rebooted which caused all of my agents to appear as offline.  

Additional details:

- I always register the agent with a PAT associated to my DevOps account, I am the server admin.
- I have tried running the agent install as myself on the build server
- I have tried running the agent install as the service account that the agent runs as on the build server

## Agent and Worker's Diagnostic Logs
The logs for the agents are all very similar and all end looking like this:

[2020-02-12 19:15:13Z INFO HostContext] Well known directory 'Bin': 'D:\BuildAgent\DevOps_Agent1\bin'
[2020-02-12 19:15:13Z INFO HostContext] Well known directory 'Root': 'D:\BuildAgent\DevOps_Agent1'
[2020-02-12 19:15:13Z INFO HostContext] Well known config file 'Certificates': 'D:\BuildAgent\DevOps_Agent1\.certificates'
[2020-02-12 19:15:13Z INFO AgentCertificateManager] Load agent certificate setting from 'D:\BuildAgent\DevOps_Agent1\.certificates'
[2020-02-12 19:15:13Z INFO AgentCertificateManager] CA 'D:\BuildAgent\DevOps_Agent1\ca-cert-bundle.pem'
[2020-02-12 19:15:13Z INFO AgentCertificateManager] Client cert 'D:\BuildAgent\DevOps_Agent1\client-cert.pem'
[2020-02-12 19:15:13Z INFO AgentCertificateManager] Client cert private key 'D:\BuildAgent\DevOps_Agent1\client-cert-key.pem'
[2020-02-12 19:15:13Z INFO AgentCertificateManager] Client cert archive 'D:\BuildAgent\DevOps_Agent1\devops-cert.pfx'
[2020-02-12 19:15:13Z INFO HostContext] Well known directory 'Bin': 'D:\BuildAgent\DevOps_Agent1\bin'
[2020-02-12 19:15:13Z INFO HostContext] Well known directory 'Root': 'D:\BuildAgent\DevOps_Agent1'
[2020-02-12 19:15:13Z INFO HostContext] Well known config file 'CredentialStore': 'D:\BuildAgent\DevOps_Agent1\.credential_store'
**[2020-02-12 19:15:13Z ERR  Terminal]** WRITE ERROR: An error occurred: CredRead throw an error for 'VSTS_AGENT_CLIENT_CERT_PASSWORD_2DD3E6CA-1C40-4093-9201-387DCFD890EA'
**[2020-02-12 19:15:13Z ERR  AgentProcess]** System.ComponentModel.Win32Exception (1168): CredRead throw an error for 'VSTS_AGENT_CLIENT_CERT_PASSWORD_2DD3E6CA-1C40-4093-9201-387DCFD890EA'
   at Microsoft.VisualStudio.Services.Agent.WindowsAgentCredentialStore.Read(String target)
   at Microsoft.VisualStudio.Services.Agent.AgentCertificateManager.LoadCertificateSettings()
   at Microsoft.VisualStudio.Services.Agent.HostContext.CreateService[T]()
   at Microsoft.VisualStudio.Services.Agent.HostContext.GetService[T]()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)

I am guessing that the agent is saving the PFX password in Windows Credential Manager for some reason but it is unable to read the password back out but I am not sure why.

The closest issue I found to my problem was [1602](https://github.com/microsoft/azure-pipelines-agent/issues/1602) however that issue is around proxy username and passwords.

**Comment by dcparsons** [comment]
I have resolved this.  This was actually a problem with the service account that was being used to run the agent.  It seems that the service account was configured to use the TEMP profile so our infrastructure team modified the user to use a "real" profile.  The services now come back online once the server is restarted.
