### ISSUE TITLE
Agent Pools using Scale Set (VMSS) fail to properly configure the instances (permission)

### ISSUE THREAD

**Issue by jeanfrancoislarente** [microsoft/azure-pipelines-agent#2953]
​I've run into the same problem with both Linux and Windows scale sets.

I followed the ​instructions at https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops and the vmss instances spin up but then get torn down and new ones get spun up.

I RDPed into one of the windows instance and was able to pick up the logs which indicate a permission issue. After a while, a retry seems to be attempted (2nd log file) where the error coming back is "not configured"

First error - permission issue in agent log on Windows instance of scale set:

```Microsoft.TeamFoundation.ServiceIdentity;<ID>:AgentPoolAdmin:<ID> needs the following permission(s) on the resource / to perform this action: Read service definitions and/or access mappings.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.IsHostedServer(String serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2020-05-01 12:17:12Z ERR  Terminal] WRITE ERROR: Access Denied: Microsoft.TeamFoundation.ServiceIdentity;<ID>:AgentPoolAdmin:<ID> needs the following permission(s) on the resource / to perform this action: Read service definitions and/or access mappings.```

2nd error:

```[2020-05-01 12:29:40Z ERR  AgentProcess] System.InvalidOperationException: Not configured
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.LoadSettings()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)```

**Comment by mjroghelia** [comment]
Please open an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for support with the scale set backed pool feature.
