### ISSUE TITLE
failure to run/config/run self hosted agent. Capability name ' DEVMGR_SHOW_NONPRESENT_DEVICES' is not valid

### ISSUE THREAD

**Issue by milamber-ls** [microsoft/azure-pipelines-agent#3012]
## Agent Version and Platform
Version of your agent?
2.169.1 including multiple past versions

OS of the machine running the agent? 
Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) 

## What's not working?
self hosted agent is not executing and when upgraded to latest version configuration failed.

My installed agent stopped working with the an error. I deleted everything, created new folder, create new PAT and tried to install latest agent version and i get the same error

`Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Capability name ' DEVMGR_SHOW_NONPRESENT_DEVICES' is not valid. Capability names must be less than 256 characters in length and may not start or end with whitespace characters.`

In device manager>View menu  I have enabled the 'show hidden devices' flag. i have looked in the logs and I found the following issue
`INFO EnvironmentCapabilitiesProvider] Adding ' DEVMGR_SHOW_NONPRESENT_DEVICES': '1'`
Please note that there is a space in the ' DEVMGR_SHOW_NONPRESENT_DEVICES'

This is a subset of the logs

[2020-06-11 14:04:07Z INFO AgentCapabilitiesProvider] Adding 'Agent.HomeDirectory': 'C:\agent-windows'
[2020-06-11 14:04:07Z INFO Terminal] WRITE LINE: Connecting to the server.
[2020-06-11 14:04:07Z ERR  VisualStudioServices] POST request to  https://<deleted>/_apis/distributedtask/pools/1/agents failed. HTTP Status: BadRequest, AFD Ref: Ref A: <deleted> Ref B: <deleted> Ref C: 2020-06-11T14:04:06Z
[2020-06-11 14:04:07Z INFO CommandSettings] Flag 'unattended': 'False'
[2020-06-11 14:04:07Z ERR  Terminal] WRITE ERROR (exception):
[2020-06-11 14:04:07Z ERR  Terminal] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Capability name ' DEVMGR_SHOW_NONPRESENT_DEVICES' is not valid. Capability names must be less than 256 characters in length and may not start or end with whitespace characters.
Parameter name: agent.SystemCapabilities
 ---> System.ArgumentException: Capability name ' DEVMGR_SHOW_NONPRESENT_DEVICES' is not valid. Capability names must be less than 256 characters in length and may not start or end with whitespace characters.
Parameter name: agent.SystemCapabilities
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
[2020-06-11 14:04:07Z ERR  Terminal] WRITE ERROR: Failed to add the agent.  Try again or ctrl-c to quit
[2020-06-11 14:04:07Z INFO CommandSettings] Arg 'agent': ''
[2020-06-11 14:04:07Z INFO CommandSettings] Flag 'unattended': 'False'
[2020-06-11 14:04:07Z INFO PromptManager] ReadValue
[2020-06-11 14:04:07Z INFO Terminal] WRITE: Enter agent name (press enter for <deleted>) > 
[2020-06-11 14:04:07Z INFO Terminal] READ LINE
[2020-06-11 14:10:51Z INFO Terminal] Read value: 'notepad C:\agent-windows\_diag\Agent_20200611-131612-utc.log'
[2020-06-11 14:10:51Z INFO Terminal] WRITE LINE: Scanning for tool capabilities.
[2020-06-11 14:10:51Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Capabilities.ICapabilitiesProvider'
[2020-06-11 14:10:51Z INFO EnvironmentCapabilitiesProvider] Adding ' DEVMGR_SHOW_NONPRESENT_DEVICES': '1'
[2020-06-11 14:10:51Z INFO EnvironmentCapabilitiesProvider] Adding 'ADSK_CLM_WPAD_PROXY_CHECK': 'FALSE'
[2020-06-11 14:10:51Z INFO EnvironmentCapabilitiesProvider] Adding 'ALLUSERSPROFILE': 'C:\ProgramData'
[2020-06-11 14:10:51Z INFO EnvironmentCapabilitiesProvider] Adding 'ANDROID_NDK_PATH': 'C:\Program Files\Android\ndk\android-ndk-r11c'
[2020-06-11 14:10:51Z INFO EnvironmentCapabilitiesProvider] Adding 'ASPNETCORE_ENVIRONMENT': 'Development'

**Comment by milamber-ls** [comment]
there was a space in the registry entry. removing it fixed the problem

**Comment by quintindk** [comment]
I too experienced something similar.

`Capability name 'SuppressAzurePowerShellBreakingChangeWarnings ' is not valid. Capability names must be less than 256 characters in length and may not start or end with whitespace characters.`

The registry fix worked for me too 💯 Thanks 👍

**Comment by cnlawrence** [comment]
Same spacing issue.  Thank you all for the regedit recommendation.  It was an easy regedit > find ' NODE_OPTIONS' > delete in my case as it was no longer needed.  I couldn't edit the registry entry Name directly. 

I was looking for a Powershell env variable, which was not present.

**Comment by lampson** [comment]
I had a similar issue with NLS_LANG but was able to remove it as a environment variable.
