### ISSUE TITLE
unable to add EnvironmentVirtualMachineResourceTags during unattended config.cmd

### ISSUE THREAD

**Issue by brittandeyoung** [microsoft/azure-pipelines-agent#3020]
## Agent Version and Platform
v2.170.1 Windows x64 Server 2019

## Azure DevOps Type and Version
https://dev.azure.com/hagerty

## What's not working?
I am unable to provide EnvironmentVirtualMachineResourceTags to the config.cmd azure pipelines agent installer script using the unattended flag. I receive the following error stating that the input argument is invalid:

```
c:\azagent\A1>config.cmd --environment --environmentname DriveTrain_DEV --agent %computername% --addEnvironmentVirtualMachineResourceTags  --environmentVMResourceTags "DataPoller" --runasservice --work '_work' --url 'https://dev.azure.com/hagerty/' --projectname 'Hagerty' --auth PAT --token MYPAT
Error reported in diagnostic logs. Please examine the log for more details.
    - c:\azagent\A1\_diag\Agent_20200618-195223-utc.log
Unrecognized command-line input arguments: 'addEnvironmentVirtualMachineResourceTags, environmentVMResourceTags'. For usage refer to: .\config.cmd --help or ./config.sh --help
```

The agent will still register to the environment, but I am unable to add tags during the unattended install. I do not see this as an option in the confiig.cmd --help , but I also see no reference to a environment agent deployment in the help pages. The help pages only contain information about deployment groups. 

## Agent and Worker's Diagnostic Logs
```[2020-06-18 19:52:23Z INFO AgentProcess] Agent package win-x64.
[2020-06-18 19:52:23Z INFO AgentProcess] Running on Windows (X64).
[2020-06-18 19:52:23Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.17763.
[2020-06-18 19:52:23Z INFO AgentProcess] Version: 2.170.1
[2020-06-18 19:52:23Z INFO AgentProcess] Commit: bb272bb43aed9038cca1f8d32f5b8bb8dfe9c2ef
[2020-06-18 19:52:23Z INFO AgentProcess] Culture: en-US
[2020-06-18 19:52:23Z INFO AgentProcess] UI Culture: en-US
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO AgentProcess] Validating directory permissions for: 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO PowerShellExeUtil] Generation: '1'
[2020-06-18 19:52:23Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2020-06-18 19:52:23Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2020-06-18 19:52:23Z INFO PowerShellExeUtil] Generation: '3'
[2020-06-18 19:52:23Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.17763.1'
[2020-06-18 19:52:23Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2020-06-18 19:52:23Z INFO AgentProcess]  'CDF'
[2020-06-18 19:52:23Z INFO AgentProcess]  'v4'
[2020-06-18 19:52:23Z INFO AgentProcess]  'v4.0'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2020-06-18 19:52:23Z INFO AgentProcess]  'Client'
[2020-06-18 19:52:23Z INFO AgentProcess]  'Full'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.7.03190'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '461814'
[2020-06-18 19:52:23Z INFO AgentProcess] Type is System.Int32
[2020-06-18 19:52:23Z INFO AgentProcess] Interpreted version: 4.7.0
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.7.03190'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '461814'
[2020-06-18 19:52:23Z INFO AgentProcess] Type is System.Int32
[2020-06-18 19:52:23Z INFO AgentProcess] Interpreted version: 4.7.0
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2020-06-18 19:52:23Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2020-06-18 19:52:23Z INFO AgentProcess] Found 2 versions:
[2020-06-18 19:52:23Z INFO AgentProcess]  4.7.0
[2020-06-18 19:52:23Z INFO AgentProcess]  4.7.0
[2020-06-18 19:52:23Z INFO AgentProcess] Testing for min NET Framework version: '4.5'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO CommandSettings] Configure {
  "AcceptTeeEula": false,
  "AddDeploymentGroupTags": false,
  "AddEnvironmentVirtualMachineResourceTags": false,
  "AddMachineGroupTags": false,
  "Agent": "VDCDATAPOLLDV00",
  "CollectionName": null,
  "DeploymentGroup": false,
  "DeploymentGroupName": null,
  "DeploymentGroupTags": null,
  "DeploymentPool": false,
  "DeploymentPoolName": null,
  "EnvironmentVMResource": true,
  "EnvironmentName": "DriveTrain_DEV",
  "EnvironmentVMResourceTags": null,
  "GitUseSChannel": false,
  "MachineGroup": false,
  "MachineGroupName": null,
  "MachineGroupTags": null,
  "MonitorSocketAddress": null,
  "NotificationPipeName": null,
  "NotificationSocketAddress": null,
  "NoRestart": false,
  "OverwriteAutoLogon": false,
  "Pool": null,
  "ProjectName": "'Hagerty'",
  "ProxyPassword": null,
  "ProxyUserName": null,
  "ProxyUrl": null,
  "Replace": false,
  "RunAsAutoLogon": false,
  "RunAsService": true,
  "SslCACert": null,
  "SslClientCert": null,
  "SslClientCertArchive": null,
  "SslClientCertKey": null,
  "SslClientCertPassword": null,
  "SslSkipCertValidation": false,
  "Url": "'https://dev.azure.com/hagerty/'",
  "WindowsLogonAccount": null,
  "WindowsLogonPassword": null,
  "Work": "'_work'",
  "Auth": "PAT",
  "LaunchBrowser": false,
  "Password": null,
  "Token": "***",
  "Unattended": false,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2020-06-18 19:52:23Z INFO AgentProcess] Arguments parsed
[2020-06-18 19:52:23Z ERR  Terminal] WRITE ERROR: Unrecognized command-line input arguments: 'addEnvironmentVirtualMachineResourceTags, environmentVMResourceTags'. For usage refer to: .\config.cmd --help or ./config.sh --help
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'Proxy': 'c:\azagent\A1\.proxy'
[2020-06-18 19:52:23Z INFO VstsAgentWebProxy] No proxy setting found.
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'Certificates': 'c:\azagent\A1\.certificates'
[2020-06-18 19:52:23Z INFO AgentCertificateManager] No certificate setting found.
[2020-06-18 19:52:23Z INFO Agent] ExecuteCommand
[2020-06-18 19:52:23Z INFO ConfigurationStore] currentAssemblyLocation: c:\azagent\A1\bin\Agent.Listener.dll
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO ConfigurationStore] binPath: c:\azagent\A1\bin
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO ConfigurationStore] RootFolder: c:\azagent\A1
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'Agent': 'c:\azagent\A1\.agent'
[2020-06-18 19:52:23Z INFO ConfigurationStore] ConfigFilePath: c:\azagent\A1\.agent
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'Credentials': 'c:\azagent\A1\.credentials'
[2020-06-18 19:52:23Z INFO ConfigurationStore] CredFilePath: c:\azagent\A1\.credentials
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'Service': 'c:\azagent\A1\.service'
[2020-06-18 19:52:23Z INFO ConfigurationStore] ServiceConfigFilePath: c:\azagent\A1\.service
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'Autologon': 'c:\azagent\A1\.autologon'
[2020-06-18 19:52:23Z INFO ConfigurationStore] AutoLogonSettingsFilePath: c:\azagent\A1\.autologon
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'Options': 'c:\azagent\A1\.options'
[2020-06-18 19:52:23Z INFO ConfigurationStore] RuntimeOptionsFilePath: c:\azagent\A1\.options
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Bin': 'c:\azagent\A1\bin'
[2020-06-18 19:52:23Z INFO HostContext] Well known directory 'Root': 'c:\azagent\A1'
[2020-06-18 19:52:23Z INFO HostContext] Well known config file 'SetupInfo': 'c:\azagent\A1\.setup_info'
[2020-06-18 19:52:23Z INFO ConfigurationStore] SetupInfoFilePath: c:\azagent\A1\.setup_info
[2020-06-18 19:52:23Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.170.1             |_|          (commit bb272bb)

[2020-06-18 19:52:23Z INFO ConfigurationManager] ConfigureAsync
[2020-06-18 19:52:23Z INFO ConfigurationStore] IsConfigured()
[2020-06-18 19:52:23Z INFO ConfigurationStore] IsConfigured: True
[2020-06-18 19:52:23Z INFO ConfigurationManager] Is configured: True
[2020-06-18 19:52:23Z ERR  Agent] System.InvalidOperationException: Cannot configure the agent because it is already configured. To reconfigure the agent, run 'config.cmd remove' or './config.sh remove' first.
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2020-06-18 19:52:23Z ERR  Terminal] WRITE ERROR: Cannot configure the agent because it is already configured. To reconfigure the agent, run 'config.cmd remove' or './config.sh remove' first.
```

**Comment by lbergeron01** [comment]
@brittandeyoung I solved it by passing the following parameters :
`--addvirtualmachineresourcetags --virtualmachineresourcetags tags1,tags2`

But it's not documented, I add to search for AddEnvironmentVirtualMachineResourceTags and EnvironmentVMResourceTags to find out the mapping.

Then confirmed this by looking at the following issue, which is closed : https://github.com/microsoft/azure-pipelines-agent/issues/2973

**Comment by brittandeyoung** [comment]
Thanks @lbergeron01 ! Those undocumented flags did the trick. I also attempted to read the code to find the flags originally, but only found the references I tried. Should I close this issue? Or leave it open because the documentation is still missing?
