### ISSUE TITLE
Azure Build Agent 2.172.1 failed : _proc should be null

### ISSUE THREAD

**Issue by reservoir-dogs** [microsoft/azure-pipelines-agent#3047]
## Agent Version and Platform
Version of your agent? 2.172.1

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
The pipeline worked last wednesday with agent's version 2.171.1.
The pipeline has no changes and Friday, it was in failure with agent's version 2.172.1.

## Agent and Worker's Diagnostic Logs
Full logs :

> 2020-07-20T09:31:30.0104966Z ##[section]Starting: Agent job 1
2020-07-20T09:31:30.0149492Z ##[debug]Cleaning agent temp folder: /home/vsts/work/_temp
2020-07-20T09:31:30.0181361Z ##[debug]Skipping overwrite %TEMP% environment variable
2020-07-20T09:31:30.1789048Z ##[section]Starting: Initialize job
2020-07-20T09:31:30.1790406Z Agent name: 'Hosted Agent'
2020-07-20T09:31:30.1791154Z Agent machine name: 'fv-az725'
2020-07-20T09:31:30.1791378Z Current agent version: '2.172.1'
2020-07-20T09:31:30.1829228Z ##[group]Operating System
2020-07-20T09:31:30.1829476Z Ubuntu
2020-07-20T09:31:30.1829626Z 18.04.4
2020-07-20T09:31:30.1829769Z LTS
2020-07-20T09:31:30.1829938Z ##[endgroup]
2020-07-20T09:31:30.1830113Z ##[group]Virtual Environment
2020-07-20T09:31:30.1830330Z Environment: ubuntu-18.04
2020-07-20T09:31:30.1830518Z Version: 20200709.0
2020-07-20T09:31:30.1830820Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200709.0/images/linux/Ubuntu1804-README.md
2020-07-20T09:31:30.1831127Z ##[endgroup]
2020-07-20T09:31:30.1832206Z Current image version: '20200709.0'
2020-07-20T09:31:30.1837487Z Agent running as: 'vsts'
2020-07-20T09:31:30.1880472Z ##[debug]Triggering repository: IntraWM. repository type: Tfvc
2020-07-20T09:31:30.1885108Z Prepare build directory.
2020-07-20T09:31:30.2138268Z ##[debug]Creating build directory: '/home/vsts/work/8'
2020-07-20T09:31:30.2139991Z ##[debug]Delete existing artifacts directory: '/home/vsts/work/8/a'
2020-07-20T09:31:30.2142468Z ##[debug]Creating artifacts directory: '/home/vsts/work/8/a'
2020-07-20T09:31:30.2144249Z ##[debug]Delete existing test results directory: '/home/vsts/work/8/TestResults'
2020-07-20T09:31:30.2144968Z ##[debug]Creating test results directory: '/home/vsts/work/8/TestResults'
2020-07-20T09:31:30.2146994Z ##[debug]Creating binaries directory: '/home/vsts/work/8/b'
2020-07-20T09:31:30.2148758Z ##[debug]Creating source directory: '/home/vsts/work/8/s'
2020-07-20T09:31:30.2190326Z Set build variables.
2020-07-20T09:31:30.2221771Z Download all required tasks.
2020-07-20T09:31:30.2338295Z Downloading task: DotNetCoreCLI (2.172.1)
2020-07-20T09:31:31.9052729Z ##[debug]Task 'DotNetCoreCLI' has been downloaded into '/home/vsts/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.172.1'.
2020-07-20T09:31:32.2094107Z Downloading task: DockerInstaller (0.172.0)
2020-07-20T09:31:32.3475194Z ##[debug]Task 'DockerInstaller' has been downloaded into '/home/vsts/work/_tasks/DockerInstaller_8e038650-f7bf-11e8-8a6c-8fff434b4eff/0.172.0'.
2020-07-20T09:31:32.3483536Z Downloading task: Docker (0.157.2)
2020-07-20T09:31:32.5286162Z ##[debug]Task 'Docker' has been downloaded into '/home/vsts/work/_tasks/Docker_e28912f1-0114-4464-802a-a3a35437fd16/0.157.2'.
2020-07-20T09:31:32.5421595Z Downloading task: PublishBuildArtifacts (1.158.3)
2020-07-20T09:31:32.6219702Z ##[debug]Task 'PublishBuildArtifacts' has been downloaded into '/home/vsts/work/_tasks/PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe/1.158.3'.
2020-07-20T09:31:32.6247792Z ##[debug]Task 'dotnet build' has following condition: 'succeeded()'.
2020-07-20T09:31:32.6291242Z ##[debug]Parsing expression: <succeeded()>
2020-07-20T09:31:32.6327313Z ##[debug]succeeded
2020-07-20T09:31:32.6331146Z ##[debug](
2020-07-20T09:31:32.6333981Z ##[debug])
2020-07-20T09:31:32.6341838Z ##[debug]Task 'dotnet test' has following condition: 'succeeded()'.
2020-07-20T09:31:32.6342842Z ##[debug]Parsing expression: <succeeded()>
2020-07-20T09:31:32.6343153Z ##[debug]succeeded
2020-07-20T09:31:32.6343348Z ##[debug](
2020-07-20T09:31:32.6343802Z ##[debug])
2020-07-20T09:31:32.6344603Z ##[debug]Task 'dotnet publish' has following condition: 'succeeded()'.
2020-07-20T09:31:32.6345211Z ##[debug]Parsing expression: <succeeded()>
2020-07-20T09:31:32.6345501Z ##[debug]succeeded
2020-07-20T09:31:32.6345693Z ##[debug](
2020-07-20T09:31:32.6345908Z ##[debug])
2020-07-20T09:31:32.6346670Z ##[debug]Task 'Install Docker 17.09.0-ce' has following condition: 'succeeded()'.
2020-07-20T09:31:32.6347256Z ##[debug]Parsing expression: <succeeded()>
2020-07-20T09:31:32.6347688Z ##[debug]succeeded
2020-07-20T09:31:32.6347896Z ##[debug](
2020-07-20T09:31:32.6348097Z ##[debug])
2020-07-20T09:31:32.6348900Z ##[debug]Task 'Build an image' has following condition: 'succeeded()'.
2020-07-20T09:31:32.6349471Z ##[debug]Parsing expression: <succeeded()>
2020-07-20T09:31:32.6349756Z ##[debug]succeeded
2020-07-20T09:31:32.6349962Z ##[debug](
2020-07-20T09:31:32.6350159Z ##[debug])
2020-07-20T09:31:32.6350847Z ##[debug]Task 'Push an image' has following condition: 'succeeded()'.
2020-07-20T09:31:32.6351387Z ##[debug]Parsing expression: <succeeded()>
2020-07-20T09:31:32.6351671Z ##[debug]succeeded
2020-07-20T09:31:32.6351876Z ##[debug](
2020-07-20T09:31:32.6352071Z ##[debug])
2020-07-20T09:31:32.6353122Z ##[debug]Task 'Publish Artifact: drop' has following condition: 'succeeded()'.
2020-07-20T09:31:32.6353730Z ##[debug]Parsing expression: <succeeded()>
2020-07-20T09:31:32.6354000Z ##[debug]succeeded
2020-07-20T09:31:32.6354212Z ##[debug](
2020-07-20T09:31:32.6354566Z ##[debug])
2020-07-20T09:31:32.6355349Z Checking job knob settings.
2020-07-20T09:31:32.6363089Z    Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
2020-07-20T09:31:32.6364108Z    Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
2020-07-20T09:31:32.6364686Z Finished checking job knob settings.
2020-07-20T09:31:32.6705792Z ##[debug]Log plugin 'TestResultLogPlugin' is disabled.
2020-07-20T09:31:32.6706198Z ##[debug]Log plugin 'TestFilePublisherPlugin' is disabled.
2020-07-20T09:31:32.6706793Z Start tracking orphan processes.
2020-07-20T09:31:32.6896129Z ##[section]Finishing: Initialize job
2020-07-20T09:31:32.7090484Z ##[debug]Evaluating condition for step: 'Checkout IntraWM@ to s'
2020-07-20T09:31:32.7141163Z ##[debug]Evaluating: SucceededNode()
2020-07-20T09:31:32.7148353Z ##[debug]Evaluating SucceededNode:
2020-07-20T09:31:32.7195000Z ##[debug]=> True
2020-07-20T09:31:32.7205090Z ##[debug]Result: True
2020-07-20T09:31:32.7250319Z ##[section]Starting: Checkout IntraWM@ to s
2020-07-20T09:31:32.7443285Z ==============================================================================
2020-07-20T09:31:32.7443951Z Task         : Get sources
2020-07-20T09:31:32.7444587Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-07-20T09:31:32.7444893Z Version      : 1.0.0
2020-07-20T09:31:32.7445396Z Author       : Microsoft
2020-07-20T09:31:32.7446207Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2020-07-20T09:31:32.7446577Z ==============================================================================
2020-07-20T09:31:33.1350758Z ##[debug]Processed: ##vso[plugininternal.updaterepositorypath alias=__designer_repo;]/home/vsts/work/8/s
2020-07-20T09:31:33.1372302Z ##[debug]Repository requires to be placed at '/home/vsts/work/8/s', current location is '/home/vsts/work/8/s'
2020-07-20T09:31:33.1596791Z Prepending PATH environment variable with directory containing 'tf'.
2020-07-20T09:31:33.1609924Z ##[debug]Processed: ##vso[task.prependpath]/home/vsts/agents/2.172.1/externals/tee
2020-07-20T09:31:33.1611335Z ##[debug]PATH: '/home/vsts/agents/2.172.1/externals/tee:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
2020-07-20T09:31:33.1733483Z ##[command]tf eula -accept
2020-07-20T09:31:33.1801062Z ##[debug]Starting process:
2020-07-20T09:31:33.1801672Z ##[debug]  File name: 'tf'
2020-07-20T09:31:33.1802156Z ##[debug]  Arguments: 'eula -accept'
2020-07-20T09:31:33.1802636Z ##[debug]  Working directory: '/home/vsts/work/8/s'
2020-07-20T09:31:33.1803129Z ##[debug]  Require exit code zero: 'True'
2020-07-20T09:31:33.1803679Z ##[debug]  Encoding web name:  ; code page: ''
2020-07-20T09:31:33.1804188Z ##[debug]  Force kill process on cancellation: 'False'
2020-07-20T09:31:33.1804669Z ##[debug]  Redirected STDIN: 'False'
2020-07-20T09:31:33.1805528Z ##[debug]  Persist current code page: 'False'
2020-07-20T09:31:33.1806060Z ##[debug]  Keep redirected STDIN open: 'False'
2020-07-20T09:31:33.1806555Z ##[debug]  High priority process: 'False'
2020-07-20T09:31:33.2114110Z ##[debug]Updated oom_score_adj to 500 for PID: 2543.
2020-07-20T09:31:33.2117866Z ##[debug]Process started with process id 2543, waiting for process exit.
2020-07-20T09:31:39.4564337Z ##[debug]STDOUT/STDERR stream read finished.
2020-07-20T09:31:39.4566286Z ##[debug]STDOUT/STDERR stream read finished.
2020-07-20T09:31:39.4665346Z ##[debug]Exited process 2543 with exit code 0
2020-07-20T09:31:39.4677862Z ##[debug]Finished process 2543 with exit code 0, and elapsed time 00:00:06.2856169.
2020-07-20T09:31:39.4692764Z Querying workspace information.
2020-07-20T09:31:39.4825074Z ##[debug]tf workspaces -format:xml "-collection:https://dev.azure.com/xxx/" -jwt:*** -noprompt
2020-07-20T09:31:39.4826754Z ##[debug]Starting process:
2020-07-20T09:31:39.4828723Z ##[debug]  File name: 'tf'
2020-07-20T09:31:39.4832592Z ##[debug]  Arguments: 'workspaces -format:xml "-collection:https://dev.azure.com/xxx/" -jwt:*** -noprompt'
2020-07-20T09:31:39.4834249Z ##[debug]  Working directory: '/home/vsts/work/8/s'
2020-07-20T09:31:39.4836150Z ##[debug]  Require exit code zero: 'False'
2020-07-20T09:31:39.4837876Z ##[debug]  Encoding web name:  ; code page: ''
2020-07-20T09:31:39.4839200Z ##[debug]  Force kill process on cancellation: 'False'
2020-07-20T09:31:39.4840349Z ##[debug]  Redirected STDIN: 'False'
2020-07-20T09:31:39.4841416Z ##[debug]  Persist current code page: 'False'
2020-07-20T09:31:39.4842879Z ##[debug]  Keep redirected STDIN open: 'False'
2020-07-20T09:31:39.4844043Z ##[debug]  High priority process: 'False'
2020-07-20T09:31:39.4845131Z ##[debug]Updated oom_score_adj to 500 for PID: 2623.
2020-07-20T09:31:39.4845963Z ##[debug]Process started with process id 2623, waiting for process exit.
2020-07-20T09:31:42.6835683Z ##[debug]No workspace matching *;Project Collection Build Service (IntralogConsulting) on computer fv-az725 found in Team Foundation Server https://dev.azure.com/xxx/.
2020-07-20T09:31:42.7744411Z ##[debug]<?xml version="1.0" encoding="utf-8"?><workspaces/>
2020-07-20T09:31:45.3560255Z ##[debug]STDOUT/STDERR stream read finished.
2020-07-20T09:31:45.3563311Z ##[debug]STDOUT/STDERR stream read finished.
2020-07-20T09:31:45.3564155Z ##[debug]Exited process 2623 with exit code 0
2020-07-20T09:31:45.3564894Z ##[debug]Finished process 2623 with exit code 0, and elapsed time 00:00:05.8779449.
2020-07-20T09:31:45.4212582Z ##[debug]Processed: ##vso[task.setvariable variable=build.repository.tfvc.workspace;issecret=False;]ws_8_8
2020-07-20T09:31:45.4355771Z ##[debug]Sources directory does not exist or is empty.
2020-07-20T09:31:45.4396932Z ##[debug]tf workspaces ws_8_8 -computer:* -format:xml "-collection:https://dev.azure.com/xxx/" -jwt:*** -noprompt
2020-07-20T09:31:45.4397531Z ##[debug]Starting process:
2020-07-20T09:31:45.4398152Z ##[debug]  File name: 'tf'
2020-07-20T09:31:45.4400753Z ##[debug]  Arguments: 'workspaces ws_8_8 -computer:* -format:xml "-collection:https://dev.azure.com/xxx/" -jwt:*** -noprompt'
2020-07-20T09:31:45.4401506Z ##[debug]  Working directory: '/home/vsts/work/8/s'
2020-07-20T09:31:45.4402032Z ##[debug]  Require exit code zero: 'False'
2020-07-20T09:31:45.4402584Z ##[debug]  Encoding web name:  ; code page: ''
2020-07-20T09:31:45.4403113Z ##[debug]  Force kill process on cancellation: 'False'
2020-07-20T09:31:45.4403624Z ##[debug]  Redirected STDIN: 'False'
2020-07-20T09:31:45.4404123Z ##[debug]  Persist current code page: 'False'
2020-07-20T09:31:45.4404613Z ##[debug]  Keep redirected STDIN open: 'False'
2020-07-20T09:31:45.4405108Z ##[debug]  High priority process: 'False'
2020-07-20T09:31:45.4413906Z ##[debug]Updated oom_score_adj to 500 for PID: 2712.
2020-07-20T09:31:45.4414373Z ##[debug]Process started with process id 2712, waiting for process exit.
2020-07-20T09:31:47.0757482Z ##[debug]No workspace matching ws_8_8;Project Collection Build Service (IntralogConsulting) on computer * found in Team Foundation Server https://dev.azure.com/xxx/.
2020-07-20T09:31:49.2237016Z ##[debug]STDOUT/STDERR stream read finished.
2020-07-20T09:31:49.2241846Z ##[debug]STDOUT/STDERR stream read finished.
2020-07-20T09:31:49.2266038Z ##[debug]Exited process 2712 with exit code 1
2020-07-20T09:31:49.2267101Z ##[debug]Finished process 2712 with exit code 1, and elapsed time 00:00:03.7860582.
2020-07-20T09:31:49.2267840Z Sleeping for 200 ms
2020-07-20T09:31:49.4257783Z Retrying. Attempt $2/$3
2020-07-20T09:31:49.4319647Z ##[error]_proc should be null. (Parameter '_proc')
2020-07-20T09:31:49.4332820Z ##[debug]Processed: ##vso[task.logissue type=error;]_proc should be null. (Parameter '_proc')
2020-07-20T09:31:49.4345358Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2020-07-20T09:31:49.4424425Z ##[debug]   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtil.Null(Object value, String name)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.TfsVCCliManager.TryRunPorcelainCommandAsync(FormatFlags formatFlags, Int32 retriesOnFailure, String[] args)
   at Agent.Plugins.Repository.TeeCliManager.WorkspacesAsync(Boolean matchWorkspaceNameOnAnyComputer)
   at Agent.Plugins.Repository.TfsVCSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2020-07-20T09:31:49.4531485Z ##[section]Finishing: Checkout IntraWM@ to s
2020-07-20T09:31:49.4554929Z ##[debug]Evaluating condition for step: 'dotnet build'
2020-07-20T09:31:49.4556958Z ##[debug]Evaluating: succeeded()
2020-07-20T09:31:49.4557549Z ##[debug]Evaluating succeeded:
2020-07-20T09:31:49.4558914Z ##[debug]=> False
2020-07-20T09:31:49.4559572Z ##[debug]Result: False
2020-07-20T09:31:49.4574755Z ##[debug]Evaluating condition for step: 'dotnet test'
2020-07-20T09:31:49.4576642Z ##[debug]Evaluating: succeeded()
2020-07-20T09:31:49.4576983Z ##[debug]Evaluating succeeded:
2020-07-20T09:31:49.4577665Z ##[debug]=> False
2020-07-20T09:31:49.4578136Z ##[debug]Result: False
2020-07-20T09:31:49.4593588Z ##[debug]Evaluating condition for step: 'dotnet publish'
2020-07-20T09:31:49.4594654Z ##[debug]Evaluating: succeeded()
2020-07-20T09:31:49.4595001Z ##[debug]Evaluating succeeded:
2020-07-20T09:31:49.4595417Z ##[debug]=> False
2020-07-20T09:31:49.4595884Z ##[debug]Result: False
2020-07-20T09:31:49.4610218Z ##[debug]Evaluating condition for step: 'Install Docker 17.09.0-ce'
2020-07-20T09:31:49.4610960Z ##[debug]Evaluating: succeeded()
2020-07-20T09:31:49.4611314Z ##[debug]Evaluating succeeded:
2020-07-20T09:31:49.4611698Z ##[debug]=> False
2020-07-20T09:31:49.4612103Z ##[debug]Result: False
2020-07-20T09:31:49.4632152Z ##[debug]Evaluating condition for step: 'Build an image'
2020-07-20T09:31:49.4633074Z ##[debug]Evaluating: succeeded()
2020-07-20T09:31:49.4633433Z ##[debug]Evaluating succeeded:
2020-07-20T09:31:49.4633845Z ##[debug]=> False
2020-07-20T09:31:49.4634233Z ##[debug]Result: False
2020-07-20T09:31:49.4649171Z ##[debug]Evaluating condition for step: 'Push an image'
2020-07-20T09:31:49.4649902Z ##[debug]Evaluating: succeeded()
2020-07-20T09:31:49.4650255Z ##[debug]Evaluating succeeded:
2020-07-20T09:31:49.4650661Z ##[debug]=> False
2020-07-20T09:31:49.4651047Z ##[debug]Result: False
2020-07-20T09:31:49.4665485Z ##[debug]Evaluating condition for step: 'Publish Artifact: drop'
2020-07-20T09:31:49.4666400Z ##[debug]Evaluating: succeeded()
2020-07-20T09:31:49.4666778Z ##[debug]Evaluating succeeded:
2020-07-20T09:31:49.4667207Z ##[debug]=> False
2020-07-20T09:31:49.4667745Z ##[debug]Result: False
2020-07-20T09:31:49.4682209Z ##[debug]Evaluating condition for step: 'Checkout IntraWM@ to s'
2020-07-20T09:31:49.4683490Z ##[debug]Evaluating: AlwaysNode()
2020-07-20T09:31:49.4683863Z ##[debug]Evaluating AlwaysNode:
2020-07-20T09:31:49.4685110Z ##[debug]=> True
2020-07-20T09:31:49.4685701Z ##[debug]Result: True
2020-07-20T09:31:49.4686186Z ##[section]Starting: Checkout IntraWM@ to s
2020-07-20T09:31:49.4691960Z ==============================================================================
2020-07-20T09:31:49.4692286Z Task         : Get sources
2020-07-20T09:31:49.4692574Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-07-20T09:31:49.4692879Z Version      : 1.0.0
2020-07-20T09:31:49.4693066Z Author       : Microsoft
2020-07-20T09:31:49.4693355Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2020-07-20T09:31:49.4693734Z ==============================================================================
2020-07-20T09:31:49.8344844Z ##[section]Finishing: Checkout IntraWM@ to s
2020-07-20T09:31:49.8412491Z ##[section]Starting: Finalize Job
2020-07-20T09:31:49.8445308Z Cleaning up task key
2020-07-20T09:31:49.8446582Z Start cleaning up orphan processes.
2020-07-20T09:31:49.8744217Z ##[section]Finishing: Finalize Job
2020-07-20T09:31:49.8786404Z ##[section]Finishing: Agent job 1

**Comment by reservoir-dogs** [comment]
Indeed, we observed in the past this error at different stages of the Checkout and if we restarted, then it ended up working.

But since Friday, the retry is systematic on this stage of the Checkout.
So, we can no longer deliver.
Do you have any idea of the initial error? or how to have more information about it?

**Comment by mjroghelia** [comment]
@reservoir-dogs Based on the logs you posted the error on the first attempt is:

```
2020-07-20T09:31:47.0757482Z ##[debug]No workspace matching ws_8_8;Project Collection Build Service (IntralogConsulting) on computer * found in Team Foundation Server https://dev.azure.com/xxx/.
```

Could you please report this at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)? The error in the second attempt is an agent bug in the retry code, but the root issue (the error on the first attempt) is not necessarily in the agent. Opening a Developer Community issue will get a wider range of support staff looking into it and made it easier to route to the best people to help.

**Comment by RuslanRasulovAkv** [comment]
We are working on this bug (_proc should be null), thanks for reporting!

**Comment by reservoir-dogs** [comment]
For your information, the agent hosted with the same version works great!
The cause could be the permissions of the Azure agent (but we haven't made any changes in the past week) or the hosting system.
Finally, we decided to work around this issue by migrating to git source control and we did that this morning which was in our plans.

**Comment by mjroghelia** [comment]
@RuslanRasulovAkv The version of the agent with the retry logic reverted for now (2.172.2) has been fully rolled out, so I'm going to close this out.
