### ISSUE TITLE
./run.sh works ./svc.sh does not - curl/ssl cert error

### ISSUE THREAD

**Issue by nreith** [microsoft/azure-pipelines-agent#3099]
## What's not working?

- `./run.sh` for interactive works fine and goes green in dashboard for agent pools
- `sudo ./svc.sh start` does not work
- It give this error on status: Agent connect error: An error occurred while sending the request.. Retrying until reconnected.
- And stays red in dashboard

## Have you tried troubleshooting?

Yes. And read all the relevant messages here.

- I have tried `--sslcacert somecert.pem` grabbed from the dev.azure.com/org website in browser, both root and full (single file)
- I have also tried `--sslskipcertvalidation`

## Agent Version and Platform
Version of your agent? 2.174.1
Linux: Ubuntu 18.04

## Agent and Worker's Diagnostic Logs

```
[2020-09-03 19:17:42Z ERR  VisualStudioServices] GET request to https://dev.azure.com/MYORG/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request.                                                          
 ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)                                    
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)              
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)         
[2020-09-03 19:17:42Z INFO VisualStudioServices] Finished operation Location.GetConnectionData                                                             
[2020-09-03 19:17:42Z INFO VisualStudioServices] Starting operation Location.GetConnectionData                                                             
[2020-09-03 19:17:42Z ERR  VisualStudioServices] GET request to https://dev.azure.com/MYORG/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request.                                                          
 ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)                                    
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)              
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)         
[2020-09-03 19:17:42Z INFO VisualStudioServices] Finished operation Location.GetConnectionData                                                             
[2020-09-03 19:17:42Z ERR  MessageListener] Catch exception during create session.                                                                         
[2020-09-03 19:17:42Z ERR  MessageListener] System.Net.Http.HttpRequestException: An error occurred while sending the request.                             
 ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)                                    
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)         
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)     
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)                
   at Microsoft.VisualStudio.Services.Agent.AgentServer.ConnectAsync(Uri serverUrl, VssCredentials credentials)                                            
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.CreateSessionAsync(CancellationToken token)                                           
[2020-09-03 19:17:42Z INFO MessageListener] Retriable exception: An error occurred while sending the request.                                              
[2020-09-03 19:17:42Z INFO MessageListener] Sleeping for 30 seconds before retrying. 
```

**Comment by nreith** [comment]
Additional context. It appears to be working from another machine fully.
What specific settings (proxy, etc.) should I be looking for when figuring out how to configure the host, which might be causing this ssl issue?

**Comment by nreith** [comment]
Closing issue, as I found it worked with interactive (not --nonattended) config, and was able to find a typo in my one-liner for --nonnattended config. All good.
