### ISSUE TITLE
New agents cannot add themselves to Azure DevOps Server 2019 (on-premises)

### ISSUE THREAD

**Issue by echalone** [microsoft/azure-pipelines-agent#3102]
## Agent Version and Platform
This problem starts with Agent version 2.174.0 (2.174.1 is also affected), while agents up to v2.173.0 are not affected.
OS of the machine running the agent: I was able to reproduce the issue on Windows 10 Pro x64 and Linux x64 (Ubuntu 18.04).

## Azure DevOps Type and Version
On-Premises Azure DevOps Server 2019 Version 17.153.29522.3 (AzureDevOps2019.Update1.1).
This might actually be the issue, maybe the VSS-API is currently only compatible to the future 2020 server (I wasn't able to test that)?
Support of the 2019 server shouldn't be dropped that fast though, so I'm kinda assuming this is a bug, not a feature ;)

## What's not working?
When trying to add the agent to an agent pool, after entering the desired agent pool and then agent name, the VSS-API tries to add the agent to the pool but instead cancels with the following error message:
```
Scanning for tool capabilities.
Connecting to the server.
Error reported in diagnostic logs. Please examine the log for more details.
    - /home/myuser/BuildAgent/_diag/Agent_<date>-<time>-utc.log
%error="907004";%:01-FOUNDATION01.Tfs_Configuration.Task.prc_AddAgent: Database Update Failure - Error %error="515";% executing INSERT statement for Task.tbl_Agent
Failed to add the agent.  Try again or ctrl-c to quit
```

## Agent and Worker's Diagnostic Logs
```
[2020-09-08 11:29:38Z INFO Terminal] WRITE LINE: Connecting to the server.
[2020-09-08 11:29:38Z ERR  VisualStudioServices] POST request to https://<mytfs>/tfs/_apis/distributedtask/pools/20/agents failed. HTTP Status: InternalServerError
[2020-09-08 11:29:38Z INFO CommandSettings] Flag 'unattended': 'False'
[2020-09-08 11:29:38Z ERR  Terminal] WRITE ERROR (exception):
[2020-09-08 11:29:38Z ERR  Terminal] Microsoft.VisualStudio.Services.Common.VssServiceException: %error="907004";%:<Server>.Tfs_Configuration.Task.prc_AddAgent: Database Update Failure - Error %error="515";% executing INSERT statement for Task.tbl_Agent
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
[2020-09-08 11:29:38Z ERR  Terminal] WRITE ERROR: Failed to add the agent.  Try again or ctrl-c to quit.
```

## Issue location
I was able to locate the issue up to file \src\Agent.Listener\Configuration\ConfigurationProvider.cs line 106 where the external VSS-API library is called via
```
return _agentServer.AddAgentAsync(agentSettings.PoolId, agent);
```
So the issue actually seems to be in the VSS-API, for which I can't find any public source though. If you can redirect me to a more appropriate repository/site (for VSS-API) to report the issue I'm fine with that, but I wouldn't know where. Until then I thought I'll post it here.

**Comment by RedRiverWeb** [comment]
Hi!

The issue is the same with the .\config file. New agent cannot be added.

**Comment by silentmark** [comment]
Hi, 

i run into same issue, i believe that 515 error is NULL value for non-nullable column, and when i run SQL profiler and check the failing procedure here is what i found: 

`exec` Task.prc_AddAgent @partitionId=1,@poolId=21,@name=N'Agent-GITTFSPRDWB02-SPO-1',@version=N'2.174.1',@osDescription=N'Microsoft Windows 6.3.9600',**@provisioningState=NULL**,@accessPoint=NULL,@maxParallelism=1,@createEnabled=0,@writerId='70D069A3-24F4-4E4B-93DD-CF360DA9D1A8',@publicKey=0x.....,@systemCapabilities=@p12,@userCapabilities=default`

And **ProvisioningState** column cannot be null in Task.tbl_Agent 

The procedure itself doesnt seem to be altering this value in any way.

**Comment by mjroghelia** [comment]
@echalone @silentmark Thanks for detailed report. The [2.174.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.174.2) pre-release should address this.

**Comment by echalone** [comment]
> 
> 
> @echalone @silentmark Thanks for detailed report. The [2.174.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.174.2) pre-release should address this.

I can confirm this problem does not occur for me any more with Agent version 2.174.2
