### ISSUE TITLE
Windows Container - Initialize Job unable to download tasks to agent

### ISSUE THREAD

**Issue by alohaninja** [microsoft/azure-pipelines-agent#3118]
## Agent Version and Platform
Version of your agent? 2.117.2

OS of the machine running the agent? Win10 v2004 => WCOW
Docker on Windows (also tried ACI - same issue)
Docker Image: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? dev.azure.com/azurecom

## What's not working?
Following [this guide on building agent using docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)

Unable to initialize job - execution resulting in below error: 
![image](https://user-images.githubusercontent.com/26234626/94091509-3f479400-fdcd-11ea-9fc8-c7bca4d53151.png)

```
2020-09-21T18:51:30.9690113Z ##[section]Starting: Initialize job
2020-09-21T18:51:30.9691851Z Agent name: 'xxxxdockeragent'
2020-09-21T18:51:30.9692252Z Agent machine name: 'B7B087D61AA3'
2020-09-21T18:51:30.9692495Z Current agent version: '2.174.2'
2020-09-21T18:51:30.9716517Z Agent running as: 'ContainerAdministrator'
2020-09-21T18:51:30.9750925Z ##[debug]Triggering repository: xxxxx. repository type: GitHub
2020-09-21T18:51:30.9753521Z Prepare build directory.
2020-09-21T18:51:32.1853670Z ##[debug]Delete existing artifacts directory: 'C:\_remotework\1\a'
2020-09-21T18:51:32.3291818Z ##[debug]Deleting artifacts directory: 'C:\_remotework\1\a'
2020-09-21T18:51:33.0147914Z ##[debug]Creating artifacts directory: 'C:\_remotework\1\a'
2020-09-21T18:51:33.1660446Z ##[debug]Delete existing test results directory: 'C:\_remotework\1\TestResults'
2020-09-21T18:51:33.3101934Z ##[debug]Deleting test results directory: 'C:\_remotework\1\TestResults'
2020-09-21T18:51:33.8161694Z ##[debug]Creating test results directory: 'C:\_remotework\1\TestResults'
2020-09-21T18:51:34.2589630Z Set build variables.
2020-09-21T18:51:34.2623051Z Download all required tasks.
2020-09-21T18:51:34.4159070Z Downloading task: NuGetToolInstaller (0.174.0)
2020-09-21T18:53:34.7187345Z ##[warning]Failed to download task 'NuGetToolInstaller'. Error The read operation failed, see inner exception.
2020-09-21T18:53:34.7201036Z ##[warning]Inner Exception: {ex.InnerException.Message}
2020-09-21T18:53:34.7206683Z ##[warning]Back off 10.49 seconds before retry.
2020-09-21T18:56:02.7951006Z ##[warning]Failed to download task 'NuGetToolInstaller'. Error The read operation failed, see inner exception.
2020-09-21T18:56:02.7958223Z ##[warning]Inner Exception: {ex.InnerException.Message}
2020-09-21T18:56:02.7964913Z ##[warning]Back off 15.303 seconds before retry.
2020-09-21T18:58:15.3816200Z ##[error]The read operation failed, see inner exception.
2020-09-21T18:58:15.3825593Z ##[debug]System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Net.Http.WinHttpException (80072EFF, 12030): Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abnormally'.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, TaskStepDefinitionReference task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, IEnumerable`1 steps)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
2020-09-21T18:58:15.3832957Z ##[section]Finishing: Initialize job
```

### Agent Logs
```
[2020-09-24 01:20:43Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\azp\agent\.credentials_rsaparams
[2020-09-24 01:20:43Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\azp\agent\.credentials_rsaparams
[2020-09-24 01:20:43Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Date: Thu, 24 Sep 2020 01:20:42 GMT
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47, Basic realm="https://tfsprodscussu3.app.visualstudio
.com/", TFS-Federated
X-TFS-ProcessId: b48415ff-7a53-4fd0-9e98-64933cc58d80
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: defec6c5-ef6d-473c-b26a-8844c234a675
X-TFS-Session: 941c7423-88c5-4978-9385-7c41a3551254
X-VSS-E2EID: 69c3b2c0-c964-4eae-abba-b3a4eaaa0a42
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://tfsprodscussu3.app.visualstudio.com/
X-TFS-FedAuthIssuer: https://dev.azure.com/azurecom/
X-VSS-AuthorizationEndpoint: https://vssps.dev.azure.com/azurecom/
X-VSS-ResourceTenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://spsprodeus27.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2Fazurecom%2F_apis%2FconnectionData
%3FconnectOptions%3D1%26lastChangeId%3D-1%26lastChangeId64%3D-1&redirect=1&hid=f4973ace-8f75-492c-957a-d6acdbb943cd&context=eyJodCI6MiwiaGlkIjoiMDAyYzU4M2ItNTljMy00YWM
3LWE4MzUtNmNkNjhkYjg0ODAzIiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIs
Imh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
Request-Context: appId=cid-v1:a6caf15a-e80b-406b-9e7e-1abf42203185
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-MSEdge-Ref: Ref A: D34E93CE8C7D410DBD5E89F2EA645A1A Ref B: STBEDGE0215 Ref C: 2020-09-24T01:20:43Z

[2020-09-24 01:20:43Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2020-09-24 01:20:43Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2020-09-24 01:20:43Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2020-09-24 01:20:43Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2020-09-24 01:20:43Z INFO CommandSettings] Arg 'work': 'C:\_remotework'
[2020-09-24 01:20:43Z INFO CommandSettings] Flag 'disableloguploads': 'False'
[2020-09-24 01:20:43Z INFO ConfigurationStore] Saving agent settings.
[2020-09-24 01:20:43Z INFO ConfigurationStore] Settings Saved.
[2020-09-24 01:20:43Z INFO Terminal] WRITE LINE: 2020-09-24 01:20:43Z: Settings Saved.
[2020-09-24 01:20:43Z INFO CommandSettings] Flag 'gituseschannel': 'False'
[2020-09-24 01:20:43Z INFO CommandSettings] Flag 'runasservice': 'False'
[2020-09-24 01:20:43Z INFO CommandSettings] Flag 'unattended': 'True'
[2020-09-24 01:20:43Z INFO PromptManager] ReadValue
[2020-09-24 01:20:43Z INFO CommandSettings] Flag 'runasautologon': 'False'
[2020-09-24 01:20:43Z INFO CommandSettings] Flag 'unattended': 'True'
[2020-09-24 01:20:43Z INFO PromptManager] ReadValue
```
### Worker Logs
```
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Work': 'C:\_remotework'
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Tasks': 'C:\_remotework\_tasks'
[2020-09-24 01:22:07Z INFO TaskManager] Ensuring task exists: ID '2c65196a-54fd-4a02-9be8-d9d1837b7c5d', version '0.174.0', name 'NuGetToolInstaller', directory 'C:\_remotework\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\0.174.0'.
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Bin': 'C:\azp\agent\bin'
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Root': 'C:\azp\agent'
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Work': 'C:\_remotework'
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'TaskZips': 'C:\_remotework\_taskzips'
[2020-09-24 01:22:07Z INFO JobServerQueue] Try to append 1 batches web console lines for record '036ccd98-84d2-4318-b0d1-7f7c7a85faff', success rate: 1/1.
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Bin': 'C:\azp\agent\bin'
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Root': 'C:\azp\agent'
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Work': 'C:\_remotework'
[2020-09-24 01:22:07Z INFO HostContext] Well known directory 'Tasks': 'C:\_remotework\_tasks'
[2020-09-24 01:22:07Z INFO JobServerQueue] Try to append 1 batches web console lines for record '036ccd98-84d2-4318-b0d1-7f7c7a85faff', success rate: 1/1.
[2020-09-24 01:23:08Z INFO JobServerQueue] Stop aggressive process web console line queue.
[2020-09-24 01:23:57Z ERR  TaskManager] Fail to download task '2c65196a-54fd-4a02-9be8-d9d1837b7c5d (NuGetToolInstaller/0.174.0)' -- Attempt: 1
[2020-09-24 01:23:57Z ERR  TaskManager] System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Net.Http.WinHttpException (80072EFF, 12030): Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abn
ormally'.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, TaskStepDefinitionReference task)
[2020-09-24 01:23:57Z INFO JobServerQueue] Try to append 1 batches web console lines for record '036ccd98-84d2-4318-b0d1-7f7c7a85faff', success rate: 1/1.
[2020-09-24 01:25:53Z ERR  TaskManager] Fail to download task '2c65196a-54fd-4a02-9be8-d9d1837b7c5d (NuGetToolInstaller/0.174.0)' -- Attempt: 2
[2020-09-24 01:25:53Z ERR  TaskManager] System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Net.Http.WinHttpException (80072EFF, 12030): Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abn
ormally'.
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, TaskStepDefinitionReference task)
[2020-09-24 01:25:53Z INFO JobServerQueue] Try to append 1 batches web console lines for record '036ccd98-84d2-4318-b0d1-7f7c7a85faff', success rate: 1/1.
[2020-09-24 01:27:50Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Net.Http.WinHttpException (80072EFF, 12030): Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abn
ormally'.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, TaskStepDefinitionReference task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, IEnumerable`1 steps)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2020-09-24 01:27:50Z ERR  JobRunner] Caught exception from InitializeJob: System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Net.Http.WinHttpException (80072EFF, 12030): Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abn
ormally'.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, TaskStepDefinitionReference task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, IEnumerable`1 steps)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
[2020-09-24 01:27:50Z INFO JobRunner] Shutting down the job server queue.
[2020-09-24 01:27:50Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2020-09-24 01:27:50Z INFO JobServerQueue] All queue process task stopped.
[2020-09-24 01:27:50Z INFO JobServerQueue] Try to append 1 batches web console lines for record '036ccd98-84d2-4318-b0d1-7f7c7a85faff', success rate: 1/1.
[2020-09-24 01:27:50Z INFO JobServerQueue] Try to append 1 batches web console lines for record '6a2fd058-6ae6-58df-2155-4f6b2eb5bf45', success rate: 1/1.
[2020-09-24 01:27:50Z INFO JobServerQueue] Web console line queue drained.
[2020-09-24 01:27:50Z INFO JobServerQueue] Uploading 2 files in one shot.
[2020-09-24 01:27:50Z INFO JobServerQueue] Try to upload 2 log files or attachments, success rate: 2/2.
[2020-09-24 01:27:50Z INFO JobServerQueue] File upload queue drained.
[2020-09-24 01:27:51Z INFO JobServerQueue] Timeline update queue drained.
[2020-09-24 01:27:51Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2020-09-24 01:27:51Z INFO TempDirectoryManager] Cleaning agent temp folder: C:\_remotework\_temp
[2020-09-24 01:27:51Z INFO JobRunner] Raising job completed event.
[2020-09-24 01:27:51Z INFO Worker] Job completed.
```

**Comment by anatolybolshakov** [comment]
Hi @alohaninja is this issue still actual for you? Does it happen intermittently or constantly? Have you tried it with the latest agent?

**Comment by anatolybolshakov** [comment]
Hi @alohaninja do you have any updates?

**Comment by anatolybolshakov** [comment]
Hi @alohaninja I'm closing this at the moment due to inactivity - please let us know if it's still actual for you.

**Comment by cawoodm** [comment]
We just had this problem - agent downloading artifact incorrectly and solved it by updating the agent to the latest version `2.188.3`.
