### ISSUE TITLE
Unattended authentication of Linux agent fails with Basic issued token provider instance requires an interactive prompt which is not allowed by the current settings

### ISSUE THREAD

**Issue by vsevolodp** [microsoft/azure-pipelines-agent#3135]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting) - Yes, topic is not covered there

## Agent Version and Platform
Version of your agent? 2.175.2

OS of the machine running the agent? Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server? https://dev.azure.com/msasg

## What's not working?
I recently created new PAT token with the scope 'Agent Pools (read, manage)' for unattended automatic connection of hosted agents to the pool where I'm an Administrator/Owner of the pool.

Since then I'm seeing error below when running
```./config.sh --unattended --acceptTeeEula --url "https://dev.azure.com/$project_name" --auth pat --pool "$pool_name" --replace
```
from automated script.
Same PAT works fine if I run config.sh from interactive console.

```
>> Connect:

Error reported in diagnostic logs. Please examine the log for more details.
```
I've tried to create new PATs but it didn't resolved the issue.

## Agent and Worker's Diagnostic Logs

Referred log file contains:
```
[2020-10-09 20:51:15Z INFO PersonalAccessToken] GetVssCredentials
[2020-10-09 20:51:15Z INFO PersonalAccessToken] token retrieved: 80 chars
[2020-10-09 20:51:15Z INFO PersonalAccessToken] cred created
[2020-10-09 20:51:15Z INFO ConfigurationManager] cred retrieved
[2020-10-09 20:51:15Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2020-10-09 20:51:15Z WARN VisualStudioServices] Authentication failed with status code 401.
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Basic realm="https://tfsprodwus22.app.visualstudio.com/"
X-TFS-ProcessId: 6ff81e02-6efc-4191-930a-29a419b4f982
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: f168829a-6215-45e3-a9f1-3e22c096b82b
X-TFS-Session: 1b369f89-5bb3-44ce-b973-9cbcd7ee884a
X-VSS-E2EID: 40ed4a4f-1541-4612-b2f8-c91c9e1393f2
Request-Context: appId=cid-v1:4cf0000f-a530-4b17-b1fd-46511d3e2339
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-MSEdge-Ref: Ref A: B9DD9D8923B341F0B98940E719A4F9CC Ref B: CO1EDGE0622 Ref C: 2020-10-09T20:51:15Z
Date: Fri, 09 Oct 2020 20:51:15 GMT

[2020-10-09 20:51:15Z WARN VisualStudioServices] Basic issued token provider instance 38092103 requires an interactive prompt which is not allowed by the current settings
[2020-10-09 20:51:15Z ERR  VisualStudioServices] GET request to https://dev.azure.com/msasg/_apis/connectionData?connectOptions=1&lastChangeId=256974929&lastChangeId64=256974929 is not authorized. Details: VS30063: You are not authorized to access https://dev.azure.com.
[2020-10-09 20:51:15Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2020-10-09 20:51:15Z INFO LocationServer] Unable to connect to https://dev.azure.com/msasg.
[2020-10-09 20:51:15Z ERR  LocationServer] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://dev.azure.com.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
[2020-10-09 20:51:15Z INFO CommandSettings] Flag 'unattended': 'True'
[2020-10-09 20:51:15Z ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://dev.azure.com.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.IsHostedServer(String serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2020-10-09 20:51:15Z ERR  Terminal] WRITE ERROR: VS30063: You are not authorized to access https://dev.azure.com.
```

**Comment by vsevolodp** [comment]
Duplicate of #3136
