### ISSUE TITLE
Unable to auth self-hosted agent with PAT. "Basic authentication requires a secure connection to the server."

### ISSUE THREAD

**Issue by Stahhl** [microsoft/azure-pipelines-agent#3167]
**Whats wrong**
Unable to auth self-hosted agent with PAT both attended and unattended.

My original problem is running a [self-contained dockeragent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops). However im also getting the same result running [self-hosted windows agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops). And i honestly dont know how to read logs inside a not running container. So i'll be using windows in my issue.

**Agent version**
- vsts-agent-win/linux-x64-2.153.1

**Tried running agent on**
- Docker (host: RHEL7 30, container: ubuntu 18.04)
- Windows 10

**Trying to connect to**
- On-prem azure devops server `http://server:8080/tfs/project`

This is the result of running the config.cmd from an elevated powershell.

<pre><code>
PS C:\Utveckling\devopsagentwindows> ./config.cmd    
Enter server URL > http://server:8080/tfs/project
Enter authentication type (press enter for Integrated) > pat
Enter personal access token > ****************************************************
Basic authentication requires a secure connection to the server.
Failed to connect.  Try again or ctrl-c to quit
Enter server URL >
</code></pre>

Stacktrace of the exception from ./_diag/

<pre><code>
[2020-11-13 15:00:08Z ERR  Terminal] System.InvalidOperationException: Basic authentication requires a secure connection to the server.
   at Microsoft.VisualStudio.Services.Common.VssBasicCredential.OnCreateTokenProvider(Uri serverUrl, IHttpResponse response)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenCredential.CreateTokenProvider(Uri serverUrl, IHttpResponse response, IssuedToken failedToken)
   at Microsoft.VisualStudio.Services.Common.VssCredentials.TryGetTokenProvider(Uri serverUrl, IssuedTokenProvider& provider)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.IsHostedServer(String serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
</code></pre>

**Comment by Stahhl** [comment]
I have been able to connect the attended windows agent using the "integrated" authentication method. So i know its at least possible to connect the agent with the server.

**Comment by Stahhl** [comment]
These are the settings i use when generating the token.

![bild](https://user-images.githubusercontent.com/51987854/99678617-4dd3c400-2a7b-11eb-9b18-e1b3539a8728.png)

**Comment by mjroghelia** [comment]
@Stahhl This error is telling you that you cannot use a PAT with http. You must use https.

**Comment by george-lloyd-nbs** [comment]
Hi,
Is there a way to bypass this control?
Thanks
