### ISSUE TITLE
Cannot connect mac to TFS without SSL: requires an interactive prompt

### ISSUE THREAD

**Issue by bvbellomo** [microsoft/azure-pipelines-agent#3271]
I am trying to ./config.sh a v2.181.2 of the build agent from a Macbook running Big Sur to our TFS server that does not support SSL and is running 15.117.27024.0.

Logs shows:
Authentication failed with status code 401.
Windows issued token provider instance 48006333 requires an interactive prompt which is not allowed by the current settings

[2021-02-17 14:38:34Z INFO AgentProcess] Agent package osx-x64.
[2021-02-17 14:38:36Z INFO AgentProcess] Running on OSX (X64).
[2021-02-17 14:38:36Z INFO AgentProcess] RuntimeInformation: Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64.
[2021-02-17 14:38:41Z INFO AgentProcess] Version: 2.181.2
[2021-02-17 14:38:41Z INFO AgentProcess] Commit: a673867fba6c7b4845163b51dfb243701806a15e
[2021-02-17 14:38:41Z INFO AgentProcess] Culture: en-US
[2021-02-17 14:38:41Z INFO AgentProcess] UI Culture: en-US
[2021-02-17 14:38:41Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:38:41Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:38:41Z INFO AgentProcess] Validating directory permissions for: '/Users/app_dev/myagent'
[2021-02-17 14:38:41Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:38:41Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:25Z INFO CommandSettings] Configure {
  "AcceptTeeEula": false,
  "AddDeploymentGroupTags": false,
  "AddEnvironmentVirtualMachineResourceTags": false,
  "AddMachineGroupTags": false,
  "AlwaysExtractTask": false,
  "Agent": null,
  "CollectionName": null,
  "DeploymentGroup": false,
  "DeploymentGroupName": null,
  "DeploymentGroupTags": null,
  "DeploymentPool": false,
  "DeploymentPoolName": null,
  "EnvironmentVMResource": false,
  "EnvironmentName": null,
  "EnvironmentVMResourceTags": null,
  "GitUseSChannel": false,
  "DisableLogUploads": false,
  "MachineGroup": false,
  "MachineGroupName": null,
  "MachineGroupTags": null,
  "MonitorSocketAddress": null,
  "NotificationPipeName": null,
  "NotificationSocketAddress": null,
  "NoRestart": false,
  "OverwriteAutoLogon": false,
  "Pool": null,
  "ProjectName": null,
  "ProxyPassword": null,
  "ProxyUserName": null,
  "ProxyUrl": null,
  "Replace": false,
  "RunAsAutoLogon": false,
  "RunAsService": false,
  "RunOnce": false,
  "SslCACert": null,
  "SslClientCert": null,
  "SslClientCertArchive": null,
  "SslClientCertKey": null,
  "SslClientCertPassword": null,
  "SslSkipCertValidation": false,
  "Url": null,
  "WindowsLogonAccount": null,
  "WindowsLogonPassword": null,
  "Work": null,
  "Auth": null,
  "LaunchBrowser": false,
  "Password": null,
  "Token": null,
  "Unattended": false,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2021-02-17 14:39:25Z INFO AgentProcess] Arguments parsed
[2021-02-17 14:39:28Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:28Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:28Z INFO HostContext] Well known config file 'Proxy': '/Users/app_dev/myagent/.proxy'
[2021-02-17 14:39:28Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-02-17 14:39:31Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:31Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:31Z INFO HostContext] Well known config file 'Certificates': '/Users/app_dev/myagent/.certificates'
[2021-02-17 14:39:31Z INFO AgentCertificateManager] No certificate setting found.
[2021-02-17 14:39:34Z INFO Agent] ExecuteCommand
[2021-02-17 14:39:34Z INFO ConfigurationStore] currentAssemblyLocation: /Users/app_dev/myagent/bin/Agent.Listener.dll
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO ConfigurationStore] binPath: /Users/app_dev/myagent/bin
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:34Z INFO ConfigurationStore] RootFolder: /Users/app_dev/myagent
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:34Z INFO HostContext] Well known config file 'Agent': '/Users/app_dev/myagent/.agent'
[2021-02-17 14:39:34Z INFO ConfigurationStore] ConfigFilePath: /Users/app_dev/myagent/.agent
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:34Z INFO HostContext] Well known config file 'Credentials': '/Users/app_dev/myagent/.credentials'
[2021-02-17 14:39:34Z INFO ConfigurationStore] CredFilePath: /Users/app_dev/myagent/.credentials
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:34Z INFO HostContext] Well known config file 'Service': '/Users/app_dev/myagent/.service'
[2021-02-17 14:39:34Z INFO ConfigurationStore] ServiceConfigFilePath: /Users/app_dev/myagent/.service
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:34Z INFO HostContext] Well known config file 'Autologon': '/Users/app_dev/myagent/.autologon'
[2021-02-17 14:39:34Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /Users/app_dev/myagent/.autologon
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:34Z INFO HostContext] Well known config file 'Options': '/Users/app_dev/myagent/.options'
[2021-02-17 14:39:34Z INFO ConfigurationStore] RuntimeOptionsFilePath: /Users/app_dev/myagent/.options
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:39:34Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:39:34Z INFO HostContext] Well known config file 'SetupInfo': '/Users/app_dev/myagent/.setup_info'
[2021-02-17 14:39:34Z INFO ConfigurationStore] SetupInfoFilePath: /Users/app_dev/myagent/.setup_info
[2021-02-17 14:39:34Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.181.2             |_|          (commit a673867)

[2021-02-17 14:39:46Z INFO ConfigurationManager] ConfigureAsync
[2021-02-17 14:39:46Z INFO ConfigurationStore] IsConfigured()
[2021-02-17 14:39:46Z INFO ConfigurationStore] IsConfigured: False
[2021-02-17 14:39:46Z INFO ConfigurationManager] Is configured: False
[2021-02-17 14:39:46Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2021-02-17 14:40:12Z INFO Terminal] WRITE LINE: 
[2021-02-17 14:40:12Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2021-02-17 14:40:12Z INFO Terminal] WRITE LINE: 
[2021-02-17 14:40:12Z INFO HostContext] Well known directory 'Bin': '/Users/app_dev/myagent/bin'
[2021-02-17 14:40:12Z INFO HostContext] Well known directory 'Root': '/Users/app_dev/myagent'
[2021-02-17 14:40:12Z INFO HostContext] Well known directory 'Externals': '/Users/app_dev/myagent/externals'
[2021-02-17 14:40:12Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /Users/app_dev/myagent/externals/tee/license.html
[2021-02-17 14:40:12Z INFO Terminal] WRITE LINE: 
[2021-02-17 14:40:12Z INFO CommandSettings] Flag 'acceptteeeula': 'False'
[2021-02-17 14:40:12Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-17 14:40:12Z INFO PromptManager] ReadValue
[2021-02-17 14:40:12Z INFO Terminal] WRITE: Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > 
[2021-02-17 14:40:12Z INFO Terminal] READ LINE
[2021-02-17 14:40:18Z INFO Terminal] Read value: 'Y'
[2021-02-17 14:40:18Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2021-02-17 14:40:18Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2021-02-17 14:40:18Z INFO CommandSettings] Flag 'environment': 'False'
[2021-02-17 14:40:18Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2021-02-17 14:40:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2021-02-17 14:40:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2021-02-17 14:40:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2021-02-17 14:40:18Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2021-02-17 14:40:18Z INFO Terminal] WRITE LINE: 
[2021-02-17 14:40:18Z INFO Terminal] WRITE LINE: >> Connect:
[2021-02-17 14:40:18Z INFO Terminal] WRITE LINE: 
[2021-02-17 14:40:18Z INFO CommandSettings] Arg 'url': ''
[2021-02-17 14:40:18Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-17 14:40:18Z INFO PromptManager] ReadValue
[2021-02-17 14:40:18Z INFO Terminal] WRITE: Enter server URL > 
[2021-02-17 14:40:18Z INFO Terminal] READ LINE
[2021-02-17 14:41:00Z INFO Terminal] Read value: 'http://10.0.0.26:8080/tfs/'
[2021-02-17 14:41:00Z INFO ConfigurationManager] GetCredentialProvider
[2021-02-17 14:41:00Z INFO CommandSettings] Arg 'auth': ''
[2021-02-17 14:41:00Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-17 14:41:00Z INFO PromptManager] ReadValue
[2021-02-17 14:41:00Z INFO Terminal] WRITE: Enter authentication type (press enter for Negotiate) > 
[2021-02-17 14:41:00Z INFO Terminal] READ LINE
[2021-02-17 14:41:05Z INFO Terminal] Read value: ''
[2021-02-17 14:41:05Z INFO PromptManager] Falling back to the default: 'Negotiate'
[2021-02-17 14:41:05Z INFO ConfigurationManager] Creating credential for auth: Negotiate
[2021-02-17 14:41:05Z INFO CredentialManager] GetCredentialProvider
[2021-02-17 14:41:05Z INFO CredentialManager] Creating type Negotiate
[2021-02-17 14:41:05Z INFO CredentialManager] Creating credential type: Negotiate
[2021-02-17 14:41:05Z INFO PersonalAccessToken] EnsureCredential
[2021-02-17 14:41:05Z INFO CommandSettings] Arg 'username': ''
[2021-02-17 14:41:05Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-17 14:41:05Z INFO PromptManager] ReadValue
[2021-02-17 14:41:05Z INFO Terminal] WRITE: Enter user name > 
[2021-02-17 14:41:05Z INFO Terminal] READ LINE
[2021-02-17 14:41:13Z INFO Terminal] Read value: 'brvibe1'
[2021-02-17 14:41:13Z INFO CommandSettings] Arg 'password': ''
[2021-02-17 14:41:13Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-17 14:41:13Z INFO PromptManager] ReadValue
[2021-02-17 14:41:13Z INFO Terminal] WRITE: Enter password > 
[2021-02-17 14:41:13Z INFO Terminal] READ SECRET
[2021-02-17 14:41:19Z INFO Terminal] Read value: '***'
[2021-02-17 14:41:19Z INFO NegotiateCredential] GetVssCredentials
[2021-02-17 14:41:19Z INFO NegotiateCredential] User name retrieved.
[2021-02-17 14:41:19Z INFO NegotiateCredential] Password retrieved.
[2021-02-17 14:41:19Z INFO NegotiateCredential] URL retrieved: http://10.0.0.26:8080/tfs/
[2021-02-17 14:41:19Z INFO ConfigurationManager] cred retrieved
[2021-02-17 14:41:33Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-02-17 14:41:47Z WARN VisualStudioServices] Authentication failed with status code 401.
Server: Microsoft-IIS/8.5
X-TFS-ProcessId: e43743f8-6e78-487b-8e29-7258b4672a33
ActivityId: d3639174-9ca0-43fb-8429-4ea8679128ab
X-TFS-Session: 69213993-e5cc-4fbc-8d8e-4a41af500d02
X-VSS-E2EID: 63df9e18-fa54-4d68-8855-961e9798220c
X-Frame-Options: SAMEORIGIN
X-TFS-SoapException: %3c%3fxml+version%3d%221.0%22+encoding%3d%22utf-8%22%3f%3e%3csoap%3aEnvelope+xmlns%3asoap%3d%22http%3a%2f%2fwww.w3.org%2f2003%2f05%2fsoap-envelope%22%3e%3csoap%3aBody%3e%3csoap%3aFault%3e%3csoap%3aCode%3e%3csoap%3aValue%3esoap%3aReceiver%3c%2fsoap%3aValue%3e%3csoap%3aSubcode%3e%3csoap%3aValue%3eUnauthorizedRequestException%3c%2fsoap%3aValue%3e%3c%2fsoap%3aSubcode%3e%3c%2fsoap%3aCode%3e%3csoap%3aReason%3e%3csoap%3aText+xml%3alang%3d%22en%22%3eTF400813%3a+Resource+not+available+for+anonymous+access.+Client+authentication+required.%3c%2fsoap%3aText%3e%3c%2fsoap%3aReason%3e%3c%2fsoap%3aFault%3e%3c%2fsoap%3aBody%3e%3c%2fsoap%3aEnvelope%3e
X-TFS-ServiceError: TF400813%3a+Resource+not+available+for+anonymous+access.+Client+authentication+required.
WWW-Authenticate: Bearer, Basic realm="http://10.0.0.26:8080/tfs", Negotiate, NTLM
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Wed, 17 Feb 2021 14:41:47 GMT

[2021-02-17 14:41:50Z WARN VisualStudioServices] Authentication failed with status code 401.
Server: Microsoft-IIS/8.5
X-TFS-ProcessId: e43743f8-6e78-487b-8e29-7258b4672a33
ActivityId: d363913c-9ca0-43fb-8429-4ea8679128ab
X-TFS-Session: 69213993-e5cc-4fbc-8d8e-4a41af500d02
X-VSS-E2EID: 63df9e18-fa54-4d68-8855-961e9798220c
X-Frame-Options: SAMEORIGIN
WWW-Authenticate: Bearer, Basic realm="http://10.0.0.26:8080/tfs", Negotiate, NTLM
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Wed, 17 Feb 2021 14:41:51 GMT

[2021-02-17 14:41:50Z WARN VisualStudioServices] Windows issued token provider instance 48006333 requires an interactive prompt which is not allowed by the current settings
[2021-02-17 14:41:50Z ERR  VisualStudioServices] GET request to http://10.0.0.26:8080/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 is not authorized. Details: VS30063: You are not authorized to access http://10.0.0.26:8080.
[2021-02-17 14:41:50Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-02-17 14:41:50Z INFO LocationServer] Unable to connect to http://10.0.0.26:8080/tfs/.
[2021-02-17 14:41:50Z ERR  LocationServer] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://10.0.0.26:8080.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
[2021-02-17 14:41:50Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-17 14:41:50Z ERR  Terminal] WRITE ERROR (exception):
[2021-02-17 14:41:50Z ERR  Terminal] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://10.0.0.26:8080.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.IsHostedServer(String serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
[2021-02-17 14:41:50Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2021-02-17 14:41:50Z INFO CommandSettings] Arg 'url': ''
[2021-02-17 14:41:50Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-17 14:41:50Z INFO PromptManager] ReadValue
[2021-02-17 14:41:50Z INFO Terminal] WRITE: Enter server URL > 
[2021-02-17 14:41:50Z INFO Terminal] READ LINE
[2021-02-17 14:42:05Z INFO Terminal] WRITE LINE: Exiting...

**Comment by anatolybolshakov** [comment]
Hi @bvbellomo is your PAT token actual and not expired, is it 'Agent Pools (read, manage)' scoped?

**Comment by bvbellomo** [comment]
I am trying to login in with Negotiate (the default authentication type) and entering my username and password directly.

Maybe I am misunderstanding PAT tokens, but I was under the impression that I could not use a PAT token unless I was connecting over SSL.  Can you confirm whether that is correct or wrong?

I do have an unexpired PAT token appropriate scoped that I created and tried to use earlier.  But I am not entering anything except the same username and password I'd log in to the TFS web interface in a browser.  I stopped trying to get my PAT token to work when I read it required SSL.

**Comment by oneframemobile** [comment]
We have a same problem. Any improvement?

**Comment by anatolybolshakov** [comment]
@bvbellomo @oneframemobile could you please check what authentication type is being set up for tfs server? (/tfs in IIS settings). From logs I assume it is Windows Authentication, which could cause this issue.

**Comment by oneframemobile** [comment]
The authentication configuration of Azure DevOps on IIS is as follow. 
By the way I am assuming this configuration is the default configuration of Azure DevOps.
What should we do ?

![image](https://user-images.githubusercontent.com/46996465/109963758-d2321600-7cfd-11eb-9249-539745ed1c25.png)

**Comment by anatolybolshakov** [comment]
@oneframemobile I assume you can't use windows authentication with mac client - so it makes sense to enable basic authentication.
Since it's more related to DevOps authentication process - could you please create a ticket on https://developercommunity.visualstudio.com/search?space=21 for further guidance if enabling of this authentication type won't help?

**Comment by bvbellomo** [comment]
It seems there are 2 questions/issues if it is in fact the Authentication type causing the problem:
1) Does enabling 'Windows Authentication' prevent using TFS with a mac build agent, regardless of what else is enabled?
2) Does using TFS with a mac build agent require enabling specific authentication options, and if so, which ones?

These are completely different questions.

**Comment by anatolybolshakov** [comment]
Hi @bvbellomo sorry for the delay - we performed additional investigation around this - could you please try to set up AZP_AGENT_USE_LEGACY_HTTP environment variable as 'true' and try to connect the agent again?

**Comment by anatolybolshakov** [comment]
Hi @bvbellomo do you have any updates?

**Comment by bvbellomo** [comment]
During the 4 months I was waiting for a reply, I was able to get SSL installed.

**Comment by anatolybolshakov** [comment]
@bvbellomo sorry for the delay - let me close this one since it's resolved for you - feel free to ask any further questions.
