### ISSUE TITLE
Unable to connect to https://dev.azure.com/***

### ISSUE THREAD

**Issue by MalteFries** [microsoft/azure-pipelines-agent#3281]
## Agent Version and Platform
2.181.1 &  2.182.1

## OS of the machine running the agent? 
Microsoft Windows 10.0.17763

## Azure DevOps Type and Version
https://dev.azure.com/draeger

## What's not working?
Since 3 days we are unable to connect the agent.
This happens with both version I mentioned above.
I tried a clean install with the newest version (see log below) but both versions are stuck at the first request.

When I open the requested url in browser I am prompted with a microsoft organization login (ADFS authentication), after entering my creds I receive the json string.
So it is not a proxy issue, since I am able to receive data.

Our self hosted servers are inside of our domain, so why are we even prompted with a login form and why is none of the available authentication working?
I tried PAT, integrated and alt, it always times out on the first request.

## Agent and Worker's Diagnostic Logs

```
[2021-02-24 07:49:01Z INFO AgentProcess] Agent package win-x64.
[2021-02-24 07:49:01Z INFO AgentProcess] Running on Windows (X64).
[2021-02-24 07:49:01Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.17763.
[2021-02-24 07:49:01Z INFO AgentProcess] Version: 2.182.1
[2021-02-24 07:49:01Z INFO AgentProcess] Commit: 6b9b997b4ca33d649fcf0631bdaa552177145043
[2021-02-24 07:49:01Z INFO AgentProcess] Culture: de-DE
[2021-02-24 07:49:01Z INFO AgentProcess] UI Culture: de-DE
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO AgentProcess] Validating directory permissions for: 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO PowerShellExeUtil] Generation: '1'
[2021-02-24 07:49:01Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion' is null.
[2021-02-24 07:49:01Z INFO PowerShellExeUtil] Unable to determine the Powershell engine version.  Possibly Powershell is not installed.
[2021-02-24 07:49:01Z INFO PowerShellExeUtil] Generation: '3'
[2021-02-24 07:49:01Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.17763.1'
[2021-02-24 07:49:01Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2021-02-24 07:49:01Z INFO AgentProcess]  'CDF'
[2021-02-24 07:49:01Z INFO AgentProcess]  'v2.0.50727'
[2021-02-24 07:49:01Z INFO AgentProcess]  'v3.0'
[2021-02-24 07:49:01Z INFO AgentProcess]  'v3.5'
[2021-02-24 07:49:01Z INFO AgentProcess]  'v4'
[2021-02-24 07:49:01Z INFO AgentProcess]  'v4.0'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Version': '2.0.50727.4927'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Install': '1'
[2021-02-24 07:49:01Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727'
[2021-02-24 07:49:01Z INFO AgentProcess] Found version: 2.0.50727
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version': '3.0.30729.4926'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Install': '1'
[2021-02-24 07:49:01Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.0'
[2021-02-24 07:49:01Z INFO AgentProcess] Found version: 3.0
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Version': '3.5.30729.4926'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Install': '1'
[2021-02-24 07:49:01Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.5'
[2021-02-24 07:49:01Z INFO AgentProcess] Found version: 3.5
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2021-02-24 07:49:01Z INFO AgentProcess]  'Client'
[2021-02-24 07:49:01Z INFO AgentProcess]  'Full'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.8.03761'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '528049'
[2021-02-24 07:49:01Z INFO AgentProcess] Type is System.Int32
[2021-02-24 07:49:01Z INFO AgentProcess] Interpreted version: 4.7.0
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.8.03761'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '528049'
[2021-02-24 07:49:01Z INFO AgentProcess] Type is System.Int32
[2021-02-24 07:49:01Z INFO AgentProcess] Interpreted version: 4.7.0
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2021-02-24 07:49:01Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2021-02-24 07:49:01Z INFO AgentProcess] Found 5 versions:
[2021-02-24 07:49:01Z INFO AgentProcess]  2.0.50727
[2021-02-24 07:49:01Z INFO AgentProcess]  3.0
[2021-02-24 07:49:01Z INFO AgentProcess]  3.5
[2021-02-24 07:49:01Z INFO AgentProcess]  4.7.0
[2021-02-24 07:49:01Z INFO AgentProcess]  4.7.0
[2021-02-24 07:49:01Z INFO AgentProcess] Testing for min NET Framework version: '4.5'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO CommandSettings] Configure {
  "AcceptTeeEula": false,
  "AddDeploymentGroupTags": false,
  "AddEnvironmentVirtualMachineResourceTags": false,
  "AddMachineGroupTags": false,
  "AlwaysExtractTask": false,
  "Agent": "***",
  "CollectionName": null,
  "DeploymentGroup": false,
  "DeploymentGroupName": null,
  "DeploymentGroupTags": null,
  "DeploymentPool": false,
  "DeploymentPoolName": null,
  "EnvironmentVMResource": false,
  "EnvironmentName": null,
  "EnvironmentVMResourceTags": null,
  "GitUseSChannel": false,
  "DisableLogUploads": false,
  "MachineGroup": false,
  "MachineGroupName": null,
  "MachineGroupTags": null,
  "MonitorSocketAddress": null,
  "NotificationPipeName": null,
  "NotificationSocketAddress": null,
  "NoRestart": false,
  "OverwriteAutoLogon": true,
  "Pool": "DraegerTestautomation",
  "ProjectName": null,
  "ProxyPassword": "***",
  "ProxyUserName": "***\\***",
  "ProxyUrl": "http://***.***.***.**:80",
  "Replace": true,
  "RunAsAutoLogon": true,
  "RunAsService": false,
  "RunOnce": false,
  "SslCACert": null,
  "SslClientCert": null,
  "SslClientCertArchive": null,
  "SslClientCertKey": null,
  "SslClientCertPassword": null,
  "SslSkipCertValidation": false,
  "Url": "https://dev.azure.com/draeger",
  "WindowsLogonAccount": "***",
  "WindowsLogonPassword": "***",
  "Work": null,
  "Auth": "pat",
  "LaunchBrowser": false,
  "Password": null,
  "Token": "***",
  "Unattended": false,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2021-02-24 07:49:01Z INFO AgentProcess] Arguments parsed
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'Proxy': 'C:\AgentTest\.proxy'
[2021-02-24 07:49:01Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'Certificates': 'C:\AgentTest\.certificates'
[2021-02-24 07:49:01Z INFO AgentCertificateManager] No certificate setting found.
[2021-02-24 07:49:01Z INFO Agent] ExecuteCommand
[2021-02-24 07:49:01Z INFO ConfigurationStore] currentAssemblyLocation: C:\AgentTest\bin\Agent.Listener.dll
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO ConfigurationStore] binPath: C:\AgentTest\bin
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO ConfigurationStore] RootFolder: C:\AgentTest
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'Agent': 'C:\AgentTest\.agent'
[2021-02-24 07:49:01Z INFO ConfigurationStore] ConfigFilePath: C:\AgentTest\.agent
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'Credentials': 'C:\AgentTest\.credentials'
[2021-02-24 07:49:01Z INFO ConfigurationStore] CredFilePath: C:\AgentTest\.credentials
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'Service': 'C:\AgentTest\.service'
[2021-02-24 07:49:01Z INFO ConfigurationStore] ServiceConfigFilePath: C:\AgentTest\.service
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'Autologon': 'C:\AgentTest\.autologon'
[2021-02-24 07:49:01Z INFO ConfigurationStore] AutoLogonSettingsFilePath: C:\AgentTest\.autologon
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'Options': 'C:\AgentTest\.options'
[2021-02-24 07:49:01Z INFO ConfigurationStore] RuntimeOptionsFilePath: C:\AgentTest\.options
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'SetupInfo': 'C:\AgentTest\.setup_info'
[2021-02-24 07:49:01Z INFO ConfigurationStore] SetupInfoFilePath: C:\AgentTest\.setup_info
[2021-02-24 07:49:01Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.182.1             |_|          (commit 6b9b997)

[2021-02-24 07:49:01Z INFO ConfigurationManager] CheckAgentRootDirectorySecure
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO ConfigurationManager] ConfigureAsync
[2021-02-24 07:49:01Z INFO ConfigurationStore] IsConfigured()
[2021-02-24 07:49:01Z INFO ConfigurationStore] IsConfigured: False
[2021-02-24 07:49:01Z INFO ConfigurationManager] Is configured: False
[2021-02-24 07:49:01Z INFO ConfigurationManager] Reset proxy base on commandline args.
[2021-02-24 07:49:01Z INFO VstsAgentWebProxy] Update proxy setting from '' to'http://***'
[2021-02-24 07:49:01Z INFO VstsAgentWebProxy] Config authentication proxy as: ****.
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Bin': 'C:\AgentTest\bin'
[2021-02-24 07:49:01Z INFO HostContext] Well known directory 'Root': 'C:\AgentTest'
[2021-02-24 07:49:01Z INFO HostContext] Well known config file 'ProxyBypass': 'C:\AgentTest\.proxybypass'
[2021-02-24 07:49:01Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2021-02-24 07:49:01Z INFO ConfigurationManager] Testing for min NET Framework version: '4.6'
[2021-02-24 07:49:01Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2021-02-24 07:49:01Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2021-02-24 07:49:01Z INFO CommandSettings] Flag 'environment': 'False'
[2021-02-24 07:49:01Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2021-02-24 07:49:01Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2021-02-24 07:49:01Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2021-02-24 07:49:01Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2021-02-24 07:49:01Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2021-02-24 07:49:01Z INFO Terminal] WRITE LINE: 
[2021-02-24 07:49:01Z INFO Terminal] WRITE LINE: >> Verbinden:
[2021-02-24 07:49:01Z INFO Terminal] WRITE LINE: 
[2021-02-24 07:49:01Z INFO CommandSettings] Arg 'url': 'https://dev.azure.com/draeger'
[2021-02-24 07:49:01Z INFO ConfigurationManager] GetCredentialProvider
[2021-02-24 07:49:01Z INFO CommandSettings] Arg 'auth': 'pat'
[2021-02-24 07:49:01Z INFO ConfigurationManager] Creating credential for auth: pat
[2021-02-24 07:49:01Z INFO CredentialManager] GetCredentialProvider
[2021-02-24 07:49:01Z INFO CredentialManager] Creating type pat
[2021-02-24 07:49:01Z INFO CredentialManager] Creating credential type: pat
[2021-02-24 07:49:01Z INFO PersonalAccessToken] EnsureCredential
[2021-02-24 07:49:01Z INFO CommandSettings] Arg 'token': '***'
[2021-02-24 07:49:01Z INFO PersonalAccessToken] GetVssCredentials
[2021-02-24 07:49:01Z INFO PersonalAccessToken] token retrieved: 52 chars
[2021-02-24 07:49:01Z INFO PersonalAccessToken] cred created
[2021-02-24 07:49:01Z INFO ConfigurationManager] cred retrieved
[2021-02-24 07:49:01Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-02-24 07:49:23Z WARN VisualStudioServices] Attempt 1 of GET request to https://dev.azure.com/draeger/_apis/connectionData?connectOptions=1&lastChangeId=291610680&lastChangeId64=291610680 failed (Socket Error: TimedOut). The operation will be retried in 11,176304 seconds.
[2021-02-24 07:49:55Z WARN VisualStudioServices] Attempt 2 of GET request to https://dev.azure.com/draeger/_apis/connectionData?connectOptions=1&lastChangeId=291610680&lastChangeId64=291610680 failed (Socket Error: TimedOut). The operation will be retried in 12,7118804 seconds.
[2021-02-24 07:50:28Z WARN VisualStudioServices] Attempt 3 of GET request to https://dev.azure.com/draeger/_apis/connectionData?connectOptions=1&lastChangeId=291610680&lastChangeId64=291610680 failed (Socket Error: TimedOut). The operation will be retried in 17,3573174 seconds.
[2021-02-24 07:51:07Z ERR  VisualStudioServices] Attempt 4 of GET request to https://dev.azure.com/draeger/_apis/connectionData?connectOptions=1&lastChangeId=291610680&lastChangeId64=291610680 failed (Socket Error: TimedOut). The maximum number of attempts has been reached.
[2021-02-24 07:51:07Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-02-24 07:51:07Z INFO LocationServer] Unable to connect to https://dev.azure.com/draeger.
[2021-02-24 07:51:07Z ERR  LocationServer] System.Net.Http.HttpRequestException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
 ---> System.Net.Sockets.SocketException (10060): Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
[2021-02-24 07:51:07Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-02-24 07:51:07Z ERR  Terminal] WRITE ERROR (exception):
[2021-02-24 07:51:07Z ERR  Terminal] System.Net.Http.HttpRequestException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
 ---> System.Net.Sockets.SocketException (10060): Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.IsHostedServer(String serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)

```

**Comment by anatolybolshakov** [comment]
Hi @MalteFries what version of on-premise server do you use?

**Comment by MalteFries** [comment]
@anatolybolshakov we are not using on-premise server, our VMs are hosted on Azure

**Comment by MalteFries** [comment]
We have restarted our ADFS controller, now it's working again.
Thanks for your time.
