### ISSUE TITLE
Self Hosted Arm32 Agent: Fatal NullRefrenceException

### ISSUE THREAD

**Issue by and-rewsmith** [microsoft/azure-pipelines-agent#3360]
## Have you tried troubleshooting?
[Troubleshooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...
2.185.0

OS of the machine running the agent? OSX/Windows/Linux/...
Raspbian Buster (arm32)

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?

https://dev.azure.com/msazure

## What's not working?

I follow the instructions in the tutorial and when my agent runs jobs I get this in the devops pane:
```
Starting: Initialize job
Agent name: 'andsmi-manual-test'
Agent machine name: 'raspberrypi-pihole'
Current agent version: '2.184.2'
Agent running as: 'pi'
Prepare build directory.
Set build variables.
Download all required tasks.
Checking job knob settings.
   Knob: TaskRestrictionsEnforcementMode = WarningOnly Source: $(agent.taskRestrictionsEnforcementMode) 
   Knob: EnableTaskRestrictionsTelemetry = true Source: $(agent.enableTaskRestrictionsTelemetry) 
Finished checking job knob settings.
##[error]Object reference not set to an instance of an object.
Finishing: Initialize job
```

From running the agent interactively, here is the output:
```
Scanning for tool capabilities.
Connecting to the server.
2021-04-13 01:40:16Z: Listening for Jobs
2021-04-13 01:43:00Z: Running job: Linux ARM32v7 Moby
2021-04-13 01:43:12Z: Job Linux ARM32v7 Moby completed with result: Failed
```

From the diag log for the job:
```
[2021-04-13 01:43:09Z INFO TaskManager] Loading task definition '/home/pi/myagent/_work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.182.0/task.json'.
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'Bin': '/home/pi/myagent/bin'
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'Root': '/home/pi/myagent'
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'Work': '/home/pi/myagent/_work'
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'Tasks': '/home/pi/myagent/_work/_tasks'
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'Bin': '/home/pi/myagent/bin'
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'Root': '/home/pi/myagent'
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'Work': '/home/pi/myagent/_work'
[2021-04-13 01:43:09Z INFO HostContext] Well known directory 'TaskZips': '/home/pi/myagent/_work/_taskzips'
[2021-04-13 01:43:09Z INFO TaskManager] Loading task definition '/home/pi/myagent/_work/_tasks/CodeSignValidationInjected_8bc4f1c1-95b1-44d2-9f1a-df3e741decb9/1.149.0/task.json'.
[2021-04-13 01:43:09Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2021-04-13 01:43:09Z ERR  JobRunner] Job initialize failed.
[2021-04-13 01:43:09Z ERR  JobRunner] Caught exception from InitializeJob: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
[2021-04-13 01:43:09Z INFO JobRunner] Shutting down the job server queue.
[2021-04-13 01:43:09Z INFO JobServerQueue] Fire signal to shutdown all queues
```

I have already tried reconfiguring and installing the dependencies. I noticed there aren't tests for arm32, so I was thinking there might be a bug? 
https://mseng.visualstudio.com/PipelineTools/_build/results?buildId=14856029&view=results

**Comment by EzzhevNikita** [comment]
Hi @and-rewsmith, am I understand correctly that you have a problem with several agent versions starting from 2.144.0 till 2.185.0? Does the problem appear constantly or periodically?
And also could you please share full agent logs (files from _diag folder) you can either attach them to this ticket or send them to my email v-niezz@microsoft.com

**Comment by and-rewsmith** [comment]
I sent them via email. The only agent version I have tested is 2.185.0. This line is part of the template which I think caused the confusion:
> Version of your agent? 2.144.0/2.144.1/...

**Comment by EzzhevNikita** [comment]
Thank you for the quick response, we will check provided logs.
Regarding the agent's version, I assume you mean 2.184.2, but not 2.185.0 - at least the logs that you provided are for this version.

**Comment by and-rewsmith** [comment]
@EzzhevNikita Yeah good catch. 2.184.2 is the agent version I am running.

**Comment by and-rewsmith** [comment]
> Does the problem appear constantly or periodically?

@EzzhevNikita Sorry forgot to answer this question. The problem appears constantly. I have tried running the install script to install all dependencies, removing the agent, then recreating a new one. However I get the same issue.

**Comment by EzzhevNikita** [comment]
@and-rewsmith I set up an arm32 agent on my raspberry pi, looks like it works as expected for me, I don't see such issues. I also would like to check one moment on your side.
As I see the agent is failing on the step when it is loading task definition for CodeSignValidationInjected task.
Could you please check and confirm that task definition exists in this location _/home/pi/myagent/_work/_tasks/CodeSignValidationInjected_8bc4f1c1-95b1-44d2-9f1a-df3e741decb9/1.149.0/task.json_ ?
Also if it Is possible could you please try to run the job without this task in the pipeline definition?

**Comment by and-rewsmith** [comment]
@EzzhevNikita 
> Could you please check and confirm that task definition exists in this location _/home/pi/myagent/_work/tasks/CodeSignValidationInjected_8bc4f1c1-95b1-44d2-9f1a-df3e741decb9/1.149.0/task.json ?

The location is slightly different (_tasks rather than tasks):
```
~/myagent/_work/_tasks/CodeSignValidationInjected_8bc4f1c1-95b1-44d2-9f1a-df3e741decb9/1.149.0/task.json
```

> Also if it Is possible could you please try to run the job without this task in the pipeline definition?

That task is auto-injected by a policy we have in place, so I am not sure there is a way to disable it. Lmk if you know of a workaround for this.

**Comment by and-rewsmith** [comment]
@EzzhevNikita It stopped happening today. Not sure what was wrong but it seems to be fixed.

**Comment by EzzhevNikita** [comment]
@and-rewsmith  Oh, that's interesting. I'm glad that the issue was resolved.
Since it is not actual anymore I am closing this ticket. Feel free to reopen it in case of additional questions.
