### ISSUE TITLE
Unable to configure newer versions of agents

### ISSUE THREAD

**Issue by Arko109** [microsoft/azure-pipelines-agent#3361]
## Agent Version and Platform
v.2.182.1/v2.184.2/v2.185.0

macOS

## Azure DevOps Type and Version
On-premises Azure DevOps Server 

Version Dev17.M153.3

## What's not working?
We are unable to configure newer versions of agents (tested with the three mentioned above), they fail with "You are not authorized to access {server_url}" message. The old version we currently have (2.153.1) can be connected without problems. We have to use the "Negotiate" authentication because our server is set up only in HTTP.

## Agent and Worker's Diagnostic Logs
```
[2021-04-13 10:56:55Z INFO CommandSettings] Arg 'url': ''
[2021-04-13 10:56:55Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-04-13 10:56:55Z INFO PromptManager] ReadValue
[2021-04-13 10:56:55Z INFO Terminal] WRITE: Enter server URL >
[2021-04-13 10:56:55Z INFO Terminal] READ LINE
[2021-04-13 10:57:11Z INFO Terminal] Read value: 'http://{server_url}/tfs'
[2021-04-13 10:57:11Z INFO ConfigurationManager] GetCredentialProvider
[2021-04-13 10:57:11Z INFO CommandSettings] Arg 'auth': ''
[2021-04-13 10:57:11Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-04-13 10:57:11Z INFO PromptManager] ReadValue
[2021-04-13 10:57:11Z INFO Terminal] WRITE: Enter authentication type (press enter for Negotiate) >
[2021-04-13 10:57:11Z INFO Terminal] READ LINE
[2021-04-13 10:57:13Z INFO Terminal] Read value: ''
[2021-04-13 10:57:13Z INFO PromptManager] Falling back to the default: 'Negotiate'
[2021-04-13 10:57:13Z INFO ConfigurationManager] Creating credential for auth: Negotiate
[2021-04-13 10:57:13Z INFO CredentialManager] GetCredentialProvider
[2021-04-13 10:57:13Z INFO CredentialManager] Creating type Negotiate
[2021-04-13 10:57:13Z INFO CredentialManager] Creating credential type: Negotiate
[2021-04-13 10:57:13Z INFO PersonalAccessToken] EnsureCredential
[2021-04-13 10:57:13Z INFO CommandSettings] Arg 'username': ''
[2021-04-13 10:57:13Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-04-13 10:57:13Z INFO PromptManager] ReadValue
[2021-04-13 10:57:13Z INFO Terminal] WRITE: Enter user name >
[2021-04-13 10:57:13Z INFO Terminal] READ LINE
[2021-04-13 10:57:18Z INFO Terminal] Read value: '{username}'
[2021-04-13 10:57:18Z INFO CommandSettings] Arg 'password': ''
[2021-04-13 10:57:18Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-04-13 10:57:18Z INFO PromptManager] ReadValue
[2021-04-13 10:57:18Z INFO Terminal] WRITE: Enter password >
[2021-04-13 10:57:18Z INFO Terminal] READ SECRET
[2021-04-13 10:57:24Z INFO Terminal] Read value: '***'
[2021-04-13 10:57:24Z INFO NegotiateCredential] GetVssCredentials
[2021-04-13 10:57:24Z INFO NegotiateCredential] User name retrieved.
[2021-04-13 10:57:24Z INFO NegotiateCredential] Password retrieved.
[2021-04-13 10:57:24Z INFO NegotiateCredential] URL retrieved: http://{server_url}/tfs
[2021-04-13 10:57:24Z INFO ConfigurationManager] cred retrieved
[2021-04-13 10:57:24Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-04-13 10:57:24Z WARN VisualStudioServices] Authentication failed with status code 401.
X-TFS-ProcessId: dab61c2b-0e7c-4761-a77d-29c104aee757
ActivityId: 4a104acf-ea63-4127-a12a-cd024b8c692a
X-TFS-Session: 20616dda-f555-4207-8b56-5ffaf0bcee37
X-VSS-E2EID: c7321a69-6d3a-470c-8afe-7ecca2e230b7
X-TFS-SoapException: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
X-TFS-ServiceError: TF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.
WWW-Authenticate: Bearer, Basic realm="http://{server_url}/tfs", Negotiate, NTLM
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Tue, 13 Apr 2021 10:57:51 GMT

[2021-04-13 10:57:24Z WARN VisualStudioServices] Authentication failed with status code 401.
X-TFS-ProcessId: dab61c2b-0e7c-4761-a77d-29c104aee757
ActivityId: 4a104acd-ea63-4127-a12a-cd024b8c692a
X-TFS-Session: 20616dda-f555-4207-8b56-5ffaf0bcee37
X-VSS-E2EID: c7321a69-6d3a-470c-8afe-7ecca2e230b7
WWW-Authenticate: Bearer, Basic realm="http://{server_url}/tfs", Negotiate, NTLM
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Tue, 13 Apr 2021 10:57:51 GMT

[2021-04-13 10:57:24Z WARN VisualStudioServices] Windows issued token provider instance 14145203 requires an interactive prompt which is not allowed by the current settings
[2021-04-13 10:57:24Z ERR  VisualStudioServices] GET request to http://{server_url}/tfs/_apis/connectionData?connectOptions=0&lastChangeId=51&lastChangeId64=51 is not authorized. Details: VS30063: You are not authorized to access http://{server_url}.
[2021-04-13 10:57:24Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-04-13 10:57:24Z INFO LocationServer] Unable to connect to http://{server_url}/tfs.
[2021-04-13 10:57:24Z ERR  LocationServer] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://{server_url}.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
[2021-04-13 10:57:24Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-04-13 10:57:24Z ERR  Terminal] WRITE ERROR (exception):
[2021-04-13 10:57:24Z ERR  Terminal] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://{server_url}.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.IsHostedServer(String serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
[2021-04-13 10:57:24Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2021-04-13 10:57:24Z INFO CommandSettings] Arg 'url': ''
[2021-04-13 10:57:24Z INFO CommandSettings] Flag 'unattended': 'False'
[2021-04-13 10:57:24Z INFO PromptManager] ReadValue
[2021-04-13 10:57:24Z INFO Terminal] WRITE: Enter server URL >
[2021-04-13 10:57:24Z INFO Terminal] READ LINE
[2021-04-13 11:01:09Z INFO Terminal] WRITE LINE: Exiting...
```

**Comment by EzzhevNikita** [comment]
That issue seems to be similar to this one https://github.com/microsoft/azure-pipelines-agent/issues/3271

**Comment by Arko109** [comment]
It is indeed similar, however there's one important info that is added in mine, for us it works with a previous version but not with latest ones, so there must've been a breaking change somewhere in-between.

**Comment by vladislav-ryzhov** [comment]
@Arko109 Hi!
Could you please set env variable **AZP_AGENT_USE_LEGACY_HTTP** to **true** and try to configure the Agent again?
Please find more information here

**Comment by Arko109** [comment]
@vladislav-ryzhov Hello, unfortunately we have updated to a newer version of Azure DevOps since I opened this issue, so we are no longer able to perform this test. We don't have the agent connection problem after the update.

**Comment by DutchBlackOp** [comment]
Hello, after upgrading our azure devops environment from Azure DevOps Server 2020 -> Azure DevOps Server 2020 Update 1 we encountered this same issue for the http connection on MacOS. The issue occured when updating our Mac agents to version 2.189.0. After using the env variable AZP_AGENT_USE_LEGACY_HTTP mentioned by @vladislav-ryzhov, connecting through http worked again.

Is this an issue with the new HTTP solution that needs to be solved first, or is the environment variable a permanent solution? Would be good to know if we can keep using this variable in the future or if it is eventually going to be deprecated.

**Comment by anatolybolshakov** [comment]
Hi @DutchBlackOp there is a related net core issue - https://github.com/dotnet/runtime/issues/25827.
In general we are planning to update net core version for agent, but it could take some time to complete migration.
