### ISSUE TITLE
SSL error when trying to download artifacts with agent version [2.188.3]

### ISSUE THREAD

**Issue by craigeaw** [microsoft/azure-pipelines-agent#3452]
## Agent Version and Platform
2.188.3

OS of the machine running the agent?
Windows Server 2019

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
With version 2.188.3, as soon as agents automatically upgraded we get an SSL error during artifact download.

## Agent and Worker's Diagnostic Logs
```
2021-06-29T20:58:30.2172776Z ##[debug]Processed: ##vso[task.logissue type=error;]The SSL connection could not be established, see inner exception.
2021-06-29T20:58:30.2183518Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2021-06-29T20:58:30.2280828Z ##[debug]   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.CheckForServerUpdatesAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.FindServiceDefinitionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.LocationForCurrentConnectionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Agent.Plugins.BuildServer..ctor(VssConnection connection)
   at Agent.Plugins.PipelineArtifactServer.DownloadAsyncV2(AgentTaskPluginExecutionContext context, ArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.BuildArtifacts.DownloadBuildArtifactTaskV1_0_0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
```

**Comment by anatolybolshakov** [comment]
Hi @craigeaw could you please make sure that all domains specified in [docs](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4) are allowed for your agent's environment - specifically for *.blob.core.windows.net?

**Comment by craigeaw** [comment]
> Hi @craigeaw could you please make sure that all domains specified in [docs](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4) are allowed for your agent's environment - specifically for *.blob.core.windows.net?

I checked with our network security team, and none of the domains in the document are being blocked. Our configuration has not changed since before agent version 2.188.3 was released, so I think it's an issue with the agent code or configuration.

**Comment by anatolybolshakov** [comment]
Could you please try to set up DISABLE_BUILD_ARTIFACTS_TO_BLOB environment variable as 'true' before agent configuration? This will disable new blob storage functionality introduced by task update.

**Comment by craigeaw** [comment]
I set this as a variable on the release. It did not seem to make a difference. See my environment variable output below (some output has been removed by me).

```
2021-06-30T18:04:17.7297981Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
				[AGENT_DEPLOYMENTGROUPID] --> [221]
				[AGENT_DISABLELOGPLUGIN_TESTFILEPUBLISHERPLUGIN] --> [true]
				[AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN] --> [true]
				[AGENT_ENABLETASKRESTRICTIONSTELEMETRY] --> [true]
				[AGENT_HOMEDIRECTORY] --> [C:\azagent\A1]
				[AGENT_ID] --> [78]
				[AGENT_JOBNAME] --> [Release]
				[AGENT_OS] --> [Windows_NT]
				[AGENT_OSARCHITECTURE] --> [X64]
				[AGENT_RELEASEDIRECTORY] --> [C:\azagent\A1\_work\r1\a]
				[AGENT_RETAINDEFAULTENCODING] --> [false]
				[AGENT_ROOTDIRECTORY] --> [C:\azagent\A1\_work]
				[AGENT_SERVEROMDIRECTORY] --> [C:\azagent\A1\externals\vstsom]
				[AGENT_TASKRESTRICTIONSENFORCEMENTMODE] --> [WarningOnly]
				[AGENT_TEMPDIRECTORY] --> [C:\azagent\A1\_work\_temp]
				[AGENT_TOOLSDIRECTORY] --> [C:\azagent\A1\_work\_tool]
				[AGENT_VERSION] --> [2.188.3]
				[AGENT_WORKFOLDER] --> [C:\azagent\A1\_work]
				[AZURE_HTTP_USER_AGENT] --> [VSTS_64bf1ad0-199a-44bf-8c53-ba6a223b94ff_release_20_1260_3048_6]
				[BUILD_BUILDID] --> [8325]
				...
				[BUILD_TYPE] --> [Build]
				[DISABLE_BUILD_ARTIFACTS_TO_BLOB] --> [true]
```

**Comment by anatolybolshakov** [comment]
@craigeaw could you please share what was the previous agent version which worked for you?

**Comment by anatolybolshakov** [comment]
@craigeaw could you please share whole agent logs for your case? You can send them to my email - v-anbols@microsoft.com

**Comment by Devops1234567890** [comment]
We're also facing the exact same issue auto-upgraded to version 2.188.3

**Comment by mkosieradzki** [comment]
@anatolybolshakov How is `DISABLE_BUILD_ARTIFACTS_TO_BLOB` flag supposed to help? If the agent crashes much earlier on:
```
Agent.Plugins.BuildServer..ctor(VssConnection connection)
```

```
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
```

**Comment by mkosieradzki** [comment]
@anatolybolshakov - also all logs are aready sent as part of `2106290050001198` SR.

**Comment by anatolybolshakov** [comment]
@alex-peck could you please take a look? Do you know maybe if it's some known issue?

**Comment by alex-peck** [comment]
This is almost definitely due to a misconfigured firewall. You are failing to reach out to the location service.

**Comment by craigeaw** [comment]
> This is almost definitely due to a misconfigured firewall. You are failing to reach out to the location service.
> 
> Can you try the agent in a different environment to confirm you are still having this issue?

Our firewall configuration has not changed since the previous working version. I confirmed with our network security team that there is no traffic being blocked by the firewall when these requests are being made by the agent. Did the firewall configuration requirements for the agent change on 6/28?

**Comment by alex-peck** [comment]
> > This is almost definitely due to a misconfigured firewall. You are failing to reach out to the location service.
> > Can you try the agent in a different environment to confirm you are still having this issue?
> 
> Our firewall configuration has not changed since the previous working version. I confirmed with our network security team that there is no traffic being blocked by the firewall when these requests are being made by the agent. Did the firewall configuration requirements for the agent change on 6/28?

Are you using a proxy of any kind? 

The change that happened was we moved from DownloadBuildArtifactsV0 (which was a JavaScript task) to DownloadBuildArtifactsV1 (which is a C# task included in the agent).

**Comment by craigeaw** [comment]
> > > This is almost definitely due to a misconfigured firewall. You are failing to reach out to the location service.
> > > Can you try the agent in a different environment to confirm you are still having this issue?
> > 
> > 
> > Our firewall configuration has not changed since the previous working version. I confirmed with our network security team that there is no traffic being blocked by the firewall when these requests are being made by the agent. Did the firewall configuration requirements for the agent change on 6/28?
> 
> Are you using a proxy of any kind?
> 
> The change that happened was we moved from DownloadBuildArtifactsV0 (which was a JavaScript task) to DownloadBuildArtifactsV1 (which is a C# task included in the agent).

No proxy. We're trying something with the FW configuration. I'll get back to you with our findings.

**Comment by craigeaw** [comment]
@alex-peck You are correct that is was misconfigured FW. It was that coupled with me misinterpreting a deployment process. Ian IP was being blocked in the 13.107.42.0/24 range. We allowed it for one server, but failed to do so for another server in the deployment group. We'll be revisiting our configuration next week to ensure the entire range is covered. Thank you for your help!

**Comment by alex-peck** [comment]
Customer confirmed this was an issue with their firewall. Closing this for now. If anyone else experiennces a similar error, please validate that your firewall is correctly configured with the [allow-list here](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4).

**Comment by lvasco** [comment]
Hi @alex-peck i have the same problem in the download of universal package but i use proxy and agent in with version 2.213.2
