### ISSUE TITLE
Azure self hosted Linux agent offline, no clear error.

### ISSUE THREAD

**Issue by alucardu** [microsoft/azure-pipelines-agent#3472]
## Agent Version and Platform
2.185.1 Linux

OS of the machine running the agent? OSX/Windows/Linux/...

## What's not working?

![image](https://user-images.githubusercontent.com/779921/127174528-d9e75d05-ae94-4bbf-886a-fbeffc7ea8a6.png)

```
/etc/systemd/system/vsts.agent.***.Dev\x20Tools.deploytools\x2d***.service
● vsts.agent.***.Dev\x20Tools.deploytools\x2d***.service - Azure Pipelines Agent (***.Dev Tools.deploytools-***)
   Loaded: loaded (/etc/systemd/system/vsts.agent.***.Dev\x20Tools.deploytools\x2d***.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-07-27 14:20:41 UTC; 5min ago
 Main PID: 26601 (runsvc.sh)
    Tasks: 8 (limit: 2322)
   Memory: 11.0M
   CGroup: /system.slice/vsts.agent.***.Dev\x20Tools.deploytools\x2d***.service
           ├─26601 /bin/bash /home/peter/runsvc.sh
           └─26604 ./externals/node10/bin/node ./bin/AgentService.js

Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at Microsoft.VisualStudio.Services.Agent.HostTraceListener.CreatePageLogWriter()
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at Microsoft.VisualStudio.Services.Agent.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32 pageSizeLimit, Int32 retentionDays)
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at Microsoft.VisualStudio.Services.Agent.HostContext..ctor(String hostType, String logFile)
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]:    at Microsoft.VisualStudio.Services.Agent.Listener.Program.Main(String[] args)
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]: Agent listener exited with error code null
Jul 27 14:26:13 deploytools-*** runsvc.sh[26601]: Agent listener exit with undefined return code, re-launch agent in 5 seconds.
```

## Agent and Worker's Diagnostic Logs

All the agent logs are empty

Worker_20210727-134223-utc.log
```
[2021-07-27 13:42:23Z INFO Program] Version: 2.185.1
[2021-07-27 13:42:23Z INFO Program] Commit: 45c52d01eec6c18e3a3e5d8e2a4859fbfc90eff7
[2021-07-27 13:42:23Z INFO Program] Culture:
[2021-07-27 13:42:23Z INFO Program] UI Culture:
[2021-07-27 13:42:23Z INFO HostContext] Well known directory 'Bin': '/home/peter/bin'
[2021-07-27 13:42:23Z INFO HostContext] Well known directory 'Root': '/home/peter'
[2021-07-27 13:42:23Z INFO HostContext] Well known config file 'Proxy': '/home/peter/.proxy'
[2021-07-27 13:42:23Z INFO VstsAgentWebProxy] No proxy setting found.
[2021-07-27 13:42:23Z INFO HostContext] Well known directory 'Bin': '/home/peter/bin'
[2021-07-27 13:42:23Z INFO HostContext] Well known directory 'Root': '/home/peter'
[2021-07-27 13:42:23Z INFO HostContext] Well known config file 'Certificates': '/home/peter/.certificates'
[2021-07-27 13:42:23Z INFO AgentCertificateManager] No certificate setting found.
[2021-07-27 13:42:23Z INFO Worker] Waiting to receive the job message from the channel.
[2021-07-27 13:42:23Z INFO Worker] Message received.
[2021-07-27 13:42:23Z INFO Worker] Job message:
 {
  "mask": [
    {
      "type": "regex",
      "value": "***"
    },
    {
      "type": "regex",
      "value": "***"
    }
  ],
  "steps": [
    {
      "inputs": {
        "project": "5ef41df0-5696-4978-8592-8dbfba779500",
        "buildType": "specific",
        "definition": "2",
        "buildId": "124",
        "artifactName": "flexwerker",
        "downloadType": "single",
        "itemPattern": "**",
        "buildVersionToDownload": "specific",
        "downloadPath": "$(system.defaultWorkingDirectory)/_**.**-flexwerker/"
      },
      "type": "task",
      "reference": {
        "id": "a433f589-fce1-4460-9ee6-44a624aeb1fb",
        "name": "DownloadBuildArtifacts",
        "version": "0.188.3"
      },
      "condition": "succeeded()",
      "id": "a6408940-f2a9-5278-9d12-931ba8306153",
      "name": "DownloadBuildArtifacts1",
      "displayName": "Download artifact - _**.**-flexwerker - flexwerker"
    },
    {
      "inputs": {
        "buildType": "specific",
        "project": "5ef41df0-5696-4978-8592-8dbfba779500",
        "definition": "2",
        "specificBuildWithTriggering": "false",
        "buildVersionToDownload": "latest",
        "allowPartiallySucceededBuilds": "false",
        "branchName": "refs/heads/master",
        "buildId": "23",
        "tags": "",
        "downloadType": "single",
        "artifactName": "flexwerker",
        "itemPattern": "**",
        "downloadPath": "$(System.ArtifactsDirectory)",
        "parallelizationLimit": "8",
        "checkDownloadedFiles": "false",
        "retryDownloadCount": "4",
        "extractTars": "false"
      },
      "type": "task",
      "reference": {
        "id": "a433f589-fce1-4460-9ee6-44a624aeb1fb",
        "name": "DownloadBuildArtifacts",
        "version": "0.188.3"
      },
      "condition": "succeeded()",
      "id": "55c5a8f1-de2e-5ee8-e6ad-888a135388fa",
      "name": "DownloadBuildArtifacts2",
      "displayName": "Download Build Artifacts"
```

**Comment by jithurjacob** [comment]
I'm also facing the same issue. The agent is shown online in Deployment Groups and Release pipeline can successfully use the agent. But in agent pool the server is offline and build pipeline cannot allocate jobs to the server.

**Comment by alucardu** [comment]
@jithurjacob I haven't resolved my issue, but could it be a disk space issue? Could you check?

**Comment by jithurjacob** [comment]
@alucardu  - It was not a disk space issue. I have it for me by running another agent as a native installation. So currently in a server, I have a docker based agent running for Deployment Group and a native agent running for Self Hosted. The docker based agent is because of a certain requirement we are having in our systems.

**Comment by smariussorin** [comment]
We have the same error. Deployed to 4 different region VM and only 3 VM are online. Same have the version: 2.189.0

**Comment by anatolybolshakov** [comment]
Hi @alucardu @jithurjacob @smariussorin do you run the agent as a service? 
From the logs above - looks like agent falied with some i/0 error while trying to start and create log files - could you please make sure that users which is used to run agent has enough permissions to write them?

**Comment by alucardu** [comment]
I am running it as a service. Going to check the permissions Monday.

**Comment by alucardu** [comment]
For me it was a disc space issue. I removed some stuff and ran `sudo ./svc.sh status` which shows:

```
2021-08-02 08:36:41Z: Listening for Jobs
```

Still got to remove some more stuff, but `/dev/sda1` was at 100% when the agent crashed:

```
/dev/sda1       9.7G  9.1G   99M  99% /
```

and now on 99% the agent is up.

**Comment by anatolybolshakov** [comment]
@jithurjacob @smariussorin closing this one since it seems to be not related to the issue on agent side - please let us know if it's still actual for you.

**Comment by laschon** [comment]
Old thread, but the solution to my problem is not mentioned here, so I thought I should add it.

The issue for me was file system permission. I was installing the service using a service account. When I changed the ownership of the agent directory to the service account, all started working correctly.

`sudo chown -R name-of-account:root /path/to/agent/`

**Comment by vidizmouseraccount** [comment]
> Old thread, but the solution to my problem is not mentioned here, so I thought I should add it.
> 
> The issue for me was file system permission. I was installing the service using a service account. When I changed the ownership of the agent directory to the service account, all started working correctly.
> 
> `sudo chown -R name-of-account /path/to/agent/`

worked for me
