### ISSUE TITLE
New build cancels running build on Linux

### ISSUE THREAD

**Issue by stefan-muc** [microsoft/azure-pipelines-agent#3506]
## Agent Version and Platform
Version of your agent?
2.188.2

OS of the machine running the agent?
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)

## Azure DevOps Type and Version
on-premises Azure DevOps Server

If on-premises, which release?
Azure DevOps Server 2020 Update 1

## What's not working?
Queuing a build in one build pipeline cancels already running build pipeline (even of other pipelines, no matter of their pipeline/repo/trigger) on the same server

## Agent and Worker's Diagnostic Logs

Relevant Job output:
```
========================== Starting Command Output ===========================
##[debug]which '/usr/bin/bash'
##[debug]found: '/usr/bin/bash'
##[debug]/usr/bin/bash arg: --noprofile
##[debug]/usr/bin/bash arg: --norc
##[debug]/usr/bin/bash arg: /home/tfs-build/Builds/Agent-01/_temp/c7705dac-81c9-4594-8c2c-37fc4530da09.sh
##[debug]exec tool: /usr/bin/bash
##[debug]arguments:
##[debug]   --noprofile
##[debug]   --norc
##[debug]   /home/tfs-build/Builds/Agent-01/_temp/c7705dac-81c9-4594-8c2c-37fc4530da09.sh
/usr/bin/bash --noprofile --norc /home/tfs-build/Builds/Agent-01/_temp/c7705dac-81c9-4594-8c2c-37fc4530da09.sh
##[debug]Re-evaluate condition on job cancellation for step: 'Sleep 10 minutes'.
##[debug]Started cancellation of executing script
##[debug]Exit code null received from tool '/usr/bin/bash'
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
```

Logs of cancelled build:
[Worker_20210818-114527-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7007225/Worker_20210818-114527-utc.log)
[Agent_20210818-114522-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7007226/Agent_20210818-114522-utc.log)

Used _pipelines.yaml_:
```
trigger:
  - develop

jobs:
- job: Job1
  displayName: Job 1

  steps:
  - checkout: none

  - task: Bash@3
    displayName: 'Sleep 10 minutes'
    inputs:
      targetType: inline
      script: 'sleep 10m'

- job: Publish_Nothing
  displayName: Publish nothing
  pool: 'Productive-Build' # other server, just for reference

  dependsOn:
  - Job1
  condition: |
      eq(dependencies.Job1.result, 'Succeeded')

  steps:
  - checkout: none

  - task: Bash@3
    displayName: 'Say hello!'
    inputs:
      targetType: inline
      script: 'echo Hello World!'
```

Build pipeline runs basically look like this (from earlier tries we did, boiling down the problem):
![AzureLinuxCancelled](https://user-images.githubusercontent.com/544335/129903374-1ebacf37-518b-4a43-bf12-ec74f70af59a.png)

**Comment by meeces2911** [comment]
Same here - although all our agents are on Windows.
Also running On Prem - Azure DevOps 2020 Update 1.

Agent version: 2.190.0

**Comment by stefan-muc** [comment]
Last days we updated to agent version 2.191.1 and as far as we can tell this fixes the problem - although I can't see anything regarding this in the changelog.

@meeces2911 Maybe try to do an update?

**Comment by meeces2911** [comment]
Hmmm, unfortunately that didn't work for me.

My logs look very similar to yours through:
```
[2021-09-05 22:52:19Z INFO MessageListener] Message '7050' received from session '9376f6dc-199f-4720-842f-fd7866974c86'.
[2021-09-05 22:52:19Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2021-09-05 22:52:19Z INFO SelfUpdater] Version '2.170.1' of 'agent' package available in server.
[2021-09-05 22:52:19Z INFO SelfUpdater] Current running agent version is 2.191.1
[2021-09-05 22:52:19Z INFO Terminal] WRITE LINE: Downgrading agent to a lower version. This is usually due to a rollback of the currently published agent for a bug fix. To disable this behavior, set environment variable AZP_AGENT_DOWNGRADE_DISABLED=true before launching your agent.
[2021-09-05 22:52:19Z INFO SelfUpdater] An update is available.
[2021-09-05 22:52:19Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2021-09-05 22:52:20Z INFO Terminal] WRITE LINE: Downloading 2.170.1 agent
...
[2021-09-05 22:52:20Z INFO SelfUpdater] Attempt 1: save latest agent into D:\agent\_work\_update\agent1.zip.
[2021-09-05 22:52:20Z INFO SelfUpdater] Download agent: begin download
[2021-09-05 22:52:20Z WARN SelfUpdater] Failed to get package 'D:\agent\_work\_update\agent1.zip' from 'https://vstsagentpackage.azureedge.net/agent/2.170.1/vsts-agent-win-x64-2.170.1.zip'. Exception System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token)
```

After 3 failed attempts at downloading an older version, it finally shuts down the agent - which cancels the build(/release) :(
(The failed attempts are because of the firewall - not concerned with that - but weirdly the auto update agent option is turned off in the pool settings)

```
[2021-09-05 22:52:26Z ERR  Terminal] WRITE ERROR: An error occurred: Agent package 'D:\agent\_work\_update\agent1.zip' failed after 3 download attempts
[2021-09-05 22:52:26Z ERR  AgentProcess] System.Threading.Tasks.TaskCanceledException: Agent package 'D:\agent\_work\_update\agent1.zip' failed after 3 download attempts
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
```

I don't _seem_ to have the issue if I manually downgrade to 2.170.1... so might just have to stuck with that for a while

**Comment by TMattes** [comment]
In our environment, it turned out that switching off the auto-update option via the pool settings in the Web interface does not work; the only working option is to delete the not wanted versions from the application tier ProgramData folder.
The switch in the Web interface seems to be completely useless...

**Comment by anatolybolshakov** [comment]
Hi @stefan-muc the error says that the relevant agent package for linux-x64 platform was not found - you may probably need to update it manually as mentioned in [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops-2019&tabs=browser#can-i-update-my-v2-agents-that-are-part-of-an-azure-devops-server-pool).
@meeces2911 do you use on-prem or cloud solution? The error you see looks different from original...
@TMattes does the agent update still be triggered for you - even if you disable auto-update for agent pool?

**Comment by meeces2911** [comment]
@anatolybolshakov For the moment on-prem

**Comment by LonDat** [comment]
Hi,
we have same issue. 
DevOps server 18.181.31230.2 (Azure DevOps Server 2020 Update 1) and Agent 2.191.1 on-premise.
When we queue multiple pipelines builds for same agent, only the last one is done, the older are cancelled.
We had no issue until migration to DevOps 2020 Update 1 from DevOps 2019 and upgrade of agents on build machine.
I did clean re-installation of agents on DevOps server already, it's not helped.
To logs below, the whole pipeline success, if no pipeline in queue.

**Agent's log:**
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper] Starting process:
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   File name: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Arguments: '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'c:\Agent-zzz_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.180.1\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''c:\Agent-zzz_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.180.1\powershell.ps1'''))"'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Working directory: 'c:\Agent-zzz_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.180.1'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Persist current code page: 'True'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper] OOM score adjustment is Linux-only.
[2021-09-07 06:47:31Z INFO ProcessInvokerWrapper] Process started with process id 11364, waiting for process exit.
[2021-09-07 06:47:32Z INFO JobServerQueue] Try to append 1 batches web console lines for record '3bf3502e-92b5-4c31-9d8d-28c756617bb9', success rate: 1/1.
[2021-09-07 06:47:32Z INFO JobServerQueue] Try to append 1 batches web console lines for record '0d26ccea-09d6-5e2d-f76b-2fc1d1b3d039', success rate: 1/1.
[2021-09-07 06:47:32Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2021-09-07 06:47:33Z INFO JobServerQueue] Try to append 1 batches web console lines for record '0d26ccea-09d6-5e2d-f76b-2fc1d1b3d039', success rate: 1/1.
[2021-09-07 06:47:34Z INFO JobServerQueue] Try to append 1 batches web console lines for record '0d26ccea-09d6-5e2d-f76b-2fc1d1b3d039', success rate: 1/1.
[2021-09-07 06:47:42Z INFO Worker] Cancellation/Shutdown message received.
[2021-09-07 06:47:42Z INFO ExpressionManager] Evaluating: succeeded()
[2021-09-07 06:47:42Z INFO ExpressionManager] Result: False
[2021-09-07 06:47:42Z INFO StepsRunner] Cancel current running step.
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] Sending CTRL_C to process 11364.
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] Successfully sent CTRL_C to process 11364.
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] Waiting for process exit or 7.5 seconds after CTRL_C signal fired.
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] Ignore Ctrl+C to current process.
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] Exited process 11364 with exit code 1
[2021-09-07 06:47:42Z INFO ProcessInvokerWrapper] Finished process 11364 with exit code 1, and elapsed time 00:00:10.7707449.

**Build's log:**
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'c:\Agent-zzz_work\_temp\e1eaed8f-9efd-4f12-9113-b197360e217d.ps1'"
##[debug]Re-evaluate condition on job cancellation for step: 'Connect to Agent's central repository'.
##[debug]Leaving Invoke-VstsTool.
##[debug]Leaving C:\Agent-zzz_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.180.1\powershell.ps1.
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: Connect to Agent's central repository

**Comment by Resident-Alien** [comment]
We have this issue as well but it is not limited to the agent, server or pool. It would appear that builds and releases will cause the cancelling of running releases. Even if the release is running on windows agent 1 and then a build runs on linux agent 2 the release running on windows agent 1 gets cancelled. It does not happen all the time but happens a lot. We tried new agents in new pools but that did not fix it. We have 19 projects and hundreds of builds and releases, some of which are scheduled or set with CI/CD, and others manual. Having a release cancel just because someone else submits a commit and a build kicks off is really annoying.

This feels more like a ADO server issue than an agent issue, but this is the first place I have seen someone report the same issue.

2021-09-08T16:46:28.2438454Z ##[error]The operation was canceled.

**Comment by anatolybolshakov** [comment]
Hi everyone, just as a quick update - at this moment this seems to be related to server side - since cancellation request comes to agent from server, and agent simply executes it.
Could you please create ticket on [developer community](https://developercommunity.visualstudio.com/search?space=22) to get right eyes on it?

**Comment by LonDat** [comment]
Hi,
thanks a lot. I find out, the bug exists there already.
https://developercommunity.visualstudio.com/t/The-operation-was-canceled/1479740?space=22&q=cancel

**Comment by anatolybolshakov** [comment]
Let me close this ticket here currently since it does not seem to be related to the agent itself.
