### ISSUE TITLE
gitVersion detection on checkout randomly fails

### ISSUE THREAD

**Issue by ralfdamaschkehiq** [microsoft/azure-pipelines-agent#3515]
## Agent Version and Platform
2.187.2, on Red Hat Enterprise Linux 7.9

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
All checkout steps in our pipelines fail about half of the time with the error: Value cannot be null. (Parameter 'gitVersion')
The rest of the time, they correctly manage to detect the git version as 2.32.0 and then complete without problems. We have not been able to determine any pattern in when the git version fetching fails, it seems entirely random. Rerunning the failed jobs normally fixes the problem, but it's a major impediment since it happens so frequently.

This seems very similar to issue [1627](https://github.com/microsoft/azure-pipelines-agent/issues/1627).

The log extract below is with system.debug = true. Please note that the UnauthorizedAccessException often occurs even when the git version retrieval works and then the checkout steps completes despite it.

## Agent and Worker's Diagnostic Logs
```
##[debug]Evaluating condition for step: 'Checkout ***'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Checkout ***
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
##[debug]Processed: ##vso[plugininternal.updaterepositorypath alias=self;]***
##[debug]Repository requires to be placed at '***', current location is '***'
Syncing repository: *** (Git)
##[debug]repository url=***
##[debug]targetPath=***
##[debug]sourceBranch=***
##[debug]sourceVersion=a6b4d4c984c452f1dc2e2a4b3702036f261f4ddd
##[debug]clean=True
##[debug]checkoutSubmodules=False
##[debug]checkoutNestedSubmodules=False
##[debug]exposeCred=False
##[debug]fetchDepth=1
##[debug]gitLfsSupport=False
##[debug]acceptUntrustedCerts=False
##[debug]schannelSslBackend=False
##[debug]Which: 'git'
##[debug]Location: '{matches.First()}'
##[debug]Get git version.
git version
##[debug]Starting process:
##[debug]  File name: '/usr/local/bin/git'
##[debug]  Arguments: 'version'
##[debug]  Working directory: '***'
##[debug]  Require exit code zero: 'False'
##[debug]  Encoding web name:  ; code page: ''
##[debug]  Force kill process on cancellation: 'False'
##[debug]  Redirected STDIN: 'False'
##[debug]  Persist current code page: 'False'
##[debug]  Keep redirected STDIN open: 'False'
##[debug]  High priority process: 'False'
##[debug]Failed to update oom_score_adj for PID: 14582.
##[debug]Exited process 14582 with exit code 0
##[debug]System.UnauthorizedAccessException: Access to the path '/proc/14582/oom_score_adj' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
##[debug]Process started with process id 14582, waiting for process exit.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Finished process 14582 with exit code 0, and elapsed time 00:00:06.7745311.

##[error]Value cannot be null. (Parameter 'gitVersion')
##[debug]Processed: ##vso[task.logissue type=error;]Value cannot be null. (Parameter 'gitVersion')
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]STDOUT/STDERR stream read finished.
##[debug]   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtil.NotNull(Object value, String name)
   at Agent.Plugins.Repository.GitCliManager.LoadGitExecutionInfo(AgentTaskPluginExecutionContext context, Boolean useBuiltInGit)
   at Agent.Plugins.Repository.GitSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
```

**Comment by kuleshovilya** [comment]
Hello @ralfdamaschkehiq Could you please provide agent logs for the failed job?

**Comment by ralfdamaschkehiq** [comment]
Hi @kuleshovilya, here you go: [Worker_20210825-143428-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7090581/Worker_20210825-143428-utc.log)

**Comment by kuleshovilya** [comment]
Yeah, it doesn't seem as agent issue so far. Both Pipeline and Agent logs both point to permission issue with process. 
Does agent run in container?

**Comment by ralfdamaschkehiq** [comment]
No, it runs on an Azure virtual machine.

**Comment by kuleshovilya** [comment]
I'd say it looks more like:
https://unix.stackexchange.com/questions/297190/owner-cant-read-proc-pid-io

And more of a system issue. You could try to reinstall agent, clean cash, update OS and packet manager etc 
Basic troubleshooting might help with that. That seems like recurring issue with a lot of CentOS\RedHat distros.
Since this is not an agent issue, I'll close it for now.
You can reopen it, if needed or ping me at v-ikuleshov@microsoft.com
