### ISSUE TITLE
GetSources on a classic pipeline fails to find git executable on Ubuntu agent

### ISSUE THREAD

**Issue by msglueck** [microsoft/azure-pipelines-agent#3547]
## Have you tried troubleshooting?
Yes, I have. Tried adding a bash task to install it, but it fails before. Added a `sudo apt-get install git -y` on the node with custom data and user data. but doesn't help

## Agent Version and Platform
2.192.0

OS of the machine running the agent?
Ubuntu 20.04 Minimal VMs

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? 
oasisEA

## What's not working?
Pipeline run is failing to do the initial source checkout due to missing git exectuable.

```
2021-09-27T10:31:32.1796514Z ##[debug]Evaluating condition for step: 'Checkout infrastructure@master to s'
2021-09-27T10:31:32.1798214Z ##[debug]Evaluating: SucceededNode()
2021-09-27T10:31:32.1798679Z ##[debug]Evaluating SucceededNode:
2021-09-27T10:31:32.1799538Z ##[debug]=> True
2021-09-27T10:31:32.1800094Z ##[debug]Result: True
2021-09-27T10:31:32.1800714Z ##[section]Starting: Checkout infrastructure@master to s
2021-09-27T10:31:32.1804507Z ==============================================================================
2021-09-27T10:31:32.1804804Z Task         : Get sources
2021-09-27T10:31:32.1805070Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2021-09-27T10:31:32.1805340Z Version      : 1.0.0
2021-09-27T10:31:32.1805527Z Author       : Microsoft
2021-09-27T10:31:32.1806296Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2021-09-27T10:31:32.1806653Z ==============================================================================
2021-09-27T10:31:33.2523881Z ##[debug]Processed: ##vso[plugininternal.updaterepositorypath alias=__designer_repo;]/agent/_work/1/s
2021-09-27T10:31:33.2528513Z ##[debug]Repository requires to be placed at '/agent/_work/1/s', current location is '/agent/_work/1/s'
2021-09-27T10:31:33.3504961Z Syncing repository: infrastructure (Git)
2021-09-27T10:31:33.3595922Z ##[debug]repository url=https://****@dev.azure.com/****/infrastructure/_git/infrastructure
2021-09-27T10:31:33.3598824Z ##[debug]targetPath=/agent/_work/1/s
2021-09-27T10:31:33.3600770Z ##[debug]sourceBranch=refs/heads/master
2021-09-27T10:31:33.3602956Z ##[debug]sourceVersion=2164b4c789c9edfaae8206f29b8a0e1a9485738a
2021-09-27T10:31:33.3605250Z ##[debug]clean=False
2021-09-27T10:31:33.3607360Z ##[debug]checkoutSubmodules=False
2021-09-27T10:31:33.3665166Z ##[debug]checkoutNestedSubmodules=False
2021-09-27T10:31:33.3667364Z ##[debug]exposeCred=True
2021-09-27T10:31:33.3670349Z ##[debug]fetchDepth=1
2021-09-27T10:31:33.3672235Z ##[debug]gitLfsSupport=False
2021-09-27T10:31:33.3674461Z ##[debug]acceptUntrustedCerts=False
2021-09-27T10:31:33.3676639Z ##[debug]schannelSslBackend=False
2021-09-27T10:31:33.3867177Z ##[debug]Which: 'git'
2021-09-27T10:31:33.4139744Z ##[debug]Not found.
2021-09-27T10:31:33.4443023Z ##[error]File not found: 'git'
2021-09-27T10:31:33.4606557Z ##[debug]Processed: ##vso[task.logissue type=error;]File not found: 'git'
2021-09-27T10:31:33.4617132Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2021-09-27T10:31:33.4743479Z ##[debug]   at Microsoft.VisualStudio.Services.Agent.Util.WhichUtil.Which(String command, Boolean require, ITraceWriter trace)
   at Agent.Plugins.Repository.GitCliManager.LoadGitExecutionInfo(AgentTaskPluginExecutionContext context, Boolean useBuiltInGit)
   at Agent.Plugins.Repository.GitSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
2021-09-27T10:31:33.4927196Z ##[section]Finishing: Checkout infrastructure@master to s
```

**Comment by msglueck** [comment]
ok, found a workaround: using Ubuntu 20.04 FULL works, since git is preinstalled.

**Comment by tatyana-kostromskaya** [comment]
Hi, @msglueck is you issue resolved now? If "yes", could I close this ticket?

**Comment by msglueck** [comment]
Would have liked to use the minimal image, but I can also live with the full image.
