### ISSUE TITLE
Download Artifact step returning "Authentication Required" on local servers

### ISSUE THREAD

**Issue by pmcconnell3** [microsoft/azure-pipelines-agent#3595]
### Agent Version and Platform

2.193.0 (and 2.194.0), Windows server 2012 R2 web servers.

### Azure DevOps Type

dev.azure.com

### What's not working?

Our Azure agent recently stopped working. We have been using Azure release pipelines for continuous deployment of an IIS application. It gives us a very non-descript "Authentication required" error. We noticed this on 10/13/2021. At the time that the error started, I believe we were on version 2.193.0. We are now on 2.194.0 and the issue is still occurring. To ensure it wasn't something with our Azure configuration, I tested this on both my work PC (on our network) and on my home PC (off network) and it worked in both places.  Therefore, it seems to only happen on our on-network servers.

This may possibly be related to https://github.com/microsoft/azure-pipelines-agent/issues/3583, however we haven't been able to tie it to a proxy issue and there are no firewall blocks occurring. We have also tried uninstalling the agents, as well as completely removing all of our Azure configuration and doing it from scratch and we get the same error.

![image](https://user-images.githubusercontent.com/93608560/139910941-2e0a2960-074e-4480-ae44-1aed6e7b8b52.png)

### Agent Diagnostic Logs

2021-10-18T20:44:18.1399175Z ##[debug]Evaluating condition for step: 'Download artifact - _myproject - _myproject'
2021-10-18T20:44:18.1439702Z ##[debug]Evaluating: succeeded()
2021-10-18T20:44:18.1445026Z ##[debug]Evaluating succeeded:
2021-10-18T20:44:18.1483132Z ##[debug]=> True
2021-10-18T20:44:18.1491321Z ##[debug]Result: True
2021-10-18T20:44:18.1532198Z ##[section]Starting: Download artifact - _myproject - _myproject
2021-10-18T20:44:18.1961448Z ==============================================================================
2021-10-18T20:44:18.1961906Z Task         : Download pipeline artifact
2021-10-18T20:44:18.1962269Z Description  : Download a named artifact from a pipeline to a local path
2021-10-18T20:44:18.1962470Z Version      : 1.2.5
2021-10-18T20:44:18.1962782Z Author       : Microsoft Corporation
2021-10-18T20:44:18.1963334Z Help         : Download a named artifact from a pipeline to a local path
2021-10-18T20:44:18.1963578Z ==============================================================================
2021-10-18T20:44:18.4789044Z Download from the specified build: #2263
2021-10-18T20:44:18.4791191Z Download artifact to: D:\azagent\myproject\_work\r1\a/_myproject/_myproject
2021-10-18T20:44:18.8728223Z Verbose, [CreateDedupManifestClientAsync] Try 1/5, retryable exception caught. Retrying in 00:00:01. Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Authentication Required
2021-10-18T20:44:18.8729052Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
2021-10-18T20:44:18.8729972Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
2021-10-18T20:44:18.8730690Z    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
2021-10-18T20:44:18.8731302Z    at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
2021-10-18T20:44:18.8731978Z    at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
2021-10-18T20:44:18.8732555Z    at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
2021-10-18T20:44:18.8733094Z    at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
2021-10-18T20:44:18.8733663Z    at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.CheckForServerUpdatesAsync(CancellationToken cancellationToken)
2021-10-18T20:44:18.8734201Z    at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.FindServiceDefinitionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
2021-10-18T20:44:18.8734958Z    at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.LocationForCurrentConnectionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
2021-10-18T20:44:18.8735519Z    at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
2021-10-18T20:44:18.8736036Z    at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
2021-10-18T20:44:18.8736631Z    at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
2021-10-18T20:44:18.8737255Z    at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
2021-10-18T20:44:18.8738854Z    at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
2021-10-18T20:44:18.8739525Z    at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
2021-10-18T20:44:18.8739923Z    at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
2021-10-18T20:44:18.8740372Z    at Microsoft.VisualStudio.Services.Agent.Blob.DedupManifestArtifactClientFactory.<>c__DisplayClass2_0.<CreateDedupManifestClientAsync>b__0()
2021-10-18T20:44:18.8740847Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
2021-10-18T20:44:18.8741215Z Verbose, Details:
2021-10-18T20:44:18.8741600Z No LastRequestResponse on exception VssServiceResponseException: Authentication Required
2021-10-18T20:44:19.9351139Z Verbose, [CreateDedupManifestClientAsync] Try 2/5, retryable exception caught. Retrying in 00:00:02.0448362. Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Authentication Required
(Log entries repeat up to 5 attempts)
2021-10-18T20:44:47.8952887Z ##[section]Finishing: Download artifact - _myproject - _myproject

**Comment by pmcconnell3** [comment]
I am closing this, we have discovered the issue. dev.azure.com got removed from our list of trusted sites on these servers.
