### ISSUE TITLE
Agent Pool stays online only for 60 minutes

### ISSUE THREAD

**Issue by rockrilvas** [microsoft/azure-pipelines-agent#3626]
## Having issue with YAML?
Please log an issue at [Azure-Pipelines-YAML](https://github.com/Microsoft/azure-pipelines-yaml). Over there we discuss YAML templates, samples for Azure Pipelines, and designs for upcoming YAML features. Also a place for the community to share best practices, ideas, and so on. File suggestions and issues here if they're specific to YAML pipelines.

## Having issue with Tasks?
NO.

## Having issue with software on Hosted Agent?
NO.

## Having generic issue with Azure-Pipelines/VSTS/TFS?
NO.

## Have you tried troubleshooting?
NOT APPLICABLE.

## Agent Version and Platform
Version of your agent? 
2.195.0
https://vstsagentpackage.azureedge.net/agent/2.195.0/vsts-agent-linux-arm64-2.195.0.tar.gz

OS of the machine running the agent? 
Ubuntu 20.4.3 LTS ARM64 (using raspberry pi)

## Azure DevOps Type and Version
visualstudio.com

## What's not working?
I am able to install the agent as should be, but after 60 minutes the agent goes goes to off-line, I have tried many steps in order to find out the route cause, I was using Deployment Groups and now I am using Agent Pool, in both cases I got the same situation.
I am almost 100% sure that proxy is not working as should be and another details I got the error below at logs.

########################################################################################
[2021-11-23 18:55:29Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/onsite/DevopsCloudAgent/.credentials_rsaparams
[2021-11-23 18:55:29Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/onsite/DevopsCloudAgent/.credentials_rsaparams
[2021-11-23 18:55:30Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2021-11-23 18:55:31Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-11-23 18:55:31Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-11-23 18:55:31Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-11-23 18:55:31Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2021-11-23 18:55:31Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-11-23 18:55:32Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-11-23 18:55:32Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-11-23 18:55:33Z INFO MessageListener] VssConnection created
[2021-11-23 18:55:33Z INFO MessageListener] Session created.
[2021-11-23 18:55:33Z INFO Terminal] WRITE LINE: 2021-11-23 18:55:33Z: Listening for Jobs
[2021-11-23 18:55:33Z INFO JobDispatcher] Set agent/worker IPC timeout to 30 seconds.
[2021-11-23 19:25:48Z INFO MessageListener] No message retrieved from session '.....................................................................................' within last 30 minutes.
[2021-11-23 19:50:59Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/f25493ae-1c98-41d7-8a33-0be75f5fe603, Basic realm="https://.................visualstudio.com/", TFS-Federated
X-TFS-ProcessId: c7fadefb-b0aa-4dbe-9ae5-12ae0fc4ac34
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: ...........................................................
X-TFS-Session: ...........................................................
X-VSS-E2EID: ...........................................................
X-VSS-SenderDeploymentId: ...........................................................
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://..............visualstudio.com/
X-TFS-FedAuthIssuer: https://...............visualstudio.com/
X-VSS-AuthorizationEndpoint: https://..........vssps.visualstudio.com/
X-VSS-ResourceTenant: ...........................................................
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://.................visualstudio.com/_signin?realm=................com&reply_to=https%3A%2F%2F................visualstudio.com%2F_apis%2Fdistributedtask%2Fpools%2F39%2Fmessages%3FsessionId%3Da7fc7d44-ee44-4f75-980b-8b46fde1e7e2&redirect=1&hid=3a2af3a4-452a-4933-86ad-3b24f0c19df0&context=eyJodCI6MiwiaGlkIjoiMDhjNzc5NjEtZGQ5My00NmJmLWE4YjktN2ZjOTE0MWNmNWU5IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
Request-Context: appId=cid-v1:1d01aa00-5a22-493d-8bc0-acd0af8f839d
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: B6AAA9DF91AB43DB9C6C00EC475EDC2B Ref B: SAO03EDGE0811 Ref C: 2021-11-23T19:50:59Z
Date: Tue, 23 Nov 2021 19:50:59 GMT
########################################################################################

**Comment by rockrilvas** [comment]
It is requiring authentication, how can I solve this and set it automatically, otherwise the agent goes offline every 60 minutes?
Thank you!

----------------------------------------------------------------------------------------------------------------------------
[2021-11-24 15:16:50Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-11-24 15:16:51Z ERR  VisualStudioServices] GET request to https://.............................................-infra.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=100261929&lastChangeId64=100261929 failed. HTTP Status: ProxyAuthenticationRequired
[2021-11-24 15:16:51Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-11-24 15:16:51Z INFO AgentServer] Catch exception during connect. 1 attempt left.
[2021-11-24 15:16:51Z ERR  AgentServer] Microsoft.VisualStudio.Services.WebApi.ProxyAuthenticationRequiredException: SP324097: Your network proxy requires authentication.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
[2021-11-24 15:16:51Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-11-24 15:16:52Z ERR  VisualStudioServices] GET request to https://..........................................visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=100261929&lastChangeId64=100261929 failed. HTTP Status: ProxyAuthenticationRequired
[2021-11-24 15:16:52Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2021-11-24 15:16:52Z ERR  MessageListener] Catch exception during create session.
[2021-11-24 15:16:52Z ERR  MessageListener] Microsoft.VisualStudio.Services.WebApi.ProxyAuthenticationRequiredException: SP324097: Your network proxy requires authentication.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.ConnectAsync(Uri serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.CreateSessionAsync(CancellationToken token)
[2021-11-24 15:16:52Z INFO MessageListener] Retriable exception: SP324097: Your network proxy requires authentication.
[2021-11-24 15:16:52Z INFO MessageListener] Sleeping for 30 seconds before retrying.

**Comment by rockrilvas** [comment]
Hello, any update?

Thank you!

**Comment by anatolybolshakov** [comment]
Hey @rockrilvas please check the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows) for agent set up behind the proxy.

**Comment by anatolybolshakov** [comment]
@rockrilvas is this issue still actual for you? Were you able to pass proxy settings to the agent?

**Comment by anatolybolshakov** [comment]
Hi @rockrilvas I'm closing this due to inactivity at the moment - please let us know if you have any further questions regarding proxy set up for the pipeline agent.

**Comment by tobiasz-gleba** [comment]
I have the same problem, I've tried setting up variables by `export` command, .env file and ./config.sh arguments.
My agent is in version `linux-x64-2.217.2`
