### ISSUE TITLE
Path incorrect during build action/task

### ISSUE THREAD

**Issue by arunprakashn** [microsoft/azure-pipelines-agent#3674]
When trying to build, the path for finding a nuget package URL is incorrect.

```
##[error]EXEC(0,0): Error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Agent-2\_ork\17\s\Source\Platform.IHC.OHS\bin\x64\Release\Microsoft.IdentityModel.Tokens.dll'.

```
If you notice, instead of "_work" in the path, it is "_ork", w - letter is missing. It is strange.

Full Error
```
EXEC : error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Agent-2\_ork\17\s\Source\Platform.IHC.OHS\bin\x64\Release\Microsoft.IdentityModel.Tokens.dll'. [C:\Agent-2\_work\17\s\Installer\Platform.IHC.OHC.InstallAction\Platform.IHC.OHS.InstallAction.csproj]
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.File.GetAttributes(String path)
     at Microsoft.Deployment.Compression.ArchiveFileStreamContext.OpenFileReadStream(String path, FileAttributes& attributes, DateTime& lastWriteTime)
     at Microsoft.Deployment.Compression.Cab.CabPacker.Pack(IPackStreamContext streamContext, IEnumerable`1 files, Int64 maxArchiveSize)
     at Microsoft.Deployment.Compression.Cab.CabEngine.Pack(IPackStreamContext streamContext, IEnumerable`1 files, Int64 maxArchiveSize)
     at Microsoft.Deployment.Compression.CompressionEngine.Pack(IPackStreamContext streamContext, IEnumerable`1 files)
     at Microsoft.Deployment.Compression.ArchiveInfo.PackFileSet(String sourceDirectory, IDictionary`2 fileNames, CompressionLevel compLevel, EventHandler`1 progressHandler)
     at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.PackInputFiles(String outputFile, IDictionary`2 fileMap)
     at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Build(String output, String sfxdll, IList`1 inputs, TextWriter log)
     at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Main(String[] args)

```

**Comment by max-zaytsev** [comment]
Hi @arunprakashn, What version of the agent are you using?  Could you please provide some repro steps?

**Comment by arunprakashn** [comment]
Agent Version is 2.189.

I have a Wix installer Project that actually uses the dlls generated by the main project. Also at time, the letter "A" goes missing as shown below, it should be "Agent" after the drive C:\

```
##[error]EXEC(0,0): Error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\gent-1\_work\2\s\Source\Platform.IHC.OHS\bin\x64\Release\Microsoft.IdentityModel.Logging.dll'.

```

**Comment by arunprakashn** [comment]
The solution builds fine in my laptop.

**Comment by max-zaytsev** [comment]
@arunprakashn 
Could you please provide a minimal reproducible project, YAML of the affected pipeline, and share the full raw log of the affected job (with enabled "Enable system diagnostic")?

**Comment by arunprakashn** [comment]
@max-zaytsev : Thank you for your quick action. Looks like I may need some time to get a trim-down version of the code since the actual codebase contains proprietary information. It appears like there is a known issue with MSBuild already with regards to the location/path. Would you please be able to confirm that there are no issues with azure build pipelines in relation to lengthy directory/file paths?

Another user reported the same error that I have reported, in another issue thread:
https://github.com/wixtoolset/issues/issues/4688

Appreciate your help in this regards !

**Comment by max-zaytsev** [comment]
@arunprakashn 
It doesn't seem like an agent issue to me. So I'm closing this ticket.
If you still have problems, please reopen the issue with more details to reproduce.

Also, there is a good place to ask general questions about azure devops pipelines - https://developercommunity.visualstudio.com/search?space=21

Thanks!
