### ISSUE TITLE
Installation of agent on CentOS 7.9 failed - The SSL connection could not be established

### ISSUE THREAD

**Issue by LiangZugeng** [microsoft/azure-pipelines-agent#3713]
## Agent Version and Platform
vsts-agent-linux-x64-2.196.2.tar.gz

## OS of the machine running the agent? OSX/Windows/Linux/...
CentOS 7.9

## Azure DevOps Type and Version
dev.azure.com

## Organization name
https://dev.azure.com/ocsmarter

## What's not working?
When deploying the environment agent using the script obtained from the Environment Add Resource tab as below.
```
mkdir azagent;cd azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.196.2/vsts-agent-linux-x64-2.196.2.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x "$(command -v systemctl)" ]; then ./config.sh --environment --environmentname "UAT" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/ocsmarter/ --work _work --projectname 'xmitg-tianyan' --auth PAT --token ????? --runasservice; sudo ./svc.sh install; sudo ./svc.sh start; else ./config.sh --environment --environmentname "UAT" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/ocsmarter/ --work _work --projectname 'xmitg-tianyan' --auth PAT --token ?????; ./run.sh; fi
```

## Diagnostic Logs
```
[2022-01-23 13:13:08Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2022-01-23 13:13:08Z INFO ConfigurationManager] Diagnostic data for request:
[SSL Policy Errors]
RemoteCertificateChainErrors: ChainStatus has returned a non empty array
[HttpRequest]
Requested URI: https://dev.azure.com/ocsmarter/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1
Request method: GET
[HttpRequestHeaders]
X-TFS-Session: 2a3cf841-6cef-4345-a401-6eaf19ee7225
X-VSS-E2EID: 44a6b190-594a-4df6-a56f-e033ba8fb163
User-Agent: VSServices/16.196.31911.0, (NetStandard; Linux 5.4.115-1.el7.elrepo.x86_64 #1 SMP Tue Apr 27 17:21:57 EDT 2021), VstsAgentCore-linux-x64/2.196.2, (Linux 5.4.115-1.el7.elrepo.x86_64 #1 SMP Tue Apr 27 17:21:57 EDT 2021)
[Certificate]
Effective date: 2021-11-10 上午12:14:27
Expiration date: 2022-11-10 上午12:14:27
Issuer: CN=Microsoft RSA TLS CA 02, O=Microsoft Corporation, C=US
Subject: CN=dev.azure.com

[2022-01-23 13:13:08Z ERR  VisualStudioServices] GET request to https://dev.azure.com/ocsmarter/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2022-01-23 13:13:08Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2022-01-23 13:13:08Z INFO LocationServer] Unable to connect to https://dev.azure.com/ocsmarter/.
[2022-01-23 13:13:08Z ERR  LocationServer] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
[2022-01-23 13:13:08Z INFO CommandSettings] Flag 'unattended': 'False'
```

I checked similar issues others posted in this repo, could not find a proper solution, please suggest how I should proceed to the troubleshooting next? Thanks.

**Comment by LiangZugeng** [comment]
curl https://dev.azure.com returned a correct result.

The result of `openssl s_client -connect dev.azure.com:443 -showcerts' is
```
openssl s_client -connect dev.azure.com:443 -showcerts
CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft RSA TLS CA 02
verify return:1
depth=0 CN = dev.azure.com
verify return:1
---
Certificate chain
 0 s:/CN=dev.azure.com
   i:/C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 02
-----BEGIN CERTIFICATE-----
MIIIkDCCBnigAwIBAgITfwAc6BoUPu97eyCVpQAAABzoGjANBgkqhkiG9w0BAQsF
ADBPMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
MSAwHgYDVQQDExdNaWNyb3NvZnQgUlNBIFRMUyBDQSAwMjAeFw0yMTExMDkxNjE0
MjdaFw0yMjExMDkxNjE0MjdaMBgxFjAUBgNVBAMTDWRldi5henVyZS5jb20wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCbx1+vI2dSStbrgJZ373V8Djmv
IouI15NNISvp44y64rpwklaV8nQ1/SILnNrdbThA0yJ9A/28h3G3E+K1KbVKHHC5
NNbb4zt1raaLZA5XrufelH/Aew04pcQnWtCWcwZ/7JHWgp3RJBzdzcSTrocvfMCM
EOFIRWpVFSi1jjnNVCEI8zOJXtlaWZZ4Ji4bTTknNBYUpQDZkycbywSJ7EmKOBw9
Ac0pfY5iDpsut+XSGTQASdaywuo0hDNpY8eBhl75iinC/c0gC8xUeaXWVdaQksUk
aG0jEqK8yH5AEa3AAM5B3izZdFWSVQf6rwHRV6HQCJNaxnCJgVDWmjc9Dd+pAgMB
AAGjggSaMIIEljCCAX4GCisGAQQB1nkCBAIEggFuBIIBagFoAHUARqVV63X6kSAw
taKJafTzfREsQXS+/Um4havy/HD+bUcAAAF9BYPtgAAABAMARjBEAiBGHS8Mlyq0
qdo+hqn99auSbYknu7zwSFw0Hnwb3z/yKgIgZTU8CGjZlwIsmIEJJ35xMdCKCrQ/
k5/6NV20dRlTWuQAdwBByMqx3yJGShDGoToJQodeTjGLGwPr60vHaPCQYpYG9gAA
AX0Fg+9vAAAEAwBIMEYCIQCOCz03TMI6DdnrDIQXSPMD5zezmp6urZXVTYfKsvMh
WwIhAMhFoqebJ8rBVJpuPLuawgjn5HgB3Riz44JDiTaoCxBNAHYAKXm+8J45OSHw
VnOfY6V35b5XfZxgCvj5TV0mXCVdx4QAAAF9BYPtrwAABAMARzBFAiEA+tX1kjvW
45REEstSzv39mY17qVStUR7SHENt095HFAACIFcHDn+VU3Pf9oHXHsrGAVaUIEdr
x4c574EApA01AsHjMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwEwCgYIKwYB
BQUHAwIwPgYJKwYBBAGCNxUHBDEwLwYnKwYBBAGCNxUIh9qGdYPu2QGCyYUbgbWe
YYX062CBXYWGjkGHwphQAgFkAgEnMIGHBggrBgEFBQcBAQR7MHkwUwYIKwYBBQUH
MAKGR2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvbXNjb3JwL01pY3Jvc29m
dCUyMFJTQSUyMFRMUyUyMENBJTIwMDIuY3J0MCIGCCsGAQUFBzABhhZodHRwOi8v
b2NzcC5tc29jc3AuY29tMB0GA1UdDgQWBBSGPyezf8d4W7CCCfRRD0QFouJcRjAO
BgNVHQ8BAf8EBAMCBLAwgaMGA1UdEQSBmzCBmIINZGV2LmF6dXJlLmNvbYIPKi5k
ZXYuYXp1cmUuY29tghBkZXZwcGUuYXp1cmUuY29tghIqLmRldnBwZS5henVyZS5j
b22CEGRldm9wcy5henVyZS5jb22CEiouZGV2b3BzLmF6dXJlLmNvbYITZGV2b3Bz
cHBlLmF6dXJlLmNvbYIVKi5kZXZvcHNwcGUuYXp1cmUuY29tMIGwBgNVHR8Egagw
gaUwgaKggZ+ggZyGTWh0dHA6Ly9tc2NybC5taWNyb3NvZnQuY29tL3BraS9tc2Nv
cnAvY3JsL01pY3Jvc29mdCUyMFJTQSUyMFRMUyUyMENBJTIwMDIuY3JshktodHRw
Oi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9jcmwvTWljcm9zb2Z0JTIw
UlNBJTIwVExTJTIwQ0ElMjAwMi5jcmwwVwYDVR0gBFAwTjBCBgkrBgEEAYI3KgEw
NTAzBggrBgEFBQcCARYnaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9tc2Nv
cnAvY3BzMAgGBmeBDAECATAfBgNVHSMEGDAWgBT/L3/hBvQ48y3tJY2Ywv4O9mz8
+jAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQAD
ggIBAFfA0ojBL/fdBS45O/oC+nzUdHzPicG7yo1asMMNxosQV0WuWx6YYAzQr/XG
Mt7VM6wjbgG1T3tCSBL7/GcaIXB+EyrHhWWgsuPEI/VN8GA9mVQe67CT4r3MSXYf
lEaFpZaLW79vFNmyyiG6cJO8EGf2bgucVb+ZBrjDBHQgkU+zAcMxfAi1HWkATBw4
OSfKchcsl8jQJq10h07DgN5LO0Odgpxtud5wqPrPOjnv0z7yWvhvjhNWhqg3r1KR
6Pi/fb31tqwhvcHTA4P6yQq8i+imYv0fOkj04TEIf8Sc6Gi5KfD64L72JvW4/Tl0
DSUs2I4LQCuWFt4eY2/f0+6mqp5Bji3fHEztxDwfwB1nm57fn7P1ux3SxQjaj+Na
Z3GpfHnISU/waGxvQNlW6nl9cKZvFpWw/nb+cxQhTz/g3m5Z4PUoHpjrUtUOiuuA
YsgRss3/FeVYl/ojHTecwNx5+dKEG/nseVsNj6RpaY66GmJasiPLSonTeZKrhnJi
4aoiYemXUX/G3D1LtwUfxRjuID81WXsk6j3QIVHoZDhPH5vUWDYd3YDBBeZvMQnL
olMhcvFl1ShSVrNl+II8rBNMhTX4GDxtjXjDa/LJp3MjnUC+e53/S4pa/znXEYr5
sspuKYBrfUx5OxkPzT3kGojHDpebZeTuX26aRF0B8BgCfa+G
-----END CERTIFICATE-----
 1 s:/C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 02
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
-----BEGIN CERTIFICATE-----
MIIFWjCCBEKgAwIBAgIQD6dHIsU9iMgPWJ77H51KOjANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJl
clRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTIw
MDcyMTIzMDAwMFoXDTI0MTAwODA3MDAwMFowTzELMAkGA1UEBhMCVVMxHjAcBgNV
BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEgMB4GA1UEAxMXTWljcm9zb2Z0IFJT
QSBUTFMgQ0EgMDIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQD0wBlZ
qiokfAYhMdHuEvWBapTj9tFKL+NdsS4pFDi8zJVdKQfR+F039CDXtD9YOnqS7o88
+isKcgOeQNTri472mPnn8N3vPCX0bDOEVk+nkZNIBA3zApvGGg/40Thv78kAlxib
MipsKahdbuoHByOB4ZlYotcBhf/ObUf65kCRfXMRQqOKWkZLkilPPn3zkYM5GHxe
I4MNZ1SoKBEoHa2E/uDwBQVxadY4SRZWFxMd7ARyI4Cz1ik4N2Z6ALD3MfjAgEED
woknyw9TGvr4PubAZdqU511zNLBoavar2OAVTl0Tddj+RAhbnX1/zypqk+ifv+d3
CgiDa8Mbvo1u2Q8nuUBrKVUmR6EjkV/dDrIsUaU643v/Wp/uE7xLDdhC5rplK9si
NlYohMTMKLAkjxVeWBWbQj7REickISpc+yowi3yUrO5lCgNAKrCNYw+wAfAvhFkO
eqPm6kP41IHVXVtGNC/UogcdiKUiR/N59IfYB+o2v54GMW+ubSC3BohLFbho/oZZ
5XyulIZK75pwTHmauCIeE5clU9ivpLwPTx9b0Vno9+ApElrFgdY0/YKZ46GfjOC9
ta4G25VJ1WKsMmWLtzyrfgwbYopquZd724fFdpvsxfIvMG5m3VFkThOqzsOttDcU
fyMTqM2pan4txG58uxNJ0MjR03UCEULRU+qMnwIDAQABo4IBJTCCASEwHQYDVR0O
BBYEFP8vf+EG9DjzLe0ljZjC/g72bPz6MB8GA1UdIwQYMBaAFOWdWTCCR1jMrPoI
VDaGezq1BE3wMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADA0BggrBgEFBQcBAQQoMCYwJAYI
KwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTA6BgNVHR8EMzAxMC+g
LaArhilodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vT21uaXJvb3QyMDI1LmNybDAq
BgNVHSAEIzAhMAgGBmeBDAECATAIBgZngQwBAgIwCwYJKwYBBAGCNyoBMA0GCSqG
SIb3DQEBCwUAA4IBAQCg2d165dQ1tHS0IN83uOi4S5heLhsx+zXIOwtxnvwCWdOJ
3wFLQaFDcgaMtN79UjMIFVIUedDZBsvalKnx+6l2tM/VH4YAyNPx+u1LFR0joPYp
QYLbNYkedkNuhRmEBesPqj4aDz68ZDI6fJ92sj2q18QvJUJ5Qz728AvtFOat+Ajg
K0PFqPYEAviUKr162NB1XZJxf6uyIjUlnG4UEdHfUqdhl0R84mMtrYINksTzQ2sH
YM8fEhqICtTlcRLr/FErUaPUe9648nziSnA0qKH7rUZqP/Ifmbo+WNZSZG1BbgOh
lk+521W+Ncih3HRbvRBE0LWYT8vWKnfjgZKxwHwJ
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=dev.azure.com
issuer=/C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 02
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 4089 bytes and written 447 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: C0160000F5A4F886055EE94C02BCBB5DE29BA775A8EF7D38ED166B52B7066155
    Session-ID-ctx: 
    Master-Key: 042FF22E9C9E325710A451B5BE07D943D1C11DB5BA49CF4D79D6C3550FB4E53564A1DBD216D9EC6E6F6529C82FD2C4C8
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1642944544
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by LiangZugeng** [comment]
I tried using `--skipsslcertvalidation` option but this option is not supported in `vsts-agent-linux-x64-2.196.2.tar.gz`.
```
[2022-01-23 13:13:08Z ERR  Terminal] WRITE ERROR: Unknown input argument from command line: "skipsslcertvalidation"
```

I also tried `export AZP_AGENT_USE_LEGACY_HTTP=true` before running config.sh, an exception was raised.
```
The handler does not support custom handling of certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.53.1"). An SSL backend based on "OpenSSL/1.1.1g" is required. Consider using System.Net.Http.SocketsHttpHandler.
```

**Comment by LiangZugeng** [comment]
Solution found after reviewing [this instruction](https://github.com/dotnet/core/blob/main/Documentation/linux-setup.md#ssl-certificate-resolution-with-snap-installs)

The issue can be fixed setting SSL_CERT_FILE and SSL_CERT_DIR environment variables in my case.

To solve this issue, in CentOS 7, before running config.sh, run the following commands:
```
export SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export SSL_CERT_DIR=/dev/null
./config.sh
```

After this, config.sh successfully registered the agent and created a systemd service in CentOS 7.

However, when the service started, it still reported the same error, to solve this, the systemd service definition file (/etc/systemd/system/vsts.agent.???.service) should be modified to set the same environment variables for the service.
```
[Service]
ExecStart=/home/username/azagent/runsvc.sh
User=username
WorkingDirectory=/home/username/azagent
KillMode=process
KillSignal=SIGTERM
TimeoutStopSec=5min
Environment="SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
Environment="SSL_CERT_DIR=/dev/null"
```

Add the last two lines to the [Service] section in the service definition file, and then
```
sudo ./svc.sh stop
sudo systemctl daemon-reload
sudo ./svc.sh start
```

I don't know why but it works, it's time to learn more on .NET ssl validation implementation on linux. Case closed.
