### ISSUE TITLE
Issue with the agent on Server 2012 R2 after TLS 1.2 on 1/31

### ISSUE THREAD

**Issue by jackwhitcomb** [microsoft/azure-pipelines-agent#3722]
After the update this morning for Azure Devops to enforce TLS 1.2, it seems a few (not all) of my older Server 2012 servers (yes we're in the process of upgrading them) cannot talk to the azure pipelines anymore. The error from the agent is below. I made sure the machine is only using TLS 1.2 with TLS 1.0,1.1 and SSL 3 disabled. dotnet framework registry is set to use only strong encryption as well for both x64 and x32.

`
[2022-01-31 17:32:50Z INFO LocationServer] Unable to connect to https://dev.azure.com/********/.
[2022-01-31 17:32:50Z ERR  LocationServer] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. -2146892963
   at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)
   at System.Net.Security.SslStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& context, String targetName, ArraySegment1 input, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)`

**Comment by kotslee** [comment]
I have the same issue with 2012 R2. What worked for me is enabling all the Cipher Suites using Nartac (1st screenshot below). 2nd screenshot below shows my SChannel settings.

![Annotation 2022-01-31 144850](https://user-images.githubusercontent.com/36685277/151886098-c8891f54-b628-4408-b547-d7a751267b0b.png)
![Annotation 2022-01-31 144957](https://user-images.githubusercontent.com/36685277/151886102-0bfaff7b-e0dc-476b-92d4-818089f6650b.jpg)

**Comment by ebuzzelli** [comment]
> I have the same issue with 2012 R2. What worked for me is enabling all the Cipher Suites using Nartac (1st screenshot below). 2nd screenshot below shows my SChannel settings.
> 
> ![Annotation 2022-01-31 144850](https://user-images.githubusercontent.com/36685277/151886098-c8891f54-b628-4408-b547-d7a751267b0b.png) ![Annotation 2022-01-31 144957](https://user-images.githubusercontent.com/36685277/151886102-0bfaff7b-e0dc-476b-92d4-818089f6650b.jpg)

This worked for me too.  It is quite the sledgehammer approach, but it got my pipelines back up and running until we can get this server upgraded.

**Comment by STJones85** [comment]
Same issue earlier, had to enable the last 2 of the 4 supported Ciphers by dev.azure.com after an SSLLabs scan and make sure Diffie-Hellman KE was set. This said, it appears Microsoft has rolled back the change as the SSLLabs scan I just ran shows the old ciphers and TLS 1.0/1.1 are enabled again.

Cipher Suites
# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
**TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256**

**Comment by EzzhevNikita** [comment]
@jackwhitcomb Could you please try to use the solution that is provided by @kotslee and check if it will help you to bypass the issue.

Generally, situation with disabling of TLS 1.0 and TLS 1.1 is expected and here Microsoft's blog describes the reasons for it - https://devblogs.microsoft.com/devops/deprecating-weak-cryptographic-standards-tls-1-0-and-tls-1-1-in-azure-devops/.

**Comment by tktackett** [comment]
> @jackwhitcomb Could you please try to use the solution that is provided by @kotslee and check if it will help you to bypass the issue.
> 
> Generally, situation with disabling of TLS 1.0 and TLS 1.1 is expected and here Microsoft's blog describes the reasons for it - https://devblogs.microsoft.com/devops/deprecating-weak-cryptographic-standards-tls-1-0-and-tls-1-1-in-azure-devops/.

We followed the guidance, but what was unexpected AND undocumented are the cipher suites used by dev.azure.com. Best practices dictate we turn the following two cipher suites off, but they seem to be required on a 2012 R2 server to access this endpoint.

TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f) DH 2048 bits FS 256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e) DH 2048 bits FS 128

**Comment by frankfuu** [comment]
> I have the same issue with 2012 R2. What worked for me is enabling all the Cipher Suites using Nartac (1st screenshot below). 2nd screenshot below shows my SChannel settings.
> 
> ![Annotation 2022-01-31 144850](https://user-images.githubusercontent.com/36685277/151886098-c8891f54-b628-4408-b547-d7a751267b0b.png) ![Annotation 2022-01-31 144957](https://user-images.githubusercontent.com/36685277/151886102-0bfaff7b-e0dc-476b-92d4-818089f6650b.jpg)

Thanks, this was a life saver for us ;)
