### ISSUE TITLE
Agent tries to downgrade itself but fails due to missing hash

### ISSUE THREAD

**Issue by Sl1ckR1ck** [microsoft/azure-pipelines-agent#3773]
Hi, 

I am facing an issue on 2 of my build agents which are running V2.198.3.

For some reason, my agent is trying to downgrade itself to V2.181.2 but fails saying that it is not able to validate the package since there is no hash.

So I have 2 questions:

1. Why does it try to downgrade itselft. The message explains that it could be due to a rollback but if i look at the versions here V2.198.3 doesnt seem to be an obsolete package...?
2. Why would it fail to download and install the agent?

Another odd behavior is that it tries to do this while it is running build and therefore terminates any of my build. 

Here is the agent log which contains the error:

`[2022-03-02 20:10:22Z INFO SelfUpdater] Version '2.181.2' of 'agent' package available in server.
[2022-03-02 20:10:22Z INFO SelfUpdater] Current running agent version is 2.198.3
[2022-03-02 20:10:22Z INFO Terminal] WRITE LINE: Downgrading agent to a lower version. This is usually due to a rollback of the currently published agent for a bug fix. To disable this behavior, set environment variable AZP_AGENT_DOWNGRADE_DISABLED=true before launching your agent.
[2022-03-02 20:10:22Z INFO SelfUpdater] An update is available.
[2022-03-02 20:10:22Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2022-03-02 20:10:22Z INFO Terminal] WRITE LINE: Downloading 2.181.2 agent
[2022-03-02 20:10:22Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\VNext\bin'
[2022-03-02 20:10:22Z INFO HostContext] Well known directory 'Root': 'C:\Agent\VNext'
[2022-03-02 20:10:22Z INFO HostContext] Well known directory 'Work': 'C:\Agent\VNext\_work'
[2022-03-02 20:10:22Z INFO SelfUpdater] Attempt 1: save latest agent into C:\Agent\VNext\_work\_update\agent1.zip.
[2022-03-02 20:10:22Z INFO SelfUpdater] Download agent: begin download
[2022-03-02 20:10:28Z INFO JobDispatcher] Successfully renew job request 344024, job is valid till 2022-03-02 8:20:28 PM
[2022-03-02 20:10:35Z INFO SelfUpdater] Download agent: finished download
[2022-03-02 20:10:35Z WARN SelfUpdater] Unable to perform the necessary checksum validation since the target package hash is missed
[2022-03-02 20:10:35Z INFO SelfUpdater] Attempt 2: save latest agent into C:\Agent\VNext\_work\_update\agent1.zip.
[2022-03-02 20:10:35Z INFO SelfUpdater] Download agent: begin download
[2022-03-02 20:10:47Z INFO SelfUpdater] Download agent: finished download
[2022-03-02 20:10:47Z WARN SelfUpdater] Unable to perform the necessary checksum validation since the target package hash is missed
[2022-03-02 20:10:47Z INFO SelfUpdater] Attempt 3: save latest agent into C:\Agent\VNext\_work\_update\agent1.zip.
[2022-03-02 20:10:47Z INFO SelfUpdater] Download agent: begin download
[2022-03-02 20:11:00Z INFO SelfUpdater] Download agent: finished download
[2022-03-02 20:11:00Z WARN SelfUpdater] Unable to perform the necessary checksum validation since the target package hash is missed
[2022-03-02 20:11:00Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2022-03-02 20:11:00Z INFO JobDispatcher] Ensure WorkerDispather for job fd490c07-0b22-5182-fac9-6d67fe1e939b run to finish, cancel any running job.
[2022-03-02 20:11:00Z INFO JobDispatcher] Send job cancellation message to worker for job fd490c07-0b22-5182-fac9-6d67fe1e939b.
[2022-03-02 20:11:25Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-03-02 20:11:25Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-03-02 20:11:25Z INFO ProcessInvokerWrapper] Exited process 42644 with exit code 103
[2022-03-02 20:11:25Z INFO ProcessInvokerWrapper] Finished process 42644 with exit code 103, and elapsed time 00:01:56.3231180.
[2022-03-02 20:11:25Z INFO JobDispatcher] finish job request for job fd490c07-0b22-5182-fac9-6d67fe1e939b with result: Canceled
[2022-03-02 20:11:25Z INFO Terminal] WRITE LINE: 2022-03-02 20:11:25Z: Job Build completed with result: Canceled
[2022-03-02 20:11:25Z INFO JobDispatcher] Stop renew job request for job fd490c07-0b22-5182-fac9-6d67fe1e939b.
[2022-03-02 20:11:25Z INFO JobDispatcher] job renew has been canceled, stop renew job request 344024.
[2022-03-02 20:11:25Z INFO JobNotification] Entering JobCompleted Notification
[2022-03-02 20:11:25Z INFO JobNotification] Entering EndMonitor
[2022-03-02 20:11:25Z ERR  Terminal] WRITE ERROR: An error occurred: Agent package checksum validation failed.
There are possible reasons why this happened:
  1) The agent package was compromised.
  2) The agent package was not fully downloaded or was corrupted during the download process.
You can skip checksum validation for the agent package by setting the environment variable DISABLE_HASH_VALIDATION=true
[2022-03-02 20:11:25Z ERR  AgentProcess] System.Threading.Tasks.TaskCanceledException: Agent package checksum validation failed.
There are possible reasons why this happened:
  1) The agent package was compromised.
  2) The agent package was not fully downloaded or was corrupted during the download process.
You can skip checksum validation for the agent package by setting the environment variable DISABLE_HASH_VALIDATION=true
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
`

**Comment by alexander-smolyakov** [comment]
Hi @Sl1ckR1ck could you please share the following information?
- Are you using Azure DevOps Services (Cloud) or Azure DevOps Server (On-prem solution)?
- If you are using Azure DevOps Services would you mind sharing organization name?
- If you are using Azure DevOps Server please share the version of the sever

**Comment by Sl1ckR1ck** [comment]
Hi @alexander-smolyakov, thank you for you reply.

> * Are you using Azure DevOps Services (Cloud) or Azure DevOps Server (On-prem solution)?
 Azure DevOps Server - On-Premise

> * If you are using Azure DevOps Server please share the version of the sever
18.181.31626.1 (Azure DevOps Server 2020 Update 1.1)

**Comment by alexander-smolyakov** [comment]
@Sl1ckR1ck,

Regarding the agent downgrade:

The on-prem solution ships with the default version of the pipelines agent and the Azure DevOps itself downgrades the pipelines agent back to the default version. There are two ways how to prevent such a behavior: 
1. Set the environment variable `AZP_AGENT_DOWNGRADE_DISABLED` to `true`. It will force the pipeline agent to skip downgrade.
2. Update the agent version for the Azure DevOps itself by putting the archive with the agent to the following folder `C:\ProgramData\Microsoft\Azure DevOps\Agents\`. Here is related documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#agent-version-and-upgrades

Regarding the issue with the hash validation, could you please set the environment variable `DISABLE_HASH_VALIDATION` to `true` to force the agent to skip hash validation?

**Comment by alexander-smolyakov** [comment]
@Sl1ckR1ck is this issue still actual to you?

**Comment by alexander-smolyakov** [comment]
Hey @Sl1ckR1ck, let me close this issue due to inactivity, feel free to request a reopening if you have any further questions.
