### ISSUE TITLE
Agent fails to start Docker container with mount as long as _work/X dir exists/uses wrong mount path

### ISSUE THREAD

**Issue by rklec** [microsoft/azure-pipelines-agent#3809]
## Agent Version and Platform
Version of your agent? 2.196.2

OS of the machine running the agent? Linux / Ubuntu 20.04

## Azure DevOps Type and Version
on-premises Azure DevOps Server

Azure DevOps Server 2020 Update 1.1

## What's not working?
I use a YAML pipeline that starts a container like this:
```yaml
        container:
          image: $[ variables.docker_dotnet ]
          options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro -v /var/cache/AzureDevOpsServerPipelineCache:/var/cache/AzureDevOpsServerPipelineCache"
```

`variables.docker_dotnet` is set to `mcr.microsoft.com/dotnet/sdk:6.0`.

The path `/var/cache/AzureDevOpsServerPipelineCache` exists on the server and is writable/assigned to the user the agent uses:
```
$ ls -la /var/cache
drwxr-xr-x  3 TFSBuild  TFSBuild 4096 Apr  7 11:06 AzureDevOpsServerPipelineCache
```

Don't wonder about the docker being mounted, that's just part of the workaround for #2043 and that is not a problem.

### What happens

Now the pipeline fails directly at initialization ("Initialize job"):
> ##[error]Access to the path '/path_to_agent/_work/1/s/"/var/cache/AzureDevOpsServerPipelineCache"' is denied.

This is clearly the wrong path. (and thus does not exist, of course - which _however_ should still not cause a Docker container start to fail.)
**However**, as soon as I delete that `/path_to_agent/_work/1` dir manually on the server (i.e. `sudo rm -rf /path_to_agent/_work/1`) the path is correctly used, i.e. it uses the correct absolute path and not such a broken and weirdly quoted path in the agent folder. It does then work correctly:
```
Starting: Initialize job
Agent name: '***AGENT_NAME***@***SERVER***'
Agent machine name: '***SERVER***'
Current agent version: '2.196.2'
Agent running as: '**AGENT_USERNAME**'
Agent is running behind proxy server: '******'
Prepare build directory.
Set build variables.
Download all required tasks.
Checking job knob settings.
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job
```

But as that of course creates the agent directory (`1`) again, this fails the next time the exactly same pipeline (same repo/YAML etc.) is executed. Thus, I assume, this can only be an issue of the agent.

(`/path_to_agent` is a replacement value also used in the logs below, but I can assure you it is the path to the agents home folder/where the agent is installed and it is the correct absolute path.)

Manually starting the docker with the same parameters (including even such a non-existing wrong path) does work (of course if the path does not exist, the mount/dir is empty.)

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

Worker log: https://gist.github.com/rklec/3b7fbcf6381f72c40e961ed07e86e13d
Agent log: https://gist.github.com/rklec/f12b5917f4ba2b30df00bf87bba40bad

The interesting part likely is this:
```
[2022-04-07 09:35:49Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.IO.IOException: Access to the path '/path_to_agent/_work/1/s/"/var/cache/AzureDevOpsServerPipelineCache"' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.DirectoryInfo.Delete()
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, IList`1 repositories, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2022-04-07 09:35:49Z ERR  JobRunner] Job initialize failed.
[2022-04-07 09:35:49Z ERR  JobRunner] Caught exception from InitializeJob: System.IO.IOException: Access to the path '/path_to_agent/_work/1/s/"/var/cache/AzureDevOpsServerPipelineCache"' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.DirectoryInfo.Delete()
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, IList`1 repositories, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
```

**Comment by rklec** [comment]
Okay, teh issue appears because the CI accidentialyl did a `mkdir -p "/var/cache/AzureDevOpsServerPipelineCache"` inside of the source directory, so it creates this `/path_to_agent/_work/1/s/"/var/cache/AzureDevOpsServerPipelineCache"` dir and that is indeed there.
The problem of the agent stil remains that the next run does not mount the absolute path `/var/cache/AzureDevOpsServerPipelineCache`, but somehow chooses/tries to mount the local relative path.

**Comment by rklec** [comment]
And yes, one directory was named `"` (so the mkdir command it executed was propbably rather `mkdir -p '"/var/cache/AzureDevOpsServerPipelineCache"'`.

**Comment by anatolybolshakov** [comment]
@rklec per agent/worker logs - seems like agent is trying to remove build directory (due to clean up settings) before job execution, but there is a new folder created inside (/path_to_agent/_work/1/s/"/var/cache/AzureDevOpsServerPipelineCache") and seems like user running agent don't have access to this one (and hence fails with deletion).
Could you please clarify how this folder is being created? Is there some other user account creating it, or there was some privileges elevation via sudo?

**Comment by rklec** [comment]
> Could you please clarify how this folder is being created?

Yes, it is created.

> Is there some other user account creating it, or there was some privileges elevation via sudo?

Actually, it's the same build pipeline, which explains why it does only fail when I run it again.

So what you said makes total sense, so what happens is:
1. first build pipeline runs successfully and accidentally creates that "wrong" folder in the source dir (`_work/1/s/`). (which itself, is not problematic though ugly/broken of course)
2. the second pipeline with the same settings runs now and then tries to clean up the created directory - but maybe at the same time starts the Docker container or tries to do it? Or somehow it messes things up?

Note what I also did was chowning the directory in the build pipeline, whcih could explain the permission errors (though I thought and checked that the agent uses the same UID inside of the container for it's user as outside of the container, so I am still a bit puzzled why this fails):
```yml
# Prepares the Linux caching directory so it is writable by the ...azpcontainer user.
# As Azure DevOps uses the same user ID as on the host, usually this likely only needs to run once.

steps:
  - task: Bash@3
    displayName: 'Chown caching directory'
    inputs:
      targetType: 'inline'
      script: |
        cacheRoot="$(lf_app_cache_root_linux)"
        currentUser=$(id -u -n)
        currentUserId=$(id -u)

        echo "##[debug]Chowing \"$cacheRoot\" to group $currentUser, id = $currentUserId."

        cmdline="sudo mkdir -p \"$cacheRoot\"" # <-- this causes that crazy dir to be created
        echo "##[command]$cmdline"
        $cmdline

        cmdline="sudo chown -R :$currentUserId \"$cacheRoot\""
        echo "##[command]$cmdline"
        $cmdline

        echo "##[debug]Ensure group has write access to cache directory."

        cmdline="sudo chmod -R g+w \"$cacheRoot\""
        echo "##[command]$cmdline"
        $cmdline
    condition: eq( variables['Agent.OS'], 'Linux' )
```

`lf_app_cache_root_linux` = `/var/cache/AzureDevOpsServerPipelineCache`

In the end, from what you say, could it be that the error message I was wondering about actually was not about the container starting but about a failed dir cleanup?

**Comment by anatolybolshakov** [comment]
@rklec yes, per stack trace this error message comes from dir cleanup stage (which happens during job initializing) - and hence failing due to permission error.
