### ISSUE TITLE
ERR  Runner] System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by irfanaslam-me** [microsoft/azure-pipelines-agent#3815]
I am having issue in installing self hosted runner error which I received is 

I was installing on ubuntu 18, 20 but result is the same

`cat Runner_20220410-175123-utc.log
[2022-04-10 17:51:23Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO HostContext] Well known config file 'Credentials': '/home/node/actions-runner/.credentials'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO HostContext] Well known config file 'Runner': '/home/node/actions-runner/.runner'
[2022-04-10 17:51:23Z INFO Listener] Runner is built for Linux (X64) - linux-x64.
[2022-04-10 17:51:23Z INFO Listener] RuntimeInformation: Linux 4.15.0-167-generic #175-Ubuntu SMP Wed Jan 5 01:56:07 UTC 2022.
[2022-04-10 17:51:23Z INFO Listener] Version: 2.288.1
[2022-04-10 17:51:23Z INFO Listener] Commit: e95a2b840b74568ec30c993462165ece91040f8e
[2022-04-10 17:51:23Z INFO Listener] Culture:
[2022-04-10 17:51:23Z INFO Listener] UI Culture:
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO Listener] Validating directory permissions for: '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO CommandLineParser] Parse
[2022-04-10 17:51:23Z INFO CommandLineParser] Parsing 5 args
[2022-04-10 17:51:23Z INFO CommandLineParser] parsing argument
[2022-04-10 17:51:23Z INFO CommandLineParser] HasArgs: False
[2022-04-10 17:51:23Z INFO CommandLineParser] Adding Command: configure
[2022-04-10 17:51:23Z INFO CommandLineParser] parsing argument
[2022-04-10 17:51:23Z INFO CommandLineParser] HasArgs: True
[2022-04-10 17:51:23Z INFO CommandLineParser] arg: url
[2022-04-10 17:51:23Z INFO CommandLineParser] parsing argument
[2022-04-10 17:51:23Z INFO CommandLineParser] HasArgs: True
[2022-04-10 17:51:23Z INFO CommandLineParser] Adding option 'url': 'https://github.com/thousandsofraccoons/rememo'
[2022-04-10 17:51:23Z INFO CommandLineParser] parsing argument
[2022-04-10 17:51:23Z INFO CommandLineParser] HasArgs: True
[2022-04-10 17:51:23Z INFO CommandLineParser] arg: token
[2022-04-10 17:51:23Z INFO CommandLineParser] parsing argument
[2022-04-10 17:51:23Z INFO CommandLineParser] HasArgs: True
[2022-04-10 17:51:23Z INFO CommandLineParser] Adding option 'token': '***'
[2022-04-10 17:51:23Z INFO Listener] Arguments parsed
[2022-04-10 17:51:23Z INFO Runner] ExecuteCommand
[2022-04-10 17:51:23Z INFO ConfigurationStore] currentAssemblyLocation: /home/node/actions-runner/bin/Runner.Listener.dll
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO ConfigurationStore] binPath: /home/node/actions-runner/bin
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO ConfigurationStore] RootFolder: /home/node/actions-runner
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO HostContext] Well known config file 'Runner': '/home/node/actions-runner/.runner'
[2022-04-10 17:51:23Z INFO ConfigurationStore] ConfigFilePath: /home/node/actions-runner/.runner
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO HostContext] Well known config file 'Credentials': '/home/node/actions-runner/.credentials'
[2022-04-10 17:51:23Z INFO ConfigurationStore] CredFilePath: /home/node/actions-runner/.credentials
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/node/actions-runner/.credentials_migrated'
[2022-04-10 17:51:23Z INFO ConfigurationStore] MigratedCredFilePath: /home/node/actions-runner/.credentials_migrated
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Bin': '/home/node/actions-runner/bin'
[2022-04-10 17:51:23Z INFO HostContext] Well known directory 'Root': '/home/node/actions-runner'
[2022-04-10 17:51:23Z INFO HostContext] Well known config file 'Service': '/home/node/actions-runner/.service'
[2022-04-10 17:51:23Z INFO ConfigurationStore] ServiceConfigFilePath: /home/node/actions-runner/.service
[2022-04-10 17:51:23Z INFO CommandSettings] Flag 'help': 'False'
[2022-04-10 17:51:23Z INFO CommandSettings] Flag 'version': 'False'
[2022-04-10 17:51:23Z INFO CommandSettings] Flag 'commit': 'False'
[2022-04-10 17:51:23Z INFO CommandSettings] Flag 'check': 'False'
[2022-04-10 17:51:23Z INFO CommandSettings] Command 'configure': 'True'
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE:
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-04-10 17:51:23Z INFO Terminal] WRITE: |
[2022-04-10 17:51:23Z INFO Terminal] WRITE: Self-hosted runner registration
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE:                         |
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-04-10 17:51:23Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-04-10 17:51:23Z INFO ConfigurationManager] ConfigureAsync
[2022-04-10 17:51:23Z INFO ConfigurationStore] IsConfigured()
[2022-04-10 17:51:23Z INFO ConfigurationStore] IsConfigured: False
[2022-04-10 17:51:23Z INFO ConfigurationManager] Is configured: False
[2022-04-10 17:51:23Z INFO CommandSettings] Arg 'url': 'https://github.com/thousandsofraccoons/rememo'
[2022-04-10 17:51:23Z INFO CommandSettings] Remove url from Arg dictionary.
[2022-04-10 17:51:23Z INFO CommandSettings] Arg 'token': '***'
[2022-04-10 17:51:23Z INFO CommandSettings] Remove token from Arg dictionary.
[2022-04-10 17:51:23Z ERR  Runner] System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2022-04-10 17:51:23Z ERR  Terminal] WRITE ERROR: Object reference not set to an instance of an object.
[2022-04-10 17:51:23Z INFO Listener] Runner execution has finished with return code 1
`

**Comment by AndreyIvanov42** [comment]
Hi @irfanaslam-me 
Based on the message ```022-04-10 17:51:23Z INFO ConfigurationStore] IsConfigured: False [2022-04-10 17:51:23Z INFO ConfigurationManager] Is configured: False [2022-04-10 17:51:23Z INFO CommandSettings] Arg 'url': 'https://github.com/thousandsofraccoons/rememo'```, the agent is configured incorrectly. Please look again at the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#download-and-configure-the-agent)

**Comment by irfanaslam-me** [comment]
@AndreyIvanov42 Thanks for the support. Resolved the issue. actually token was expired and runner was not picking the tag. But now all are okay.
