### ISSUE TITLE
Pipeline on private MacOS agent SVN Checkout fails with xml error (1,1)

### ISSUE THREAD

**Issue by ajaco56** [microsoft/azure-pipelines-agent#3820]
Checking out SVN code from known good svn repo 

2022-04-14T19:40:54.7296160Z ##[debug]<?xml version="1.0" encoding="UTF-8"?>
2022-04-14T19:40:54.7297280Z ##[debug]<info>
2022-04-14T19:40:54.7298280Z ##[debug]<entry
2022-04-14T19:40:54.7299290Z ##[debug]   kind="dir"
2022-04-14T19:40:54.7300410Z ##[debug]   path="raop"
2022-04-14T19:40:54.7301560Z ##[debug]   revision="496">
2022-04-14T19:40:54.7302780Z ##[debug]<url>https://***.***.***.***/svn/svn_macport/raop</url>
2022-04-14T19:40:54.7304370Z ##[debug]<relative-url>^/raop</relative-url>
2022-04-14T19:40:54.7305490Z ##[debug]<repository>
2022-04-14T19:40:54.7306650Z ##[debug]<root>https://***.***.***.***/svn/svn_macport</root>
2022-04-14T19:40:54.7308310Z ##[debug]<uuid>73f75cef-7701-0010-baaa-c1d8a5475ba2</uuid>
2022-04-14T19:40:54.7309600Z ##[debug]</repository>
2022-04-14T19:40:54.7310750Z ##[debug]<commit
2022-04-14T19:40:54.7311910Z ##[debug]   revision="358">
2022-04-14T19:40:54.7313690Z ##[debug]<date>2022-01-22T11:44:31.234940Z</date>
2022-04-14T19:40:54.7314990Z ##[debug]</commit>
2022-04-14T19:40:54.7316270Z ##[debug]</entry>
2022-04-14T19:40:54.7317450Z ##[debug]</info>

always fails with 

2022-04-14T19:40:54.7446020Z **##[error]There is an error in XML document (1, 1).**
2022-04-14T19:40:54.7463270Z ##[debug]Processed: ##vso[task.logissue type=error;]There is an error in XML document (1, 1).
2022-04-14T19:40:54.7476460Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2022-04-14T19:40:54.7480410Z ##[debug]   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Agent.Plugins.Repository.SvnCliManager.GetLatestRevisionAsync(String serverPath, String sourceRevision)
   at Agent.Plugins.Repository.SvnCliManager.UpdateWorkspace(String rootPath, Dictionary`2 distinctMappings, Boolean cleanRepository, String sourceBranch, String revision)
   at Agent.Plugins.Repository.SvnSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)

I suspect **System.Xml.Serialization.XmlSerializer.Deserialize** is not reading the generated xml properly, please advise/help

Andreas Jacobs

**Comment by AndreyIvanov42** [comment]
Hi @ajaco56  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by ajaco56** [comment]
HI, for the curious I found out what happened:

on the self hosted agent when you run env.sh **without!** first setting your LANG environment (in my case : export LANG=en_US.UTF-8), the error will appear bc the job does not know the locale to be used and just fails with mentioned error.

When setting the LANG env before! to the proper value , it works as expected.

I would suggest to have a more informative message to appear in the log, f.i. ._**.... did you check your LANG env settings on the agent?....**_

This can be closed

Andreas Jacobs
