### ISSUE TITLE
SSL issue registering Azure DevOps agent

### ISSUE THREAD

**Issue by ceilingfish** [microsoft/azure-pipelines-agent#3836]
## Agent Version and Platform
2.202.1 & v2.204.0  

OS of the machine running the agent? Windows Server 2019

## Azure DevOps Type and Version
dev.azure.com

organization name: https://dev.azure.com/AxiCore

## What's not working?
I am trying to register a VM as a DevOps environment from the command line using:

    c:\AzureDevOpsAgent\config.cmd --environment --environmentname redacted-environment --agent host --runasservice --work _work --url https://dev.azure.com/AxiCore/ --projectname RedactedProject --auth PAT --token REDACTED--unattended

This seems to have happened recently (possibly after the adoption of TLS 1.3?). I have tried running this command preceded by `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls13` as well, but it has not made a difference.

## Agent and Worker's Diagnostic Logs
The logs emitted are:

```
[2022-05-09 16:09:19Z INFO AgentProcess] Agent package win-x64.
[2022-05-09 16:09:19Z INFO AgentProcess] Running on Windows (X64).
[2022-05-09 16:09:19Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.17763.
[2022-05-09 16:09:19Z INFO AgentProcess] Version: 2.204.0
[2022-05-09 16:09:19Z INFO AgentProcess] Commit: 166abe8635999375bb798213066ccafbdd7e3875
[2022-05-09 16:09:19Z INFO AgentProcess] Culture: en-US
[2022-05-09 16:09:19Z INFO AgentProcess] UI Culture: en-US
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO AgentProcess] Validating directory permissions for: 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO PowerShellExeUtil] Generation: '1'
[2022-05-09 16:09:19Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2022-05-09 16:09:19Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2022-05-09 16:09:19Z INFO PowerShellExeUtil] Generation: '3'
[2022-05-09 16:09:19Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.17763.1'
[2022-05-09 16:09:19Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2022-05-09 16:09:19Z INFO AgentProcess]  'CDF'
[2022-05-09 16:09:19Z INFO AgentProcess]  'v2.0.50727'
[2022-05-09 16:09:19Z INFO AgentProcess]  'v3.0'
[2022-05-09 16:09:19Z INFO AgentProcess]  'v3.5'
[2022-05-09 16:09:19Z INFO AgentProcess]  'v4'
[2022-05-09 16:09:19Z INFO AgentProcess]  'v4.0'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Version': '2.0.50727.4927'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Install': '1'
[2022-05-09 16:09:19Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727'
[2022-05-09 16:09:19Z INFO AgentProcess] Found version: 2.0.50727
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version': '3.0.30729.4926'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Install': '1'
[2022-05-09 16:09:19Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.0'
[2022-05-09 16:09:19Z INFO AgentProcess] Found version: 3.0
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Version': '3.5.30729.4926'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Install': '1'
[2022-05-09 16:09:19Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.5'
[2022-05-09 16:09:19Z INFO AgentProcess] Found version: 3.5
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2022-05-09 16:09:19Z INFO AgentProcess]  'Client'
[2022-05-09 16:09:19Z INFO AgentProcess]  'Full'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.8.03761'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '528049'
[2022-05-09 16:09:19Z INFO AgentProcess] Type is System.Int32
[2022-05-09 16:09:19Z INFO AgentProcess] Interpreted version: 4.7.0
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.8.03761'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '528049'
[2022-05-09 16:09:19Z INFO AgentProcess] Type is System.Int32
[2022-05-09 16:09:19Z INFO AgentProcess] Interpreted version: 4.7.0
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2022-05-09 16:09:19Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2022-05-09 16:09:19Z INFO AgentProcess] Found 5 versions:
[2022-05-09 16:09:19Z INFO AgentProcess]  2.0.50727
[2022-05-09 16:09:19Z INFO AgentProcess]  3.0
[2022-05-09 16:09:19Z INFO AgentProcess]  3.5
[2022-05-09 16:09:19Z INFO AgentProcess]  4.7.0
[2022-05-09 16:09:19Z INFO AgentProcess]  4.7.0
[2022-05-09 16:09:19Z INFO AgentProcess] Testing for min NET Framework version: '4.5'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Setting up value for origin: Configure.Password
[2022-05-09 16:09:19Z INFO HostContext] Value is empty.
[2022-05-09 16:09:19Z INFO HostContext] Setting up value for origin: Configure.ProxyPassword
[2022-05-09 16:09:19Z INFO HostContext] Value is empty.
[2022-05-09 16:09:19Z INFO HostContext] Setting up value for origin: Configure.SslClientCert
[2022-05-09 16:09:19Z INFO HostContext] Value is empty.
[2022-05-09 16:09:19Z INFO HostContext] Setting up value for origin: Configure.Token
[2022-05-09 16:09:19Z INFO HostContext] Setting up value for origin: Configure.WindowsLogonPassword
[2022-05-09 16:09:19Z INFO HostContext] Value is empty.
[2022-05-09 16:09:19Z INFO CommandSettings] Configure {
  "AcceptTeeEula": false,
  "AddDeploymentGroupTags": false,
  "AddEnvironmentVirtualMachineResourceTags": false,
  "AddMachineGroupTags": false,
  "AlwaysExtractTask": false,
  "Agent": "host",
  "CollectionName": null,
  "DeploymentGroup": false,
  "DeploymentGroupName": null,
  "DeploymentGroupTags": null,
  "DeploymentPool": false,
  "DeploymentPoolName": null,
  "EnvironmentVMResource": true,
  "EnvironmentName": "redacted-environment",
  "EnvironmentVMResourceTags": null,
  "GitUseSChannel": false,
  "DisableLogUploads": false,
  "MachineGroup": false,
  "MachineGroupName": null,
  "MachineGroupTags": null,
  "MonitorSocketAddress": null,
  "NotificationPipeName": null,
  "NotificationSocketAddress": null,
  "NoRestart": false,
  "OverwriteAutoLogon": false,
  "Pool": null,
  "ProjectName": "RedactedProject",
  "ProxyPassword": null,
  "ProxyUserName": null,
  "ProxyUrl": null,
  "Replace": false,
  "RunAsAutoLogon": false,
  "RunAsService": true,
  "RunOnce": false,
  "PreventServiceStart": false,
  "SslCACert": null,
  "SslClientCert": null,
  "SslClientCertArchive": null,
  "SslClientCertKey": null,
  "SslClientCertPassword": null,
  "SslSkipCertValidation": false,
  "Url": "https://dev.azure.com/REDACTED/",
  "WindowsLogonAccount": null,
  "WindowsLogonPassword": null,
  "Work": "_work",
  "Auth": "PAT",
  "LaunchBrowser": false,
  "Password": null,
  "Token": "***",
  "Unattended": true,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2022-05-09 16:09:19Z INFO AgentProcess] Arguments parsed
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'Proxy': 'C:\AzureDevOpsAgent\.proxy'
[2022-05-09 16:09:19Z INFO VstsAgentWebProxy] No proxy setting found.
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'Certificates': 'C:\AzureDevOpsAgent\.certificates'
[2022-05-09 16:09:19Z INFO AgentCertificateManager] No certificate setting found.
[2022-05-09 16:09:19Z INFO Agent] ExecuteCommand
[2022-05-09 16:09:19Z INFO ConfigurationStore] currentAssemblyLocation: C:\AzureDevOpsAgent\bin\Agent.Listener.dll
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO ConfigurationStore] binPath: C:\AzureDevOpsAgent\bin
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO ConfigurationStore] RootFolder: C:\AzureDevOpsAgent
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'Agent': 'C:\AzureDevOpsAgent\.agent'
[2022-05-09 16:09:19Z INFO ConfigurationStore] ConfigFilePath: C:\AzureDevOpsAgent\.agent
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'Credentials': 'C:\AzureDevOpsAgent\.credentials'
[2022-05-09 16:09:19Z INFO ConfigurationStore] CredFilePath: C:\AzureDevOpsAgent\.credentials
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'Service': 'C:\AzureDevOpsAgent\.service'
[2022-05-09 16:09:19Z INFO ConfigurationStore] ServiceConfigFilePath: C:\AzureDevOpsAgent\.service
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'Autologon': 'C:\AzureDevOpsAgent\.autologon'
[2022-05-09 16:09:19Z INFO ConfigurationStore] AutoLogonSettingsFilePath: C:\AzureDevOpsAgent\.autologon
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'Options': 'C:\AzureDevOpsAgent\.options'
[2022-05-09 16:09:19Z INFO ConfigurationStore] RuntimeOptionsFilePath: C:\AzureDevOpsAgent\.options
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO HostContext] Well known config file 'SetupInfo': 'C:\AzureDevOpsAgent\.setup_info'
[2022-05-09 16:09:19Z INFO ConfigurationStore] SetupInfoFilePath: C:\AzureDevOpsAgent\.setup_info
[2022-05-09 16:09:19Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.204.0             |_|          (commit 166abe8)

[2022-05-09 16:09:19Z INFO ConfigurationManager] CheckAgentRootDirectorySecure
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Bin': 'C:\AzureDevOpsAgent\bin'
[2022-05-09 16:09:19Z INFO HostContext] Well known directory 'Root': 'C:\AzureDevOpsAgent'
[2022-05-09 16:09:19Z INFO ConfigurationManager] ConfigureAsync
[2022-05-09 16:09:19Z INFO ConfigurationStore] IsConfigured()
[2022-05-09 16:09:19Z INFO ConfigurationStore] IsConfigured: False
[2022-05-09 16:09:19Z INFO ConfigurationManager] Is configured: False
[2022-05-09 16:09:19Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2022-05-09 16:09:19Z INFO ConfigurationManager] Testing for min NET Framework version: '4.6'
[2022-05-09 16:09:19Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2022-05-09 16:09:19Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2022-05-09 16:09:19Z INFO CommandSettings] Flag 'environment': 'True'
[2022-05-09 16:09:19Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2022-05-09 16:09:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2022-05-09 16:09:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2022-05-09 16:09:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2022-05-09 16:09:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2022-05-09 16:09:19Z INFO Terminal] WRITE LINE: 
[2022-05-09 16:09:19Z INFO Terminal] WRITE LINE: >> Connect:
[2022-05-09 16:09:19Z INFO Terminal] WRITE LINE: 
[2022-05-09 16:09:19Z INFO CommandSettings] Arg 'url': 'https://dev.azure.com/REDACTED/'
[2022-05-09 16:09:19Z INFO EnvironmentVMResourceConfigProvider] url - https://dev.azure.com/REDACTED/
[2022-05-09 16:09:19Z INFO ConfigurationManager] GetCredentialProvider
[2022-05-09 16:09:19Z INFO CommandSettings] Arg 'auth': 'PAT'
[2022-05-09 16:09:19Z INFO ConfigurationManager] Creating credential for auth: PAT
[2022-05-09 16:09:19Z INFO CredentialManager] GetCredentialProvider
[2022-05-09 16:09:19Z INFO CredentialManager] Creating type PAT
[2022-05-09 16:09:19Z INFO CredentialManager] Creating credential type: PAT
[2022-05-09 16:09:19Z INFO PersonalAccessToken] EnsureCredential
[2022-05-09 16:09:19Z INFO CommandSettings] Arg 'token': '***'
[2022-05-09 16:09:19Z INFO PersonalAccessToken] GetVssCredentials
[2022-05-09 16:09:19Z INFO PersonalAccessToken] token retrieved: 52 chars
[2022-05-09 16:09:19Z INFO PersonalAccessToken] cred created
[2022-05-09 16:09:19Z INFO ConfigurationManager] cred retrieved
[2022-05-09 16:09:19Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2022-05-09 16:09:19Z WARN VisualStudioServices] Attempt 1 of GET request to https://dev.azure.com/REDACTED/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 11.165028 seconds.
[2022-05-09 16:09:31Z WARN VisualStudioServices] Attempt 2 of GET request to https://dev.azure.com/REDACTED/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 12.6872579 seconds.
[2022-05-09 16:09:43Z WARN VisualStudioServices] Attempt 3 of GET request to https://dev.azure.com/REDACTED/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 16.7875566 seconds.
[2022-05-09 16:10:00Z ERR  VisualStudioServices] Attempt 4 of GET request to https://dev.azure.com/REDACTED/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The maximum number of attempts has been reached.
[2022-05-09 16:10:00Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2022-05-09 16:10:00Z INFO LocationServer] Unable to connect to https://dev.azure.com/REDACTED/.
[2022-05-09 16:10:00Z ERR  LocationServer] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
[2022-05-09 16:10:00Z INFO CommandSettings] Flag 'unattended': 'True'
[2022-05-09 16:10:00Z ERR  Agent] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.GetConnectionData(String serverUrl, VssCredentials credentials, ILocationServer locationServer)
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.DetermineDeploymentType(String serverUrl, VssCredentials credentials, ILocationServer locationServer)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2022-05-09 16:10:00Z ERR  Terminal] WRITE ERROR: The SSL connection could not be established, see inner exception.

```

**Comment by ceilingfish** [comment]
This appears to be because dev.azure.com only supports TLS 1.2 (I thought you folks had rolled back deprecation of TLS 1.1 & 1.0?), with the following cipher suites:

TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256

I'm _guessing_ this is a mistake, as those cipher suites don't appear to be on Windows server 2019 or 2022. I found that downloading https://www.nartac.com/Products/IISCrypto and setting best practices resolved the issue.

**Comment by kirill-ivlev** [comment]
@ceilingfish could you please also check that there are no network issues on this machine? (For example, try to fetch some ADO url from PowerShell e.g: 

`Invoke-WebRequest -Uri "https://dev.azure.com/REDACTED/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1"`

Azure DevOps still support TLS 1.0 / 1.1 / 1.2 (https://devblogs.microsoft.com/visualstudio/azure-devops-requires-tls-1-2-on-all-connections-including-visual-studio/)

Also, unfortunately Windows Server 2019 will not support TLS 1.3 
You can check supported SSL protocols in the official documentation: https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support

**Comment by alexander-smolyakov** [comment]
@ceilingfish let me close this ticket due to inactivity. Feel free to request a reopening if the issue is still actual.
