### ISSUE TITLE
"Value cannot be null. (Parameter 'ContainerId')" and auto-updating agends causes disruption/cancel jobs

### ISSUE THREAD

**Issue by rklec** [microsoft/azure-pipelines-agent#3850]
## Have you tried troubleshooting?
Yes

## Agent Version and Platform
Version of your agent? 2.204.0

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
on-premises

Azure DevOps Server 2020 Update 1.1

## Setup

We have multiple agents on the same server, but for this test I offline'd all of them and only have one running:

![grafik](https://user-images.githubusercontent.com/71322635/170703572-34ced2a5-3e09-447e-9ad7-02ebf6b87221.png)

The build steps are all multi-staged and all use (the same) container setups including the https://github.com/microsoft/azure-pipelines-agent/issues/2043 workaround to install sudo in a container:
```yaml
# a workaround to install sudo in sudo-less containers
# required Docker to be mounted or installed in the container in /tmp/docker
# see https://github.com/microsoft/azure-pipelines-agent/issues/2043#issuecomment-687983301

steps:
  - task: Bash@3
    displayName: 'Install sudo'
    inputs:
      targetType: 'inline'
      script: |
        ! command -v sudo >/dev/null 2>&1 || { echo "sudo is already installed" >&2; exit; }

        cmdline='
        # proxy configuration first
        export HTTP_PROXY="$(***OUR_PROXY_VARIABLE****)"
        export HTTPS_PROXY="$(***OUR_PROXY_VARIABLE****)"
        export http_proxy="$HTTP_PROXY"
        export https_proxy="$HTTPS_PROXY"
        # update and install
        apt-get update&&DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo'

        echo "##[command]$cmdline"
        /tmp/docker exec -t -u 0 $(Agent.ContainerId) \
        sh -c "$cmdline"
      failOnStderr: true
    condition: eq( variables['Agent.OS'], 'Linux' )
```

The step to install PowerShell in a container is also simple enough:
```yaml
steps:
  - task: Bash@3
    displayName: 'Install Powershell'
    inputs:
      targetType: 'inline'
      script: |
        ! command -v pwsh >/dev/null 2>&1 || { echo "powershell/pwsh is already installed" >&2; exit; }

        # proxy configuration first
        export HTTP_PROXY="$(***OUR_PROXY_VARIABLE****)"
        export HTTPS_PROXY="$(***OUR_PROXY_VARIABLE****)"
        export http_proxy="$HTTP_PROXY"
        export https_proxy="$HTTPS_PROXY"
        # use noninteractive mode on package installation.
        export DEBIAN_FRONTEND="noninteractive"

        # Install system components
        # echo "##[command]sudo -E apt-get update && sudo -E apt-get install -y curl gnupg apt-transport-https"
        sudo -E apt-get update && sudo -E apt-get install -y curl gnupg apt-transport-https git

        # from https://docs.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.2#installation-on-debian-11-via-package-repository

        # Import the public repository GPG keys
        # echo "##[command]curl https://packages.microsoft.com/keys/microsoft.asc | sudo -E apt-key add -"
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo -E apt-key add -

        # Register the Microsoft Product feed
        # echo "##[command]sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list'"
        sudo -E sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list'

        # Update the list of products
        # echo "##[command]sudo -E apt-get update"
        sudo -E apt-get update

        # Install PowerShell
        # echo "##[command]sudo -E apt-get install -yq powershell"
        sudo -E apt-get install -yq powershell
    condition: eq( variables['Agent.OS'], 'Linux' )
```

The used container is `mcr.microsoft.com/dotnet/sdk:6.0`, which is embedded like this:
```yaml
        container:
          image: $[ variables.docker_dotnet ]
          options: "-v /usr/bin/docker:/tmp/docker:ro -v [...]"
```

So we can reproduce the error by queuing multiple builds/(when multiple agents are active) start multiple of them in parallel.

### The silent cancelling of jobs

After running a job, the agent seems to stop and try to update itself. This causes to cancel all builds which were still in queued. The update fails as our on-premise server does not have that agent version yet which it wants to update to (likely a version mismatch, I verified the URL, it does indeed not exist/return a 404 error with that JSON error message you see here):

```
[2022-05-27 09:48:01Z INFO JobDispatcher] job renew has been canceled, stop renew job request 88127.
[2022-05-27 09:48:01Z INFO JobNotification] Entering JobCompleted Notification
[2022-05-27 09:48:01Z INFO JobNotification] Entering EndMonitor
[2022-05-27 09:48:02Z INFO RSAFileKeyManager] Loading RSA key parameters from file ***PATH_TO_AGENTS****/coffeemaker/.credentials_rsaparams
[2022-05-27 09:48:02Z INFO MessageListener] Message '132' received from session 'c83b5414-d77e-405e-85a0-405141c792ff'.
[2022-05-27 09:48:02Z INFO ConfigurationStore] HasCredentials()
[2022-05-27 09:48:02Z INFO ConfigurationStore] stored True
[2022-05-27 09:48:02Z INFO CredentialManager] GetCredentialProvider
[2022-05-27 09:48:02Z INFO CredentialManager] Creating type OAuth
[2022-05-27 09:48:02Z INFO CredentialManager] Creating credential type: OAuth
[2022-05-27 09:48:02Z INFO RSAFileKeyManager] Loading RSA key parameters from file ***PATH_TO_AGENTS****/coffeemaker/.credentials_rsaparams
[2022-05-27 09:48:02Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2022-05-27 09:48:02Z ERR  VisualStudioServices] GET request to https://**********/_apis/distributedtask/packages/agent/linux-x64/2.195.2 failed. HTTP Status: NotFound
[2022-05-27 09:48:03Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2022-05-27 09:48:03Z INFO JobDispatcher] Ensure WorkerDispather for job eee3a9c7-940c-5514-7dcf-4c8a1ef62099 run to finish, cancel any running job.
[2022-05-27 09:48:03Z INFO JobDispatcher] Job request eee3a9c7-940c-5514-7dcf-4c8a1ef62099 processed succeed.
[2022-05-27 09:48:03Z ERR  Terminal] WRITE ERROR: Fehler: A package with type agent, platform linux-x64, version 2.195.2 was not found.
[2022-05-27 09:48:03Z ERR  AgentProcess] Microsoft.TeamFoundation.DistributedTask.WebApi.PackageNotFoundException: A package with type agent, platform linux-x64, version 2.195.2 was not found.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent con>   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.UpdateNeeded(String targetVersion, CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
```

(log from an old run, new run is included in the logs at the end)

Note it apparently started the job already, which was then cancelled:
![grafik](https://user-images.githubusercontent.com/71322635/170715260-04d5ea0c-6906-406b-ba5f-a2df3bc155a5.png)

It just did not quite got far:
![grafik](https://user-images.githubusercontent.com/71322635/170713642-bd7a62f4-a336-4684-a4d3-af47bc20e145.png)

```
Starting: Initialize job
Agent name: 'microwave@***********'
Agent machine name: '***********'
Current agent version: '2.204.0'
Agent running as: '***AGENT_USERNAME***'
Agent is running behind proxy server: '***********'
##[debug]Triggering repository: ***********. repository type: Git
Prepare build directory.
##[debug]Delete existing build directory: '/***********/microwave/_work/12'
##[debug]Deleting build directory: '/***********'/microwave/_work/12'
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, IList`1 repositories, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
Finishing: Initialize job
```

Maybe a timing problem?

Update path:
* When clicking in ADS to add a new agent, this version is suggested: 2.181.2
* Current version of agent: 2.204.0
* Agent tries to update to: 2.195.2

This causes some jobs to be silently cancelled in the UI (as if a user would have clicked "Cancel" for them), which is of course kinda bad:
![grafik](https://user-images.githubusercontent.com/71322635/170711812-c8c90574-709b-4b63-8b95-946e1755e9c5.png)

### The strange ContainerId error

Also, **in some _other_ CI runs**, all **Bash** tasks are shown with a very strange "ContainerId" error failure:

![grafik](https://user-images.githubusercontent.com/71322635/170714405-50644f19-6be9-4198-af2a-0600005fd675.png)

```
2022-05-27T12:48:13.7151823Z ##[debug]Evaluating condition for step: 'Install Powershell'
2022-05-27T12:48:13.7152575Z ##[debug]Evaluating: eq(variables['Agent.OS'], 'Linux')
2022-05-27T12:48:13.7152847Z ##[debug]Evaluating eq:
2022-05-27T12:48:13.7153087Z ##[debug]..Evaluating indexer:
2022-05-27T12:48:13.7153365Z ##[debug]....Evaluating variables:
2022-05-27T12:48:13.7153635Z ##[debug]....=> Object
2022-05-27T12:48:13.7153910Z ##[debug]....Evaluating String:
2022-05-27T12:48:13.7154169Z ##[debug]....=> 'Agent.OS'
2022-05-27T12:48:13.7154645Z ##[debug]..=> 'Linux'
2022-05-27T12:48:13.7154925Z ##[debug]..Evaluating String:
2022-05-27T12:48:13.7155154Z ##[debug]..=> 'Linux'
2022-05-27T12:48:13.7155354Z ##[debug]=> True
2022-05-27T12:48:13.7155729Z ##[debug]Expanded: eq('Linux', 'Linux')
2022-05-27T12:48:13.7156039Z ##[debug]Result: True
2022-05-27T12:48:13.7156337Z ##[section]Starting: Install Powershell
2022-05-27T12:48:13.7160850Z ==============================================================================
2022-05-27T12:48:13.7161093Z Task         : Bash
2022-05-27T12:48:13.7161271Z Description  : Run a Bash script on macOS, Linux, or Windows
2022-05-27T12:48:13.7161459Z Version      : 3.179.0
2022-05-27T12:48:13.7161623Z Author       : Microsoft Corporation
2022-05-27T12:48:13.7161847Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2022-05-27T12:48:13.7162114Z ==============================================================================
2022-05-27T12:48:13.7166168Z ##[error]Value cannot be null. (Parameter 'ContainerId')
2022-05-27T12:48:13.7167581Z ##[debug]System.ArgumentNullException: Value cannot be null. (Parameter 'ContainerId')
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2022-05-27T12:48:13.7168474Z ##[section]Finishing: Install Powershell
```

## Agent and Worker's Diagnostic Logs

Both sanitized and uploaded to:
https://gist.github.com/rklec/55e7361dee504ae6ad663c76a73840ff

Looking in there, what is notably and I cannot explain right now is this entry:
```
[2022-05-27 12:48:12Z ERR  TempDirectoryManager] System.OperationCanceledException: The operation was canceled.
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.TempDirectoryManager.InitializeTempDirectory(IExecutionContext jobContext)
```

Seems it cannot clean the temp folder as it is supposed to do?

But the agent does have access to them:
```
$ ls -la _work
insgesamt 80
drwxr-xr-x 20 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:50 .
drwxr-xr-x  6 ***AGENT_USERNAME*** root     4096 Mai 27 13:06 ..
drwxr-xr-x  8 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 25 05:00 1
drwxr-xr-x  8 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:11 10
drwxr-xr-x  7 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:12 11
drwxr-xr-x  8 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 12
drwxr-xr-x  7 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:48 13
drwxr-xr-x  6 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 25 05:01 2
drwxr-xr-x  7 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 25 05:02 3
drwxr-xr-x  8 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 26 05:00 4
drwxr-xr-x  6 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 26 05:01 5
drwxr-xr-x  7 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 26 05:02 6
drwxr-xr-x  8 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 05:00 7
drwxr-xr-x  6 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 05:01 8
drwxr-xr-x  7 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 05:02 9
drwxr-xr-x  3 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 25 05:00 node_modules
drwxr-xr-x  4 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 26 05:01 SourceRootMapping
drwxr-xr-x  8 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 25 05:01 _tasks
drwxr-xr-x  2 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:50 _temp
drwxr-xr-x  2 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 25 05:00 _tool
[...]/microwave/_work$ ls -la 12
insgesamt 32
drwxr-xr-x  8 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 .
drwxr-xr-x 20 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:50 ..
drwxr-xr-x  2 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 a
drwxr-xr-x  2 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 b
drwxr-xr-x  6 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 ************
drwxr-xr-x  6 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 ************
drwxr-xr-x  2 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 s
drwxr-xr-x  2 ***AGENT_USERNAME*** ***AGENT_USERNAME*** 4096 Mai 27 14:47 TestResults
```

But that may be unrelated....

**Edit:** In other logs/runs, it seems to be some other random stuff that is cancelled:

* some enumeration:

```
[2022-05-27 12:01:33Z INFO BuildDirectoryManager] Checking if build directory exists: '/********/microwave/_work/10'
[2022-05-27 12:01:33Z ERR  BuildJobExtension] Caught cancellation exception from JobExtension Initialization: System.OperationCanceledException: The operation was canceled.
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, IList`1 repositories, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2022-05-27 12:01:33Z ERR  JobRunner] Job is canceled during initialize.
[2022-05-27 12:01:33Z ERR  JobRunner] Caught exception: System.OperationCanceledException: The operation was canceled.
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.DeleteDirectory(IExecutionContext executionContext, String description, String path)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.CreateDirectory(IExecutionContext executionContext, String description, String path, Boolean deleteExisting)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildDirectoryManager.PrepareDirectory(IExecutionContext executionContext, IList`1 repositories, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
```

* or something in `StepsRunner`:
```
[2022-05-27 12:46:43Z INFO JobServerQueue] Try to append 1 batches web console lines for record '2efb869f-462e-4d21-96d9-00f23825295f', success rate: 1/1.
[2022-05-27 12:46:43Z ERR  StepsRunner] Caught cancellation exception from step: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Container.DockerCommandManager.ExecuteDockerCommandAsync(IExecutionContext context, String command, String options, IList`1 standardIns, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Container.DockerCommandManager.DockerPull(IExecutionContext context, String image)
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.PullContainerAsync(IExecutionContext executionContext, ContainerInfo container)
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.PullContainerAsync(IExecutionContext executionContext, ContainerInfo container)
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
[2022-05-27 12:46:43Z INFO StepsRunner] Step result: Canceled
[2022-05-27 12:46:43Z INFO StepsRunner] No need for updating job result with current step result 'Canceled'.
[2022-05-27 12:46:43Z INFO StepsRunner] Current state: job state = 'Canceled'
[2022-05-27 12:46:43Z INFO StepsRunner] Processing step: DisplayName='Checkout *************** to ***************', ContinueOnError=False, Enabled=True
[2022-05-27 12:46:43Z INFO ExpressionManager] Evaluating: SucceededNode()
[2022-05-27 12:46:43Z INFO ExpressionManager] Result: False
[2022-05-27 12:46:43Z INFO StepsRunner] Skipping step due to condition evaluation.
[2022-05-27 12:46:43Z INFO StepsRunner] Processing step: DisplayName='Checkout *************** to ***************', ContinueOnError=False, Enabled=True
[2022-05-27 12:46:43Z INFO ExpressionManager] Evaluating: SucceededNode()
[2022-05-27 12:46:43Z INFO ExpressionManager] Result: False
[2022-05-27 12:46:43Z INFO StepsRunner] Skipping step due to condition evaluation.
[2022-05-27 12:46:43Z INFO StepsRunner] Processing step: DisplayName='Install sudo', ContinueOnError=False, Enabled=True
[2022-05-27 12:46:43Z INFO ExpressionManager] Evaluating: eq(variables['Agent.OS'], 'Linux')
[2022-05-27 12:46:43Z INFO ExpressionManager] Expanded: eq('Linux', 'Linux')
[2022-05-27 12:46:43Z INFO ExpressionManager] Result: True
[2022-05-27 12:46:43Z INFO StepsRunner] Starting the step.
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Bin': '/***PATH_TO_AGENTS****/microwave/bin'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Root': '/***PATH_TO_AGENTS****/microwave'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Work': '/***PATH_TO_AGENTS****/microwave/_work'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Tasks': '/***PATH_TO_AGENTS****/microwave/_work/_tasks'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Bin': '/***PATH_TO_AGENTS****/microwave/bin'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Root': '/***PATH_TO_AGENTS****/microwave'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Work': '/***PATH_TO_AGENTS****/microwave/_work'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'TaskZips': '/***PATH_TO_AGENTS****/microwave/_work/_taskzips'
[2022-05-27 12:46:43Z INFO TaskManager] Loading task definition '/***PATH_TO_AGENTS****/microwave/_work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.179.0/task.json'.
[2022-05-27 12:46:43Z INFO TaskRunner] Get handler data for target platform Linux
[2022-05-27 12:46:43Z INFO TaskRunner] Handler data is of type Microsoft.VisualStudio.Services.Agent.Worker.Node10HandlerData
[2022-05-27 12:46:43Z ERR  StepsRunner] Caught exception from step: System.ArgumentNullException: Value cannot be null. (Parameter 'ContainerId')
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
[2022-05-27 12:46:43Z INFO StepsRunner] Step result: Failed
[2022-05-27 12:46:43Z INFO StepsRunner] Update job result with current step result 'Failed'.
[2022-05-27 12:46:43Z INFO StepsRunner] Current state: job state = 'Canceled'
[2022-05-27 12:46:43Z INFO StepsRunner] Processing step: DisplayName='Install Powershell', ContinueOnError=False, Enabled=True
[2022-05-27 12:46:43Z INFO ExpressionManager] Evaluating: eq(variables['Agent.OS'], 'Linux')
[2022-05-27 12:46:43Z INFO ExpressionManager] Expanded: eq('Linux', 'Linux')
[2022-05-27 12:46:43Z INFO ExpressionManager] Result: True
[2022-05-27 12:46:43Z INFO StepsRunner] Starting the step.
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Bin': '/***PATH_TO_AGENTS****/microwave/bin'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Root': '/***PATH_TO_AGENTS****/microwave'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Work': '/***PATH_TO_AGENTS****/microwave/_work'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Tasks': '/***PATH_TO_AGENTS****/microwave/_work/_tasks'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Bin': '/***PATH_TO_AGENTS****/microwave/bin'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Root': '/***PATH_TO_AGENTS****/microwave'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'Work': '/***PATH_TO_AGENTS****/microwave/_work'
[2022-05-27 12:46:43Z INFO HostContext] Well known directory 'TaskZips': '/***PATH_TO_AGENTS****/microwave/_work/_taskzips'
[2022-05-27 12:46:43Z INFO TaskManager] Loading task definition '/***PATH_TO_AGENTS****/microwave/_work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.179.0/task.json'.
[2022-05-27 12:46:43Z INFO TaskRunner] Get handler data for target platform Linux
[2022-05-27 12:46:43Z INFO TaskRunner] Handler data is of type Microsoft.VisualStudio.Services.Agent.Worker.Node10HandlerData
[2022-05-27 12:46:43Z ERR  StepsRunner] Caught exception from step: System.ArgumentNullException: Value cannot be null. (Parameter 'ContainerId')
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
[2022-05-27 12:46:43Z INFO StepsRunner] Step result: Failed
[2022-05-27 12:46:43Z INFO StepsRunner] Update job result with current step result 'Failed'.
[2022-05-27 12:46:43Z INFO StepsRunner] Current state: job state = 'Canceled'
[2022-05-27 12:46:43Z INFO StepsRunner] Processing step: DisplayName='Debug: Show LFApp variables and parameters', ContinueOnError=False, Enabled=True
[2022-05-27 12:46:43Z INFO ExpressionManager] Evaluating: SucceededNode()
[2022-05-27 12:46:43Z INFO ExpressionManager] Result: False
[2022-05-27 12:46:43Z INFO StepsRunner] Skipping step due to condition evaluation.
[2022-05-27 12:46:43Z INFO StepsRunner] Processing step: DisplayName='Debug: Show all environment variables', ContinueOnError=False, Enabled=True
[2022-05-27 12:46:43Z INFO ExpressionManager] Evaluating: SucceededNode()
[2022-05-27 12:46:43Z INFO ExpressionManager] Result: False
```

### What should happen? / Questions
* IMHO, updating agents, even if it fails, should not cause a disruption -> the jobs should just stay in the queue
* Even if a technical error cancels them, there should be some error explaining why this was done, instead of the "silent cancelling" behavior as of now.
* And in case it shows an error: IMHO the error message with that ContainerId is absolutely confusing and should not be shown. Instead something that actually points to the error should be shown. As from what I think right now, that error is also just caused by the fact that the agent was stopped etc.
* Generally, why does the agent try to update to this version and what version should it actually use now?
   * I tried downgrading one agent to 2.181.2, i.e. the version the AzureDevOps server promotes and this just still causes it to update.  
   * Would it really be wise to update (i.e. still "downgrade") the agent to v2.195.2, which it apparently wants, even though the ADS server does not seem to have/recommend it (otherwise auto-update would work).
   * Also, why does the agent even try/does downgrades? Would not it be better if it really would only _upgrade_ and not downgrade itself? (Edit: just saw https://github.com/microsoft/azure-pipelines-agent/issues/3773, which seems to be related)

**Comment by KonstantinTyukalov** [comment]
You can send this logs to my email: v-ktyukalov@microsoft.com

**Comment by rklec** [comment]
The sanitized logs are linked as GitHub Gists under "Agent and Worker's Diagnostic Logs" in the original issue.

**Comment by rklec** [comment]
@KonstantinTyukalov Any news regarding this here?
