### ISSUE TITLE
Agent registration fails if pool name contains a space

### ISSUE THREAD

**Issue by arvindgorur** [microsoft/azure-pipelines-agent#3885]
## Agent Version and Platform
v2.204.0

OS of the machine running the agent? Windows 2016

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
When running config.cmd in unattended mode, the registration fails if the pool name contains a space. For example. if the pool name is "Test Pool", it errors out with the message:
```
 "Agent pool not found: ''Test'
```
Encountered this behaviour with both the current version and v2.200.0

The command that was run:
```
config.cmd --unattended --token <redacted> --agent agent007 --runAsService --windowsLogonAccount user@domain.com --windowsLogonPassword some_password --pool 'Test Pool' --url https://dev.azure.com/myorg/ --auth pat --acceptTeeEula"
```

## Agent and Worker's Diagnostic Logs
```
[2022-06-23 19:46:08Z INFO Terminal] WRITE LINE: 
[2022-06-23 19:46:08Z INFO Terminal] WRITE LINE: >> Register Agent:
[2022-06-23 19:46:08Z INFO Terminal] WRITE LINE: 
[2022-06-23 19:46:08Z INFO CommandSettings] Arg 'pool': ''Test'
[2022-06-23 19:46:08Z INFO CommandSettings] Flag 'unattended': 'True'
[2022-06-23 19:46:08Z ERR  Agent] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentPoolNotFoundException: Agent pool not found: ''Test'
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.GetPoolIdAndName(AgentSettings agentSettings, CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2022-06-23 19:46:08Z ERR  Terminal] WRITE ERROR: Agent pool not found: ''Test'
```

**Comment by AndreyIvanov42** [comment]
Thank you for the report. When we have enough resources, we will be able to take a closer look at this issue. As a workaround, you can use names without spaces for now

**Comment by ivanduplenskikh** [comment]
Hi, @arvindgorur.
Thanks for your report.
It's happened due to features of [Environment.GetCommandLineArgs Method](https://learn.microsoft.com/en-us/dotnet/api/system.environment.getcommandlineargs?view=net-7.0#remarks), especially:
`Command line arguments are delimited by spaces. You can use double quotation marks (") to include spaces within an argument. The single quotation mark ('), however, does not provide this functionality.`

**Comment by ivanduplenskikh** [comment]
@arvindgorur, we have not received a response from you. I'm closing this issue for now.
Please reopen if your issue is not resolved.
