### ISSUE TITLE
Individual CI doesn't work, while manual trigger works fine - Azure Devops Server - Self Signed Certificate 

### ISSUE THREAD

**Issue by sahin52** [microsoft/azure-pipelines-agent#3906]
I am using an Azure DevOps Server 2020 on my Windows 2019 server. And I use a git server (Bonobo) to have my repository (Selected other git, when configuring repository source). I use self signed certificate for this repository. 
In my Azure Devops Server, I set this config:  
```
git config --system http.sslverify "false"
git config --global http.sslverify "false"
```
since cert is self signed. Now, *when I run the pipeline manually, I can start the pipeline and it works like a charm* . But when it comes to Individual (automated) running, I get error. Here is the output (there is no log, this is from summary page):  
```
An exception occurred while polling the repository.  Error: Microsoft.TeamFoundation.Build2.Server.Extensions.ExternalConnectorException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.TeamFoundation.Build2.Server.Extensions.GitConnector.GetBranches(IVssRequestContext requestContext, ExternalConnection connection, Int32 timeoutSeconds, Boolean useAnonymousAccess)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.Build2.Server.Extensions.GitConnector.GetBranches(IVssRequestContext requestContext, ExternalConnection connection, Int32 timeoutSeconds, Boolean useAnonymousAccess)
   at Microsoft.TeamFoundation.Build2.Server.Extensions.GitSourceProvider.GetMatchingBranchRefs(IVssRequestContext requestContext, BuildDefinition definition, IList`1 branchFilters)
   at Microsoft.TeamFoundation.Build2.Server.Extensions.GitSourceProvider.GetSourceVersionsToBuild(IVssRequestContext requestContext, BuildDefinition definition, List`1 branchFilters, Boolean batchChanges, String previousVersionEvaluated, Dictionary`2& ciData, String& lastVersionEvaluated)
   at Microsoft.TeamFoundation.Build2.Server.Extensions.BuildPollingJobExtension.Run(IVssRequestContext requestContext, TeamFoundationJobDefinition jobDefinition, DateTime queueTime, String& resultMessage).
```

And when I look at git version of the server and git version of Azure devops server, they are different.  
The logs of Azure Devops Server webpage logs says 
```
git version
git version 2.28.0.windows.1
```
but when I check for git version from powershell, I get different version: 
```
git --version
git version 2.37.1.windows.1
```

I guess, the configurations for git is different for Azure Devops and for the server.  
I investigated even more, and found out that all git configs are looking for the same location. I guess the Individual automated run is running over a different structure. 

Taken from [this ticket](https://developercommunity.visualstudio.com/t/buildpollingjobextension-and-self-signed-certifica/290168): `But if TFS is using something else for polling for External Git repository rather then Git.exe (like some Web API)`  
I guess Azure Devops is using something other than Git.exe. Btw I haven't changed any configuration (other than git config command above) in server, you can test this with dev.azure.com and you will get the same results.

Edit: Oops I forgot to mention that I added `GIT_SSL_NO_VERIFY 1` setting in variables of pipeline variables.

**Comment by KonstantinTyukalov** [comment]
Hi @sahin52 thank you for reporting!
We are currently working on higher priority tickets, let us come back soon.

**Comment by sahin52** [comment]
I now understand, Individual CI is polling the repository in order to understand if there is a change, while manual trigger works when we click on run. The polling process is the cause of the error.

**Comment by sahin52** [comment]
Btw the solution to this problem is to have a proper https connection for the url. if it's self signed, or the certificate has timed out, you may face this problem. Closing the issue.
