### ISSUE TITLE
Azure Devops - Unable to update hosted agent from v2.202.0 to v2.204.0

### ISSUE THREAD

**Issue by deal0f49-21** [microsoft/azure-pipelines-agent#3912]
Updating the agent though DevOps page in the Agent Pool section does not update the agent to the latest version. It results in following error during the update and settles on the current version without any update.

**C:\agent\_work\_update\bin\Agent.Listener.dll does not have a valid MS signature.
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileSignedByMicrosoft(String filePath, Tracing trace, String expectedEKU)**

Event viewer shows this error
**An error occurred: Authenticode validation of agent assemblies failed.**
## Agent Version and Platform
Installed version of hosted agent ? 2.202.0

OS of the machine running the agent? Windows Server 2008 R2

## Azure DevOps Type and Version : dev.azure.com 

[2022-07-19 14:46:23Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2022-07-19 14:46:23Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2022-07-19 14:46:23Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2022-07-19 14:46:23Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2022-07-19 14:46:23Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2022-07-19 14:46:23Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2022-07-19 14:46:23Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2022-07-19 14:46:23Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2022-07-19 14:46:23Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2022-07-19 14:46:23Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2022-07-19 14:46:23Z INFO MessageListener] VssConnection created
[2022-07-19 14:46:24Z INFO MessageListener] Session created.
[2022-07-19 14:46:24Z INFO Terminal] WRITE LINE: 2022-07-19 14:46:24Z: Listening for Jobs
[2022-07-19 14:46:24Z INFO JobDispatcher] Set agent/worker IPC timeout to 30 seconds.
[2022-07-19 14:49:42Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2022-07-19 14:49:42Z INFO MessageListener] Message '753' received from session '3e611466-0279-43bf-926e-aa53d94d240e'.
[2022-07-19 14:49:42Z INFO ConfigurationStore] HasCredentials()
[2022-07-19 14:49:42Z INFO ConfigurationStore] stored True
[2022-07-19 14:49:42Z INFO CredentialManager] GetCredentialProvider
[2022-07-19 14:49:42Z INFO CredentialManager] Creating type OAuth
[2022-07-19 14:49:42Z INFO CredentialManager] Creating credential type: OAuth
[2022-07-19 14:49:42Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2022-07-19 14:49:42Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2022-07-19 14:49:42Z INFO SelfUpdater] Version '2.204.0' of 'agent' package available in server.
[2022-07-19 14:49:42Z INFO SelfUpdater] Current running agent version is 2.202.0
[2022-07-19 14:49:42Z INFO SelfUpdater] An update is available.
[2022-07-19 14:49:42Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2022-07-19 14:49:42Z INFO Terminal] WRITE LINE: Downloading 2.204.0 agent
[2022-07-19 14:49:42Z INFO HostContext] Well known directory 'Bin': 'C:\agent\bin'
[2022-07-19 14:49:42Z INFO HostContext] Well known directory 'Root': 'C:\agent'
[2022-07-19 14:49:42Z INFO HostContext] Well known directory 'Work': 'C:\agent\_work'
[2022-07-19 14:49:42Z INFO SelfUpdater] Attempt 1: save latest agent into C:\agent\_work\_update\agent1.zip.
[2022-07-19 14:49:42Z INFO SelfUpdater] Download agent: begin download
[2022-07-19 14:49:44Z INFO SelfUpdater] Download agent: finished download
[2022-07-19 14:49:46Z INFO SelfUpdater] Checksum validation succeeded
[2022-07-19 14:49:48Z INFO SelfUpdater] Finished getting latest agent package at: C:\agent\_work\_update.
[2022-07-19 14:49:48Z INFO SelfUpdater] File C:\agent\_work\_update\bin\Agent.Listener.dll has a valid authenticode signature.
[2022-07-19 14:49:48Z ERR  SelfUpdater] Microsoft.VisualStudio.Services.Agent.Listener.VerificationException: File C:\agent\_work\_update\bin\Agent.Listener.dll does not have a valid MS signature.
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileSignedByMicrosoft(String filePath, Tracing trace, String expectedEKU)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.VerifyAgentAuthenticode(String agentFolderPath)
[2022-07-19 14:49:48Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2022-07-19 14:49:48Z ERR  Terminal] WRITE ERROR: An error occurred: Authenticode validation of agent assemblies failed.
[2022-07-19 14:49:48Z ERR  AgentProcess] System.Exception: Authenticode validation of agent assemblies failed.
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)

**Comment by KonstantinTyukalov** [comment]
Hi @deal0f49-21!
We support Windows Server starting from version [2012](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#check-prerequisites)
We are not supporting Windows Server 2008.
This problem is not reproduced on newer operating systems.

Is it possible in your case to upgrade to a newer version of Windows Server to meet our requirements?

Thank you

**Comment by KonstantinTyukalov** [comment]
@deal0f49-21 let me close this issue as we are not supporting Windows Server 2008.
Please let us know if you have any questions.
Thanks
