### ISSUE TITLE
The bearer is not valid until

### ISSUE THREAD

**Issue by rui-tsg-je** [microsoft/azure-pipelines-agent#3919]
I have created a release pipeline in the Azure DevOps and I have installed Azure Agent in a Windows 2019. 
The Azure Pipeline Agent service fails to start.

Agent Version and Platform
Installed version of hosted agent ? v2.202.1

OS of the machine running the agent? Windows Server 2019

Azure DevOps Type and Version : dev.azure.com

Agent and Worker's Diagnostic Logs
```
[2022-07-25 09:16:52Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\azagent\A1\.credentials_rsaparams
[2022-07-25 09:16:53Z ERR  VisualStudioServices] POST request to https://vssps.dev.azure.com/aaaaaaa/_apis/oauth2/token failed. HTTP Status: BadRequest, AFD Ref: Ref A: F7D481FAA81C4E9C97D4CD720CA079EE Ref B: LON21EDGE1211 Ref C: 2022-07-25T08:17:00Z
[2022-07-25 09:16:53Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2022-07-25 09:16:53Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2022-07-25 09:16:53Z ERR  MessageListener] Catch exception during create session.
[2022-07-25 09:16:53Z ERR  MessageListener] Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenRequestException: The bearer <secret removed> is not valid until 7/25/2022 9:16:53 AM. Current server time is 7/25/2022 8:17:00 AM.
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.ConnectAsync(Uri serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.CreateSessionAsync(CancellationToken token)
[2022-07-25 09:16:53Z INFO MessageListener] Local clock might skewed.
[2022-07-25 09:16:53Z ERR  Terminal] WRITE ERROR: The local machine's clock may be out of sync with the server time by more than five minutes. Please sync your clock with your domain or internet time and try again.
[2022-07-25 09:16:53Z INFO MessageListener] The OAuth token request exception haven't reached retry limit.
[2022-07-25 09:16:53Z ERR  Terminal] WRITE ERROR: 2022-07-25 09:16:53Z: Agent connect error: The bearer <secret removed> is not valid until 7/25/2022 9:16:53 AM. Current server time is 7/25/2022 8:17:00 AM.. Retrying until reconnected.
[2022-07-25 09:16:53Z INFO MessageListener] Sleeping for 30 seconds before retrying.
```

These are server Date and Time Settings

![image](https://user-images.githubusercontent.com/40278369/180737258-f9b4ef2f-ab23-44b5-bf2d-59c72421a49f.png)

Due to legacy software installed in the server this Date and time settings are required.

**Comment by DenisRumyantsev** [comment]
Hi, @rui-tsg-je, thanks for reporting this issue. We will take a look at it when we finish working on more prioritized issues.

**Comment by mkArtak** [comment]
One of my self hosted agents wasn't starting. Checked the logs and have a similar issue. The agent was running fine up until this point. Checked the PAT and it's not expired. So not sure what can be the cause.

**Comment by mkArtak** [comment]
Turns out this was due to clock mismatch between the AZDO servers and the agent VM time. The clock has changed today but the VM didn't update the time yet. So fixing the clock resulted in the agent to start up successfully again.
