### ISSUE TITLE
Unable to connect to https://dev.azure.com/{organization}. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by vishnuprakash9845** [microsoft/azure-pipelines-agent#3977]
### Agent Version and Platform
v.2.210.1 and Windows 10 OS and 8 GB RAM 

### Azure DevOps Type and Version
On-premises Azure DevOps Server

### What's not working?
We are unable to configure self hosted agents (tested with the three VM's mentioned above with same configurations), they fail with "Unable to connect to https://dev.azure.com/{organization}. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

### Followed below steps

1-Virtual Machine has Windows 10 OS and 8 GB RAM 
2-Downloaded the latest Agent (2.210.1) from Devops Server and Extracted it
3- Invoked the config.cmd from CMD and entered the details

Server URL :  https://dev.azure.com/{organization}
PAT Token : xxxxxxxxxxxxxxxx

then it will wait for some time (60-90 ) seconds then it will display the following error

### Agent and Worker's Diagnostic Logs

[2022-09-28 10:26:41Z INFO AgentProcess] Agent package win-x64.
[2022-09-28 10:26:41Z INFO AgentProcess] Running on Windows (X64).
[2022-09-28 10:26:41Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.20348.
[2022-09-28 10:26:41Z INFO AgentProcess] Version: 2.210.1
[2022-09-28 10:26:41Z INFO AgentProcess] Commit: fae6a0b2b5df0e047d
[2022-09-28 10:26:41Z INFO AgentProcess] Culture: en-IN
[2022-09-28 10:26:41Z INFO AgentProcess] UI Culture: en-US
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO AgentProcess] Validating directory permissions for: 'C:\Agent'
[2022-09-28 10:26:41Z INFO PowerShellExeUtil] Generation: '1'
[2022-09-28 10:26:41Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2022-09-28 10:26:41Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2022-09-28 10:26:41Z INFO PowerShellExeUtil] Generation: '3'
[2022-09-28 10:26:41Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.20348.1'
[2022-09-28 10:26:41Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2022-09-28 10:26:41Z INFO AgentProcess]  'CDF'
[2022-09-28 10:26:41Z INFO AgentProcess]  'v4'
[2022-09-28 10:26:41Z INFO AgentProcess]  'v4.0'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2022-09-28 10:26:41Z INFO AgentProcess]  'Client'
[2022-09-28 10:26:41Z INFO AgentProcess]  'Full'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.8.04161'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '528449'
[2022-09-28 10:26:41Z INFO AgentProcess] Type is System.Int32
[2022-09-28 10:26:41Z INFO AgentProcess] Interpreted version: 4.7.0
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.8.04161'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '528449'
[2022-09-28 10:26:41Z INFO AgentProcess] Type is System.Int32
[2022-09-28 10:26:41Z INFO AgentProcess] Interpreted version: 4.7.0
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2022-09-28 10:26:41Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2022-09-28 10:26:41Z INFO AgentProcess] Found 2 versions:
[2022-09-28 10:26:41Z INFO AgentProcess]  4.7.0
[2022-09-28 10:26:41Z INFO AgentProcess]  4.7.0
[2022-09-28 10:26:41Z INFO AgentProcess] Testing for min NET Framework version: '4.5'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Setting up value for origin: Configure.Password
[2022-09-28 10:26:41Z INFO HostContext] Value is empty.
[2022-09-28 10:26:41Z INFO HostContext] Setting up value for origin: Configure.ProxyPassword
[2022-09-28 10:26:41Z INFO HostContext] Value is empty.
[2022-09-28 10:26:41Z INFO HostContext] Setting up value for origin: Configure.SslClientCert
[2022-09-28 10:26:41Z INFO HostContext] Value is empty.
[2022-09-28 10:26:41Z INFO HostContext] Setting up value for origin: Configure.Token
[2022-09-28 10:26:41Z INFO HostContext] Value is empty.
[2022-09-28 10:26:41Z INFO HostContext] Setting up value for origin: Configure.WindowsLogonPassword
[2022-09-28 10:26:41Z INFO HostContext] Value is empty.
[2022-09-28 10:26:41Z INFO CommandSettings] Configure {
  "AcceptTeeEula": false,
  "AddDeploymentGroupTags": false,
  "AddEnvironmentVirtualMachineResourceTags": false,
  "AddMachineGroupTags": false,
  "AlwaysExtractTask": false,
  "Agent": null,
  "CollectionName": null,
  "DeploymentGroup": false,
  "DeploymentGroupName": null,
  "DeploymentGroupTags": null,
  "DeploymentPool": false,
  "DeploymentPoolName": null,
  "EnableServiceSidTypeUnrestricted": false,
  "EnvironmentVMResource": false,
  "EnvironmentName": null,
  "EnvironmentVMResourceTags": null,
  "GitUseSChannel": false,
  "DisableLogUploads": false,
  "MachineGroup": false,
  "MachineGroupName": null,
  "MachineGroupTags": null,
  "MonitorSocketAddress": null,
  "NotificationPipeName": null,
  "NotificationSocketAddress": null,
  "NoRestart": false,
  "OverwriteAutoLogon": false,
  "Pool": null,
  "ProjectName": null,
  "ProxyPassword": null,
  "ProxyUserName": null,
  "ProxyUrl": null,
  "Replace": false,
  "RunAsAutoLogon": false,
  "RunAsService": false,
  "RunOnce": false,
  "PreventServiceStart": false,
  "SslCACert": null,
  "SslClientCert": null,
  "SslClientCertArchive": null,
  "SslClientCertKey": null,
  "SslClientCertPassword": null,
  "SslSkipCertValidation": false,
  "Url": null,
  "WindowsLogonAccount": null,
  "WindowsLogonPassword": null,
  "Work": null,
  "Auth": null,
  "LaunchBrowser": false,
  "Password": null,
  "Token": null,
  "Unattended": false,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2022-09-28 10:26:41Z INFO AgentProcess] Arguments parsed
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'Proxy': 'C:\Agent\.proxy'
[2022-09-28 10:26:41Z INFO VstsAgentWebProxy] No proxy setting found.
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'Certificates': 'C:\Agent\.certificates'
[2022-09-28 10:26:41Z INFO AgentCertificateManager] No certificate setting found.
[2022-09-28 10:26:41Z INFO Agent] ExecuteCommand
[2022-09-28 10:26:41Z INFO ConfigurationStore] currentAssemblyLocation: C:\Agent\bin\Agent.Listener.dll
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO ConfigurationStore] binPath: C:\Agent\bin
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO ConfigurationStore] RootFolder: C:\Agent
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'Agent': 'C:\Agent\.agent'
[2022-09-28 10:26:41Z INFO ConfigurationStore] ConfigFilePath: C:\Agent\.agent
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'Credentials': 'C:\Agent\.credentials'
[2022-09-28 10:26:41Z INFO ConfigurationStore] CredFilePath: C:\Agent\.credentials
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'Service': 'C:\Agent\.service'
[2022-09-28 10:26:41Z INFO ConfigurationStore] ServiceConfigFilePath: C:\Agent\.service
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'Autologon': 'C:\Agent\.autologon'
[2022-09-28 10:26:41Z INFO ConfigurationStore] AutoLogonSettingsFilePath: C:\Agent\.autologon
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'Options': 'C:\Agent\.options'
[2022-09-28 10:26:41Z INFO ConfigurationStore] RuntimeOptionsFilePath: C:\Agent\.options
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO HostContext] Well known config file 'SetupInfo': 'C:\Agent\.setup_info'
[2022-09-28 10:26:41Z INFO ConfigurationStore] SetupInfoFilePath: C:\Agent\.setup_info
[2022-09-28 10:26:41Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.210.1             |_|          (commit fae6a0b)

[2022-09-28 10:26:41Z INFO ConfigurationManager] CheckAgentRootDirectorySecure
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Bin': 'C:\Agent\bin'
[2022-09-28 10:26:41Z INFO HostContext] Well known directory 'Root': 'C:\Agent'
[2022-09-28 10:26:41Z INFO ConfigurationManager] ConfigureAsync
[2022-09-28 10:26:41Z INFO ConfigurationStore] IsConfigured()
[2022-09-28 10:26:41Z INFO ConfigurationStore] IsConfigured: False
[2022-09-28 10:26:41Z INFO ConfigurationManager] Is configured: False
[2022-09-28 10:26:41Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2022-09-28 10:26:41Z INFO ConfigurationManager] Testing for min NET Framework version: '4.6'
[2022-09-28 10:26:41Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2022-09-28 10:26:41Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2022-09-28 10:26:41Z INFO CommandSettings] Flag 'environment': 'False'
[2022-09-28 10:26:41Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2022-09-28 10:26:41Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2022-09-28 10:26:41Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2022-09-28 10:26:41Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2022-09-28 10:26:41Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2022-09-28 10:26:42Z INFO Terminal] WRITE LINE: 
[2022-09-28 10:26:42Z INFO Terminal] WRITE LINE: >> Connect:
[2022-09-28 10:26:42Z INFO Terminal] WRITE LINE: 
[2022-09-28 10:26:42Z INFO CommandSettings] Arg 'url': ''
[2022-09-28 10:26:42Z INFO CommandSettings] Flag 'unattended': 'False'
[2022-09-28 10:26:42Z INFO PromptManager] ReadValue
[2022-09-28 10:26:42Z INFO Terminal] WRITE: Enter server URL > 
[2022-09-28 10:26:42Z INFO Terminal] READ LINE
[2022-09-28 10:27:00Z INFO Terminal] Read value: 'https://dev.azure.com/{ORGANIZATION}'
[2022-09-28 10:27:00Z INFO ConfigurationManager] GetCredentialProvider
[2022-09-28 10:27:00Z INFO CommandSettings] Arg 'auth': ''
[2022-09-28 10:27:00Z INFO CommandSettings] Flag 'unattended': 'False'
[2022-09-28 10:27:00Z INFO PromptManager] ReadValue
[2022-09-28 10:27:00Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2022-09-28 10:27:00Z INFO Terminal] READ LINE
[2022-09-28 10:27:02Z INFO Terminal] Read value: ''
[2022-09-28 10:27:02Z INFO PromptManager] Falling back to the default: 'PAT'
[2022-09-28 10:27:02Z INFO ConfigurationManager] Creating credential for auth: PAT
[2022-09-28 10:27:02Z INFO CredentialManager] GetCredentialProvider
[2022-09-28 10:27:02Z INFO CredentialManager] Creating type PAT
[2022-09-28 10:27:02Z INFO CredentialManager] Creating credential type: PAT
[2022-09-28 10:27:02Z INFO PersonalAccessToken] EnsureCredential
[2022-09-28 10:27:02Z INFO CommandSettings] Arg 'token': ''
[2022-09-28 10:27:02Z INFO CommandSettings] Flag 'unattended': 'False'
[2022-09-28 10:27:02Z INFO PromptManager] ReadValue
[2022-09-28 10:27:02Z INFO Terminal] WRITE: Enter personal access token > 
[2022-09-28 10:27:02Z INFO Terminal] READ SECRET
[2022-09-28 10:27:36Z INFO HostContext] Setting up value for origin: Terminal.ReadSecret
[2022-09-28 10:27:36Z INFO Terminal] Read value: '***'
[2022-09-28 10:27:36Z INFO PersonalAccessToken] GetVssCredentials
[2022-09-28 10:27:36Z INFO PersonalAccessToken] token retrieved: 52 chars
[2022-09-28 10:27:36Z INFO PersonalAccessToken] cred created
[2022-09-28 10:27:36Z INFO ConfigurationManager] cred retrieved
[2022-09-28 10:27:36Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2022-09-28 10:28:08Z WARN VisualStudioServices] Attempt 1 of GET request to https://dev.azure.com/{ORGANIZATION}/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: TimedOut). The operation will be retried in 10.9719504 seconds.
[2022-09-28 10:28:40Z WARN VisualStudioServices] Attempt 2 of GET request to https://dev.azure.com/{ORGANIZATION}/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: TimedOut). The operation will be retried in 13.0596796 seconds.
[2022-09-28 10:29:14Z WARN VisualStudioServices] Attempt 3 of GET request to https://dev.azure.com/{ORGANIZATION}/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: TimedOut). The operation will be retried in 15.8620456 seconds.
[2022-09-28 10:29:51Z ERR  VisualStudioServices] Attempt 4 of GET request to https://dev.azure.com/{ORGANIZATION}/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: TimedOut). The maximum number of attempts has been reached.
[2022-09-28 10:29:51Z INFO VisualStudioServices] Finished operation Location.GetConnectionData

**[2022-09-28 10:29:51Z INFO LocationServer] _Unable to connect to https://dev.azure.com/{ORGANIZATION}.
[2022-09-28 10:29:51Z ERR  LocationServer] System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
[2022-09-28 10:29:51Z INFO CommandSettings] Flag 'unattended': 'False'
[2022-09-28 10:29:51Z ERR  Terminal] WRITE ERROR (exception):
[2022-09-28 10:29:51Z ERR  Terminal] System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.GetConnectionData(String serverUrl, VssCredentials credentials, ILocationServer locationServer)
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.DetermineDeploymentType(String serverUrl, VssCredentials credentials, ILocationServer locationServer)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)_**

[2022-09-28 10:29:51Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2022-09-28 10:29:51Z INFO CommandSettings] Arg 'url': ''
[2022-09-28 10:29:51Z INFO CommandSettings] Flag 'unattended': 'False'
[2022-09-28 10:29:51Z INFO PromptManager] ReadValue
[2022-09-28 10:29:51Z INFO Terminal] WRITE: Enter server URL > 
[2022-09-28 10:29:51Z INFO Terminal] READ LINE

**Comment by vishnuprakash9845** [comment]
> Hi @vishnuprakash9845, could you please confirm that the organization you try to configure agent for is accessible via browser on affected VMs?

Yes, we tried on the VM's. We are able to access URL.

**Comment by smjltd** [comment]
same thing happening on Azyre DevOps Server with self hosted Agents.
