### ISSUE TITLE
Can't remove registered agent

### ISSUE THREAD

**Issue by digital88** [microsoft/azure-pipelines-agent#4006]
Agent version: 2.196.2
Platform: win-x64
OS: Microsoft Windows

When I try to remove existing agent by executing command "config.cmd remove" it crashes. Can you please tell me manual steps I need to do to completly remove agent, I want to reinstall this agent with different settings. This agent was registered by different user, maybe this is the cause of error.

Here is complete crash log:

[2022-10-25 15:52:25Z INFO AgentProcess] Agent package win-x64.
[2022-10-25 15:52:25Z INFO AgentProcess] Running on Windows (X64).
[2022-10-25 15:52:25Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 6.3.9600.
[2022-10-25 15:52:25Z INFO AgentProcess] Version: 2.196.2
[2022-10-25 15:52:25Z INFO AgentProcess] Commit: 857ee0a007816cefe5752aff035de33c800bfb6b
[2022-10-25 15:52:25Z INFO AgentProcess] Culture: ru-RU
[2022-10-25 15:52:25Z INFO AgentProcess] UI Culture: en-US
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Bin': 'C:\AzureAgent\bin'
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Root': 'C:\AzureAgent'
[2022-10-25 15:52:25Z INFO AgentProcess] Validating directory permissions for: 'C:\AzureAgent'
[2022-10-25 15:52:25Z INFO PowerShellExeUtil] Generation: '1'
[2022-10-25 15:52:25Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2022-10-25 15:52:25Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2022-10-25 15:52:25Z INFO PowerShellExeUtil] Generation: '3'
[2022-10-25 15:52:25Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.14409.1005'
[2022-10-25 15:52:25Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2022-10-25 15:52:25Z INFO AgentProcess]  'CDF'
[2022-10-25 15:52:25Z INFO AgentProcess]  'v2.0.50727'
[2022-10-25 15:52:25Z INFO AgentProcess]  'v3.0'
[2022-10-25 15:52:25Z INFO AgentProcess]  'v3.5'
[2022-10-25 15:52:25Z INFO AgentProcess]  'v4'
[2022-10-25 15:52:25Z INFO AgentProcess]  'v4.0'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Version': '2.0.50727.4927'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Install': '1'
[2022-10-25 15:52:25Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727'
[2022-10-25 15:52:25Z INFO AgentProcess] Found version: 2.0.50727
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version': '3.0.30729.4926'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Install': '1'
[2022-10-25 15:52:25Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.0'
[2022-10-25 15:52:25Z INFO AgentProcess] Found version: 3.0
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Version': '3.5.30729.4926'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Install': '1'
[2022-10-25 15:52:25Z INFO AgentProcess] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.5'
[2022-10-25 15:52:25Z INFO AgentProcess] Found version: 3.5
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2022-10-25 15:52:25Z INFO AgentProcess]  'Client'
[2022-10-25 15:52:25Z INFO AgentProcess]  'Full'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.8.03761'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '528049'
[2022-10-25 15:52:25Z INFO AgentProcess] Type is System.Int32
[2022-10-25 15:52:25Z INFO AgentProcess] Interpreted version: 4.7.0
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.8.03761'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '528049'
[2022-10-25 15:52:25Z INFO AgentProcess] Type is System.Int32
[2022-10-25 15:52:25Z INFO AgentProcess] Interpreted version: 4.7.0
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2022-10-25 15:52:25Z INFO AgentProcess] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2022-10-25 15:52:25Z INFO AgentProcess] Found 5 versions:
[2022-10-25 15:52:25Z INFO AgentProcess]  2.0.50727
[2022-10-25 15:52:25Z INFO AgentProcess]  3.0
[2022-10-25 15:52:25Z INFO AgentProcess]  3.5
[2022-10-25 15:52:25Z INFO AgentProcess]  4.7.0
[2022-10-25 15:52:25Z INFO AgentProcess]  4.7.0
[2022-10-25 15:52:25Z INFO AgentProcess] Testing for min NET Framework version: '4.5'
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Bin': 'C:\AzureAgent\bin'
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Root': 'C:\AzureAgent'
[2022-10-25 15:52:25Z INFO CommandSettings] Remove {
  "Auth": null,
  "LaunchBrowser": false,
  "Password": null,
  "Token": null,
  "Unattended": false,
  "UserName": null,
  "Help": false,
  "Version": false
}
[2022-10-25 15:52:25Z INFO AgentProcess] Arguments parsed
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Bin': 'C:\AzureAgent\bin'
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Root': 'C:\AzureAgent'
[2022-10-25 15:52:25Z INFO HostContext] Well known config file 'Proxy': 'C:\AzureAgent\.proxy'
[2022-10-25 15:52:25Z INFO VstsAgentWebProxy] Config proxy at: http://proxy-address(redacted):8080.
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Bin': 'C:\AzureAgent\bin'
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Root': 'C:\AzureAgent'
[2022-10-25 15:52:25Z INFO HostContext] Well known config file 'ProxyCredentials': 'C:\AzureAgent\.proxycredentials'
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Bin': 'C:\AzureAgent\bin'
[2022-10-25 15:52:25Z INFO HostContext] Well known directory 'Root': 'C:\AzureAgent'
[2022-10-25 15:52:25Z INFO HostContext] Well known config file 'CredentialStore': 'C:\AzureAgent\.credential_store'
[2022-10-25 15:52:25Z ERR  Terminal] WRITE ERROR: CredRead throw an error for 'VSTS_AGENT_PROXY_43F8A9B6-1733-43F6-A8FC-6122D7F89209'
[2022-10-25 15:52:25Z ERR  AgentProcess] System.ComponentModel.Win32Exception (1168): CredRead throw an error for 'VSTS_AGENT_PROXY_43F8A9B6-1733-43F6-A8FC-6122D7F89209'
   at Microsoft.VisualStudio.Services.Agent.WindowsAgentCredentialStore.Read(String target)
   at Microsoft.VisualStudio.Services.Agent.VstsAgentWebProxy.LoadProxySetting()
   at Microsoft.VisualStudio.Services.Agent.VstsAgentWebProxy.Initialize(IHostContext context)
   at Microsoft.VisualStudio.Services.Agent.HostContext.CreateService[T]()
   at Microsoft.VisualStudio.Services.Agent.HostContext.GetService[T]()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)

**Comment by digital88** [comment]
Ok, fixed it.

Step 1. Delete .proxyconfig
Step 2. In cmd do: 
set VSTS_HTTP_PROXY=http://proxy-address:8080
set VSTS_HTTP_PROXY_USERNAME=username
set VSTS_HTTP_PROXY_PASSWORD=secret_password

Then run "config.cmd remove"
