### ISSUE TITLE
[BUG]: Agent 3.214.0 on M2 ARM 64 agents cancels builds instead of queueing 

### ISSUE THREAD

**Issue by vincentcastagna** [microsoft/azure-pipelines-agent#4205]
### What happened?

We have a self-hosted pool of agents running on M2 mac machine (ARM64).

It seems that each time a project request an agent to do a job, if one agent of the given pool was already running a build/job on another project, it would cancel the build of the other project in favor of the new one, instead of simply Queuing the new job. 

This is a major issue as many projects builds at the same time on this pool, cancelling each other, each time the same agent is selected but running. 

It doesn't seem to be consistent though. Sometimes it would cancel the build, sometimes it wouldn't and will let two agents run from the same pool. Sometimes it would just cancel it, even if the agent selected is different from the one running. 

**EDIT** : I was able to find a workaround for that, which is to UNCHECK **Allow agents in this pool to automatically update** 

![image](https://user-images.githubusercontent.com/15191066/225701927-afeca303-3c49-4386-8684-60b8c28bf7c3.png)

**Note** : I also tried to update the agent version used, to be 3.217.1 from ADO UI, which is the latest release, but it doesn't work. Agents are still running on 3.214.0, high chances it's related. 

### Versions

AzureDevops agent 3.214.0 

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ventura 13.2

### Relevant log output

```shell
##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

**Comment by sergey-koryshev** [comment]
Hi @vincentcastagna, could you please share full diagnostic logs from the affected agent, you can send it on my email v-skoryshev@microsoft.com. And please send us link to last affected build.

**Comment by vincentcastagna** [comment]
@sergey-koryshev will provide the full diag logs to the given email in the coming days. Will not be possible to share the link to the build as it is a private ADO project.

**Comment by sergey-koryshev** [comment]
@vincentcastagna, the link will be helpful for us since we can to investigate telemetry of it despite it's private, but we need link to last repro since telemetry is not stored for long time.
