### ISSUE TITLE
[Question]:  tasks downloading proxy support

### ISSUE THREAD

**Issue by a-dawg** [microsoft/azure-pipelines-agent#4228]
### Describe your question

I have to use a proxy for any outgoing connections. It looks like proxyurl from the docs is only used for source code and artifacts. When triggering a build, the linux azuredevop agent first download the required tasks. It fails when using the proxyurl parameters or add my http_proxy vars to  the .env file or setting the proxy on my entire system (auth check fails for agent then)

whats is the recommended configuration?

### Versions

3.128

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

rhel8

**Comment by DmitriiBobreshev** [comment]
Hi @a-dawg, thank you for the question, when you pass --proxyurl argument all traffic from the agent(from the task itself it working via [task-lib](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/docs/proxy.md)) should go through the proxy. 
I've checked it with my agent and seems like everything works fine, the URL for the task is https://dev.azure.com/%orgName%/_apis/distributedtask/tasks/%taskId%/%taskVersion%. 
Could you please check that the URL allowed under the proxy, also could you please share the pipeline failed [diagnostic logs](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)?

**Comment by a-dawg** [comment]
thanks for your response. here is the job diagnostic log:
````
Starting: Initialize job
Agent name: 'ocpadmin'
Agent machine name: 'xxxx'
Current agent version: '3.218.0'
Agent running as: 'root'
Agent is running behind proxy server: 'http://proxy.xxxx:xxxx'/
##[debug]Triggering repository: ***-dashboard. repository type: Git
Prepare build directory.
##[debug]Delete existing artifacts directory: '/opt/azuredevops_agent/1/a'
##[debug]Deleting artifacts directory: '/opt/azuredevops_agent/1/a'
##[debug]Creating artifacts directory: '/opt/azuredevops_agent/1/a'
##[debug]Delete existing test results directory: '/opt/azuredevops_agent/1/TestResults'
##[debug]Deleting test results directory: '/opt/azuredevops_agent/1/TestResults'
##[debug]Creating test results directory: '/opt/azuredevops_agent/1/TestResults'
Set build variables.
Download all required tasks.
Downloading task: Bash (3.214.0)
##[warning]Failed to download task 'Bash'. Error Service Unavailable
##[warning]Back off 27.106 seconds before retry.
##[warning]Failed to download task 'Bash'. Error Service Unavailable
##[warning]Back off 20.055 seconds before retry.
##[warning]Failed to download task 'Bash'. Error Service Unavailable
##[error]Service Unavailable
##[debug]Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Service Unavailable
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentHttpClient.GetTaskContentZipAsync(Guid taskId, TaskVersion version, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, TaskStepDefinitionReference task) in /home/vsts/work/1/s/src/Agent.Worker/TaskManager.cs:line 213
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, IEnumerable`1 steps) in /home/vsts/work/1/s/src/Agent.Worker/TaskManager.cs:line 76
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message) in /home/vsts/work/1/s/src/Agent.Worker/JobExtension.cs:line 106
Finishing: Initialize job
````

I do not see any denies in my proxy logs, so I assume for this part the agent does not go through the proxy, as the docs seems to suggest it.

**Comment by DmitriiBobreshev** [comment]
@a-dawg Thank you for the logs. Could you please tell us the proxy server you're using and share the proxy configuration if it's possible to reproduce the error?
