### ISSUE TITLE
[BUG]: Agent Kerberos authentication

### ISSUE THREAD

**Issue by aqustiq** [microsoft/azure-pipelines-agent#4229]
### What happened?

Configured IIS to work in Kerberos mode only on Azure DevOps 2020.1.2 server.
Login from browser works but when I try to register DevOps Agent with the same credentials I get error
`VS30063: You are not authorized to access https://devops20prod.internal.xxxx.xx.`
Same result If I use PAT authentication.
In both cases in the logs shows that Agent tries to establish only NTLM authentication.

Does agent support Kerberos authentication?

### Versions

Azure DevOps Agent 3.218.0 / RHEL 9

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2020.1.2

### Operation system

Windows Server 2022

### Relevant log output

```shell
[2023-04-04 17:56:08Z INFO RSAFileKeyManager] Loading RSA key parameters from file /XXXX/vsts-agent/.credentials_rsaparams
[2023-04-04 17:56:08Z ERR  VisualStudioServices] POST request to https://devops20prod.internal.XXXX.xx/_apis/oauth2/token failed. HTTP Status: Unauthorized
[2023-04-04 17:56:08Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2023-04-04 17:56:08Z ERR  VisualStudioServices] OAuth issued token provider instance 16014678 failed to retrieve a token.
Reason: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenHttpClient.GetTokenAsync(VssOAuthGrant grant, VssOAuthClientCredential credential, VssOAuthTokenParameters tokenParameters, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
[2023-04-04 17:56:08Z WARN VisualStudioServices] Authentication failed with status code 401.
X-TFS-ProcessId: a01a594e-81c6-4b39-b229-15edd3ba4517
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: 7d6bdd99-6bcf-4218-af1c-261623699645
X-TFS-Session: 0c68b543-8f22-4100-9c2e-761f51742027
X-VSS-E2EID: 9c1a1439-ab0d-4a64-9511-a25fdab38926
WWW-Authenticate: Bearer, Basic realm="https://devops20prod.internal.XXXX.xx/", Negotiate
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Tue, 04 Apr 2023 17:56:08 GMT

[2023-04-04 17:56:08Z INFO RSAFileKeyManager] Loading RSA key parameters from file /XXXX/vsts-agent/.credentials_rsaparams
[2023-04-04 17:56:08Z ERR  VisualStudioServices] POST request to https://devops20prod.internal.XXXX.xx/_apis/oauth2/token failed. HTTP Status: Unauthorized
[2023-04-04 17:56:08Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2023-04-04 17:56:08Z ERR  VisualStudioServices] OAuth issued token provider instance 16014678 failed to retrieve a token.
Reason: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenHttpClient.GetTokenAsync(VssOAuthGrant grant, VssOAuthClientCredential credential, VssOAuthTokenParameters tokenParameters, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
[2023-04-04 17:56:08Z WARN VisualStudioServices] Authentication failed with status code 401.
X-TFS-ProcessId: a01a594e-81c6-4b39-b229-15edd3ba4517
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: 7d6bdd9b-6bcf-4218-af1c-261623699645
X-TFS-Session: 0c68b543-8f22-4100-9c2e-761f51742027
X-VSS-E2EID: 9c1a1439-ab0d-4a64-9511-a25fdab38926
WWW-Authenticate: Bearer, Basic realm="https://devops20prod.internal.XXXX.xx/", Negotiate
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Tue, 04 Apr 2023 17:56:08 GMT

[2023-04-04 17:56:08Z ERR  VisualStudioServices] GET request to https://devops20prod.internal.XXXX.xx/_apis/connectionData?connectOptions=0&lastChangeId=22&lastChangeId64=22 is not authorized. Details: VS30063: You are not authorized to access https://devops20prod.internal.XXXX.xx.
[2023-04-04 17:56:08Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2023-04-04 17:56:08Z ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://devops20prod.internal.XXXX.xx.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/AgentServer.cs:line 214
   at Microsoft.VisualStudio.Services.Agent.AgentServer.ConnectAsync(Uri serverUrl, VssCredentials credentials) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/AgentServer.cs:line 78
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) in /home/vsts/work/1/s/src/Agent.Listener/Configuration/ConfigurationManager.cs:line 347
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command) in /home/vsts/work/1/s/src/Agent.Listener/Agent.cs:line 99
[2023-04-04 17:56:08Z ERR  Terminal] WRITE ERROR: VS30063: You are not authorized to access https://devops20prod.internal.XXXX.xx.
```

**Comment by DmitriiBobreshev** [comment]
Hi @a-dawg, thanks for the question,  the agent supports Kerberos auth for AzureDevops Servers, based on [similar issues](https://developercommunity.visualstudio.com/t/build-agent-tfs-2017-kerberos/157147#T-N157508), for PAT authentication you should enable the Anonymous Authentication for the site. 

You also could try to use Negotiate auth type with the login/password provided. Could you please try will it help or not?
Also could you please attach logs for Negotiate auth type to check the error?

**Comment by aqustiq** [comment]
Hi @DmitriiBobreshev , thank you for quick reply.
Following this guide https://techcommunity.microsoft.com/t5/iis-support-blog/setting-up-kerberos-authentication-for-a-website-in-iis/ba-p/347882 and other on the same them Kerberos doesn't work with Anonymous Authentication and it should be disabled.

Please see attached log with Negotiate auth of VSTS.

[Agent_20230405-163227-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/11161005/Agent_20230405-163227-utc.log)

**Comment by aqustiq** [comment]
PAT auth full log

[Agent_20230404-175602-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/11161027/Agent_20230404-175602-utc.log)

**Comment by rarroyocorptax** [comment]
I am also experiencing this conflict. All sources state Anonymous Authentication must be disabled as a part of enabling Kerberos on ADOS resources. It appears that build agents require this setting to be enabled (link below) for build agents to work as expected.  

https://stackoverflow.com/questions/69739921/what-is-the-appropriate-agent-setup-on-an-azure-devops-on-premise-server-with-di

Is there no support for having Kerberos enabled _and_ registering build agents on-prem?

**Comment by aqustiq** [comment]
Any updates on RHEL9 support?

**Comment by evm2556** [comment]
Hey was there any resolution figured out? This is blocking us. We cannot disable Anonymous Authentication and use on premise agents.

**Comment by elmance123** [comment]
Our team is also having the same issues as this has this issue been solved or is it ongoing?

**Comment by rsatcodehub** [comment]
Same issue, did anyone found workaround or fix for this, please share.

**Comment by aqustiq** [comment]
> Same issue, did anyone found workaround or fix for this, please share.

Yes. It work now with latest agent version and use PAT for agent registration with server.
