### ISSUE TITLE
[BUG]: GSSAPI operation failed with error - An unsupported mechanism was requested. NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'

### ISSUE THREAD

**Issue by gongliangping** [microsoft/azure-pipelines-agent#4235]
### What happened?

1.Get linux agent vsts-agent-linux-x64-3.218.0.tar.gz;
2.Execute ./config.sh, then get error message "GSSAPI operation failed with error - An unsupported mechanism was requested. NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'"
![image](https://user-images.githubusercontent.com/28795955/231044654-94439f69-cfeb-433f-8d03-865925dc7b9c.png)

### Versions

Azure DevOps Server 2020 Update 1.1/CentOS Linux release 7.9.2009 (Core)

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2020 Update 1.1

### Operation system

Centos7.9

**Comment by gongliangping** [comment]
linux agent version is vsts-agent-linux-x64-3.218.0.tar.gz

**Comment by KonstantinTyukalov** [comment]
@gongliangping could you try to install the following package: gss-ntlmssp

**Comment by aqustiq** [comment]
@KonstantinTyukalov same issue is related also to RHEL 9. In RHEL9 gss-ntlmssp package doesn't exist because NTLM is deprecated technology and was dropped in latest Linux OS.
That why we need to adopt as soon as possible Agent connection by Kerberos authentication. (See BUG #4229)

**Comment by SteveSims2** [comment]
I am currently experiencing this issue on ubuntu 18.04 as well as 22.04 with the gss-ntlmssp package installed.  I have the issue with both vsts-agent-linux-x64-2.187.1.tar.gz  and  vsts-agent-linux-x64-3.237.1.tar.gz 

A bit strange because I have other instances of these same Linux os versions that did not have this issue.   Looking everywhere on the internet for answers but nothing seems to address the issue.

[2024-04-02 23:25:54Z INFO IntegratedCredential] GetVssCredentials
[2024-04-02 23:25:54Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 23:25:55Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 23:25:55Z INFO LocationServer] Unable to connect to https://redact....
[2024-04-02 23:25:55Z ERR  LocationServer] System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mech
anisms to negotiate).
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectio
nPool, CancellationToken cancellationToken)

**Comment by SteveSims2** [comment]
Nevermind, I'll post what I did wrong in case it helps someone else.

1. Join your ubuntu machine to the realm.
2. Login as the same user that you are going to run your build agent as.
3. Ensure that you extract all of the agent tar files as that user and NOT as root.
4. Run ./config.sh as non-root, and then become root and run ./svc.sh and install <username> and then ./svc.sh start
5. You won't have any GSS issue (for the reasons that I did), and no errors about anonymous auth being rejected.

It will just start and work if you do that.

If you try to login to the machine as a local user and set it up that way, then you will have a mysterious GSS failure.   In retrospect I guess this should have been obvious, since that local Linux account didn't constitute valid credentials.

**Comment by rsatcodehub** [comment]
Did anyone have luck with RHEL 9? I am having the same issues. 

Strangely, when I curl to http://dev.zure.com, I get a response, but not with the https one.

**Comment by BradT123163** [comment]
Same issues here - I have a successfull SSL connection over https for the server but still getting the same error
"NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'"

**Comment by SteveSims2** [comment]
Brad, I just noticed in my post I failed to mention the requirement to:
```
sudo su
apt update
apt install --no-install-recommends gss-ntlmssp

```
After that,
1. Ensure that you have joined your agent machine to the realm (domain)
2. Logged in to the machine _with the same user credentials you will use for the agent_.
3. Extract the vsts_....tar as that user (not root) so that it owns the files and has write permission to all of them
4. ./config.sh (as non-root)
5. ./svc.sh install <domainuserid> (as root)
6. ./svc.sh start

Note that in all of my successes of doing this, I have set the /etc/sssd/sssd.conf options as follows:

```
[sssd]
domains = mydomain.com
config_file_version = 2
services = nss, pam

[domain/alogent.com]
ad_domain = mydomain.com
krb5_realm = MYDOMAIN.COM
realmd_tags = manages-system joined-with-adcli 
cache_credentials = True
id_provider = ad
krb5_store_password_if_offline = True
default_shell = /bin/bash
ldap_id_mapping = True
use_fully_qualified_names = False
fallback_homedir = /home/%u@%d
access_provider = ad
ad_gpo_access_control = permissive

```
Note the use fully qualified domain names set to false.
systemctl daemon-reload
systemctl restart sssd

Now I can id a domain user without specifying the domain

id <domainuser>

If you do that, then when you run step 5:
./svc.sh install <domainuserid> (as root)

You only need to mention the domain user id, and do not need to specify domain at all.

**Comment by Bofutw** [comment]
I'm also experiencing the same issue with RHEL9. Has there been any update or workaround discovered?

**Comment by SteveSims2** [comment]
I have a K8s pod that runs an old TFS agent.   However, no matter what I tried, only the PAT token auth worked for it.   So I'm sorry I don't know how to get any form of integrated auth working for that.

**Comment by arp-mbender** [comment]
> I have a K8s pod that runs an old TFS agent. However, no matter what I tried, only the PAT token auth worked for it. So I'm sorry I don't know how to get any form of integrated auth working for that.

I think I managed to get this resolved. The solution was to install an newer version of the GSS API plugin.
```
ADD http://ftp.de.debian.org/debian/pool/main/g/gss-ntlmssp/gss-ntlmssp_1.2.0-1_amd64.deb /gss-ntlmssp.deb
RUN dpkg -i /gss-ntlmssp.deb && rm /gss-ntlmssp.deb
```

Note that the latest versions will not work in Ubuntu 22.04 as they have more dependencies, but the above version works OK and permits the agent to use NEGOTIATE from within Docker. Still... this is all really poorly documented and this feels like workaround, not a proper "fix".

**Comment by SteveSims2** [comment]
Perfect.  I'll try to get your method to work for me also.  Thanks dude...

**Comment by arp-mbender** [comment]
> Perfect. I'll try to get your method to work for me also. Thanks dude...

Note you may need to install the dependencies manually using `apt` beforehand, for example `libwbclient0`. But as stated previously the `apt`-gettable packages should be sufficient.
