### ISSUE TITLE
[BUG]: The bearer <secret removed> is not valid after daylight saving in Egypt 

### ISSUE THREAD

**Issue by ahmedsopeah** [microsoft/azure-pipelines-agent#4263]
### What happened?

i have a deployment group agent installed on our windows server 2016, and the daylight has newly applied in Egypt, and the time is changed but since that, it keeps giving error in the agent log

The bearer <secret removed> is not valid until 5/4/2023 12:02:58 AM. Current server time is 5/3/2023 11:03:00 PM.

i tried to change the time manually back, change the time zone, made the machine time with UTC 
but all failed 
but i can see that the current server time mentioned in the log is not correct meanwhile the machine time is correct 

the time mentioned in log is not the same as the machine time 

### Versions

Azure DevOps version 3.220
Windows server 2016

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Relevant log output

```shell
[2023-05-04 00:02:58Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\azagent\A3\.credentials_rsaparams
[2023-05-04 00:02:58Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\azagent\A3\.credentials_rsaparams
[2023-05-04 00:02:59Z ERR  VisualStudioServices] POST request to https://vssps.dev.azure.com/dttmoj/_apis/oauth2/token failed. HTTP Status: BadRequest, AFD Ref: Ref A: B7E7C42F2178422D922663251F5D7C94 Ref B: CAI30EDGE0108 Ref C: 2023-05-03T23:03:00Z
[2023-05-04 00:02:59Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2023-05-04 00:02:59Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2023-05-04 00:02:59Z INFO AgentServer] Catch exception during connect. 4 attempt left.
[2023-05-04 00:02:59Z ERR  AgentServer] Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenRequestException: The bearer <secret removed> is not valid until 5/4/2023 12:02:58 AM. Current server time is 5/3/2023 11:03:00 PM.
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
[2023-05-04 00:02:59Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2023-05-04 00:02:59Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/7b894711-1447-4ee2-8f33-7ea0821378be, Basic realm="https://tfsprodsin1.app.visualstudio.com/", TFS-Federated
```

**Comment by DenisRumyantsev** [comment]
@ahmedsopeah fixing the clock should fix this issue.
We already had similar issues —
https://github.com/microsoft/azure-pipelines-agent/issues/2393
https://github.com/microsoft/azure-pipelines-agent/issues/3919
