### ISSUE TITLE
[BUG]: macos arm64 self-hosted agent cannot update automatically

### ISSUE THREAD

**Issue by ferben** [microsoft/azure-pipelines-agent#4284]
### What happened?

Update from web cannot be processed (Settings→Agent Pools→[myPool]→macMiniM1→update Agent).
Update other platforms like Win, Linux, LinuxARM works fine, but not macos arm64.

### Versions

macOS: 13.4

Installed DevOps Agent: 3.220.0
New DevOps Agent: 3.220.2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

macOS 13

### Relevant log output

```shell
23-05-19 04:59:16Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2023-05-19 04:59:16Z ERR  VisualStudioServices] GET request to https://dev.azure.com/storeit/_apis/distributedtask/packages/agent/osx-arm64/3.220.2 failed. HTTP Status: NotFound, AFD Ref: Ref A: 6110B64F57854E38BF42792E381188A8 Ref B: PRG01EDGE0517 Ref C: 2023-05-19T04:59:17Z
[2023-05-19 04:59:17Z INFO Agent] Ignore agent update exception. Microsoft.TeamFoundation.DistributedTask.WebApi.PackageNotFoundException: A package with type agent, platform osx-arm64, version 3.220.2 was not found.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.UpdateNeeded(String targetVersion, CancellationToken token) in /Users/runner/work/1/s/src/Agent.Listener/SelfUpdater.cs:line 138
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token) in /Users/runner/work/1/s/src/Agent.Listener/SelfUpdater.cs:line 70
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce) in /Users/runner/work/1/s/src/Agent.Listener/Agent.cs:line 346
[2023-05-19 04:59:17Z INFO Agent] Auto update task finished at backend, there is no available agent update needs to apply, continue message queue looping.
```

**Comment by LiliaSabitova** [comment]
Hi @ferben, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by ferben** [comment]
I think it's resolved by development. Now it works.
