### ISSUE TITLE
[BUG]: Job Delays if Azure Metadata Instance service is not avaialble

### ISSUE THREAD

**Issue by afscrome** [microsoft/azure-pipelines-agent#4316]
### What happened?

In our environment, we're seeing every job take about 20secs longer than it shoud.  e.g. in the below example, the job is taking  24 sec, but each step is no more than 1 second

![image](https://github.com/microsoft/azure-pipelines-agent/assets/289860/d302cae6-8789-4a83-a0b6-38c0201773b2)

After some debugging, this delay seems to be caused by a timeout on a call to the Azure Instance Metadata Service.  The machines this job is timing out on are on premise vms, not hosted in Azure.  After adding a Windows Firewall rule to block all traffic to `169.254.169.254`, this delay disapears.

I would expect running an agent outside of Azure to not incure a 20 second penalty on every job execution.

1. Can you reduce the timeout for this call - 20 secs seems a long time
2. Can this check for Azure Metadata be done on agent startup, rather than re-computed on every single job run?

### Versions

Agent.Listener.exe 3.218.0.0
Microsoft Windows Server 2019 Datacenter 10.0.17763 Build 17763

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Version controll system

git

### Relevant log output

```shell
[2023-06-07 14:56:39Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'e5bdd4ac-156d-5ece-78e0-8d8fdbb08457', success rate: 1/1.
[2023-06-07 14:56:54Z INFO JobServerQueue] Stop aggressive process web console line queue.
[2023-06-07 14:56:59Z INFO HttpTrace] Trace System.Net.Http.Exception event:
{ Exception = System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (169.254.169.254:80)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken), Request = Method: GET, RequestUri: 'http://169.254.169.254/metadata/instance?format=text&api-version=2021-02-01', Version: 1.1, Content: <null>, Headers:
{
  Metadata: true
  traceparent: 00-61d2048a9f287d4c0d26f04a08414a25-946b6ea592d261ce-00
} }
[2023-06-07 14:56:59Z INFO HttpTrace] Trace System.Net.Http.HttpRequestOut.Stop event:
{ Response = , Request = Method: GET, RequestUri: 'http://169.254.169.254/metadata/instance?format=text&api-version=2021-02-01', Version: 1.1, Content: <null>, Headers:
{
  Metadata: true
  traceparent: 00-61d2048a9f287d4c0d26f04a08414a25-946b6ea592d261ce-00
}, RequestTaskStatus = Faulted }
[2023-06-07 14:56:59Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = , LoggingRequestId = f713840f-7aa7-4aa6-a66a-4d310f0b9e60, Timestamp = 21131099434231, RequestTaskStatus = Faulted }
```

**Comment by afscrome** [comment]
Looks like this was fixed in the release earlier this week through #4249
