### ISSUE TITLE
[BUG]: Config.cmd doesn't honor a gMSA passed via WindowsLogonAccount

### ISSUE THREAD

**Issue by aledeniz** [microsoft/azure-pipelines-agent#4343]
### What happened?

Config.cmd doesn't honor a gMSA passed via WindowsLogonAccount: it does ask me the password all the times.
If I enter the gMSA name without a trailing $, correctly complains I didn't add the $. Once I add the $, the prompt ask me for a password. 
Cannot deploy a gMSA unattended, I have to manually work around each deployed agent afterwards.
I have tried both with MyDomain\MyGMSA$ and MyGMSA$@MyDomain.tld, no joy either way.

### Versions

3.220.5, but I have seen this in previous versions, both 2.x and 3.x.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Relevant log output

```shell
PS C:\agent\a1> $agentFullName = 'a1'
PS C:\agent\a1> .\config.cmd --pool MyPool --agent $agentFullName --runasservice --work "D:\r\$agent" --url 'https://dev.azure.com/myACMEOrg/' --auth PAT --token ******** --WindowsLogonAccount myDomain\myGMSA$ --enableservicesidtypeunrestricted

  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v3.220.5             |_|          (commit 5faff7c)


>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
2023-07-06 19:31:20Z: Settings Saved.
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ > **
Invalid windows credentials entered. Try again or ctrl-c to quit
Enter Password for the account myDomain\myGMSA$ > **
Invalid windows credentials entered. Try again or ctrl-c to quit
Enter Password for the account myDomain\myGMSA$ > *
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
Enter Password for the account myDomain\myGMSA$ >
```

**Comment by aledeniz** [comment]
I had a look at the source code.
I reckon that the deployment could work if could reach line 139 in https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Listener/Configuration.Windows/WindowsServiceControlManager.cs ( _windowsServiceHelper.InstallService( .. );)

Unfortunately it cannot reach there. 
I can see in the trace file both line 83 and 84, so it does exit via the throw at line 85.

This is what I get in the trace:

> [2023-07-06 20:03:23Z INFO CommandSettings] Arg 'windowslogonaccount': 'myDomain\myGMSA$'
[2023-07-06 20:03:23Z INFO WindowsServiceControlManager] LogonAccount after transforming: myDomain\myGMSA$, user: myGMSA$, domain: myDomain
[2023-07-06 20:03:25Z INFO CommandSettings] Arg 'windowslogonpassword': ''
[2023-07-06 20:03:25Z INFO CommandSettings] Flag 'unattended': 'True'
[2023-07-06 20:03:25Z INFO PromptManager] ReadValue
[2023-07-06 20:03:25Z WARN WindowsServiceControlManager] LogonAccount myDomain\myGMSA$ is not managed service account, although you did not specify WindowsLogonPassword - maybe you wanted to use managed service account? Please see https://aka.ms/gmsa for guidelines to set up sMSA/gMSA account. 
[2023-07-06 20:03:25Z WARN WindowsServiceControlManager] Value cannot be null. (Parameter 'Invalid configuration provided for windowslogonpassword. Terminating unattended configuration.')
[2023-07-06 20:03:25Z ERR  Agent] System.ArgumentNullException: Value cannot be null. (Parameter 'Invalid configuration provided for windowslogonpassword. Terminating unattended configuration.')
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.PromptManager.ReadValue(String argName, String description, Boolean secret, String defaultValue, Func`2 validator, Boolean unattended) in D:\a\1\s\src\Agent.Listener\Configuration\PromptManager.cs:line 76
   at Microsoft.VisualStudio.Services.Agent.Listener.CommandSettings.GetArgOrPrompt(String argValue, String name, String description, String defaultValue, Func`2 validator) in D:\a\1\s\src\Agent.Listener\CommandSettings.cs:line 662
   at Microsoft.VisualStudio.Services.Agent.Listener.CommandSettings.GetWindowsLogonPassword(String accountName) in D:\a\1\s\src\Agent.Listener\CommandSettings.cs:line 414
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.WindowsServiceControlManager.ConfigureService(AgentSettings settings, CommandSettings command) in D:\a\1\s\src\Agent.Listener\Configuration.Windows\WindowsServiceControlManager.cs:line 70
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) in D:\a\1\s\src\Agent.Listener\Configuration\ConfigurationManager.cs:line 416
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command) in D:\a\1\s\src\Agent.Listener\Agent.cs:line 99
[2023-07-06 20:03:25Z ERR  Terminal] WRITE ERROR: Value cannot be null. (Parameter 'Invalid configuration provided for windowslogonpassword. Terminating unattended configuration.')

I am wondering if the issue is environmental? For some reason the local system cannot get a password for this service account?

**Comment by aledeniz** [comment]
I have amended the title and the details.
As stated, I managed to deploy successfully the agent with a gMSA. 
This was due an environmental issue on the target computer.
The way this condition is reported (both with or without --unattended) is misleading. We need a clearer error message to advise of this scenario.

**Comment by DenisRumyantsev** [comment]
Hi, @aledeniz thanks for reporting!
We will consider how we can improve the error message for this scenario.
