### ISSUE TITLE
[Question]: Error occurred while calling WinVerifyTrust, during update agent

### ISSUE THREAD

**Issue by mariankral** [microsoft/azure-pipelines-agent#4357]
### Describe your question

I used Update all agents in DevOps, Agent pool tab.
Can you help me how to update agents, please ?

[2023-07-13 06:37:59Z INFO SelfUpdater] Version '3.220.5' of 'agent' package available in server.
[2023-07-13 06:37:59Z INFO SelfUpdater] Current running agent version is 3.218.0
[2023-07-13 06:37:59Z INFO SelfUpdater] An update is available.
[2023-07-13 06:37:59Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2023-07-13 06:37:59Z INFO Terminal] WRITE LINE: Downloading 3.220.5 agent
[2023-07-13 06:37:59Z INFO HostContext] Well known directory 'Bin': 'C:\agent\bin'
[2023-07-13 06:37:59Z INFO HostContext] Well known directory 'Root': 'C:\agent'
[2023-07-13 06:37:59Z INFO HostContext] Well known directory 'Work': 'C:\agent\_work'
[2023-07-13 06:38:02Z INFO SelfUpdater] Attempt 1: save latest agent into C:\agent\_work\_update\agent1.zip.
[2023-07-13 06:38:02Z INFO SelfUpdater] Download agent: begin download
[2023-07-13 06:38:06Z INFO SelfUpdater] Download agent: finished download
[2023-07-13 06:38:07Z INFO SelfUpdater] Checksum validation succeeded
[2023-07-13 06:38:13Z INFO SelfUpdater] Finished getting latest agent package at: C:\agent\_work\_update.
[2023-07-13 06:38:20Z ERR  SelfUpdater] Error occurred while calling WinVerifyTrust: System.InvalidOperationException: Structures containing SafeHandle fields are not allowed in this operation.
   at System.StubHelpers.HandleMarshaler.ConvertSafeHandleToNative(SafeHandle handle, CleanupWorkListElement& cleanupWorkList)
--- End of stack trace from previous location ---
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at Microsoft.VisualStudio.Services.Agent.Listener.UnsafeNativeMethods.WinVerifyTrust(IntPtr hwnd, Guid pgActionID, WinTrustData pWVTData)
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileAuthenticodeSignatureHelper(String filePath, Tracing trace) in D:\a\1\s\src\Agent.Listener\ValidationHelper\InstallerVerifier.cs:line 159
[2023-07-13 06:38:20Z ERR  SelfUpdater] System.InvalidOperationException: Structures containing SafeHandle fields are not allowed in this operation.
   at System.StubHelpers.HandleMarshaler.ConvertSafeHandleToNative(SafeHandle handle, CleanupWorkListElement& cleanupWorkList)
--- End of stack trace from previous location ---
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at Microsoft.VisualStudio.Services.Agent.Listener.UnsafeNativeMethods.WinVerifyTrust(IntPtr hwnd, Guid pgActionID, WinTrustData pWVTData)
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileAuthenticodeSignatureHelper(String filePath, Tracing trace) in D:\a\1\s\src\Agent.Listener\ValidationHelper\InstallerVerifier.cs:line 159
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileSignedByMicrosoft(String filePath, Tracing trace, String expectedEKU) in D:\a\1\s\src\Agent.Listener\ValidationHelper\InstallerVerifier.cs:line 32
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.VerifyAgentAuthenticode(String agentFolderPath) in D:\a\1\s\src\Agent.Listener\SelfUpdater.cs:line 677
[2023-07-13 06:38:20Z INFO Agent] Ignore agent update exception. System.Exception: Authenticode validation of agent assemblies failed.
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token) in D:\a\1\s\src\Agent.Listener\SelfUpdater.cs:line 458
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token) in D:\a\1\s\src\Agent.Listener\SelfUpdater.cs:line 82
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce) in D:\a\1\s\src\Agent.Listener\Agent.cs:line 346
[2023-07-13 06:38:20Z INFO Agent] Auto update task finished at backend, there is no available agent update needs to apply, continue message queue looping.

### Versions

Agent 3.218.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2012 R2

**Comment by aleksandrlevochkin** [comment]
Thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon. 
Looks like the error only happens on Windows Server 2012, so it might be specifically related to this version of Windows, we'll investigate further.

**Comment by reavild1** [comment]
We also have this issue. Also Windows Server 2012R2

**Comment by ptik31** [comment]
This issue is not actually stale.
Updating the build agent "automatically" is not possible as described.

Just tried to update from 3.236.0 to 3.236.1. Stucks while downloading:
![image](https://github.com/microsoft/azure-pipelines-agent/assets/102354084/9e014bff-11e7-42dd-9bac-5ab8499024a3)

**Comment by toddbrownmcis** [comment]
I was able to workaround this issue on Win2012R2 by setting the [DISABLE_AUTHENTICODE_VALIDATION](https://github.com/microsoft/azure-pipelines-agent/blob/71326127e31a747eff0c98de7b93fa047af85dc0/src/Agent.Sdk/Knob/AgentKnobs.cs#L472) knob in the agent .env file as follows and restarting the agent.

`DISABLE_AUTHENTICODE_VALIDATION=true`

This knob is used to: _"Disables authenticode validation for agent package during self update. Set this to any non-empty value to disable."_
