### ISSUE TITLE
[BUG]: Unable to update agent since upgrading to v3.218.0

### ISSUE THREAD

**Issue by d-miles** [microsoft/azure-pipelines-agent#4363]
### What happened?

Hi, I have a script that automatically downloads the latest agent from the github release page, then prompts all of our deployment and build agents to update using the Azure DevOps API. I should have noticed sooner, but this basically stopped working after the agent updated to v3.218.0 on April 2nd, 2023. 

Then, on May 7th, the latest version (v3.220.0) was retrieved and prompted to upgrade -- but this failed. Since then, every week it has been failing to upgrade the agent and so all of my agents are still sitting at v3.218.0.

I've included the full log of the update from May 21st, 2023.

This seems to be a duplicate of the question #4357, but I wanted to report it as a bug and provide further information.

According to the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops), v3.x still supports Windows Server 2012+, so it's not clear what's wrong as of the 3.x release but something isn't working.

### Versions

Azure Pipelines Agent 3.218.0 / Windows Server 2012R2

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2019.1.2 (Dev17.M153.6)

### Operation system

Windows Server 2012R2

### Version controll system

TFVC

### Relevant log output

```shell
[2023-05-22 05:00:08Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file D:\azagent\A1\.credentials_rsaparams
[2023-05-22 05:00:08Z INFO MessageListener] Message '38' received from session 'e0e8ccb5-0b86-4afa-8d37-71048de5b2a5'.
[2023-05-22 05:00:08Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2023-05-22 05:00:08Z INFO SelfUpdater] Version '3.220.2' of 'agent' package available in server.
[2023-05-22 05:00:08Z INFO SelfUpdater] Current running agent version is 3.218.0
[2023-05-22 05:00:08Z INFO SelfUpdater] An update is available.
[2023-05-22 05:00:08Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2023-05-22 05:00:08Z INFO Terminal] WRITE LINE: Downloading 3.220.2 agent
[2023-05-22 05:00:08Z INFO HostContext] Well known directory 'Bin': 'D:\azagent\A1\bin'
[2023-05-22 05:00:08Z INFO HostContext] Well known directory 'Root': 'D:\azagent\A1'
[2023-05-22 05:00:08Z INFO HostContext] Well known directory 'Work': 'D:\azagent\A1\_work'
[2023-05-22 05:00:08Z INFO SelfUpdater] Attempt 1: save latest agent into D:\azagent\A1\_work\_update\agent1.zip.
[2023-05-22 05:00:08Z INFO SelfUpdater] Download agent: begin download
[2023-05-22 05:00:12Z INFO SelfUpdater] Download agent: finished download
[2023-05-22 05:00:12Z INFO SelfUpdater] Skipping checksum validation for offline agent update
[2023-05-22 05:01:11Z INFO SelfUpdater] Finished getting latest agent package at: D:\azagent\A1\_work\_update.
[2023-05-22 05:01:11Z ERR  SelfUpdater] Error occurred while calling WinVerifyTrust: System.InvalidOperationException: Structures containing SafeHandle fields are not allowed in this operation.
   at System.StubHelpers.HandleMarshaler.ConvertSafeHandleToNative(SafeHandle handle, CleanupWorkListElement& cleanupWorkList)
--- End of stack trace from previous location ---
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at Microsoft.VisualStudio.Services.Agent.Listener.UnsafeNativeMethods.WinVerifyTrust(IntPtr hwnd, Guid pgActionID, WinTrustData pWVTData)
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileAuthenticodeSignatureHelper(String filePath, Tracing trace) in D:\a\1\s\src\Agent.Listener\ValidationHelper\InstallerVerifier.cs:line 159
[2023-05-22 05:01:11Z ERR  SelfUpdater] System.InvalidOperationException: Structures containing SafeHandle fields are not allowed in this operation.
   at System.StubHelpers.HandleMarshaler.ConvertSafeHandleToNative(SafeHandle handle, CleanupWorkListElement& cleanupWorkList)
--- End of stack trace from previous location ---
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at Microsoft.VisualStudio.Services.Agent.Listener.UnsafeNativeMethods.WinVerifyTrust(IntPtr hwnd, Guid pgActionID, WinTrustData pWVTData)
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileAuthenticodeSignatureHelper(String filePath, Tracing trace) in D:\a\1\s\src\Agent.Listener\ValidationHelper\InstallerVerifier.cs:line 159
   at Microsoft.VisualStudio.Services.Agent.Listener.InstallerVerifier.VerifyFileSignedByMicrosoft(String filePath, Tracing trace, String expectedEKU) in D:\a\1\s\src\Agent.Listener\ValidationHelper\InstallerVerifier.cs:line 32
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.VerifyAgentAuthenticode(String agentFolderPath) in D:\a\1\s\src\Agent.Listener\SelfUpdater.cs:line 677
[2023-05-22 05:01:11Z INFO Agent] Ignore agent update exception. System.Exception: Authenticode validation of agent assemblies failed.
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.DownloadLatestAgent(CancellationToken token) in D:\a\1\s\src\Agent.Listener\SelfUpdater.cs:line 458
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveAgent, CancellationToken token) in D:\a\1\s\src\Agent.Listener\SelfUpdater.cs:line 82
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.RunAsync(AgentSettings settings, Boolean runOnce) in D:\a\1\s\src\Agent.Listener\Agent.cs:line 346
[2023-05-22 05:01:11Z INFO Agent] Auto update task finished at backend, there is no available agent update needs to apply, continue message queue looping.
[2023-05-22 05:07:39Z WARN VisualStudioServices] Authentication failed with status code 401.
X-TFS-ProcessId: feb4ec40-59b5-495f-99d2-b3c8201f73f2
ActivityId: a39b68b2-a10e-443e-bcb4-831b7487904a
X-TFS-Session: 1f35dad2-5007-4f0e-9d7a-62f600d7318b
X-VSS-E2EID: 3400cd73-2c14-4fa0-8944-71ed9211f444
X-TFS-SoapException: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
X-TFS-ServiceError: TF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.
WWW-Authenticate: Bearer, Basic realm="http://example.com:8080/tfs/", Negotiate, NTLM
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Mon, 22 May 2023 05:07:39 GMT

[2023-05-22 05:07:39Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file D:\azagent\A1\.credentials_rsaparams
[2023-05-22 05:07:39Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
```

**Comment by miro-poliak** [comment]
Same issue here.

**Comment by DenisNikulin5** [comment]
Hi there! 

We are looking into the issue but since the Windows Server 2012 R2 end-of-life date (October 10, 2023) will come soon, we can't guarantee that we have time to release the fix. And it also means supporting this OS will be stopped for us as well. We highly recommend moving to Windows Server 2016 or newer. 

Thanks!

**Comment by toddbrownmcis** [comment]
I was able to workaround this issue on Win2012R2 by setting the [DISABLE_AUTHENTICODE_VALIDATION](https://github.com/microsoft/azure-pipelines-agent/blob/71326127e31a747eff0c98de7b93fa047af85dc0/src/Agent.Sdk/Knob/AgentKnobs.cs#L472) knob in the agent .env file as follows and restarting the agent.

`DISABLE_AUTHENTICODE_VALIDATION=true`

This knob is used to: _"Disables authenticode validation for agent package during self update. Set this to any non-empty value to disable."_
