### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by gooNi-b** [microsoft/azure-pipelines-agent#4384]
### What happened?

I am trying to regist for Azure Devops' Employment Groups.

I used the command generated by Azure Devops.

After the installation is complete, it fails with the error below while attempting to connect to Azure Pipelines.

"TF400898: An Internal Error Occurred. Activity Id: 1a8f66c2-0334-4507-ba26-8e069 1df06cf."

logs
=
...
[2023-08-07 01:18:11Z INFO ConfigurationManager] cred retrieved
[2023-08-07 01:18:11Z INFO PersonalAccessToken] GetVssCredentials
[2023-08-07 01:18:11Z INFO PersonalAccessToken] token retrieved: 52 chars
[2023-08-07 01:18:11Z INFO PersonalAccessToken] cred created
[2023-08-07 01:18:11Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2023-08-07 01:18:12Z ERR  VisualStudioServices] GET request to https://vnstit.visualstudio.com/_apis/connectionData failed. HTTP Status: InternalServerError, AFD Ref: Ref A: FC0DCB4D5DED4B3BA94F6A3D86826400 Ref B: PUS03EDGE0314 Ref C: 2023-08-07T01:18:11Z
[2023-08-07 01:18:12Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2023-08-07 01:18:12Z INFO LocationServer] Unable to connect to https://vnstit.visualstudio.com/.
[2023-08-07 01:18:12Z ERR  LocationServer] Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898: An Internal Error Occurred. Activity Id: b9c08311-fcf3-4bea-9779-59890af730a3.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/LocationServer.cs:line 36
[2023-08-07 01:18:12Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-08-07 01:18:12Z ERR  Terminal] WRITE ERROR (exception):
...

Currently, on-premise VM are successfully connected, but Azure VMs are not registering with the above error.

What should I check?

### Versions

agent v3.224.1 / Ubuntu 18.04.2 LTS (GNU/Linux 4.18.0-1019-azure x86_64)

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 18.04.2 LTS

### Version controll system

TFVC

### Relevant log output

```shell
...

[2023-08-07 01:18:09Z INFO Terminal] WRITE LINE:
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v3.224.1             |_|          (commit 7861f5f)

[2023-08-07 01:18:09Z INFO ConfigurationManager] ConfigureAsync
[2023-08-07 01:18:09Z INFO ConfigurationStore] IsConfigured()
[2023-08-07 01:18:09Z INFO ConfigurationStore] IsConfigured: False
[2023-08-07 01:18:09Z INFO ConfigurationManager] Is configured: False
[2023-08-07 01:18:09Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2023-08-07 01:18:10Z INFO Terminal] WRITE LINE:
[2023-08-07 01:18:10Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2023-08-07 01:18:10Z INFO Terminal] WRITE LINE:
[2023-08-07 01:18:10Z INFO HostContext] Well known directory 'Bin': '/home/wcsm/azagent/bin'
[2023-08-07 01:18:10Z INFO HostContext] Well known directory 'Root': '/home/wcsm/azagent'
[2023-08-07 01:18:10Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /home/wcsm/azagent/license.html
[2023-08-07 01:18:10Z INFO Terminal] WRITE LINE:
[2023-08-07 01:18:10Z INFO CommandSettings] Flag 'acceptteeeula': 'True'
[2023-08-07 01:18:10Z INFO CommandSettings] Flag 'deploymentgroup': 'True'
[2023-08-07 01:18:10Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2023-08-07 01:18:10Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2023-08-07 01:18:10Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2023-08-07 01:18:10Z INFO PersonalAccessToken] cred created
[2023-08-07 01:18:10Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2023-08-07 01:18:11Z ERR  VisualStudioServices] GET request to https://vnstit.visualstudio.com/_apis/connectionData failed. HTTP Status: InternalServerError, AFD Ref: Ref A: F873A4F7E0894E90858D0B7D6B76B11B Ref B: PUS03EDGE0309 Ref C: 2023-08-07T01:18:10Z
[2023-08-07 01:18:11Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2023-08-07 01:18:11Z INFO LocationServer] Unable to connect to https://vnstit.visualstudio.com/.
[2023-08-07 01:18:11Z ERR  LocationServer] Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898: An Internal Error Occurred. Activity Id: 1a8f66c2-0334-4507-ba26-8e0691df06cf.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/LocationServer.cs:line 36
[2023-08-07 01:18:11Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-08-07 01:18:11Z ERR  Terminal] WRITE ERROR (exception):
[2023-08-07 01:18:11Z ERR  Terminal] Microsoft.VisualStudio.Services.Common.VssServiceException: TF400898: An Internal Error Occurred. Activity Id: 1a8f66c2-0334-4507-ba26-8e0691df06cf.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/LocationServer.cs:line 36
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.GetConnectionData(String serverUrl, VssCredentials credentials, ILocationServer locationServer) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs:line 94
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.DetermineDeploymentType(String serverUrl, VssCredentials credentials, ILocationServer locationServer) in /home/vsts/work/1/s/src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs:line 85
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.checkIsHostedServer(IConfigurationProvider agentProvider, AgentSettings agentSettings, ICredentialProvider credProvider) in /home/vsts/work/1/s/src/Agent.Listener/Configuration/ConfigurationManager.cs:line 826
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) in /home/vsts/work/1/s/src/Agent.Listener/Configuration/ConfigurationManager.cs:line 157
[2023-08-07 01:18:11Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2023-08-07 01:18:11Z INFO CommandSettings] Arg 'url': 'https://vnstit.visualstudio.com/'
[2023-08-07 01:18:11Z INFO DeploymentGroupAgentConfigProvider] url - https://vnstit.visualstudio.com/
[2023-08-07 01:18:11Z INFO ConfigurationManager] GetCredentialProvider
[2023-08-07 01:18:11Z INFO CommandSettings] Arg 'auth': 'PAT'
[2023-08-07 01:18:11Z INFO ConfigurationManager] Creating credential for auth: PAT
[2023-08-07 01:18:11Z INFO CredentialManager] GetCredentialProvider
[2023-08-07 01:18:11Z INFO CredentialManager] Creating type PAT
[2023-08-07 01:18:11Z INFO CredentialManager] Creating credential type: PAT
[2023-08-07 01:18:11Z INFO PersonalAccessToken] EnsureCredential
[2023-08-07 01:18:11Z INFO CommandSettings] Arg 'token': '***'
[2023-08-07 01:18:11Z INFO ConfigurationManager] cred retrieved
[2023-08-07 01:18:11Z INFO PersonalAccessToken] GetVssCredentials

...
```

**Comment by kirill-ivlev** [comment]
Hi @gooNi-b, thank you for reaching us!

You marked the option that you are using "MS Hosted agent", but based on logs it is more likely that you trying to connect from the "self-hosted" agent, right?

Do you have any network restrictions/or a proxy server installed?
Based on the provided logs it looks like Azure DevOps Servers are not reachable from the machine where you are configuring the agent.

Could you please provide additional details on this issue?

**Comment by gooNi-b** [comment]
@kirill-ivlev, Thank you.
Yes. "Self-hosted" is correct.
Outbound is not restricted, and ping to "vnstit.visualstudio.com" is working normally.

**Comment by kirill-ivlev** [comment]
Hi @gooNi-b,
Sorry for leaving this ticket unattended, could you please confirm that issue is still relevant for you?
And if yes, could you please share _diag folder from agent [to me](mailto:v-kivlev@microsoft.com)?

**Comment by kirill-ivlev** [comment]
@gooNi-b, I'm closing since we didn't get your response, please feel free to re-open issue if it is still occurs.
