### ISSUE TITLE
[BUG]: not reproducible IOException: The parameter is incorrect on fetching files via Git

### ISSUE THREAD

**Issue by riQQ** [microsoft/azure-pipelines-agent#4541]
### What happened?

The pipeline was canceled because of the IOException: The parameter is incorrect. The next run on the same agent / system just one minute later succeeded.

Seems to be the same issue as https://github.com/dotnet/runtime/issues/21726.
The same stacktrace can also be found here: https://developercommunity.visualstudio.com/t/build-pipeline-triggers-unexpectedly-on-completed/1200505.

Exception:
```
System.IO.IOException: The parameter is incorrect.
    at System.ConsolePal.ControlCHandlerRegistrar.Unregister()
    at System.Console.remove_CancelKeyPress(ConsoleCancelEventHandler value)
    at Agent.PluginHost.Program.Main(String[] args) in D:\a\1\s\src\Agent.PluginHost\Program.cs:line 202
```
### Versions

Agent version: 2.220.0
Operating system: Windows Server 2016 

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20230721.2)

### Operation system

Windows Server 2016 Standard

### Version controll system

Git

### Relevant log output

```shell
2023-11-27T08:16:59.3940230Z ##[section]Starting: Build
2023-11-27T08:16:59.6555923Z ##[section]Starting: Initialize job
2023-11-27T08:16:59.6822475Z Agent name: '<redacted>'
2023-11-27T08:16:59.6822795Z Agent machine name: '<redacted>'
2023-11-27T08:16:59.6822938Z Current agent version: '2.220.0'
<...>
2023-11-27T08:17:03.3267199Z remote: Azure Repos        
2023-11-27T08:17:03.3291593Z remote: 
2023-11-27T08:17:03.3292100Z remote: Found 57408 objects to send. (64 ms)        
...
2023-11-27T08:17:08.9352844Z Receiving objects:  46% (26561/57408), 238.37 MiB | 48.30 MiB/s
2023-11-27T08:17:09.5229603Z Receiving objects:  46% (26563/57408), 313.74 MiB | 48.57 MiB/s
2023-11-27T08:17:09.5326610Z ##[error]The operation was canceled.
2023-11-27T08:17:09.6626940Z Unhandled exception. System.IO.IOException: The parameter is incorrect.
2023-11-27T08:17:09.6628380Z    at System.ConsolePal.ControlCHandlerRegistrar.Unregister()
2023-11-27T08:17:09.6629295Z    at System.Console.remove_CancelKeyPress(ConsoleCancelEventHandler value)
2023-11-27T08:17:09.6630487Z    at Agent.PluginHost.Program.Main(String[] args) in D:\a\1\s\src\Agent.PluginHost\Program.cs:line 202
2023-11-27T08:17:10.0972340Z ##[error]The operation was canceled.
2023-11-27T08:17:10.0977207Z ##[section]Finishing: Checkout <redacted>
2023-11-27T08:17:10.1317787Z ##[section]Starting: Cleanup build directories
```

**Comment by riQQ** [comment]
Not stale

**Comment by riQQ** [comment]
Not stale

**Comment by riQQ** [comment]
Not stale

**Comment by riQQ** [comment]
Not stale

**Comment by riQQ** [comment]
Not stale
