### ISSUE TITLE
[Question]: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by qinweizhen1** [microsoft/azure-pipelines-agent#4712]
### Describe your question

When I configured it on a Linux system, I entered the URL of https and threw the following error:

Enter server URL> https://xxx.xxxx.com/DigitalOfficeCollection

Enter authentication type (press enter for PAT)>

Enter personal access token>****************************************************

Error reported in diagnostic logs Please examine the log for more details

-/tfssagent/diag/Agent_20240314-073247 utc.log

The SSL connection could not be established, see inner exception

Failed to connect Try again or ctrl-c to quit

How to configure to ignore SSL authentication

### Versions

2.181.2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

CentOS

**Comment by DmitriiBobreshev** [comment]
Hi @qinweizhen1, thanks for the question, did you use any type of proxy? Could you please try the latest agent version [3,326.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.236.1)?

**Comment by qinweizhen1** [comment]
我使用了3.236.1版本，还是不行。有没有参数可以控制，让它忽略SSL验证

**Comment by qinweizhen1** [comment]
I used version 3.236.1, but it still doesn't work. Is there a parameter that can be controlled to ignore SSL verification

**Comment by DmitriiBobreshev** [comment]
@qinweizhen1, yes, you can pass [--sslskipcertvalidation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2022#work-with-ssl-server-certificate) during the agent configuration, in that case all SSL error should be ignored

**Comment by erstert3st** [comment]
same
[log.log](https://github.com/microsoft/azure-pipelines-agent/files/14651691/log.log)

**Comment by aleksandrlevochkin** [comment]
@qinweizhen1 Did the `-sslskipcertvalidation` option work for you?

@erstert3st Could you please try the newest version of the agent? Judging by the logs you're using v3.225.0, which does not include this bugfix: https://github.com/microsoft/azure-pipelines-agent/pull/4533

**Comment by aleksandrlevochkin** [comment]
@erstert3st Hi, do you have any updates?

**Comment by aleksandrlevochkin** [comment]
For now I'm closing the issue, please feel free to re-open if you still have this problem with the latest agent's version and `-sslskipcertvalidation` parameter enabled.

**Comment by cliffAtOsaic** [comment]
This is still not working for me
Linux agent 3.225.0 which as far as I can tell is the latest version

**Comment by cliffAtOsaic** [comment]
Thanks for the response.  I was able to upgrade to version 4.246.1.  I believe I downloaded it from here: https://github.com/microsoft/azure-pipelines-agent.

I was able to use `--sslskipcertvalidation` to install the agent.  Initially it even connected and I was able to start the service.  However, now it keeps failing with SSL errors again.  I can't even remove the agent:

```
~/myagent$ ./config.sh remove --auth pat --token <redacted>
Removing agent from the server
Error reported in diagnostic logs. Please examine the log for more details.
    - /home/adm.605473/myagent/_diag/Agent_20241016-165950-utc.log
Failed: Removing agent from the server
The SSL connection could not be established, see inner exception.
```

```
~/myagent$ cat /home/adm.605473/myagent/_diag/Agent_20241016-165950-utc.log | grep error
[*** Sensitive Info *** 16:59:50Z INFO AgentCertificateManager] Ignore SSL server certificate validation error
```

```
~/myagent$ cat /home/adm.605473/myagent/_diag/Agent_20241016-165950-utc.log | grep exception
[*** Sensitive Info *** 16:59:51Z ERR  VisualStudioServices] GET request to https://pw1appdvop01.ibddomain.net/_apis/connectionData failed. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   --- End of inner exception stack trace ---
[*** Sensitive Info *** 16:59:51Z ERR  LocationServer] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   --- End of inner exception stack trace ---
[*** Sensitive Info *** 16:59:51Z ERR  Agent] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   --- End of inner exception stack trace ---
[*** Sensitive Info *** 16:59:51Z ERR  Terminal] WRITE ERROR: The SSL connection could not be established, see inner exception.
````

**Comment by cliffAtOsaic** [comment]
Not sure if it was `--sslskipcertvalidation` or verification, trying the other:

```
~/myagent$ ./config.sh remove --auth pat --token theyoqv2udyuyhhp5pjmn5ljodluiqovyer2wji42gpmc7lln46q --sslskipcertvalidation
Error reported in diagnostic logs. Please examine the log for more details.
    - /home/adm.605473/myagent/_diag/Agent_20241016-174534-utc.log
Unrecognized command-line input arguments: 'sslskipcertvalidation'. For usage refer to: .\config.cmd --help or ./config.sh --help
Removing agent from the server
Failed: Removing agent from the server
The SSL connection could not be established, see inner exception.
```

It seems like I need to globally disable SSL but I can't find a way to do that.

This is a self-hosted build agent trying to connect to a self-hosted Azure DevOps Server.  SSL just "works" in Windows but configuring it for Linux has been a PITA.

**Comment by aleksandrlevochkin** [comment]
@cliffAtOsaic I would like to ask a few questions:

1. What Linux distro do you use?
2. Do you use a proxy?
3. Are you able to send requests to your org with `curl` from the same machine where the agent is running?
4. Do you have [client SSL certificates](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2022#work-with-ssl-client-certificate) enabled in the IIS options of the ADO Server?

**Comment by cliffAtOsaic** [comment]
> [@cliffAtOsaic](https://github.com/cliffAtOsaic) I would like to ask a few questions:
> 
> 1. What Linux distro do you use?
> 2. Do you use a proxy?
> 3. Are you able to send requests to your org with `curl` from the same machine where the agent is running?
> 4. Do you have [client SSL certificates](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2022#work-with-ssl-client-certificate) enabled in the IIS options of the ADO Server?

I have answers to the first 3 questions; the fourth I am waiting to hear back on.

1. Ubuntu LTS 
2. No
3. Yes

I am able to communicate with Azure DevOps Server from the machine in other ways, but I am unable to bypass SSL when it comes to using this machine as a build agent.

**Comment by erstert3st** [comment]
I had the same problem. I explicitly exported all HTTPS certificates from Azure DevOps via the browser and imported them into Linux (why? The logs looked like an SSL problem).
my args: --auth PAT --gitUseSChannel   --sslskipcertvalidation

**Comment by cliffAtOsaic** [comment]
I don't have permission to reopen this issue.  I would like to propose it be reopened as bypassing SSL verification doesn't seem to work as intended.

**Comment by jeancc** [comment]
> [@qinweizhen1](https://github.com/qinweizhen1), yes, you can pass [--sslskipcertvalidation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2022#work-with-ssl-server-certificate) during the agent configuration, in that case all SSL error should be ignored

Only for Windows. Does not work for Linux or Mac.

**Comment by jeancc** [comment]
Trying to create an agent on linux machine (ubuntu). Azure Devops Server on Widnows machine, with certificate signed with my own CA certificate.

I've installed the CA certificate into linux machine store: 
`sudo cp local-ca.crt /usr/local/share/ca-certificates
sudo update-ca-certificates`

But I'm not able to run with success the config.sh script, using PAT as connection system and a personal acces token (PAT). The result is always:
`The SSL connection could not be established, see inner exception`

Watching the log, I can see:

`[Certificate]
Effective date: 5/2/2025 14:00:58
Expiration date: 5/2/2026 14:00:58
Issuer: CN=tecnausacerts, OU=DD, O=tecnausa, L=Elche, S=Comunidad Valenciana, C=ES
Subject: CN=signageserverdd, OU=DD, O=tecnausa, L=Elche, S=Comunidad Valenciana, C=ES

[2025-02-06 08:46:47Z ERR  VisualStudioServices] GET request to https://signageserverdd:44369/Signage/_apis/connectionData failed. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.`

My local Azure Devops Server is not accesible from outside our network, the Linux machine for the agent is in the same local network. So, the only solution I think is create my own Certificate Authority certificate and install in the linux machine. But is not working...

**Comment by erstert3st** [comment]
@jeancc 
I know that shouldn’t be the solution, but have you tried to export it manually via the browser or cli tool? Our cert didn’t work either, but one of the exports via browser did...

**Comment by jeancc** [comment]
Exported from Edge, installed on linux machine. Same result: 

`The SSL connection could not be established, see inner exception.`

Inner exception:

`[SSL Policy Errors]`
`RemoteCertificateNameMismatch: Certificate name mismatch`
`RemoteCertificateChainErrors: ChainStatus has returned a non empty array`
`[HttpRequest]`
`Requested URI: https://signageserverdd:44369/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1`
`Request method: GET`
`[HttpRequestHeaders]`
`X-TFS-Session: 0574d43e-f276-44f7-adb3-602fb7cbce57`
`...`
`[Certificate]`
`Effective date: 6/2/2025 11:37:43`
`Expiration date: 6/2/2026 11:37:43`
`Issuer: E=jeronimo@tecnausa.com, CN=TECNAUSA, OU=DD, O=TECNAUSA, L=ELCHE, S=ALICANTE, C=ES`
`Subject: E=jeronimo@tecnausa.com, CN=TECNAUSA, OU=DD, O=TECNAUSA, L=ELCHE, S=ALICANTE, C=ES`
`[2025-02-06 12:46:22Z ERR  VisualStudioServices] GET request to https://signageserverdd:44369/_apis/connectionData failed. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.`
`---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.`

**Comment by krisdg** [comment]
Same here

OS: Ubuntu 24.04
Arch: armv7l
Agent version: 4.251.0

```
[2025-03-06 12:35:28Z ERR  Terminal] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection) in /mnt/vss/_work/1/s/src/Microsoft.VisualStudio.Services.Agent/LocationServer.cs:line 36
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.GetConnectionData(String serverUrl, VssCredentials credentials, ILocationServer locationServer, Boolean skipServerCertificateValidation) in /mnt/vss/_work/1/s/src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs:line 94
   at Microsoft.VisualStudio.Services.Agent.Util.ServerUtil.DetermineDeploymentType(String serverUrl, VssCredentials credentials, ILocationServer locationServer, Boolean skipServerCertificateValidation) in /mnt/vss/_work/1/s/src/Microsoft.VisualStudio.Services.Agent/Util/ServerUtil.cs:line 85
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.CheckIsHostedServer(IConfigurationProvider agentProvider, AgentSettings agentSettings, ICredentialProvider credProvider, Boolean skipServerCertificateValidation) in /mnt/vss/_work/1/s/src/Agent.Listener/Configuration/ConfigurationManager.cs:line 1010
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) in /mnt/vss/_work/1/s/src/Agent.Listener/Configuration/ConfigurationManager.cs:line 163
[2025-03-06 12:35:28Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2025-03-06 12:35:28Z INFO CommandSettings] Arg 'url': 'https://dev.azure.com/******'
[2025-03-06 12:35:28Z INFO ConfigurationManager] GetCredentialProvider
[2025-03-06 12:35:28Z INFO CommandSettings] Arg 'auth': 'pat'
[2025-03-06 12:35:28Z INFO ConfigurationManager] Creating credential for auth: pat
[2025-03-06 12:35:28Z INFO CredentialManager] GetCredentialProvider
[2025-03-06 12:35:28Z INFO CredentialManager] Creating type pat
[2025-03-06 12:35:28Z INFO CredentialManager] Creating credential type: pat
[2025-03-06 12:35:28Z INFO PersonalAccessToken] EnsureCredential
[2025-03-06 12:35:28Z INFO CommandSettings] Arg 'token': '***'
[2025-03-06 12:35:28Z INFO ConfigurationManager] cred retrieved
[2025-03-06 12:35:28Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2025-03-06 12:35:28Z INFO PersonalAccessToken] GetVssCredentials
[2025-03-06 12:35:28Z INFO PersonalAccessToken] token retrieved: 84 chars
[2025-03-06 12:35:28Z INFO PersonalAccessToken] cred created
[2025-03-06 12:35:28Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2025-03-06 12:35:28Z INFO Terminal] WRITE LINE: Exiting...
[2025-03-06 12:35:28Z INFO ConfigurationManager] Diagnostic data for request:
[SSL Policy Errors]
RemoteCertificateChainErrors: ChainStatus has returned a non empty array
[HttpRequest]
Requested URI: https://dev.azure.com/******/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1
Request method: GET
[HttpRequestHeaders]
X-TFS-Session: db4208bc-dfbb-464b-9fed-7ec38415eb5a
X-VSS-E2EID: 7b84cb18-38db-4e04-99ec-213f2fd196dc
User-Agent: VSServices/19.246.35414.0, (NetStandard; Ubuntu 24.04.1 LTS), VstsAgentCore-linux-arm/4.251.0, (Ubuntu 24.04.1 LTS)
[Certificate]
Effective date: 12/18/2024 06:32:42
Expiration date: 06/16/2025 06:32:42
Issuer: CN=Microsoft Azure RSA TLS Issuing CA 03, O=Microsoft Corporation, C=US
Subject: CN=dev.azure.com, O=Microsoft Corporation, L=Redmond, S=WA, C=US
[ChainStatus]
Status: NotTimeValid
Status Information: certificate has expired```

System date is correct (ntp)
