### ISSUE TITLE
[Question]: Android Signing Task signing .aab always error out with password is wrong message.

### ISSUE THREAD

**Issue by dev-win911** [microsoft/azure-pipelines-agent#4729]
### Describe your question

I have a classic Azure pipeline using Azure hosted windows-latest (i.e server 2022 with VS installed) that builds MaUI Android App. After the build i have a task "Android Signing" to sign android app (.aab) but no matter what i do it always says password is wrong.

Error message:
C:\Windows\system32\cmd.exe /D /S /C "C:\Android\android-sdk\build-tools\34.0.0\apksigner.bat sign --ks D:\a\_temp\MaUI_Key.keystore --ks-pass "pass:***" --ks-key-alias MaUI_Key --key-pass "pass:***" --verbose D:\a\1\s\Mobile\{Project}\obj\QA\net8.0-android34.0\android\bin\com.{Project}.mobile.aab"
##[debug]Agent environment resources - Disk: D:\ Available 11815.00 MB out of 14333.00 MB, Memory: Used 1943.00 MB out of 7167.00 MB, CPU: Usage 1.74%
Failed to load signer "signer #1"
java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2092)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:383)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:269)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:202)
	at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:438)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:353)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:92)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 9 more

Things I have tried. 
I used the same keystore file, alias, keystore, and alias password to distribute it locally and it worked fine.

On the Azure pipeline i am using secret variables stored in variable groups and they are linked to the pipeline.
I have also tried putting all the information directly on the pipeline.

Seems like nothing is working.

Anything that I am missing? 
![Error](https://github.com/microsoft/azure-pipelines-agent/assets/137184628/792290bb-a36e-4810-9dbc-92c5de9db3ac)
![pipelineConfig](https://github.com/microsoft/azure-pipelines-agent/assets/137184628/7f1beaf3-1df8-4333-a2db-80ce7d73b50f)

### Versions

Azure devops online portal (don't know the version)

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

server 2022

### Version controll system

azure devops

**Comment by dev-win911** [comment]
Fixed it
