### ISSUE TITLE
[BUG] VMSS extension Microsoft.Azure.DevOps.Pipelines.Agent fails with VS30063: You are not authorized to access https://dev.azure.com

### ISSUE THREAD

**Issue by FelipeEmerimRandon** [microsoft/azure-pipelines-agent#4746]
### What happened?

After an automatic agent upgrade to version 2.237.1 in the extension, our VMSS VMs would no longer start and consume jobs from the job queue. In the VMSS logs, we see that there is an error initializing the agent. 

It seems that the generated token in version 2.237.1 requires a prompt which cannot be used in the CLI, this results in the unauthorized error.

Downgrading to version 2.236.0 by changing the agentDownloadUrl in the extension settings makes our agents start working with no issues. 

This only seems to affect Linux VMSS agents as we have a Windows pool running with no issues on version 2.237.1.

### Versions

Agent version 2.237.1 / Ubuntu 22.04
Microsoft.Azure.DevOps.Pipelines.Agent version: 1.23

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Version controll system

Azure Devops

### Relevant log output

```shell
[2024-04-02 15:00:30Z INFO AgentProcess] Agent package linux-x64.
[2024-04-02 15:00:30Z INFO AgentProcess] Running on Linux (X64).
[2024-04-02 15:00:30Z INFO AgentProcess] RuntimeInformation: Linux 6.2.0-1019-azure #19~22.04.1-Ubuntu SMP Wed Jan 10 22:57:03 UTC 2024.
[2024-04-02 15:00:30Z INFO AgentProcess] Version: 3.237.1
[2024-04-02 15:00:30Z INFO AgentProcess] Commit: 8faa26d5e44d8b58b2a670cc1a597e67761c990c
[2024-04-02 15:00:30Z INFO AgentProcess] Culture: 
[2024-04-02 15:00:30Z INFO AgentProcess] UI Culture: 
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO AgentProcess] Validating directory permissions for: '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Setting up value for origin: Configure.Password
[2024-04-02 15:00:30Z INFO HostContext] Value is empty.
[2024-04-02 15:00:30Z INFO HostContext] Setting up value for origin: Configure.ProxyPassword
[2024-04-02 15:00:30Z INFO HostContext] Value is empty.
[2024-04-02 15:00:30Z INFO HostContext] Setting up value for origin: Configure.SslClientCert
[2024-04-02 15:00:30Z INFO HostContext] Value is empty.
[2024-04-02 15:00:30Z INFO HostContext] Setting up value for origin: Configure.Token
[2024-04-02 15:00:30Z INFO HostContext] Setting up value for origin: Configure.WindowsLogonPassword
[2024-04-02 15:00:30Z INFO HostContext] Value is empty.
[2024-04-02 15:00:30Z INFO CommandSettings] Configure {
  "AcceptTeeEula": true,
  "AddDeploymentGroupTags": false,
  "AddEnvironmentVirtualMachineResourceTags": false,
  "AddMachineGroupTags": false,
  "AlwaysExtractTask": false,
  "Agent": null,
  "CollectionName": null,
  "DeploymentGroup": false,
  "DeploymentGroupName": null,
  "DeploymentGroupTags": null,
  "DeploymentPool": false,
  "DeploymentPoolName": null,
  "EnableServiceSidTypeUnrestricted": false,
  "EnvironmentVMResource": false,
  "EnvironmentName": null,
  "EnvironmentVMResourceTags": null,
  "GitUseSChannel": false,
  "DisableLogUploads": false,
  "MachineGroup": false,
  "MachineGroupName": null,
  "MachineGroupTags": null,
  "MonitorSocketAddress": null,
  "NotificationPipeName": null,
  "NotificationSocketAddress": null,
  "NoRestart": false,
  "OverwriteAutoLogon": false,
  "Pool": "rdn-dev-us-dig-vmss-02",
  "ProjectName": null,
  "ProxyPassword": null,
  "ProxyUserName": null,
  "ProxyUrl": null,
  "Replace": true,
  "RunAsAutoLogon": false,
  "RunAsService": false,
  "RunOnce": false,
  "PreventServiceStart": false,
  "SslCACert": null,
  "SslClientCert": null,
  "SslClientCertArchive": null,
  "SslClientCertKey": null,
  "SslClientCertPassword": null,
  "SslSkipCertValidation": false,
  "Url": "https://dev.azure.com/digital-office/",
  "WindowsLogonAccount": null,
  "WindowsLogonPassword": null,
  "Work": null,
  "Auth": "pat",
  "LaunchBrowser": false,
  "Password": null,
  "Token": "***",
  "Unattended": true,
  "UserName": null,
  "ClientId": null,
  "TenantId": null,
  "ClientSecret": null,
  "Help": false,
  "Version": false
}
[2024-04-02 15:00:30Z INFO AgentProcess] Arguments parsed
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'Proxy': '/agent/.proxy'
[2024-04-02 15:00:30Z INFO VstsAgentWebProxy] No proxy setting found.
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'Certificates': '/agent/.certificates'
[2024-04-02 15:00:30Z INFO AgentCertificateManager] No certificate setting found.
[2024-04-02 15:00:30Z INFO Agent] ExecuteCommand
[2024-04-02 15:00:30Z INFO ConfigurationStore] currentAssemblyLocation: /agent/bin/Agent.Listener.dll
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO ConfigurationStore] binPath: /agent/bin
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO ConfigurationStore] RootFolder: /agent
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'Agent': '/agent/.agent'
[2024-04-02 15:00:30Z INFO ConfigurationStore] ConfigFilePath: /agent/.agent
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'Credentials': '/agent/.credentials'
[2024-04-02 15:00:30Z INFO ConfigurationStore] CredFilePath: /agent/.credentials
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'Service': '/agent/.service'
[2024-04-02 15:00:30Z INFO ConfigurationStore] ServiceConfigFilePath: /agent/.service
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'Autologon': '/agent/.autologon'
[2024-04-02 15:00:30Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /agent/.autologon
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'Options': '/agent/.options'
[2024-04-02 15:00:30Z INFO ConfigurationStore] RuntimeOptionsFilePath: /agent/.options
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO HostContext] Well known config file 'SetupInfo': '/agent/.setup_info'
[2024-04-02 15:00:30Z INFO ConfigurationStore] SetupInfoFilePath: /agent/.setup_info
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v3.237.1             |_|          (commit 8faa26d)

[2024-04-02 15:00:30Z INFO ConfigurationManager] ConfigureAsync
[2024-04-02 15:00:30Z INFO ConfigurationStore] IsConfigured()
[2024-04-02 15:00:30Z INFO ConfigurationStore] IsConfigured: False
[2024-04-02 15:00:30Z INFO ConfigurationManager] Is configured: False
[2024-04-02 15:00:30Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: 
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: 
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:30Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /agent/license.html
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: 
[2024-04-02 15:00:30Z INFO CommandSettings] Flag 'acceptteeeula': 'True'
[2024-04-02 15:00:30Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2024-04-02 15:00:30Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2024-04-02 15:00:30Z INFO CommandSettings] Flag 'environment': 'False'
[2024-04-02 15:00:30Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2024-04-02 15:00:30Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2024-04-02 15:00:30Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2024-04-02 15:00:30Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2024-04-02 15:00:30Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: 
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: >> Connect:
[2024-04-02 15:00:30Z INFO Terminal] WRITE LINE: 
[2024-04-02 15:00:30Z INFO CommandSettings] Arg 'url': 'https://dev.azure.com/digital-office/'
[2024-04-02 15:00:30Z INFO ConfigurationManager] GetCredentialProvider
[2024-04-02 15:00:30Z INFO CommandSettings] Arg 'auth': 'pat'
[2024-04-02 15:00:30Z INFO ConfigurationManager] Creating credential for auth: pat
[2024-04-02 15:00:30Z INFO CredentialManager] GetCredentialProvider
[2024-04-02 15:00:30Z INFO CredentialManager] Creating type pat
[2024-04-02 15:00:30Z INFO CredentialManager] Creating credential type: pat
[2024-04-02 15:00:30Z INFO PersonalAccessToken] EnsureCredential
[2024-04-02 15:00:30Z INFO CommandSettings] Arg 'token': '***'
[2024-04-02 15:00:30Z INFO ConfigurationManager] cred retrieved
[2024-04-02 15:00:30Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2024-04-02 15:00:30Z INFO PersonalAccessToken] GetVssCredentials
[2024-04-02 15:00:30Z INFO PersonalAccessToken] token retrieved: 951 chars
[2024-04-02 15:00:30Z INFO PersonalAccessToken] cred created
[2024-04-02 15:00:31Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 15:00:32Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 15:00:33Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 15:00:33Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 15:00:33Z INFO PersonalAccessToken] GetVssCredentials
[2024-04-02 15:00:33Z INFO PersonalAccessToken] token retrieved: 951 chars
[2024-04-02 15:00:33Z INFO PersonalAccessToken] cred created
[2024-04-02 15:00:33Z INFO Terminal] WRITE LINE: Connecting to server ...
[2024-04-02 15:00:33Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2024-04-02 15:00:33Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 15:00:33Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 15:00:34Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2024-04-02 15:00:34Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 15:00:34Z INFO AgentServer] Establish connection with 60 seconds timeout.
[2024-04-02 15:00:34Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 15:00:34Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 15:00:34Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 15:00:35Z INFO ConfigurationManager] Test Connection complete.
[2024-04-02 15:00:35Z INFO HostContext] Well known directory 'Bin': '/agent/bin'
[2024-04-02 15:00:35Z INFO HostContext] Well known directory 'Root': '/agent'
[2024-04-02 15:00:35Z INFO HostContext] Well known config file 'RSACredentials': '/agent/.credentials_rsaparams'
[2024-04-02 15:00:35Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 15:00:35Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 15:00:36Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2024-04-02 15:00:36Z WARN VisualStudioServices] Authentication failed with status code 401.
Cache-Control: no-cache
Pragma: no-cache
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/812a6bd0-5829-4196-b2be-d0580b7bd0cb, Basic realm="https://tfsprodsbr1.app.visualstudio.com/", TFS-Federated
X-TFS-ProcessId: 11ca73fc-a677-49c3-af5d-dd7c55f75028
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: 9da30e2e-0940-4efd-b0fe-5fb39c3a5d46
X-TFS-Session: 6d6e3465-104d-47af-8388-2dda8d85eb91
X-VSS-E2EID: 6c974843-f0fe-430e-8f75-0b0e2a7694f2
X-VSS-SenderDeploymentId: b4e8a57a-550b-b919-0f48-a3abbfb7797c
X-Frame-Options: SAMEORIGIN
X-TFS-FedAuthRealm: https://tfsprodsbr1.app.visualstudio.com/
X-TFS-FedAuthIssuer: https://dev.azure.com/digital-office/
X-VSS-AuthorizationEndpoint: https://vssps.dev.azure.com/digital-office/
X-VSS-ResourceTenant: 812a6bd0-5829-4196-b2be-d0580b7bd0cb
X-VSS-S2STargetService: 00000002-0000-8888-8000-000000000000/visualstudio.com
X-TFS-FedAuthRedirect: https://spsprodcus1.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2Fdigital-office%2F_apis%2FconnectionData%3FconnectOptions%3D1%26lastChangeId%3D-1%26lastChangeId64%3D-1&redirect=1&hid=37b0a289-059a-4b0b-a66b-9d912e5bbe30&context=eyJodCI6MiwiaGlkIjoiNDYzZGI3NGYtZDZkOC00NTAyLWIwYzMtNzk4MjliMGFiZmI3IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
Request-Context: appId=cid-v1:59ac3d9a-3105-4df6-af76-1ffe22300eed
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: 43E2C6BEFA154E54AFB35FACBE0756D9 Ref B: BN3EDGE1106 Ref C: 2024-04-02T15:00:36Z
Date: Tue, 02 Apr 2024 15:00:36 GMT

[2024-04-02 15:00:36Z WARN VisualStudioServices] Basic issued token provider instance 64828693 requires an interactive prompt which is not allowed by the current settings
[2024-04-02 15:00:36Z ERR  VisualStudioServices] GET request to https://dev.azure.com/digital-office/_apis/connectionData is not authorized. Details: VS30063: You are not authorized to access https://dev.azure.com.
[2024-04-02 15:00:36Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2024-04-02 15:00:36Z ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://dev.azure.com.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.CheckForServerUpdatesAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.FindServiceDefinitionsAsync(String serviceType, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetResourceLocationsAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Agent.Listener.Configuration.FeatureFlagProvider.GetFeatureFlagWithCred(IHostContext context, String featureFlagName, ITraceWriter traceWriter, AgentSettings settings, VssCredentials creds, CancellationToken ctk) in /mnt/vss/_work/1/s/src/Agent.Listener/Configuration/FeatureFlagProvider.cs:line 59
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IRSAKeyManagerExtensions.GetStoreAgentTokenInNamedContainerFF(IRSAKeyManager _, IHostContext hostContext, ITraceWriter trace, AgentSettings agentSettings, VssCredentials creds, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/src/Agent.Listener/Configuration/IRSAKeyManager.cs:line 59
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) in /mnt/vss/_work/1/s/src/Agent.Listener/Configuration/ConfigurationManager.cs:line 187
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command) in /mnt/vss/_work/1/s/src/Agent.Listener/Agent.cs:line 103
[2024-04-02 15:00:36Z ERR  Terminal] WRITE ERROR: VS30063: You are not authorized to access https://dev.azure.com.
```

**Comment by brunoscota** [comment]
im facing the same issue here. My VMSS is stopped by this problem

**Comment by FelipeEmerimRandon** [comment]
We have used the following powershell script to manually downgrade the agent version

```powershell
Connect-AzAccount
Set-AzContext "LC Digital Office - DEV/QAS"
$ss = Get-AzResource -Id "azure-vmss-id" -ExpandProperties
$ss.Properties.virtualMachineProfile.extensionProfile.extensions.properties.settings[0].agentDownloadUrl = 'https://vstsagentpackage.azureedge.net/agent/3.236.0/vsts-agent-linux-x64-3.236.0.tar.gz'
$ss | Set-AzResource
```

**Comment by brunoscota** [comment]
> We have used the following powershell script to manually downgrade the agent version
> 
> ```powershell
> Connect-AzAccount
> Set-AzContext "subscription-name"
> $ss = Get-AzResource -Id "azure-vmss-id" -ExpandProperties
> $ss.Properties.virtualMachineProfile.extensionProfile.extensions.properties.settings[0].agentDownloadUrl = 'https://vstsagentpackage.azureedge.net/agent/3.236.0/vsts-agent-linux-x64-3.236.0.tar.gz'
> $ss | Set-AzResource
> ```

worked for me this workaround. Thank you @FelipeEmerimRandon

**Comment by FelipeEmerimRandon** [comment]
Sadly, the extension will automatically revert the changes after some time, so we will need to constantly run the workaround to keep the VMSS working.

**Comment by PChiesa** [comment]
> We have used the following powershell script to manually downgrade the agent version
> 
> ```powershell
> Connect-AzAccount
> Set-AzContext "subscription-name"
> $ss = Get-AzResource -Id "azure-vmss-id" -ExpandProperties
> $ss.Properties.virtualMachineProfile.extensionProfile.extensions.properties.settings[0].agentDownloadUrl = 'https://vstsagentpackage.azureedge.net/agent/3.236.0/vsts-agent-linux-x64-3.236.0.tar.gz'
> $ss | Set-AzResource
> ```

Thank you @FelipeEmerimRandon !

**Comment by fsoares212** [comment]
Same issue here! We have a SEV A opened with Microsoft on this.

Thanks for the steps @FelipeEmerimRandon. We are asking them to escalate to Product Group team.

**Comment by Alexlofern** [comment]
Same issue, I downgrade the version too....

**Comment by merlynomsft** [comment]
Thank you for the reports.  We are looking into this issue; we'll keep you posted.

**Comment by merlynomsft** [comment]
This fix for this issue is complete and verified in v3.238.0.  We apologize for the impact this issue had.  Thank you everyone for reporting this and especially @FelipeEmerimRandon for the detailed report and sharing a workaround.
