### ISSUE TITLE
[BUG]: 3.239.1 fails to connect to git

### ISSUE THREAD

**Issue by tisonv** [microsoft/azure-pipelines-agent#4814]
### What happened?

After updating from 3.238.0 to 3.239.1, all builds fail.
Rollbacked to 3.238.0 and it works again

### Versions

2.239.1 on Windows 2019

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2022.1 (AzureDevOpsServer_20240305.2)

### Operation system

Windows Server 2019

### Version controll system

Git

### Relevant log output

```shell
git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
fatal: unable to access 'https://XXXXX/Collection/YYY/_git/YYY/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013)
##[warning]Git fetch failed with exit code 128, back off 6,964 seconds before retry.
```

**Comment by DmitriiBobreshev** [comment]
Hi @tisonv, Thanks for the feedback. We suspect that the problem might be related to git extraheader, agent should remove it after [the execution](https://github.com/microsoft/azure-pipelines-agent/blob/5c5295cd0e3c1c77ecaba922edad74bec3b51a65/src/Agent.Plugins/GitSourceProvider.cs#L693). Could you please check that the Agent have access to it with write permissions and you have nothing in it? 
Also could you please install a fresh agent from scratch to check will it works fine?

**Comment by tisonv** [comment]
Hello @DmitriiBobreshev ! Thanks for the reply
The account running the service is an admin of the collection. I guess it should have all the required permission by default.
The 3.239.1 agent is installed by hand from the zip from github (no automated upgrade from Azure DevOps. Azure DevOps and the agent have very limited internet access)

**Comment by tisonv** [comment]
I tested the 3.240.1 and the problem is no more.
I suspect this has something to do with https://github.com/microsoft/azure-pipelines-agent/commit/04e4b9830a9582fbf5c5d9bbe7142caf4d9968e7 https://github.com/microsoft/azure-pipelines-agent/compare/v3.239.1...v3.240.1

**Comment by tisonv** [comment]
@DmitriiBobreshev 

We skipped 3.241.1.
We tried to install 3.242.1 and the problem is back.

in the Agent log, I get the following warnings. I don't know if they are linked.
```
[2024-08-05 14:09:55Z WARN VisualStudioServices] Authentication failed with status code 401.
X-TFS-ProcessId: ...
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: ...
X-TFS-Session: ...
X-VSS-E2EID: ...
X-VSS-SenderDeploymentId: ...
X-TFS-SoapException: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22fr%22%3ETF400813%3A%20ressource%20non%20disponible%20pour%20l%27acc%C3%A8s%20anonyme.%20L%27authentification%20client%20est%20requise.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
X-TFS-ServiceError: TF400813%3A%20ressource%20non%20disponible%20pour%20l%27acc%C3%A8s%20anonyme.%20L%27authentification%20client%20est%20requise.
WWW-Authenticate: Bearer, Basic realm="https://XXXXX/", Negotiate, NTLM
```
```
[2024-08-05 14:09:55Z ERR  VisualStudioServices] GET request to https://XXXXX/_apis/FeatureFlags/DistributedTask.Agent.UseMaskingPerformanceEnhancements is not authorized. Details: TF400813: L'utilisateur n'est pas autorisé à accéder à cette ressource.
[2024-08-05 14:09:55Z WARN FeatureFlagProvider] Unable to retrieve feature flag with following exception: Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: L'utilisateur n'est pas autorisé à accéder à cette ressource.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Agent.Listener.Configuration.FeatureFlagProvider.GetFeatureFlagWithCred(IHostContext context, String featureFlagName, ITraceWriter traceWriter, AgentSettings settings, VssCredentials creds, CancellationToken ctk) in D:\a\_work\1\s\src\Agent.Listener\Configuration\FeatureFlagProvider.cs:line 62
```

We register our agents with `PAT`as `Negotiate`. 
There are no warning / error during the installation process.

As a test, we gave the account full privileges on the collection from the Azure DevOps console but no success.

**Comment by DmitriiBobreshev** [comment]
Hi @tisonv, seems like you have problems with certain git versions on windows machines, as I see, now, a default version of git which is provided by the agent is [2.45.2](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Misc/externals.sh#L22). Since the agent worked fine for you in version 3.240.1 where the default version was 2.39 let's try to run the pipeline under this version. 
You can set [USE_GIT_2_39_4 knob ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Knob/AgentKnobs.cs#L110) (as a pipeline or env variable) the agent should download this git version from [blobstorage](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Worker/GitManager.cs#L119), so if you have firewall rules, please make sure that the url is not blocking. The agent will download this version with a first run and will continue to use it after. The PR with the changes [is here](https://github.com/microsoft/azure-pipelines-agent/pull/4850). 

From the other side, the error from the start of the topic seems related to the ssl certificate, so, could you please also try to configure agent with [--sslskipcertvalidation ](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2022#work-with-ssl-server-certificate) option and with [agent.gituseschannel](https://github.com/microsoft/azure-pipelines-agent/blob/d309ec536e0e9f2c1cbbe6cc30cdb7f03eef9303/src/Agent.Plugins/GitSourceProvider.cs#L36) variable. In that case [http.sslVerify=false](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/GitSourceProvider.cs#L778) and [http.sslbackend](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/GitSourceProvider.cs#L812) arguments will be passed to git.

**Comment by tisonv** [comment]
I activated the knob and it works ! Thank you !!!

Do you know what changed between 2.39.4 and the next versions that required a knob to be added ?
I can't access the work items describing the problem.
It may help on updating our configuration.

**Comment by DmitriiBobreshev** [comment]
@tisonv, the WI is about some mingit library dependency and most probably not related to your problem.
What I've found is that your error might be related [to ssl certificate ](https://github.com/desktop/desktop/issues/2187).
Could you please tell are you using self-signed certificate? 
Is the certificate added to the Windows certificate storage on agents' machines and on the server?

**Comment by tisonv** [comment]
@DmitriiBobreshev 
Historically our Azure DevOps was self signed until  a couple years ago when the access was migrated through an appliance that signed queries from http to https with a common certificate.
There aren't anymore self signed certificate on the server (The old one expired in 07/2023).
I searched if there was any reference to this certificate (`git config --system --list` and the registry) but nothing to be found.

Could a configuration to be inherited through other other means ? The agents are not on the Azure DevOps server and are completely erased at each upgrade.

> the WI is about some minigit library dependency and most probably not related to your problem. 

Still weird the newest git versions give the problem and not the older ones though.

**Comment by DenisNikulin5** [comment]
@tisonv Could you please set environment variables `GIT_CURL_VERBOSE=1` and `GIT_TRACE=1`, rerun your pipeline with and without the USE_GIT_2_39_4 knob and share your logs? It will help to debug an issue.

**Comment by tisonv** [comment]
@DenisNikulin5 yes but it won't be possible until tomorrow

**Comment by DenisNikulin5** [comment]
@tisonv You can use any release where you face the issue

**Comment by tisonv** [comment]
Here you are @DenisNikulin5 :

```
2024-09-24T13:30:56.8974814Z ##[section]Démarrage : Extraire XXX.Api@main pour s
2024-09-24T13:30:56.9237445Z ==============================================================================
2024-09-24T13:30:56.9238308Z Task         : Get sources
2024-09-24T13:30:56.9238663Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2024-09-24T13:30:56.9238923Z Version      : 1.0.0
2024-09-24T13:30:56.9239218Z Author       : Microsoft
2024-09-24T13:30:56.9239685Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2024-09-24T13:30:56.9239976Z ==============================================================================
2024-09-24T13:30:57.8069498Z Syncing repository: XXX.Api (Git)
2024-09-24T13:30:57.8074101Z Préfixation de la variable d’environnement Path avec le répertoire contenant « git.exe ».
2024-09-24T13:30:57.8080673Z ##[command]git version
2024-09-24T13:30:58.1802030Z 15:30:58.159976 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:30:58.1807510Z 15:30:58.175594 git.c:465               trace: built-in: git version
2024-09-24T13:30:58.1967549Z git version 2.45.2.windows.1
2024-09-24T13:30:58.2017450Z ##[command]git lfs version
2024-09-24T13:30:58.3580432Z 15:30:58.347550 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:30:58.3790914Z 15:30:58.363135 git.c:750               trace: exec: git-lfs version
2024-09-24T13:30:58.3791476Z 15:30:58.363135 run-command.c:657       trace: run_command: git-lfs version
2024-09-24T13:30:58.7122020Z 15:30:58.589077 trace git-lfs: exec: git 'version'
2024-09-24T13:30:58.8162609Z git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)
2024-09-24T13:30:58.8279662Z ##[command]git config --get remote.origin.url
2024-09-24T13:30:58.9850361Z 15:30:58.969914 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:30:59.0120305Z 15:30:59.001161 git.c:465               trace: built-in: git config --get remote.origin.url
2024-09-24T13:30:59.0299250Z ##[command]git clean -ffdx
2024-09-24T13:30:59.1808547Z 15:30:59.173040 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:30:59.1954933Z 15:30:59.188672 git.c:465               trace: built-in: git clean -ffdx
2024-09-24T13:30:59.2188647Z ##[command]git reset --hard HEAD
2024-09-24T13:30:59.3617716Z 15:30:59.360542 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:30:59.3778936Z 15:30:59.376210 git.c:465               trace: built-in: git reset --hard HEAD
2024-09-24T13:30:59.3798818Z fatal: Could not parse object 'HEAD'.
2024-09-24T13:30:59.3920810Z ##[warning]Unable to run "git clean -ffdx" and "git reset --hard HEAD" successfully, delete source folder instead.
2024-09-24T13:30:59.4118846Z ##[command]git init "D:\agent\_work\19\s"
2024-09-24T13:30:59.6006375Z 15:30:59.594919 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:30:59.6146314Z 15:30:59.610539 git.c:465               trace: built-in: git init 'D:\agent\_work\19\s'
2024-09-24T13:30:59.6815776Z Initialized empty Git repository in D:/agent/_work/19/s/.git/
2024-09-24T13:30:59.6823731Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-09-24T13:30:59.6824055Z hint: is subject to change. To configure the initial branch name to use in all
2024-09-24T13:30:59.6824353Z hint: of your new repositories, which will suppress this warning, call:
2024-09-24T13:30:59.6824551Z hint:
2024-09-24T13:30:59.6824746Z hint: 	git config --global init.defaultBranch <name>
2024-09-24T13:30:59.6824920Z hint:
2024-09-24T13:30:59.6825117Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-09-24T13:30:59.6827572Z hint: 'development'. The just-created branch can be renamed via this command:
2024-09-24T13:30:59.6828223Z hint:
2024-09-24T13:30:59.6828593Z hint: 	git branch -m <name>
2024-09-24T13:30:59.6904351Z ##[command]git remote add origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:30:59.8830622Z 15:30:59.876172 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:30:59.8995043Z 15:30:59.891799 git.c:465               trace: built-in: git remote add origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:30:59.9155715Z ##[command]git config gc.auto 0
2024-09-24T13:31:00.0651530Z 15:31:00.063666 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:00.0805429Z 15:31:00.079316 git.c:465               trace: built-in: git config gc.auto 0
2024-09-24T13:31:00.0952034Z ##[command]git config --get-all http.https://server/collection/XXX/_git/XXX.Api.extraheader
2024-09-24T13:31:00.2553913Z 15:31:00.251180 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:00.2725088Z 15:31:00.266854 git.c:465               trace: built-in: git config --get-all http.https://server/collection/XXX/_git/XXX.Api.extraheader
2024-09-24T13:31:00.2824395Z ##[command]git config --get-all http.extraheader
2024-09-24T13:31:00.4452344Z 15:31:00.438680 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:00.4638988Z 15:31:00.454303 git.c:465               trace: built-in: git config --get-all http.extraheader
2024-09-24T13:31:00.4757560Z ##[command]git config --get-regexp .*extraheader
2024-09-24T13:31:00.6343124Z 15:31:00.626181 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:00.6519147Z 15:31:00.641798 git.c:465               trace: built-in: git config --get-regexp '.*extraheader'
2024-09-24T13:31:00.6621112Z ##[command]git config --get-all http.proxy
2024-09-24T13:31:00.8311125Z 15:31:00.815118 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:00.8536495Z 15:31:00.846379 git.c:465               trace: built-in: git config --get-all http.proxy
2024-09-24T13:31:00.8658232Z ##[command]git config http.version HTTP/1.1
2024-09-24T13:31:01.0350898Z 15:31:01.018255 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:01.0541393Z 15:31:01.049537 git.c:465               trace: built-in: git config http.version HTTP/1.1
2024-09-24T13:31:01.0827746Z ##[command]git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
2024-09-24T13:31:01.2549062Z 15:31:01.252661 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:01.2719173Z 15:31:01.268280 git.c:465               trace: built-in: git fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
2024-09-24T13:31:01.2731195Z 15:31:01.268280 run-command.c:657       trace: run_command: GIT_DIR=.git git remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:01.3282060Z 15:31:01.315122 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:01.3294592Z 15:31:01.315122 git.c:750               trace: exec: git-remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:01.3295146Z 15:31:01.315122 run-command.c:657       trace: run_command: git-remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:01.4547233Z 15:31:01.440130 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:01.6114771Z 15:31:01.598371 http.c:868              == Info: Couldn't find host server in the .netrc file; using defaults
2024-09-24T13:31:01.6267704Z 15:31:01.614039 http.c:868              == Info: Host server:443 was resolved.
2024-09-24T13:31:01.6268226Z 15:31:01.614039 http.c:868              == Info: IPv6: (none)
2024-09-24T13:31:01.6268463Z 15:31:01.614039 http.c:868              == Info: IPv4: 128.1.1.65
2024-09-24T13:31:01.6271836Z 15:31:01.614039 http.c:868              == Info:   Trying 128.1.1.65:443...
2024-09-24T13:31:01.6284623Z 15:31:01.614039 http.c:868              == Info: Connected to server (128.1.1.65) port 443
2024-09-24T13:31:01.6285021Z 15:31:01.614039 http.c:868              == Info: schannel: disabled automatic use of client certificate
2024-09-24T13:31:01.9345879Z 15:31:01.926544 http.c:868              == Info: schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013)
2024-09-24T13:31:01.9346917Z 15:31:01.926544 http.c:868              == Info: Closing connection
2024-09-24T13:31:01.9347537Z 15:31:01.926544 http.c:868              == Info: schannel: shutting down SSL/TLS connection with server port 443
2024-09-24T13:31:01.9357940Z fatal: unable to access 'https://server/collection/XXX/_git/XXX.Api/': schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013)
2024-09-24T13:31:02.0324439Z ##[warning]Git fetch failed with exit code 128, back off 5,953 seconds before retry.
2024-09-24T13:31:07.9249984Z ##[command]git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
2024-09-24T13:31:08.0889358Z 15:31:08.079633 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:08.1102730Z 15:31:08.095274 git.c:465               trace: built-in: git fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
2024-09-24T13:31:08.1111711Z 15:31:08.095274 run-command.c:657       trace: run_command: GIT_DIR=.git git remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:08.1670550Z 15:31:08.157753 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:08.1692456Z 15:31:08.157753 git.c:750               trace: exec: git-remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:08.1693521Z 15:31:08.157753 run-command.c:657       trace: run_command: git-remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:08.2174117Z 15:31:08.204626 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:08.2299758Z 15:31:08.220252 http.c:868              == Info: Couldn't find host server in the .netrc file; using defaults
2024-09-24T13:31:08.2406207Z 15:31:08.235876 http.c:868              == Info: Host server:443 was resolved.
2024-09-24T13:31:08.2407168Z 15:31:08.235876 http.c:868              == Info: IPv6: (none)
2024-09-24T13:31:08.2407793Z 15:31:08.235876 http.c:868              == Info: IPv4: 128.1.1.65
2024-09-24T13:31:08.2408476Z 15:31:08.235876 http.c:868              == Info:   Trying 128.1.1.65:443...
2024-09-24T13:31:08.2416105Z 15:31:08.235876 http.c:868              == Info: Connected to server (128.1.1.65) port 443
2024-09-24T13:31:08.2416973Z 15:31:08.235876 http.c:868              == Info: schannel: disabled automatic use of client certificate
2024-09-24T13:31:08.2536315Z 15:31:08.251505 http.c:868              == Info: schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013)
2024-09-24T13:31:08.2537847Z 15:31:08.251505 http.c:868              == Info: Closing connection
2024-09-24T13:31:08.2538508Z 15:31:08.251505 http.c:868              == Info: schannel: shutting down SSL/TLS connection with server port 443
2024-09-24T13:31:08.2546531Z fatal: unable to access 'https://server/collection/XXX/_git/XXX.Api/': schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013)
2024-09-24T13:31:08.3467285Z ##[warning]Git fetch failed with exit code 128, back off 4,386 seconds before retry.
2024-09-24T13:31:12.6828532Z ##[command]git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
2024-09-24T13:31:12.8639411Z 15:31:12.851402 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:12.8896351Z 15:31:12.882666 git.c:465               trace: built-in: git fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
2024-09-24T13:31:12.8907698Z 15:31:12.882666 run-command.c:657       trace: run_command: GIT_DIR=.git git remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:12.9378078Z 15:31:12.929544 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:12.9393950Z 15:31:12.929544 git.c:750               trace: exec: git-remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:12.9394448Z 15:31:12.929544 run-command.c:657       trace: run_command: git-remote-https origin https://server/collection/XXX/_git/XXX.Api
2024-09-24T13:31:12.9871347Z 15:31:12.976412 exec-cmd.c:243          trace: resolved executable dir: D:/agent/externals/git/mingw64/bin
2024-09-24T13:31:13.0065684Z 15:31:12.992039 http.c:868              == Info: Couldn't find host server in the .netrc file; using defaults
2024-09-24T13:31:13.0161476Z 15:31:13.007651 http.c:868              == Info: Host server:443 was resolved.
2024-09-24T13:31:13.0162311Z 15:31:13.007651 http.c:868              == Info: IPv6: (none)
2024-09-24T13:31:13.0162573Z 15:31:13.007651 http.c:868              == Info: IPv4: 128.1.1.65
2024-09-24T13:31:13.0162901Z 15:31:13.007651 http.c:868              == Info:   Trying 128.1.1.65:443...
2024-09-24T13:31:13.0171945Z 15:31:13.007651 http.c:868              == Info: Connected to server (128.1.1.65) port 443
2024-09-24T13:31:13.0172367Z 15:31:13.007651 http.c:868              == Info: schannel: disabled automatic use of client certificate
2024-09-24T13:31:13.0297789Z 15:31:13.023287 http.c:868              == Info: schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013)
2024-09-24T13:31:13.0299725Z 15:31:13.023287 http.c:868              == Info: Closing connection
2024-09-24T13:31:13.0305743Z 15:31:13.023287 http.c:868              == Info: schannel: shutting down SSL/TLS connection with server port 443
2024-09-24T13:31:13.0308257Z fatal: unable to access 'https://server/collection/XXX/_git/XXX.Api/': schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013)
2024-09-24T13:31:13.0955019Z ##[error]Git fetch failed with exit code: 128
2024-09-24T13:31:13.1664403Z ##[section]Fin : Extraire XXX.Api@main pour s
```

**Comment by DenisNikulin5** [comment]
@tisonv Looks like there is something wrong with the certificate. But I have no idea why it doesn't affect the old git.

Could you please [check](https://superuser.com/questions/1800816/curl-35-schannel-next-initializesecuritycontext-failed-the-revocation-func) if revocation server URL in your certificate is correct and the agent is able to reach the server from its network?

**Comment by DenisNikulin5** [comment]
Closing the issue since there's no response for 2 weeks. Please feel free to reopen the issue if you still have some problems!
